- fp8_requirements.txt
Update fbgemm version to stable 0.8.0. Previous rc4 version was accidentally deprecated in https://pypi.org/project/fbgemm-gpu/#history .
> Update fbgemm version

- llama_toolchain/inference/api/config.py
- llama_toolchain/inference/api_instance.py
- llama_toolchain/inference/client.py
- llama_toolchain/inference/event_logger.py
- llama_toolchain/inference/inference.py
- llama_toolchain/inference/ollama.py
- requirements.txt
- tests/test_inference.py
- tests/test_ollama_inference.py
- Fixed non-streaming inference sever/client/event_logger code 
- Added tests for inline inference to verify that things are working 
`python -m unittest tests/test_inference.py`
- Added non-streaming inference using ollama python apis 
- Added tests to verify that ollama inference can implement the inference api spec across tools, custom tools, etc.
- Streaming inference and appropriate tests 
- [TBD] Setup instructions for ollama and configuration 
- [TBD] pass right request options like temperature, etc
> Added Ollama as an inference impl 

- llama_toolchain/cli/model/list.py
We now surface older (Llama 2, Llama 3) models in the CLI. By default, let's only want to show the latest and greatest, and be exhaustive when you pass the `--show-all` flag.
```bash
$ llama model list
```
```
+---------------------------------------+---------------------------------------------+----------------+----------------------------+
| Model Descriptor                      | HuggingFace Repo                            | Context Length | Hardware Requirements      |
+---------------------------------------+---------------------------------------------+----------------+----------------------------+
| Meta-Llama3.1-8B                      | meta-llama/Meta-Llama-3.1-8B                | 128K           | 1 GPU, each >= 20GB VRAM   | …
```
> Hide older models

- llama_toolchain/agentic_system/api/datatypes.py
- llama_toolchain/agentic_system/client.py
- llama_toolchain/agentic_system/meta_reference/agent_instance.py
- llama_toolchain/agentic_system/meta_reference/agentic_system.py
- llama_toolchain/agentic_system/meta_reference/safety.py
- llama_toolchain/agentic_system/meta_reference/system_prompt.py
- llama_toolchain/agentic_system/utils.py
- llama_toolchain/safety/api/datatypes.py
- Add support for json format in `AgenticSystemInstanceConfig`
- Updated the method `get_agentic_prefix_messages` to support both `json` and `function_tag` formats. 
- Updated the agentic_system client to pass custom tools 
- Other minor fixes to get safety shileds working properly 
Test with 
```
llama distribution start --name hhh
python -m llama_toolchain.agentic_system.client localhost 5000
```
Goes with PR in llama-models 
https://github.com/meta-llama/llama-models/pull/110
> Updates to prompt for tool calls

- llama_toolchain/agentic_system/meta_reference/agentic_system.py
- llama_toolchain/agentic_system/meta_reference/config.py
- llama_toolchain/distribution/distribution.py
- llama_toolchain/distribution/server.py
Ever since we introduced distributions, "internal" tools like Brave / Wolfram were broken. This was because we got their keys from `.env`, but the CWD for starting the distribution was inside the installed `llama_toolchain` package. There's no way a user could put a `.env` there. 
Instead, I am moving the API keys specification to the `AgenticSystemConfig` -- a more natural place.
> Add API keys to AgenticSystemConfig instead of relying on dotenv

- llama_toolchain/cli/download.py
bug:
used undeclared variable (M) in download.py.
when the disk space not enough NameError occured.
Test:
The error now displays correctly after the fix.
> fixed bug in download not enough disk space condition

- llama_toolchain/inference/adapters/tgi/__init__.py
- llama_toolchain/inference/adapters/tgi/tgi.py
- llama_toolchain/inference/providers.py
**Why this PR? What does it do?**
We want to add support for TGI as a _provider_ for the Llama Stack Inference API. That is, a Llama stack distribution should be able to point to a TGI container running model inference and adapt the responses to fit the Llama Stack Inference protocol. 
This PR adds such an adapter. 
**Test Plan** 
First start up the TGI container:
```
podman run --rm -it \
--network host \
-v $HOME/.cache/huggingface:/data \
ghcr.io/huggingface/text-generation-inference:latest \
--dtype bfloat16 \
--model-id meta-llama/Meta-Llama-3.1-8B-Instruct \
--port 5009
```
Then build a Llama Stack adhoc build
```
$ llama stack build adhoc \
agentic_system=meta-reference,safety=remote,memory=remote,inference=remote::tgi \
--name tgi
```
This will create a conda environment with the …
> [inference] Add a TGI adapter

- requirements.txt
llama stack 0.0.13 seems to need the latest llama-models to run
> upgrade llama_models

- llama_toolchain/agentic_system/api/api.py
- llama_toolchain/agentic_system/meta_reference/agent_instance.py
- llama_toolchain/agentic_system/meta_reference/context_retriever.py
- llama_toolchain/agentic_system/meta_reference/rag/context_retriever.py
Sometimes when doing RAG, we need custom logic to convert the user messages to a query that can be sent to memory banks for retrieval purposes. 
This could be as simple as strong concatenation in some cases or using an LLM for query generation. 
This PR introduces a notion of `MemoryQueryGenerators` and associated configs. 
Agent reads this config to understand how to generate the query before calling memory apis. 
Tested with -- 
1. Start distro 
```
llama stack run local --name {distro_name} 
```
2. Run RAG script 
```
PYTHONPATH=. python examples/scripts/rag_with_memory_bank.py localhost 5000 --disable-safety 
```
> Query generators for RAG query

- docs/cli_reference.md
- llama_toolchain/cli/stack/build.py
- llama_toolchain/cli/stack/configure.py
- llama_toolchain/cli/stack/run.py
- llama_toolchain/core/build_conda_env.sh
- llama_toolchain/core/build_container.sh
- llama_toolchain/core/datatypes.py
- llama_toolchain/core/package.py
```
$ llama stack build
Enter value for name (required): a
Enter value for distribution (default: local) (required): 
Enter value for api_providers (optional): 
Enter value for image_type (default: conda) (required): 
...
...
YAML configuration has been written to /home/xiyan/.llama/builds/local/conda/a.yaml
Target `a` built with configuration at /home/xiyan/.llama/builds/local/conda/a.yaml
Build spec configuration saved at /home/xiyan/.llama/distributions/local/conda/a-build.yaml
```
```
$ cat ~/.llama/distributions/local/conda/8b-test-build.yaml
name: 8b-test
distribution: local
api_providers: null
package_type: conda_env
$ llama stack build --config ~/.llama/distributions/local/conda/a-build.yaml
```
```
$ llama stack configure ~/.llama/builds/local/conda/a.yaml
Configuration already …
```
> Add config file based CLI

- llama_toolchain/agentic_system/providers.py
- llama_toolchain/core/datatypes.py
- llama_toolchain/core/distribution.py
- llama_toolchain/core/distribution_registry.py
- llama_toolchain/core/server.py
- llama_toolchain/inference/providers.py
- llama_toolchain/memory/meta_reference/faiss/faiss.py
- llama_toolchain/memory/providers.py
- llama_toolchain/safety/providers.py
- llama_toolchain/telemetry/api/api.py
- llama_toolchain/telemetry/console/__init__.py
- llama_toolchain/telemetry/console/config.py
- llama_toolchain/telemetry/console/console.py
- llama_toolchain/telemetry/providers.py
- llama_toolchain/telemetry/tracing.py
A simple Telemetry API with three basic notions:
- An Event happening at a point in time.
- A Span which represents a time-period and encloses events. Spans are hierarchical -- i.e., they form a tree.
- A Trace which is essentially a "root" Span with some additional metadata.
This should be roughly compatible with OpenTelemetry even though the goal is to keep it extremely minimal as far as possible. The most interesting part will be evolving the Event type to be a discriminated union of very opinionated event types which correspond to things happening in the ML app lifecycle.
I added a simple `console` provider for this API, tied standard Python logger to this API as well (for unstructured logging). We may or may not keep unstructured logging around but it is a start.
Sample output:
> Simplified Telemetry API and tying it to logger

- llama_toolchain/agentic_system/client.py
- llama_toolchain/memory/api/api.py
- llama_toolchain/memory/client.py
- llama_toolchain/memory/common/file_utils.py
- llama_toolchain/memory/common/vector_store.py
- llama_toolchain/memory/providers.py
Adds support for `data:... ` format in URL. 
This way we can now take files as base64 encoded bytes and pass to the server where its decoded. 
Also added support for easy pdf loading. 
Start local distro. 
Run the memory client which also has files that get added to index along with standard URLs. 
```
python -m llama_toolchain.agentic_system.client localhost 5000
```
> Support `data:` in URL for memory. Add ootb support for pdfs

- docs/getting_started.md
- llama_stack/cli/stack/build.py
- llama_stack/cli/stack/configure.py
- llama_stack/cli/stack/run.py
- llama_stack/distribution/datatypes.py
✅  add back wizard for `llama stack build`
```
$ llama stack build
> Please enter an unique name for identifying your Llama Stack build distribution (e.g. my-local-stack): stack-1
> Please enter the image type you want your distribution to be built with (docker or conda): conda
Now, let's configure your Llama Stack distribution specs with API providers
> Please enter the API provider for the inference API: (default=meta-reference): meta-reference
> Please enter the API provider for the safety API: (default=meta-reference): meta-reference
> Please enter the API provider for the agents API: (default=meta-reference): meta-reference
> Please enter the API provider for the memory API: (default=meta-reference): meta-reference
> Please enter the API provider for the telemetry API: …
```
> CLI - add back build wizard, configure with name instead of build.yaml

- llama_stack/cli/stack/build.py
```
llama stack build --name foo
```
> fix prompt with name args

- llama_stack/providers/utils/memory/vector_store.py
- https://github.com/meta-llama/llama-models/blob/43fcc08422a9a2105aeae7a5f09f3404dc478c5c/models/llama3/api/datatypes.py#L29
- URL is defined as a string type in OpenAPI spec, client do not have a way to specify URL v.s. raw content. 
- This causes an issue where URL strings passed to server is indistinguishable from raw content or we should read from URL. 
- Check content against URL pattern match to determine whether URL is needed. 
- test with memory SDK client
```
python sdk_examples/memory/client.py
```
- Before Fix: 
```
Score: 0.8463434066929127
Chunk:
========
Chunk(content='https://raw.githubusercontent.com/pytorch/torchtune/main/docs/source/tutorials/llama3.rst', document_id='num-2', token_count=22)
========
Score: 0.6421850715500633
Chunk:
======== …
```
> Fix memory URL parsing

- llama_stack/providers/adapters/inference/tgi/tgi.py
Tested using the following -- 
1. Build conda distribution using `remote::tgi` for inference and meta-reference for rest of apis. 
Here is the run config -- 
```
built_at: '2024-09-19T21:11:18.928309'
image_name: local-dell-tgi
docker_image: null
conda_env: local-dell-tgi
apis_to_serve:
- inference
- safety
- agents
- memory
provider_map:
inference:
provider_id: remote::tgi
config:
url: http://localhost:2020
api_token: null
hf_endpoint_name: null
safety:
provider_id: meta-reference
config:
llama_guard_shield: null
prompt_guard_shield: null
agents:
provider_id: meta-reference
config: {}
memory:
provider_id: meta-reference
config: {}
telemetry:
provider_id: meta-reference
config: {}
```
2. Start Dell's custom TGI Adaptor 
```
DOCKER_BINARY=podman DOCKER_OPTS="--network host" with-proxy …
```
> Allow TGI adaptor to have non-standard llama model names

- docs/getting_started.ipynb
Fixes typo for setup instruction for starting Llama Stack Server section after cloning the git repo
Before:
> $ cd llama-stack
After
> $ cd llama-stack-apps
> Fixes typo for setup instruction for starting Llama Stack Server section 

- llama_stack/distribution/templates/local-hf-endpoint-build.yaml
- llama_stack/distribution/templates/local-hf-serverless-build.yaml
- llama_stack/distribution/templates/local-tgi-build.yaml
- llama_stack/providers/adapters/inference/tgi/__init__.py
- llama_stack/providers/adapters/inference/tgi/config.py
- llama_stack/providers/adapters/inference/tgi/tgi.py
- llama_stack/providers/registry/inference.py
Hi there :wave: This is a follow-up PR after @hanouticelina's work in https://github.com/meta-llama/llama-stack/pull/53 and @hardikjshah's PR https://github.com/meta-llama/llama-stack/pull/84. At the moment the TGI Adapter is suitable for either a local TGI deployment or a server deployed on [Inference Endpoint](https://huggingface.co/docs/inference-endpoints/index).
This PR adds a new type of adapter that works with our serverless [Inference API](https://huggingface.co/docs/api-inference/index) as well. In practice, the adapter is the same, only the `await initiliaze(config)` logic changes to set the correct inference URL to call. 
I also took the opportunity to switch from a sync inference client to `AsyncInferenceClient` since llama-stack supports it (inputs/outputs are the same, it …
> Make TGI adapter compatible with HF Inference API

- README.md
- docs/cli_reference.md
- docs/getting_started.md
Fix broken `/sdk_examples` link to llama-stack-apps repo
Remove extra space in README.md
> Fix links & format

- docs/cli_reference.md
- llama_stack/cli/model/describe.py
- llama_stack/cli/model/list.py
- tests/test_inference.py
Updated text references of `HuggingFace` to `Hugging Face`.
Also a Minor typo, `donwload` to `download`.
No change to parameter values.
(and great work on llama-stack!)
> Minor typos, HuggingFace -> Hugging Face

- rfcs/RFC-0001-llama-stack.md
This PR fixes the broken links for the following three items: 
- [llama-stack-spec.yaml](https://github.com/meta-llama/llama-stack/blob/main/docs/resources/llama-stack-spec.yaml)
- [llama-stack-spec.html](https://github.com/meta-llama/llama-stack/blob/main/docs/resources/llama-stack-spec.html)
- sample inference endpoint implementation -> [`server.py`](https://github.com/meta-llama/llama-stack/blob/main/llama_stack/distribution/server/server.py)
> Fix broken links in RFC-0001-llama-stack.md

- llama_stack/cli/stack/build.py
The first time I ran `llama stack build`, I quickly hit enter at the
first prompt asking for a name, assuming it would use the default
given in the help text. This caused a failure later on that wasn't
very obvious. I was using the `docker` format and a blank name caused
an invalid tag format that failed the image build.
This change adds validation for the `name` parameter to ensure it's
not empty before proceeding.
> Validate `name` in `llama stack build`

- llama_stack/providers/impls/meta_reference/inference/generation.py
I got this error message and tried to the run the command presented
and it didn't work. The model needs to be give with `--model-id`
instead of as a positional argument.
> inference: Fix download command in error msg

- llama_stack/cli/stack/configure.py
I got this error message and noticed the typo in the message. It
directed the user to run `llama stack build first`, which is not a
valid command.
> configure: Fix a error msg typo

- docs/getting_started.md
Podman works as an alternative to Docker, but it wasn't immediately
obvious going through the quickstart how to enable it aside from
installing the docker alias. Add a note that points users to the
correct env var to use podman.
> docs: Note how to use podman

- llama_stack/distribution/utils/config_dirs.py
Support for https://github.com/meta-llama/llama-stack/issues/129 & https://github.com/meta-llama/llama-stack/issues/111 to specify download directory through env var. 
```
export LLAMA_STACK_CONFIG_DIR=/custom/path/to/.llama
llama download --source meta --model-id Llama3.2-1B
```
> add env for LLAMA_STACK_CONFIG_DIR

- llama_stack/apis/inference/client.py
- llama_stack/apis/safety/client.py
- llama_stack/providers/impls/meta_reference/inference/config.py
- llama_stack/providers/impls/meta_reference/inference/generation.py
- llama_stack/providers/impls/meta_reference/safety/safety.py
- llama_stack/providers/impls/meta_reference/safety/shields/llama_guard.py
- llama_stack/providers/registry/safety.py
- llama_stack/providers/utils/inference/__init__.py
- llama_stack/providers/utils/inference/augment_messages.py
We should use Inference APIs to execute Llama Guard instead of directly needing to use HuggingFace APIs. The actual inference consideration is handled by Inference.
> Use inference APIs for executing Llama Guard

- llama_stack/cli/stack/build.py
- llama_stack/cli/stack/configure.py
- llama_stack/distribution/build.py
- llama_stack/distribution/build_conda_env.sh
1. `build` --> get $CONDA_PREFIX in `build_conda_env.sh` instead of looking for $CONDA_PREFIX at CLI runtime. 
2. `configure` --> add option for looking at $CONDA_PREFIX while searching for build files
```
llama stack build
> Enter a name for your Llama Stack (e.g. my-local-stack): c-7
> Enter the image type you want your Llama Stack to be built as (docker or conda): conda
llama stack configure <name>
llama stack run <name>
```
> [CLI] remove dependency on CONDA_PREFIX in CLI

- llama_stack/distribution/request_headers.py
- llama_stack/distribution/server/server.py
- llama_stack/providers/adapters/inference/together/together.py
- llama_stack/providers/adapters/safety/together/together.py
In the previous design, the server endpoint at the top-most level extracted the headers from the request and set provider data (e.g., private keys) that the implementations could retrieve using `get_request_provider_data()`. 
However, as Yogish has shown in #138, this is not sufficient. Consider the `/agents` API -- Together uses the standard "meta-reference" implementation for it but the inference provider is set to be Together. When an incoming request arrives, no "provider data validator" is registered for Agents because Agents isn't using the Together provider at all. However, when the agent calls inference as its dependency, the inference implementation _does_ need the Together API key. 
The solution is straightforward:
- the server at the top-level does not have the correct context …
> Extract provider data properly (attempt 2)

- llama_stack/providers/utils/inference/augment_messages.py
I believe this is a typo.
As a result, calling this tool with vision models doesn't work properly.
It causes:
```
ValueError: Non supported ToolPromptFormat ToolPromptFormat.json
```
Here's fix.
> `is_multimodal` accepts `core_model_id`  not model itself.

- llama_stack/providers/registry/inference.py
Support for Bedrock inference providers has been applied with the following merges:
https://github.com/meta-llama/llama-stack/commit/95abbf576b4b078e72b779f534cbaf696e30ecab
However, it was overwritten in the next merge.
https://github.com/meta-llama/llama-stack/commit/56aed59eb4c9915676c6fc7aac009dad97e7ead2
As a result, Bedrock is not displayed as an inference provider.
```
llama stack list-providers inference
```
```
+------------------------+----------------------------------------------------------------------------------+
| Provider Type          | PIP Package Dependencies                                                         |
+------------------------+----------------------------------------------------------------------------------+
| remote                 | …
```
> fix broken bedrock inference provider

- llama_stack/distribution/build_container.sh
- llama_stack/distribution/configure_container.sh
- llama_stack/distribution/start_container.sh
commit c39ba235087291b3901cf2ddd68f5526e97ab67f
Author: Russell Bryant <rbryant@redhat.com>
Date:   Fri Sep 27 14:05:18 2024 +0000
Fix podman+selinux compatibility
When I ran `llama stack configure` for my `docker` based stack on my
system using podman + SELinux (CentOS Stream 9), The `podman run`
command failed due to SELinux blocking access to the volume mount.
As a simple fix, disable SELinux label checking.
> Fix podman+selinux compatibility

- llama_stack/distribution/build_container.sh
- llama_stack/distribution/configure_container.sh
- llama_stack/distribution/start_container.sh
da33fa0 docker: Install in editable mode for dev purposes
commit da33fa0f80967490bd14e9fbf5cd917c873cac0d
Author: Russell Bryant <rbryant@redhat.com>
Date:   Mon Sep 30 16:30:04 2024 +0000
docker: Install in editable mode for dev purposes
While rebuilding a stack using the `docker` image type and having
`LLAMA_STACK_DIR` set so it installs `llama_stack` from my local
source, I noticed that once built, it just used the image build cache
and didn't pull in changes to my source.
1. Install in editable mode (`pip install -e`) for dev purposes.
2. Mount the source into the container for `configure` and `run` so
that the editable install works.
> docker: Install in editable mode for dev purposes

- llama_stack/distribution/build_container.sh
- llama_stack/distribution/configure_container.sh
- llama_stack/distribution/start_container.sh
Before using `--security-opt label=disable`, check that SELinux is
enabled. Otherwise, the option is not relevant.
This fixes errors on Mac.
Closes #166
> docker: Check for selinux before using `--security-opt`

- .pre-commit-config.yaml
- docs/cli_reference.md
- llama_stack/providers/registry/inference.py
- llama_stack/providers/utils/inference/augment_messages.py
Note the image here is a bad link, but I don't have content for it:
---
You can even run `llama model prompt-format` see all of the templates and their tokens:
```
llama model prompt-format -m Llama3.2-3B-Instruct
```
<p align="center">
</p>
> Adds markdown-link-check and fixes a broken link

- llama_stack/apis/inference/client.py
I was running this client for testing purposes and being able to
specify which model to use is a convenient addition. This change makes
that possible.
> inference: Add model option to client

- llama_stack/cli/download.py
A misspelled model name on download emits a verbose exception stack without a clear error message. The fix is to move the the intended model `None` check up before first use of model.
Example failing command: `llama download --source huggingface --model-id unknown`
Testing...
Note, below uses 'Llama-3.1-8B' as the invalid model name, and 'Llama3.1-8B' (no dash after 'Llama') as the correct model name.
```
$ git branch
download-check-model-found-before-use
* main
```
```
$ llama download --source huggingface --model-id Llama3.1-8B
Fetching 13 files: 100%|███...███| 13/13 [00:00<00:00, 16860.22it/s]
Successfully downloaded model to /home/dev/.llama/checkpoints/Llama3.1-8B
```
```
$ llama download --source huggingface --model-id Llama-3.1-8B
File …
```
> Check that the model is found before use.

- llama_stack/distribution/templates/local-vllm-build.yaml
- llama_stack/providers/adapters/inference/__init__.py
- llama_stack/providers/impls/vllm/__init__.py
- llama_stack/providers/impls/vllm/config.py
- llama_stack/providers/impls/vllm/vllm.py
- llama_stack/providers/registry/inference.py
This seems to be working in a very basic state, at least.
* using the provided iference test client, i've tested chat completion with
streaming and not streaming.
* I have only tested with `Llama3.1-8B-Instruct` and `Llama3.2-1B-Instruct`
* Multi-GPU support is working in conda, but not docker at the moment (more work
is needed in the docker image - additional dependencies necessary).
* Tool support probably doesn't work since I haven't tested it at all.
a08fd8f Add boilerplate for vllm inference provider
31a0c51 Add vllm to the inference registry
08da5d0 Add a local-vllm template
5626e79 Implement (chat_)completion for vllm provider
commit a08fd8f3317f419a4962100af9f3da0f44064baa
Author: Russell Bryant <rbryant@redhat.com>
Date:   Sat Sep 28 18:46:35 2024 +0000
Add boilerplate for vllm …
> Inline vLLM inference provider

- llama_stack/cli/download.py
Improve the message that gives a hint about the URL needed for
downloading a llama model. This now includes the URL someone should
visit if they have not already done so.
Closes #202
Signed-off-by: Russell Bryant <russell.bryant@gmail.com>
> download: improve help text

- llama_stack/providers/impls/ios/inference/LocalInferenceImpl/LocalInference.swift
Making llama runner's `stop()` function accessible to the world
> Add function for stopping inference

- .flake8
- .github/workflows/pre-commit.yml
Closes #172 
e6c3a4b ci: Run pre-commit checks in CI
adeee1e flake8: Fix config formatting error
commit e6c3a4b162ab1690cc0a196fbb45acc39313b280
Author: Russell Bryant <rbryant@redhat.com>
Date:   Thu Oct 3 13:52:24 2024 +0000
ci: Run pre-commit checks in CI
Run the pre-commit checks in a github workflow to validate that a PR
or a direct push to the repo does not introduce new errors.
commit adeee1eb5022fc59257180964b48130931ddfe20
Author: Russell Bryant <rbryant@redhat.com>
Date:   Thu Oct 3 14:00:20 2024 +0000
flake8: Fix config formatting error
The list of paths under `exclude` had a formatting error. Entries must
be separated by commas.
> ci: Run pre-commit checks in CI

- llama_stack/providers/adapters/inference/databricks/databricks.py
- llama_stack/providers/adapters/inference/fireworks/fireworks.py
- llama_stack/providers/adapters/inference/ollama/ollama.py
- llama_stack/providers/adapters/inference/tgi/tgi.py
- llama_stack/providers/adapters/inference/together/together.py
- llama_stack/providers/impls/vllm/vllm.py
- llama_stack/providers/utils/inference/openai_compat.py
This is not used since we are processing the response, not the request.
> Remove request arg from chat completion response processing

- llama_stack/apis/memory_banks/client.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/tests/agents/provider_config_example.yaml
- llama_stack/providers/tests/agents/test_agents.py
- llama_stack/providers/tests/memory/provider_config_example.yaml
- llama_stack/providers/tests/memory/test_memory.py
- agent cold start may have cases to register memory_banks without specifying provider_id. 
https://github.com/meta-llama/llama-stack/blob/9fcf5d58e0aefea19700344424745d45c08e1ddf/llama_stack/providers/impls/meta_reference/agents/agent_instance.py#L642-L648
Calling register_memory_bank w/o provider_id fail 
```
response = await client.register_memory_bank(
VectorMemoryBankDef(
identifier="test_bank2",
embedding_model="all-MiniLM-L6-v2",
chunk_size_in_tokens=512,
overlap_size_in_tokens=64,
)
)
```
> [bugfix] fix case for agent when memory bank registered without specifying provider_id

- llama_stack/providers/impls/meta_reference/inference/config.py
- llama_stack/providers/impls/meta_reference/inference/inference.py
Sometimes llama-stack is used as a library (and not as a server) -- in some of these cases, the client code can wish to take control of setting up the distributed process group. This can happen in test cases (run via `torchrun`) or in eval harnesses. This PR adds an option to make this possible.
**Test Plan** 
```
MODEL_IDS=Llama3.2-3B-Instruct \
PROVIDER_ID=meta-reference \
PROVIDER_CONFIG=~/.llama/tests/inf_providers.yaml \
torchrun ~/.conda/envs/quant/bin/pytest -s llama_stack/providers/tests/inference/test_inference.py --tb=short --disable-warnings
```
with the following config for meta-reference provider:
```
providers:
- provider_id: meta-reference
provider_type: meta-reference
config:
model: Llama3.2-3B-Instruct
create_distributed_process_group: false
```
> Add an option to not use elastic agents for meta-reference inference

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/agents/agents.py
- llama_stack/apis/agents/client.py
- llama_stack/apis/inference/client.py
- llama_stack/apis/inference/inference.py
- llama_stack/distribution/routers/routers.py
- llama_stack/providers/adapters/inference/bedrock/bedrock.py
- llama_stack/providers/adapters/inference/databricks/databricks.py
- llama_stack/providers/adapters/inference/fireworks/fireworks.py
- llama_stack/providers/adapters/inference/ollama/ollama.py
- llama_stack/providers/adapters/inference/tgi/tgi.py
- llama_stack/providers/adapters/inference/together/together.py
- llama_stack/providers/impls/meta_reference/agents/agent_instance.py
- llama_stack/providers/impls/meta_reference/agents/agents.py
- llama_stack/providers/impls/meta_reference/inference/generation.py
- llama_stack/providers/impls/meta_reference/inference/inference.py
- llama_stack/providers/impls/meta_reference/inference/model_parallel.py
- llama_stack/providers/impls/meta_reference/inference/parallel_utils.py
- llama_stack/providers/impls/meta_reference/safety/llama_guard.py
- llama_stack/providers/impls/vllm/vllm.py
- llama_stack/providers/tests/agents/test_agents.py
- llama_stack/providers/tests/inference/test_inference.py
PR #201 had made several changes while trying to fix issues with getting the `stream=False` branches of inference and agents API working. As part of this, it made a change which was slightly gratuitous. Namely, making `chat_completion()` and brethren "def" instead of "async def". 
The rationale was that this allowed the user (within llama-stack) of this to use it as:
```
async for chunk in api.chat_completion(params)
```
However, it causes unnecessary confusion for several folks. Given that clients (e.g., llama-stack-apps) anyway use the SDK methods (which are completely isolated) this choice was not ideal. Let's revert back so the call now looks like:
```
async for chunk in await api.chat_completion(params)
```
**Bonus**
Added a `completion()` implementation for the meta-reference …
> Make all methods `async def` again; add completion() for meta-reference

- llama_stack/providers/adapters/inference/ollama/ollama.py
- llama_stack/providers/tests/inference/provider_config_example.yaml
- llama_stack/providers/tests/inference/test_inference.py
- llama_stack/providers/utils/inference/openai_compat.py
- llama_stack/providers/utils/inference/prompt_adapter.py
This PR implements the completion API for ollama adapter.
Test plan:
PROVIDER_ID=test-ollama PROVIDER_CONFIG=tests/inference/provider_config_example.yaml MODEL_IDS="Llama3.2-1B-Instruct" pytest -s tests/inference/test_inference.py --tb=short --disable-warnings -rs
PROVIDER_ID=meta-reference PROVIDER_CONFIG=tests/inference/provider_config_example.yaml MODEL_IDS="Llama3.2-1B-Instruct" pytest -s tests/inference/test_inference.py --tb=short --disable-warnings -rs
> add completion() for ollama

- llama_stack/apis/inference/client.py
- llama_stack/apis/inference/inference.py
- llama_stack/distribution/routers/routers.py
- llama_stack/providers/adapters/inference/bedrock/bedrock.py
- llama_stack/providers/adapters/inference/databricks/databricks.py
- llama_stack/providers/adapters/inference/fireworks/fireworks.py
- llama_stack/providers/adapters/inference/ollama/ollama.py
- llama_stack/providers/adapters/inference/tgi/tgi.py
- llama_stack/providers/adapters/inference/together/together.py
- llama_stack/providers/adapters/inference/vllm/vllm.py
- llama_stack/providers/impls/meta_reference/agents/tests/test_chat_agent.py
- llama_stack/providers/impls/meta_reference/inference/generation.py
- llama_stack/providers/impls/meta_reference/inference/inference.py
- llama_stack/providers/registry/inference.py
- llama_stack/providers/tests/inference/test_inference.py
- llama_stack/providers/utils/inference/prompt_adapter.py
Added support for structured output in the API and added a reference implementation for meta-reference. 
A few notes:
- Two formats are specified in the API: Json schema and EBNF based grammar
- Implementation only supports Json for now
- We use `lm-format-enhancer` to provide the implementation right now but may change this especially because BNF grammars aren't supported by that library.
Fireworks has support for structured output and Together has limited supported for it too. Subsequent PRs will add these changes. We would like _all_ our inference providers to provide structured output for llama models since it is an extremely important and highly sought-after need by the developers.
> Add support for Structured Output / Guided decoding

- llama_stack/providers/impls/vllm/vllm.py
Conflict between llama_models.llama3.api.datatypes.SamplingParams and vllm.sampling_params.SamplingParams results in errors while processing VLLM engine requests. The PR aliases vllm samplingparams to resolve the conflict.
The problem really occurs due to the blanket import `from llama_models.llama3.api.datatypes import *` in `vllm.py`. If we can update that to import specific modules instead of the entire namespace, the proposed fix here is not necessary.
Before:
```
curl http://localhost:5000/inference/chat_completion -H "Content-Type: application/json" -d '{"model": "Llama3.1-8B-Instruct", "messages": [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "Write me a 2 sentence poem about the moon"}], "sampling_params": {"temperature": 0.7, "seed": …
```
> [bug] Fix import conflict for SamplingParams

- llama_stack/apis/agents/agents.py
- llama_stack/providers/impls/meta_reference/agents/agents.py
Added implementations for not implemented methods for agents
> Added implementations for get_agents_session, delete_agents_session and delete_agents

- llama_stack/providers/adapters/inference/together/together.py
- llama_stack/providers/tests/inference/test_inference.py
As title. 
**Test Plan:**
```
MODEL_IDS=Llama3.1-8B-Instruct \
PROVIDER_ID=together \
PROVIDER_CONFIG=providers.yaml \
$CONDA_PREFIX/bin/pytest -s llama_stack/providers/tests/inference/test_inference.py::test_structured_output --tb=short --disable-warnings
```
The providers.yaml file above will look like:
```
providers:
- provider_id: together
provider_type: remote::together
config: {}
provider_data:
together:
together_api_key: <TOGETHER_API_KEY>
```
> Support structured output for Together

- llama_stack/providers/utils/inference/openai_compat.py
We already set it in ollama.py. This is not needed and will cause other providers to fail.
> dont set num_predict for all providers

- llama_stack/providers/impls/meta_reference/inference/generation.py
- llama_stack/providers/impls/meta_reference/inference/quantization/hadamard_utils.py
- llama_stack/providers/impls/meta_reference/inference/quantization/loader.py
The current code for int4 quantization with Spinquant does not implement hadamard transform for the last layer in FFN, as a result the model generates gibberish outputs. This PR fixs it.
> Added hadamard transform for spinquant

- llama_stack/providers/adapters/inference/together/together.py
- llama_stack/providers/tests/inference/test_inference.py
Implements completion() API for together 
Addresses #168
Tested completion for both stream and non streaming cases for non structured output  and non streaming case for structured output
PROVIDER_ID=test-together PROVIDER_CONFIG=../configs/provider_config_example.yaml with-proxy pytest -s tests/inference/test_inference.py --tb=short --disable-warnings -rs
```
PROVIDER_ID=test-together MODEL_IDS="Llama3.1-8B-Instruct" PROVIDER_CONFIG=../configs/provider_config_example.yaml with-proxy pytest -s tests/inference/test_inference.py --tb=short --disable-warnings -rs
/home/dineshyv/.conda/envs/stack/lib/python3.10/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous …
```
> completion() for together

- llama_stack/providers/adapters/inference/fireworks/fireworks.py
- llama_stack/providers/tests/inference/test_inference.py
implements completetion() API for fireworks
```
PROVIDER_ID=test-fireworks MODEL_IDS="Llama3.1-8B-Instruct" PROVIDER_CONFIG=../configs/provider_config_example.yaml with-proxy pytest -s tests/inference/test_inference.py --tb=short --disable-warnings -rs
/home/dineshyv/.conda/envs/stack/lib/python3.10/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", …
```
> completion() for fireworks

- llama_stack/distribution/build_container.sh
Pip has a 3.3GB cache of torch and friends. Do not keep this in the image. The vllm inference image should be around 6.7 GB after this. It's currently > 10 GB.
It removes the 3.3 GB cache of files that are downloaded.
> Do not cache pip

- docs/openapi_generator/pyopenapi/operations.py
- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/agents/agents.py
- llama_stack/apis/inference/inference.py
- llama_stack/distribution/client.py
- llama_stack/distribution/resolver.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/datatypes.py
- llama_stack/providers/tests/agents/test_agents.py
- llama_stack/providers/tests/memory/test_memory.py
We have frequently bit-rotten (apis/<api>/client.py) files. They have two drawbacks:
- we need to hand-write these client implementations (work!)
- they often are poorly written and untested
- they are accompanied with some useful testing code which is useful for developers but not intended for end users.
This PR is the first step towards killing these hand-written implementations. It dynamically creates Client classes for each API protocol and registers appropriate methods based on type introspection.
First, I ran an ollama server (`ollama run llama3.2:3b-instruct-fp16`) and then started a Llama Stack using `--template ollama` on port 5003.
Then I set up the following yaml for testing:
```yaml
providers:
- provider_id: remote
provider_type: remote
config: 
host: localhost
port: 5003
``` …
> add dynamic clients for all APIs

- llama_stack/providers/adapters/inference/bedrock/bedrock.py
This is needed after the async refactor.
testplan:
* llama stack build --template bedrock --image-type conda
* llama stack run bedrock --port 5000
*  python examples/inference/client.py localhost 5000 
```
User>hello world, write me a 2 sentence poem about the moon
Assistant>
Here is a 2-sentence poem about the moon:
The moon glows bright in the midnight sky,
A beacon of wonder, as it passes by.
[ModelDefWithProvider(identifier='Llama3.1-8B-Instruct', llama_model='Llama3.1-8B-Instruct', metadata={}, provider_id='remote::bedrock'), ModelDefWithProvider(identifier='Llama3.1-70B-Instruct', llama_model='Llama3.1-70B-Instruct', metadata={}, provider_id='remote::bedrock'), ModelDefWithProvider(identifier='Llama3.1-405B-Instruct', llama_model='Llama3.1-405B-Instruct', metadata={}, …
```
> fix bedrock impl

- llama_stack/providers/adapters/memory/pgvector/pgvector.py
Makes the following fixes for pgvector:
* Sets auto commit to true to commit any writes. else we need to explicitly call commit after every write.
* Fixes parsing logic of load models since the columns are indexed by column name, which requires the dict mode to be set
> pgvector fixes

- llama_stack/providers/adapters/inference/vllm/vllm.py
We get this traceback:
File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/adapters/inference/vllm/vllm.py", line 136, in _stream_chat_completion async for chunk in process_chat_completion_stream_response( TypeError: process_chat_completion_stream_response() takes 2 positional arguments but 3 were given
This corrects the error by deleting the "request" variable to match other inference adapters.
Mentioned in  #357 
Please describe the tests that you ran to verify your changes and relevant result summary. 
python -m llama_stack.apis.safety.client localhost 5000
> Correct a traceback in vllm

- llama_stack/providers/adapters/inference/vllm/__init__.py
- llama_stack/providers/adapters/inference/vllm/config.py
- llama_stack/providers/adapters/inference/vllm/vllm.py
- llama_stack/providers/registry/inference.py
- llama_stack/providers/tests/inference/fixtures.py
Enables support for `remote::vllm` adapter for inference. That is, you can run `vllm` server independently outside the llama stack distribution and be able to connect to it and work with everything else on top.
Added a fixture. Tested as:
```bash
pytest -v -s -m "vllm_remote and llama_3b" test_inference.py --env VLLM_URL=http://localhost:5101/v1
```
(after starting a vllm container serving Llama3.2-3B-Instruct)
> Enable remote::vllm

- llama_stack/providers/remote/inference/fireworks/config.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- Add llama-guard-3-8b
- Add header API key handling
Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration or test plan.
```
(stack) bchen@dev-modeling:~/llama-stack/llama-stack/llama_stack/providers/tests/inference(update_fireworks_client)$ python -m pytest -s -v -m "fireworks and llama_3b" test_text_inference.py --env FIREWORKS_API_KEY=$FIREWORKS_API_KEY
/home/bchen/.local/lib/python3.10/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of …
```
> [LlamaStack][Fireworks] Update client and add unittest

- llama_stack/apis/resource.py
- llama_stack/apis/safety/client.py
- llama_stack/apis/safety/safety.py
- llama_stack/apis/shields/client.py
- llama_stack/apis/shields/shields.py
- llama_stack/distribution/datatypes.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/datatypes.py
- llama_stack/providers/inline/agents/meta_reference/safety.py
- llama_stack/providers/inline/agents/meta_reference/tests/test_chat_agent.py
- llama_stack/providers/inline/meta_reference/codeshield/code_scanner.py
- llama_stack/providers/inline/safety/meta_reference/safety.py
- llama_stack/providers/remote/inference/bedrock/bedrock.py
- llama_stack/providers/remote/safety/bedrock/bedrock.py
- llama_stack/providers/remote/safety/sample/sample.py
- llama_stack/providers/tests/inference/fixtures.py
- llama_stack/providers/tests/safety/conftest.py
- llama_stack/providers/tests/safety/fixtures.py
- llama_stack/providers/tests/safety/test_safety.py
This PR is the first in a series of PRs migrating llama stack's RoutableObjects to a Resource type. This PR just migrates the shield object. 
Resource base class is going to be a base class going forward for all resources provided by providers including models, memory banks etc.
Testing:
```
pytest -v -s llama_stack/providers/tests/safety/test_safety.py -m "bedrock" --bedrock-guardrail-id="u2ejjbiducwl" --bedrock-guardrail-version=DRAFT
/Users/dineshyv/miniconda3/envs/stack/lib/python3.13/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for …
```
> Resource oriented design for shields

- distributions/meta-reference-gpu/compose.yaml
Fixes issue of : `line 30: mapping key "deploy" already defined at line 15` due to duplicate deploy keys
> fix duplicate `deploy` in  compose.yaml

- llama_stack/apis/eval_tasks/eval_tasks.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/datatypes.py
- llama_stack/providers/inline/eval/meta_reference/eval.py
- llama_stack/providers/tests/eval/test_eval.py
Tests: 
```
pytest -v -s -m meta_reference_eval_together_inference_huggingface_datasetio llama_stack/providers/tests/eval/test_eval.py --env TOGETHER_API_KEY=<KEY>
/Users/dineshyv/miniconda3/envs/stack/lib/python3.10/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_S …
```
> migrate evals to resource

- llama_stack/apis/scoring/scoring.py
- llama_stack/apis/scoring_functions/scoring_functions.py
- llama_stack/distribution/datatypes.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/datatypes.py
- llama_stack/providers/inline/scoring/braintrust/braintrust.py
- llama_stack/providers/inline/scoring/braintrust/scoring_fn/fn_defs/answer_correctness.py
- llama_stack/providers/inline/scoring/braintrust/scoring_fn/fn_defs/factuality.py
- llama_stack/providers/inline/scoring/meta_reference/scoring.py
- llama_stack/providers/inline/scoring/meta_reference/scoring_fn/base_scoring_fn.py
- llama_stack/providers/inline/scoring/meta_reference/scoring_fn/fn_defs/equality.py
- llama_stack/providers/inline/scoring/meta_reference/scoring_fn/fn_defs/llm_as_judge_base.py
- llama_stack/providers/inline/scoring/meta_reference/scoring_fn/fn_defs/regex_parser_multiple_choice_answer.py
- llama_stack/providers/inline/scoring/meta_reference/scoring_fn/fn_defs/subset_of.py
- llama_stack/providers/inline/scoring/meta_reference/scoring_fn/regex_parser_scoring_fn.py
- llama_stack/providers/tests/scoring/fixtures.py
tests:
```
pytest -v -s -m meta_reference_scoring_fireworks_inference llama_stack/providers/tests/scoring/test_scoring.py --env FIREWORKS_API_KEY=<KEY>
/Users/dineshyv/miniconda3/envs/stack/lib/python3.10/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET)) …
```
> migrate scoring fns to resource

- llama_stack/distribution/datatypes.py
- llama_stack/providers/adapters/datasetio/huggingface/huggingface.py
- llama_stack/providers/tests/eval/conftest.py
- llama_stack/providers/tests/eval/fixtures.py
- llama_stack/providers/tests/eval/test_eval.py
- fixes issue w/ eval task register
- Add EvalTask to RoutableObject datatypes to fix eval task registration
```python
client.eval_tasks.register(
eval_task_id="meta-reference-mmlu",
dataset_id="mmlu",
scoring_functions=["meta-reference::regex_parser_multiple_choice_answer"],
)
```
```
llama-stack-client eval_tasks list
```
```
pytest -v -s -m meta_reference_eval_together_inference eval/test_eval.py
pytest -v -s -m meta_reference_eval_together_inference_huggingface_datasetio eval/test_eval.py
```
> fix eval task registration

- docs/openapi_generator/generate.py
- llama_stack/apis/resource.py
- llama_stack/distribution/datatypes.py
- llama_stack/distribution/server/server.py
- llama_stack/distribution/stack.py
- llama_stack/distribution/store/registry.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/tests/agents/conftest.py
- llama_stack/providers/tests/agents/fixtures.py
- llama_stack/providers/tests/agents/test_agents.py
- llama_stack/providers/tests/inference/fixtures.py
- llama_stack/providers/tests/memory/fixtures.py
- llama_stack/providers/tests/memory/test_memory.py
- llama_stack/providers/tests/resolver.py
- llama_stack/providers/tests/safety/fixtures.py
This PR brings back the facility to not force registration of resources onto the user. This is not just annoying but actually not feasible sometimes. For example, you may have a Stack which boots up with private providers for inference for models A and B. There is no way for the user to actually know which model is being served by these providers now (to be able to register it.)
How will this avoid the users needing to do registration? In a follow-up diff, I will make sure I update the sample run.yaml files so they list the models served by the distributions explicitly. So when users do `llama stack build --template <...>` and run it, their distributions come up with the right set of models they expect. 
For self-hosted distributions, it also allows us to have a place to explicit list the …
> Allow specifying resources in StackRunConfig

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/datasets/datasets.py
- llama_stack/apis/eval_tasks/eval_tasks.py
- llama_stack/apis/memory_banks/memory_banks.py
- llama_stack/apis/models/models.py
- llama_stack/apis/resource.py
- llama_stack/apis/scoring_functions/scoring_functions.py
- llama_stack/apis/shields/shields.py
- llama_stack/distribution/datatypes.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/distribution/stack.py
- llama_stack/providers/inline/safety/llama_guard/llama_guard.py
- llama_stack/providers/tests/agents/fixtures.py
- llama_stack/providers/tests/inference/fixtures.py
- llama_stack/providers/tests/safety/fixtures.py
- llama_stack/providers/tests/scoring/fixtures.py
This is a follow-up to #425. That PR allows for specifying models in the registry, but each entry needs to look like:
```yaml
- identifier: ...
provider_id: ...
provider_resource_identifier: ...
```
This is headache-inducing.
The current PR makes this situation better by adopting the shape of our APIs. Namely, we need the user to only specify `model-id`. The rest should be optional and figured out by the Stack. You can always override it.
Here's what example `ollama` "full stack" registry looks like (we still need to kill or simplify shield_type crap):
```yaml
models:
- model_id: Llama3.2-3B-Instruct
- model_id: Llama-Guard-3-1B
shields:
- shield_id: llama_guard
shield_type: llama_guard
```
See test plan for #425. Re-ran it.
> Enable sane naming of registered objects with defaults

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- docs/source/getting_started/index.md
- llama_stack/apis/inference/inference.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/inline/eval/meta_reference/eval.py
- llama_stack/providers/inline/inference/meta_reference/generation.py
- llama_stack/providers/inline/inference/meta_reference/inference.py
- llama_stack/providers/inline/inference/vllm/vllm.py
- llama_stack/providers/inline/scoring/llm_as_judge/scoring_fn/llm_as_judge_scoring_fn.py
- llama_stack/providers/remote/inference/bedrock/bedrock.py
- llama_stack/providers/remote/inference/databricks/databricks.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/tests/inference/fixtures.py
- llama_stack/providers/tests/inference/test_text_inference.py
- llama_stack/providers/utils/inference/model_registry.py
- llama_stack/providers/utils/inference/prompt_adapter.py
This PR changes the way model id gets translated to the final model name that gets passed through the provider. 
Major changes include:
1) Providers are responsible for registering an object and as part of the registration returning the object with the correct provider specific name of the model provider_resource_id
2) To help with the common look ups different names a new ModelLookup class is created.
Tested all inference providers including together, fireworks, vllm, ollama, meta reference and bedrock
> Inference to use provider resource id to register and validate

- llama_stack/apis/datasets/datasets.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/inline/datasetio/localfs/datasetio.py
- llama_stack/providers/inline/eval/meta_reference/eval.py
- llama_stack/providers/inline/scoring/basic/scoring.py
- llama_stack/providers/inline/scoring/braintrust/braintrust.py
- llama_stack/providers/inline/scoring/llm_as_judge/scoring.py
- `schema` should not a field w/ pydantic warnings
- change `schema` to `dataset_schema`
```
pytest -v -s -m meta_reference_eval_together_inference_huggingface_datasetio eval/test_eval.py
```
> change schema -> dataset_schema

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/agents/meta_reference/persistence.py
- [This PR solves the issue where agents cannot keep track of instructions after executing the first turn because system instructions were not getting appended in the messages list. It also solves the issue where turns are not being fetched in the appropriate sequence.] Addresses issue (#issue)
- I have a file which has a precise prompt which requires more than one turn to be executed will share the file below. I ran that file as a python script to make sure that the turns are being executed as per the instructions after making the code change
```
import asyncio
from typing import List, Optional, Dict …
```
> PR-437-Fixed bug to allow system instructions after first turn

- distributions/remote-vllm/compose.yaml
- distributions/remote-vllm/run.yaml
- llama_stack/distribution/server/server.py
We'd like our docker steps to require _ZERO EDITS_ to a YAML file in order to get going. This is often not possible because depending on the provider, we do need some configuration input from the user. Environment variables are the best way to obtain this information.
This PR allows our run.yaml to contain `${env.FOO_BAR}` placeholders which can be replaced using `docker run -e FOO_BAR=baz` (and similar `docker compose` equivalent).
For remote-vllm, example `run.yaml` snippet looks like this:
```yaml
providers:
inference:
- provider_id: vllm-0
provider_type: remote::vllm
config:
url: ${env.LLAMA_INFERENCE_VLLM_URL:http://host.docker.internal:5100/v1}
max_tokens: ${env.MAX_TOKENS:4096}
api_token: fake
- provider_id: vllm-1
provider_type: remote::vllm
config:
url: …
```
> add support for ${env.FOO_BAR} placeholders in run.yaml files

- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/tests/inference/test_model_registration.py
- llama_stack/providers/utils/inference/model_registry.py
tests:
pytest -v -s -m "ollama" llama_stack/providers/tests/inference/test_text_inference.py
pytest -v -s -m vllm_remote llama_stack/providers/tests/inference/test_text_inference.py --env VLLM_URL="http://localhost:9798/v1"
> model registration in ollama and vllm check against the available models in the provider

- llama_stack/distribution/routers/routing_tables.py
- llama_stack/distribution/store/registry.py
- llama_stack/distribution/store/tests/test_registry.py
This PR makes the following changes:
1) Fixes the get_all and initialize impl to actually read the values returned from the range call to kvstore and not keys. 
2) The start_key and end_key are fixed to correct perform the range query after the key format changes
3) Made the cache registry thread safe since there are multiple initializes called for each routing table.
Tests:
* Start stack
* Register dataset
* Kill stack
* Bring stack up
* dataset list
```
llama-stack-client datasets list
+--------------+---------------+---------------------------------------------------------------------------------+---------+
| identifier   | provider_id   | metadata                                                                        | type    | …
```
> make distribution registry thread safe and other fixes

- llama_stack/providers/adapters/datasetio/huggingface/config.py
- llama_stack/providers/adapters/datasetio/huggingface/huggingface.py
- local persistence for HF dataset provider
- follow https://github.com/meta-llama/llama-stack/pull/375
**e2e**
1. fresh llama stack run w/ yaml
2. kill server
3. restart llama stack run w/ yaml
```yaml
datasets:
- dataset_id: mmlu
provider_id: huggingface-0
url:
uri: https://huggingface.co/datasets/llamastack/evals
metadata:
path: llamastack/evals
name: evals__mmlu__details
split: train
dataset_schema:
input_query:
type: string
expected_answer:
type: string
```
> local persistent for hf dataset provider

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/models/client.py
- llama_stack/apis/models/models.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/distribution/store/registry.py
- llama_stack/providers/tests/inference/test_model_registration.py
* Changes the registry to store only one RoutableObject per identifier. Before it was a list, which is not really required.
* Adds impl for updates and deletes
* Updates routing table to handle updates correctly
```
❯ llama-stack-client models list
+------------------------+---------------+------------------------------------+------------+
| identifier             | provider_id   | provider_resource_id               | metadata   |
+========================+===============+====================================+============+
| Llama3.1-405B-Instruct | fireworks-0   | fireworks/llama-v3p1-405b-instruct | {}         |
+------------------------+---------------+------------------------------------+------------+
| Llama3.1-8B-Instruct   | fireworks-0   | fireworks/llama-v3p1-8b-instruct   | {} …
```
> Support model resource updates and deletes

- llama_stack/distribution/routers/routing_tables.py
- llama_stack/distribution/store/registry.py
We are calling the initialize function on the registery in the common routing table impl, which is incorrect as the common routing table is the base class inherited by each resource's routing table. this change moves remove that and add the initialize to the creation, where it inits once server run.
> init registry once

- llama_stack/cli/stack/configure.py
Removes from the `llama build configure` deprecation message the `--configure` flag because the `llama stack run` command does not support this flag.
> Fix build configure deprecation message

- llama_stack/cli/llama.py
- llama_stack/cli/model/model.py
- llama_stack/cli/model/verify_download.py
- llama_stack/cli/verify_download.py
It is important to verify large checkpoints downloaded via `llama model download` because subtle corruptions can easily happen with large file system writes. This PR adds a `verify-download` subcommand. Note that verification itself is a very time consuming process (and will take several **minutes** for the 405B model), hence this is a separate subcommand (and not part of the download which can already be time-consuming) and there are spinners and a bit of a "show" around it in the implementation.
> Add a verify-download command to llama CLI

- llama_stack/providers/inline/memory/faiss/faiss.py
tests:
```
torchrun $CONDA_PREFIX/bin/pytest -v -s -m "faiss" llama_stack/providers/tests/memory/test_memory.py
```
> await initialize in faiss

- llama_stack/cli/stack/run.py
**Summary:**
Extend the shorthand run command so it can run successfully when config exists under DISTRIBS_BASE_DIR (i.e. ~/.llama/distributions).
For example, imagine you created a new stack using the `llama stack build` command where you named it "my-awesome-llama-stack".
```
$ llama stack build
> Enter a name for your Llama Stack (e.g. my-local-stack): my-awesome-llama-stack
```
To run the stack you created you will have to use long config path:
```
llama stack run ~/.llama/distributions/llamastack-my-awesome-llama-stack/my-awesome-llama-stack-run.yaml
```
With this change, you can start it using the stack name instead of full path:
```
llama stack run my-awesome-llama-stack
```
**Test Plan:**
Verify command fails when stack doesn't exist
```
python3 -m llama_stack.cli.llama stack run …
```
> Extend shorthand support for the `llama stack run` command

- llama_stack/providers/inline/eval/meta_reference/__init__.py
- llama_stack/providers/inline/eval/meta_reference/eval.py
- llama_stack/providers/inline/scoring/llm_as_judge/scoring_fn/fn_defs/llm_as_judge_405b_simpleqa.py
- llama_stack/providers/inline/scoring/llm_as_judge/scoring_fn/fn_defs/llm_as_judge_base.py
- llama_stack/providers/inline/scoring/llm_as_judge/scoring_fn/llm_as_judge_scoring_fn.py
- llama_stack/providers/registry/eval.py
- add ability to run agents generation for full eval (generate + scoring)
- pre-register SimpleQA  benchmark llm-as-judge scoring function in code
- eval_task_config_simpleqa_search.json
```json
{
"type": "benchmark",
"eval_candidate": {
"type": "agent",
"config": {
"model": "Llama3.1-405B-Instruct",
"instructions": "Please use the search tool to answer the question.",
"sampling_params": {
"strategy": "greedy",
"temperature": 1.0,
"top_p": 0.9
},
"tools": [
{
"type": "brave_search",
"engine": "brave",
"api_key": "API_KEY"
}
],
"tool_choice": "auto",
"tool_prompt_format": "json",
"input_shields": [],
"output_shields": [],
"enable_session_persistence": false
}
}
}
```
> [Agentic Eval] add ability to run agents generation

- llama_stack/providers/tests/inference/test_model_registration.py
- llama_stack/providers/utils/inference/__init__.py
- llama_stack/providers/utils/inference/model_registry.py
This PR allows models to be registered with provider as long as the user specifies a llama model, even though the model does not match our prebuilt provider specific mapping.
Test:
pytest -v -s llama_stack/providers/tests/inference/test_model_registration.py -m "together" --env TOGETHER_API_KEY=<KEY>
> Allow models to be registered as long as llama model is provided

- llama_stack/distribution/server/server.py
- llama_stack/distribution/stack.py
This PR adds a method in stack to return the stackrunconfig object based on the template name. This will be used to instantiate a direct client without the need for an explicit run.yaml
> get stack run config based on template name

- llama_stack/providers/remote/inference/ollama/ollama.py
add more quantized model support for ollama.
Tested with ollama docker that run llama3.2 3b 4bit model.
```
root@docker-desktop:/# ollama ps
NAME           ID              SIZE      PROCESSOR    UNTIL
llama3.2:3b    a80c4f17acd5    3.5 GB    100% CPU     3 minutes from now
```
> add quantized model ollama support

- llama_stack/apis/models/models.py
- llama_stack/cli/download.py
remove another model_ pydantic namespace warning and convert old-style 'class Config' to new-style 'model_config' workaround.
also a whitespace change to get past -
flake8...................................................................Failed
llama_stack/cli/download.py:296:85: E226 missing whitespace around arithmetic operator
llama_stack/cli/download.py:297:54: E226 missing whitespace around arithmetic operator
> remove pydantic namespace warnings using model_config

- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/utils/inference/model_registry.py
adds a new method build_model_alias_with_just_llama_model which is needed for cases like ollama's quantized models which do not really have a repo in hf and an entry in SKU list.
pytest -v -s -m "ollama" llama_stack/providers/tests/inference/test_text_inference.py
> support adding alias for models without hf repo/sku entry

- llama_stack/apis/agents/agents.py
- llama_stack/providers/inline/agents/meta_reference/tools/builtin.py
- llama_stack/providers/tests/agents/test_agents.py
Add Tavily as a built-in search tool, in addition to Brave and Bing.
It's tested using ollama remote, showing parity to the Brave search tool. 
- Install and run ollama with `ollama run llama3.1:8b-instruct-fp16`
- Build ollama distribution `llama stack build --template ollama --image-type conda`
- Run ollama `stack run /$USER/.llama/distributions/llamastack-ollama/ollama-run.yaml --port 5001`
- Client test command: `python - m agents.test_agents.TestAgents.test_create_agent_turn_with_tavily_search`, with enviroments:
MASTER_ADDR=0.0.0.0;MASTER_PORT=5001;RANK=0;REMOTE_STACK_HOST=0.0.0.0;REMOTE_STACK_PORT=5001;TAVILY_SEARCH_API_KEY=tvly-<YOUR-KEY>;WORLD_SIZE=1
Test passes on the specific case (ollama remote).
Server output: 
```
Listening on ['::', '0.0.0.0']:5001
INFO:     Started server …
```
> Support Tavily as built-in search tool.

- llama_stack/providers/remote/memory/chroma/chroma.py
- llama_stack/providers/remote/memory/pgvector/pgvector.py
The chroma provider maintains a cache but does not sync up with chroma on a cold start. this change adds a fallback to read from chroma on a cache miss.
```bash
#start stack
llama stack run /Users/dineshyv/.llama/distributions/llamastack-together/together-run.yaml
PYTHONPATH=. python -m examples.agents.rag_with_memory_bank localhost 5000
No available shields. Disable safety.
Using model: Llama3.1-8B-Instruct
Created session_id=b951b14f-a9d2-43a3-8b80-d80114d58322 for Agent(0687a251-6906-4081-8d4c-f52e19db9dd7)
memory_retrieval> Retrieved context from banks: ['test_bank'].
====
Here are the retrieved documents for relevant context:
=== START-RETRIEVED-CONTEXT ===
id:num-1; content:_
the template from Llama2 to better support multiturn conversations. The same text
in the Lla...
>
inference> …
```
> fall to back to read from chroma/pgvector when not in cache

- llama_stack/distribution/routers/routing_tables.py
Remove a check which skips provider registration if a resource is already in stack registry. Since we do not reconcile state with provider, register should always call into provider's register endpoint.
```
╰─❯ llama stack run /Users/dineshyv/.llama/distributions/llamastack-together/together-run.yaml
#register memory bank
❯ llama-stack-client memory_banks register your_memory_bank_name --type vector --provider-id inline::faiss-0
Memory Bank Configuration:
{
│   'memory_bank_type': 'vector',
│   'chunk_size_in_tokens': 512,
│   'embedding_model': 'all-MiniLM-L6-v2',
│   'overlap_size_in_tokens': 64
}
#register again
❯ llama-stack-client memory_banks register your_memory_bank_name --type vector --provider-id inline::faiss-0
Memory Bank Configuration:
{
│   'memory_bank_type': 'vector',
│ …
```
> register with provider even if present in stack

- llama_stack/cli/stack/run.py
- llama_stack/distribution/build_container.sh
- llama_stack/distribution/server/server.py
When running with dockers, the idea is that users be able to work purely with the `llama stack` CLI. They should not need to know about the existence of any YAMLs unless they need to. This PR enables it.
The docker command now doesn't need to volume mount a yaml and can simply be:
```bash
docker run -v ~/.llama/:/root/.llama \
--env A=a --env B=b
```
Check with conda first (no regressions):
```bash
LLAMA_STACK_DIR=. llama stack build --template ollama
llama stack run ollama --port 5001
```
Check with docker
```bash
LLAMA_STACK_DIR=. llama stack build --template ollama --image-type docker
export INFERENCE_MODEL="meta-llama/Llama-3.2-3B-Instruct"
docker run -it  -p 5001:5001 \
-v ~/.llama:/root/.llama \
-v $PWD:/app/llama-stack-source \
localhost/distribution-ollama:dev \
--port 5001 \ …
```
> Make run yaml optional so dockers can start with just --env

- llama_stack/cli/stack/build.py
- llama_stack/providers/registry/safety.py
Safety provider `inline::meta-reference` is now deprecated. However, we 
* aren't checking / printing the deprecation message in `llama stack build`
* make the deprecated (unusable) provider
So I (1) added checking and (2) made `inline::llama-guard` the default
Before
```
File "/home/dalton/.conda/envs/nov22/bin/llama", line 8, in <module>
sys.exit(main())
File "/home/dalton/all/llama-stack/llama_stack/cli/llama.py", line 46, in main
parser.run(args)
File "/home/dalton/all/llama-stack/llama_stack/cli/llama.py", line 40, in run
args.func(args)
File "/home/dalton/all/llama-stack/llama_stack/cli/stack/build.py", line 177, in _run_stack_build_command
self._run_stack_build_command_from_build_config(build_config)
File …
```
> Fix `llama stack build` in 0.0.54

- llama_stack/apis/models/client.py
- llama_stack/distribution/server/server.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/agents/meta_reference/agents.py
- llama_stack/providers/inline/agents/meta_reference/persistence.py
- llama_stack/providers/inline/eval/meta_reference/eval.py
- llama_stack/providers/inline/memory/faiss/faiss.py
- llama_stack/providers/remote/memory/chroma/chroma.py
- llama_stack/providers/remote/telemetry/opentelemetry/config.py
- llama_stack/providers/remote/telemetry/opentelemetry/opentelemetry.py
- llama_stack/providers/utils/telemetry/tracing.py
This PR fixes some of the issues with our telemetry setup to enable logs to be delivered to opentelemetry and jaeger. Main fixes
1) Updates the open telemetry provider to use the latest oltp exports instead of deprected ones.
2) Adds a tracing middleware, which injects traces into each HTTP request that the server recieves and this is going to be the root trace. Previously, we did this in the create_dynamic_route method, which is actually not the actual exectuion flow, but more of a config and this causes the traces to end prematurely. Through middleware, we plugin the trace start and end at the right location.
3) We manage our own methods to create traces and spans and this does not fit well with Opentelemetry SDK since it does not support provide a way to take in traces and spans that …
> Fix opentelemetry adapter

- llama_stack/providers/remote/inference/ollama/ollama.py
Update the llama model supported list for Ollama.
> Update Ollama supported llama model list

- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/tests/inference/fixtures.py
* Add a test fixture for tgi
* Fixes the logic to correctly pass the llama model for chat completion
Fixes #514
pytest -k "tgi" llama_stack/providers/tests/inference/test_text_inference.py --env TGI_URL=http://localhost:$INFERENCE_PORT --env TGI_API_TOKEN=$HF_TOKEN
> Tgi fixture

- llama_stack/distribution/request_headers.py
- llama_stack/providers/inline/scoring/braintrust/__init__.py
- llama_stack/providers/inline/scoring/braintrust/braintrust.py
- llama_stack/providers/inline/scoring/braintrust/config.py
- llama_stack/providers/registry/scoring.py
- llama_stack/providers/tests/eval/conftest.py
- llama_stack/providers/tests/eval/fixtures.py
- llama_stack/providers/tests/scoring/fixtures.py
- braintrust scoring provider requires OPENAI_API_KEY env variable to be set
- move this to be able to be set as request headers (e.g. like together / fireworks api keys) 
- fixes pytest with agents dependency
**E2E**
```
llama stack run 
```
```yaml
scoring:
- provider_id: braintrust-0
provider_type: inline::braintrust
config: {}
```
**Client**
```python
self.client = LlamaStackClient(
base_url=os.environ.get("LLAMA_STACK_ENDPOINT", "http://localhost:5000"),
provider_data={
"openai_api_key": os.environ.get("OPENAI_API_KEY", ""),
},
)
```
- run `llama-stack-client eval run_scoring`
**Unit Test**
```
pytest -v -s -m meta_reference_eval_together_inference eval/test_eval.py
```
```
pytest -v -s -m braintrust_scoring_together_inference scoring/test_scoring.py --env …
```
> fixes tests & move braintrust api_keys to request headers

- llama_stack/providers/remote/inference/nvidia/config.py
this allows setting an NVIDIA_BASE_URL variable to control the NVIDIAConfig.url option
`pytest -s -v --providers inference=nvidia llama_stack/providers/tests/inference/ --env NVIDIA_BASE_URL=http://localhost:8000`
> allow env NVIDIA_BASE_URL to set NVIDIAConfig.url

- README.md
- docs/source/contributing/new_api_provider.md
- docs/source/distributions/self_hosted_distro/meta-reference-gpu.md
- docs/source/distributions/self_hosted_distro/meta-reference-quantized-gpu.md
- docs/to_situate/developer_cookbook.md
- docs/zero_to_hero_guide/README.md
- llama_stack/templates/meta-reference-gpu/doc_template.md
- llama_stack/templates/meta-reference-quantized-gpu/doc_template.md
Many of the URLs pointing to the Llama Stack's Read The Docs webpages were broken, presumably due to recent refactor of the documentation. This PR fixes all effected URLs throughout the repository.
> Fix URLs to Llama Stack Read the Docs Webpages

- docs/zero_to_hero_guide/README.md
Fixes readme to remove redundant information and added llama-stack-client cli instructions.
- [ X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ X] Ran pre-commit to handle lint / formatting issues.
- [ X] Read the [contributor guideline](https://github.com/meta-llama/llama-stack/blob/main/CONTRIBUTING.md),
- [ X] Updated relevant documentation.
> Guide readme fix

- docs/source/distributions/self_hosted_distro/ollama.md
Fixes a broken Ollama link and formatting on this page: https://llama-stack.readthedocs.io/en/latest/distributions/self_hosted_distro/ollama.html
To:
> Fix broken Ollama link

- llama_stack/providers/tests/inference/test_text_inference.py
i find `test_structured_output` to be flakey. it's both a functionality and accuracy test -
```
answer = AnswerFormat.model_validate_json(response.completion_message.content)
assert answer.first_name == "Michael"
assert answer.last_name == "Jordan"
assert answer.year_of_birth == 1963
assert answer.num_seasons_in_nba == 15
```
it's an accuracy test because it checks the value of first/last name, birth year, and num seasons.
i find that -
- llama-3.1-8b-instruct and llama-3.2-3b-instruct pass the functionality portion
- llama-3.2-3b-instruct consistently fails the accuracy portion (thinking MJ was in the NBA for 14 seasons)
- llama-3.1-8b-instruct occasionally fails the accuracy portion
suggestions (not mutually exclusive) -
1. turn the test into functionality only, skip the value checks
2. …
> reduce the accuracy requirements to pass the chat completion structured output test

- docs/source/distributions/importing_as_library.md
- llama_stack/providers/remote/inference/ollama/ollama.py
1. removed [incorrect assertion](https://github.com/meta-llama/llama-stack/blob/435f34b05e84f1747b28570234f25878cf0b31c4/llama_stack/providers/remote/inference/ollama/ollama.py#L183) in ollama.py
2. fixed a typo in [this line](https://github.com/meta-llama/llama-stack/blob/435f34b05e84f1747b28570234f25878cf0b31c4/docs/source/distributions/importing_as_library.md?plain=1#L24), as `model=` should be `model_id=` .
tested with code:
```python
import asyncio
import os
from llama_stack_client.lib.direct.direct import LlamaStackDirectClient
from llama_stack_client.types import SystemMessage, UserMessage
async def main():
os.environ["INFERENCE_MODEL"] = "meta-llama/Llama-3.2-1B-Instruct"
client = await LlamaStackDirectClient.from_template("ollama")
await client.initialize()
response = await …
```
> removed assertion in ollama.py and fixed typo in the readme

- llama_stack/apis/safety/client.py
When running:
python -m llama_stack.apis.safety.client localhost 5000
The API server was logging:
INFO:    ::1:57176 - "POST /safety/run_shield HTTP/1.1" 404 Not Found
This patch uses the versioned API, uses the updated safety endpoint, and updates the model name to what's being served. The above python command now demonstrates a passing and failing example.
> Fix up safety client for versioned API

- README.md
- llama_stack/providers/inline/telemetry/meta_reference/config.py
- llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
#525 introduced a telemetry configuration named jaeger, but what it really is pointing to is an OTLP HTTP endpoint which is supported by most servers in the ecosystem, including raw opentelemetry collectors, several APMs, and even https://github.com/ymtdzzz/otel-tui
I chose to rename this to "otel" as it will bring in more people to the ecosystem vs feeling it only works with jaeger.  Later, we can use the [standard ENV](https://opentelemetry.io/docs/specs/otel/protocol/exporter/) to configure this if we like so that you can override things with variables people might expect.
Note: I also added to the README that you have to install conda. Depending on experience level of the user, and especially with miniforge vs other ways, I felt this helps.
I would like to test this, but actually got …
> Renames otel config from jaeger to otel

- docs/source/getting_started/index.md
Addresses a few errors I got when running the quick start guide: https://llama-stack.readthedocs.io/en/latest/getting_started/index.html. We should keep this up to date to maintain engagement with the community.
I've annotated the PR below. Could you PTAL 🙏 ?
> doc: quickstart guide errors

- docs/source/distributions/ondevice_distro/android_sdk.md
Updating the kotlin docs to refer to version 0.0.54.1 of the SDK instead of 0.0.54 because we discovered a bug in 0.0.54 where local module as a dependencies are not included automatically. See https://github.com/meta-llama/llama-stack-client-kotlin/commit/593ed21d5f91934b2486a93de4c19b1b38ae4708
docs changes. Changes are tested on the llama stack apps side separately and verified to be working
> Bump kotlin docs to 0.0.54.1

- llama_stack/distribution/build.py
- llama_stack/distribution/library_client.py
- llama_stack/distribution/tests/library_client_test.py
- llama_stack/providers/remote/inference/ollama/ollama.py
This PR does a few things:
- it moves "direct client" to llama-stack repo instead of being in the llama-stack-client-python repo
- renames it to `LlamaStackLibraryClient`
- actually makes synchronous generators work 
- makes streaming and non-streaming work properly
In many ways, this PR makes things finally "work"
See a `library_client_test.py` I added. This isn't really quite a test yet but it demonstrates that this mode now works. Here's the invocation and the response:
```
INFERENCE_MODEL=meta-llama/Llama-3.2-3B-Instruct python llama_stack/distribution/tests/library_client_test.py ollama
```
> Make LlamaStackLibraryClient work correctly

- README.md
I think I misunderstood the meaning of “single node” when describing the type of the Cerebras integration. It should be hosted instead of single node as the inference is done via API call.
cc: @ashwinb @raghotham 
> Update integration type for Cerebras to hosted

- docs/source/building_applications/telemetry.md
- A follow-up for #572
- The command in the original PR did not run
- Remove `--set` command unnecessary since Jaeger 2.1.0
```
$ docker run --rm --name jaeger \
-p 16686:16686 -p 4318:4318 \
jaegertracing/jaeger:2.1.0
2024/12/07 19:07:13 application version: git-commit=65cff3c30823ea20d3dc48bae39d5685ae307da5, git-version=v2.1.0, build-date=2024-12-06T21:17:15Z
...
```
> Fix Jaeger instructions

- llama_stack/cli/stack/build.py
- llama-stack build --config help text references example_configs which no longer exists
- Update to refer new directory format to avoid confusion
> doc: llama-stack build --config help text references old directory

- docs/source/contributing/new_api_provider.md
- docs/source/distributions/configuration.md
Fixed some typos that I spotted while reading the new/updated docs.
> Fix some typos in distributions/providers docs

- llama_stack/apis/memory_banks/memory_banks.py
- llama_stack/apis/models/models.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/distribution/store/registry.py
- llama_stack/providers/utils/inference/model_registry.py
This PR adds a new model type field to support embedding models to be registered. Summary of changes:
1) Each registered model by default is an llm model. 
2) User can specify an embedding model type, while registering.If specified, the model bypass the llama model checks since embedding models can by of any type and based on llama.
3) User needs to include the  required embedding dimension in metadata. This will be used by embedding generation to generate the requried size of embeddings.
This PR will go together will need to be merged with two follow up PRs that will include test plans.
> add model type to APIs

- llama_stack/providers/tests/eval/conftest.py
- llama_stack/providers/tests/eval/fixtures.py
- llama_stack/providers/tests/eval/test_eval.py
- llama_stack/providers/tests/scoring/conftest.py
- llama_stack/providers/tests/scoring/fixtures.py
- llama_stack/providers/tests/scoring/test_scoring.py
- remove model registration & parameterize model in scoring/eval pytests
```
pytest -v -s -m meta_reference_eval_together_inference eval/test_eval.py
pytest -v -s -m meta_reference_eval_together_inference_huggingface_datasetio eval/test_eval.py
```
```
pytest -v -s -m llm_as_judge_scoring_together_inference scoring/test_scoring.py --judge-model meta-llama/Llama-3.2-3B-Instruct
pytest -v -s -m basic_scoring_together_inference scoring/test_scoring.py
```
> refactor scoring/eval pytests

- llama_stack/providers/remote/datasetio/huggingface/huggingface.py
**Why**
- huggingface datasets could have extra unused columns, some of these columns (e.g. images) is unable to be casted as JSON over http requests for datasetio. 
- it is also inefficient to create a new dataset that's a subset of columns
**Solution**
- drop columns not specified by dataset schema
Tested with script: https://gist.github.com/yanxi0830/23be5725e0d82d79e24cc5dd1d21b571
> [/datasetio] drop columns not specified by dataset schema for huggingface provider

- llama_stack/providers/inline/memory/faiss/__init__.py
- llama_stack/providers/inline/memory/faiss/faiss.py
- llama_stack/providers/registry/memory.py
- llama_stack/providers/remote/memory/chroma/__init__.py
- llama_stack/providers/remote/memory/chroma/chroma.py
- llama_stack/providers/remote/memory/pgvector/__init__.py
- llama_stack/providers/remote/memory/pgvector/pgvector.py
- llama_stack/providers/remote/memory/qdrant/__init__.py
- llama_stack/providers/remote/memory/qdrant/qdrant.py
- llama_stack/providers/remote/memory/weaviate/__init__.py
- llama_stack/providers/remote/memory/weaviate/weaviate.py
- llama_stack/providers/tests/memory/conftest.py
- llama_stack/providers/tests/memory/fixtures.py
- llama_stack/providers/tests/memory/test_memory.py
- llama_stack/providers/utils/memory/vector_store.py
Moves all the memory providers to use the inference API and improved the memory tests to setup the inference stack correctly and use the embedding models
torchrun $CONDA_PREFIX/bin/pytest -v -s -k "meta_reference" --inference-model="Llama3.2-3B-Instruct"  --embedding-model="sentence-transformers/all-MiniLM-L6-v2"  llama_stack/providers/tests/inference/test_embeddings.py --env EMBEDDING_DIMENSION=384
pytest -v -s llama_stack/providers/tests/memory/test_memory.py --providers="inference=together,memory=weaviate" --embedding-model="togethercomputer/m2-bert-80M-2k-retrieval"  --env EMBEDDING_DIMENSION=768  --env TOGETHER_API_KEY=<API-KEY> --env WEAVIATE_API_KEY=foo --env WEAVIATE_CLUSTER_URL=bar
pytest -v -s llama_stack/providers/tests/memory/test_memory.py …
> Vector store inference api

- README.md
@ashwinb sorry I missed this earlier in https://github.com/meta-llama/llama-stack/pull/604.
> Add missing environments field for vLLM provider

- .gitignore
- docs/openapi_generator/generate.py
- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- docs/source/building_applications/index.md
- llama_stack/apis/telemetry/telemetry.py
- llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
- llama_stack/providers/utils/telemetry/dataset_mixin.py
- llama_stack/providers/utils/telemetry/sqlite_trace_store.py
- llama_stack/providers/utils/telemetry/trace_protocol.py
We cannot use recursive types because not only does our OpenAPI generator not like them, even if it did, it is not easy for all client languages to automatically construct proper APIs (especially considering garbage collection) around them. For now, we can return a `Dict[str, SpanWithStatus]` instead of `SpanWithChildren` and rely on the client to reconstruct the tree.
Also fixed a super subtle issue with the OpenAPI generation process (monkey-patching of json_schema_type wasn't working because of import reordering.)
> Update Telemetry API so OpenAPI generation can work

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/remote/inference/bedrock/bedrock.py
- llama_stack/templates/bedrock/bedrock.py
**Why**
- When AgentConfig has no `input_shields` / `output_shields` defined, we still outputs a shield_call step with violation=None. This is impossible to distinguish the case b/w (1) no violation from running shields v.s. (2) no shields call
**What**
- We should not have a shield_call step when no `input_shields` / `output_shields` are defined. 
- Also removes a never reached try/catch code block in agent loop. `run_multiple_shields` is never called in the try block (verified by stacktrace print)
**Side Note**
- pre-commit fix
Tested w/ DirectClient via: https://gist.github.com/yanxi0830/b48f2a53b6f5391b9ff1e39992bc05b3
**No Shields**
**With Input + Output Shields**
**Input Shields Only**
E2E pytest
```
LLAMA_STACK_BASE_URL=http://localhost:5000 pytest -v …
```
> [bugfix] no shield_call when there's no shields configured

- README.md
This PR fixes a broken link in the README.md that was causing a 404 error. The link to `getting_started.ipynb` was pointing to a non-existent file. Updated it to point to the correct notebook `Llama_Stack_Building_AI_Applications.ipynb` which contains the walk-through for text and vision inference llama_stack_client APIs.
1. Verified that the new notebook path exists:
```bash
ls docs/notebooks/Llama_Stack_Building_AI_Applications.ipynb
```
2. Verified the notebook content contains text and vision inference examples by:
- Checking the notebook contents
- Confirming the presence of vision models like Llama-3.2-11B-Vision-Instruct
- Verifying llama_stack_client API usage examples
> docs: Update getting_started.ipynb link to correct jupyter notebook path in README.md

- docs/source/distributions/self_hosted_distro/cerebras.md
- llama_stack/providers/remote/inference/cerebras/cerebras.py
- llama_stack/templates/cerebras/run.yaml
Cerebras is rolling out support for llama 3.3 70b and deprecating llama 3.1 70b. This PR updates the documentation, config, and internal mapping to reflect this change.
cc: @ashwinb @raghotham
> Update Cerebras from Llama 3.1 to 3.3

- llama_stack/providers/utils/telemetry/trace_protocol.py
- llama_stack/providers/utils/telemetry/tracing.py
Serialize objects to built in types to avoid otel warnings
╰─❯ llama stack run ~/.llama/distributions/llamastack-together/together-run.yaml
> store attributes values in builtin types to avoid otel warnings

- llama_stack/providers/remote/inference/nvidia/openai_utils.py
```
from .nvidia import NVIDIAInferenceAdapter
File "/localhome/local-cdgamarose/llama-stack/llama_stack/providers/remote/inference/nvidia/nvidia.py", line 37, in <module>
from .openai_utils import (
File "/localhome/local-cdgamarose/llama-stack/llama_stack/providers/remote/inference/nvidia/openai_utils.py", line 11, in <module>
from llama_models.llama3.api.datatypes import (
ImportError: cannot import name 'CompletionMessage' from 'llama_models.llama3.api.datatypes' (/localhome/local-cdgamarose/.local/lib/python3.10/site-packages/llama_models/llama3/api/datatypes.py)
++ error_handler 62
```
Deploy NIM using docker from …
> Fixed imports for inference

- llama_stack/apis/tools/tools.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/inline/tool_runtime/brave_search/brave_search.py
- llama_stack/providers/registry/tool_runtime.py
- llama_stack/providers/remote/tool_runtime/model_context_protocol/__init__.py
- llama_stack/providers/remote/tool_runtime/model_context_protocol/config.py
- llama_stack/providers/remote/tool_runtime/model_context_protocol/model_context_protocol.py
Changes:
* Adds a new API to discover tools available on a runtime
* Adds a new model context protocol provider
```
uv run mcp-simple-tool --transport sse --port 56000
curl -X POST 'http://localhost:5000/alpha/toolgroups/register' \
-H 'Content-Type: application/json' \
-d '{
"tool_group": { "name": "simple_mcp_group",
"type": "model_context_protocol",
"endpoint": {"uri": "http://localhost:56000/sse"}
},
"provider_id": "model-context-protocol"
}'
curl -X POST 'http://localhost:5000/alpha/tool-runtime/invoke' \
-H 'Content-Type: application/json' \
-d '{
"tool_id": "fetch",
"args": {
"url": "http://google.com/"
}
}'
```
> add model context protocol provider

- llama_stack/providers/remote/inference/fireworks/config.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/utils/inference/prompt_adapter.py
- llama_stack/templates/fireworks/run.yaml
- Makes Llama 70B 3.3 available for fireworks
```shell
pip install -e . \
&& llama stack build --config distributions/fireworks/build.yaml --image-type conda \
&& llama stack run distributions/fireworks/run.yaml \
--port 5000
```
```python
response = client.inference.chat_completion(
model_id="Llama3.3-70B-Instruct",
messages=[
{"role": "user", "content": "hello world"},
],
)
```
> Add Llama 70B 3.3 to fireworks

- llama_stack/providers/inline/eval/meta_reference/eval.py
- llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
- llama_stack/templates/experimental-post-training/build.yaml
- llama_stack/templates/experimental-post-training/run.yaml
- Add related Apis in experimental-post-training template to enable eval on the finetuned checkpoint in the template
- A small bug fix on meta reference eval
- A small error handle improvement on post training 
From client side issued an E2E post training request https://github.com/meta-llama/llama-stack-client-python/pull/70 and get eval results successfully
> [torchtune integration] post training + eval

- llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
There is a torchtune release this morning https://github.com/pytorch/torchtune/releases/tag/v0.5.0 and breaks post training apis
spinning up server and the post training works again after the fix 
We need to think hard of how to avoid this happen again and have a fast follow up on this after holidays
> Fix post training apis broken by torchtune release

- README.md
This is not needed since `conda activate stack` has already been executed.
> Removed unnecessary CONDA_PREFIX env var in installation guide

- llama_stack/providers/remote/inference/ollama/ollama.py
Adds 3.3 70B support to Ollama inference provider
<details>
<summary>Manual</summary>
```bash
ollama pull llama3.3:70b
ollama run llama3.3:70b --keepalive 60m
export LLAMA_STACK_PORT=5000
pip install -e . \
&& llama stack build --template ollama --image-type conda \
&& llama stack run ./distributions/ollama/run.yaml \
--port $LLAMA_STACK_PORT \
--env INFERENCE_MODEL=Llama3.3-70B-Instruct \
--env OLLAMA_URL=http://localhost:11434
export LLAMA_STACK_PORT=5000
llama-stack-client --endpoint http://localhost:$LLAMA_STACK_PORT \
inference chat-completion \
--model-id Llama3.3-70B-Instruct \
--message "hello, what model are you?"
```
</details>
> Add 3.3 70B to Ollama inference provider

- docs/source/distributions/building_distro.md
This fixes the following errors:
```
ValueError: Provider `meta-reference` is not available for API `agents`
ValueError: Provider `meta-reference` is not available for API `telemetry`
```
> Add missing "inline::" prefix for providers in building_distro.md

- llama_stack/distribution/ui/page/evaluations/app_eval.py
- llama_stack/distribution/ui/page/evaluations/native_eval.py
- llama_stack/providers/utils/telemetry/trace_protocol.py
This fixes the pre-commit check when running locally (not sure why this was not caught on CI check):
```
> pre-commit run --show-diff-on-failure --color=always --all-files
trim trailing whitespace.................................................Passed
check python ast.........................................................Passed
check for merge conflicts................................................Passed
check for added large files..............................................Passed
fix end of files.........................................................Passed
Insert license in comments...............................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1 …
```
> Fix failing flake8 E226 check

- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/tests/inference/test_text_inference.py
Addresses issue #679
- Adds support for the response_format field for chat completions and completions so users can get their outputs in JSON
<details>
<summary>Integration tests</summary>
`pytest llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_structured_output -k ollama -s -v`
```python
llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_structured_output[llama_8b-ollama] PASSED
llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_structured_output[llama_3b-ollama] PASSED
================================== 2 passed, 18 deselected, 3 warnings in 41.41s ==================================
```
</details>
<details>
<summary>Manual Tests</summary>
```
export …
```
> Add JSON structured outputs to Ollama Provider

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Contributes to issue (#407)
tl;dr - @subramen was getting a 500 error because llama-stack called code_interpreter when it never was defined as a tool.
Prevents failures like:
```
File "/opt/conda/envs/llamastack-vllm-stack/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 206, in sse_generator
async for item in await event_gen:
File "/opt/conda/envs/llamastack-vllm-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agents.py", line 138, in _create_agent_turn_streaming
async for event in agent.create_and_execute_turn(request):
File "/opt/conda/envs/llamastack-vllm-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 179, in …
```
> [#407] Agents: Avoid calling tools that haven't been explicitly enabled

- docs/zero_to_hero_guide/00_Inference101.ipynb
- docs/zero_to_hero_guide/README.md
Pinning zero2hero to 0.0.61 and updated readme
- Did a end to end test on the server and inference for 0.0.61
Server output:
> Made changes to readme and pinning to llamastack v0.0.61

- llama_stack/providers/inline/post_training/torchtune/common/utils.py
- llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
Post training apis are broken after the import * refactor https://github.com/meta-llama/llama-stack/pull/689. This PR is adding the missing import back
Issue a post training request from client and the training finishes successfully
> [Post Training] Fix missing import

- llama_stack/templates/experimental-post-training/run.yaml
Colab notebook provides some limited free T4 GPU. 
Making post training template e2e works with colab notebook T4 is critical for early adoption of the stack post training apis. However, we found that the existing LlamaModelParallelGenerator (https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/inline/inference/meta_reference/inference.py#L82) in meta-reference inference implementation isn't compatible with T4 machine. 
In this PR, We change to disable create_distributed_process_group for inference api in post training run.yaml config and setup up the distributed env variables in notebook 
to make meta reference inference compatible with the free T4 machine
Test with the WIP post training showcase colab notebook …
> Change post training run.yaml inference config 

- llama_stack/apis/post_training/post_training.py
- llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
The current code hardcode the validation steps to run (forgot to change it after testing). in this PR, we make it configurable by training config
On client side, issue a post training request with 20 validation steps, server side logging shows that it runs 20 validation steps successfully
> [Post training] make validation steps configurable

- llama_stack/distribution/server/server.py
- llama_stack/distribution/start_container.sh
This fixes the issue when using `llama stack run` by correctly specifying entrypoint:
```
LLAMA_STACK_DIR=. llama stack run /home/yutang/.llama/distributions/llamastack-vllm/vllm-run.yaml
Using config file: /home/yutang/.llama/distributions/llamastack-vllm/vllm-run.yaml
+ command -v selinuxenabled
+ selinuxenabled
+ DOCKER_OPTS=' --security-opt label=disable'
+ mounts=
+ '[' -n . ']'
++ readlink -f .
+ mounts=' -v /home/yutang/repos/llama-stack:/app/llama-stack-source'
+ '[' -n '' ']'
+ version_tag=latest
+ '[' -n '' ']'
+ '[' -n . ']'
+ version_tag=dev
+ podman run --security-opt label=disable -it -p 5000:5000 -v /home/yutang/.llama/distributions/llamastack-vllm/vllm-run.yaml:/app/config.yaml -v /home/yutang/repos/llama-stack:/app/llama-stack-source localhost/distribution-vllm:dev python …
```
> Fix incorrect entrypoint for broken `llama stack run`

- llama_stack/providers/remote/inference/vllm/vllm.py
The current message is incorrect and model arg is not needed in `completion_request_to_prompt`.
> Fix assert message and call to completion_request_to_prompt in remote:vllm

- llama_stack/providers/remote/inference/groq/groq.py
Contributes towards: #432
RE: https://github.com/meta-llama/llama-stack/pull/609
I missed this one while refactoring. Fixes:
```python
File "/Users/aidand/dev/llama-stack/llama_stack/distribution/server/server.py", line 191, in endpoint
return await maybe_await(value)
File "/Users/aidand/dev/llama-stack/llama_stack/distribution/server/server.py", line 155, in maybe_await
return await value
File "/Users/aidand/dev/llama-stack/llama_stack/providers/utils/telemetry/trace_protocol.py", line 101, in async_wrapper
result = await method(self, *args, **kwargs)
File "/Users/aidand/dev/llama-stack/llama_stack/distribution/routers/routers.py", line 156, in chat_completion
return await provider.chat_completion(**params)
File …
```
> Fix Groq invalid self.config reference

- llama_stack/distribution/library_client.py
Remove the default log handlers for notebook to avoid polluting logs
> remove default logger handlers when using libcli with notebook

- llama_stack/providers/inline/eval/meta_reference/eval.py
- llama_stack/providers/inline/scoring/basic/scoring.py
- llama_stack/providers/inline/scoring/braintrust/braintrust.py
- llama_stack/providers/inline/scoring/llm_as_judge/scoring.py
- llama_stack/providers/utils/common/data_schema_validator.py
- there's no value in keeping data schema validation logic in a DataSchemaValidatorMixin
- move into data schema validation logic into standalone utils
```
pytest -v -s -m llm_as_judge_scoring_together_inference scoring/test_scoring.py --judge-model meta-llama/Llama-3.2-3B-Instruct
pytest -v -s -m basic_scoring_together_inference scoring/test_scoring.py
pytest -v -s -m braintrust_scoring_together_inference scoring/test_scoring.py
pytest -v -s -m meta_reference_eval_together_inference eval/test_eval.py
pytest -v -s -m meta_reference_eval_together_inference_huggingface_datasetio eval/test_eval.py
```
> move DataSchemaValidatorMixin into standalone utils

- .github/workflows/release.yml
This PR adds a workflow to automatically publish the package (including attestations) to Python upon tag/release creation.
Note that this relies on trusted publishing: https://docs.pypi.org/trusted-publishers/
> Add automatic PyPI release GitHub workflow

- docs/openapi_generator/pyopenapi/generator.py
- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/distribution/request_headers.py
- llama_stack/providers/inline/scoring/braintrust/braintrust.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/groq/groq.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/remote/tool_runtime/bing_search/bing_search.py
- llama_stack/providers/remote/tool_runtime/brave_search/brave_search.py
- llama_stack/providers/remote/tool_runtime/tavily_search/tavily_search.py
- llama_stack/providers/remote/tool_runtime/wolfram_alpha/wolfram_alpha.py
- llama_stack/providers/tests/resolver.py
Add another header so client SDKs can identify their versions which can be used for immediate detection of possible compatibility issues. A semver mismatch against the wrong server should be immediately flagged and requests should be denied.
Also change `X-LlamaStack-ProviderData` to `X-LlamaStack-Provider-Data` since that hyphenation is better.
> Add X-LlamaStack-Client-Version, rename ProviderData -> Provider-Data

- llama_stack/distribution/server/server.py
When we bump up `major.minor` we want to make sure clients can immediately detect a version change and appropriately error out. It is not reasonable to keep checking for API-level backwards compatibility across such version bumps. Over time, we will make the check based only on the major version perhaps.
Manually updated `__version__` in the client SDK to be "0.1.0" which is incompatible with server's current version "0.0.63", got the following error: 
Without this update, the CLI worked correctly.
> Check version incompatibility

- llama_stack/providers/inline/datasetio/localfs/config.py
- llama_stack/providers/inline/datasetio/localfs/datasetio.py
Add persistency logic for localfs datasetio provider
https://github.com/meta-llama/llama-stack/issues/539
> Add persistence for localfs datasets

- tests/client-sdk/memory/test_memory.py
Summary:
Part of https://github.com/meta-llama/llama-stack/issues/651
Requirements
* add more integration tests in tests/client-sdk covering functionalities in llama-stack-apps
Porting tests from
* llama_stack/providers/tests/memory/test_memory.py
Ensuring we cover some basic functions
* MemoryResource src/llama_stack_client/resources/memory.py
* MemoryBanksResource src/llama_stack_client/resources/memory_banks.py
Test Plan:
Run against the stack as lib
```
LLAMA_STACK_CONFIG=tests/client-sdk/memory/resources/run.yaml pytest tests/client-sdk/memory -v
tests/client-sdk/memory/test_memory.py::test_memory_bank_retrieve PASSED                                                                                                                 [ 16%] …
```
> Consolidating Memory tests under client-sdk

- llama_stack/cli/stack/run.py
This was missed in https://github.com/meta-llama/llama-stack/pull/706. I tested `llama_stack.distribution.server.server` but didn't test `llama stack run`. cc @ashwinb
> Expose LLAMASTACK_PORT in cli.stack.run

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/batch_inference/batch_inference.py
- llama_stack/apis/inference/inference.py
- llama_stack/apis/tools/tools.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/inline/inference/meta_reference/inference.py
- llama_stack/providers/inline/inference/sentence_transformers/sentence_transformers.py
- llama_stack/providers/inline/inference/vllm/vllm.py
- llama_stack/providers/remote/inference/bedrock/bedrock.py
- llama_stack/providers/remote/inference/cerebras/cerebras.py
- llama_stack/providers/remote/inference/databricks/databricks.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/groq/groq.py
- llama_stack/providers/remote/inference/nvidia/nvidia.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/utils/inference/prompt_adapter.py
We are setting a default value of json for tool prompt format, which conflicts with llama 3.2/3.3 models since they use python list. This PR changes the defaults to None and in the code,  we infer default based on the model.
Addresses: #695 
Tests:
❯ LLAMA_STACK_BASE_URL=http://localhost:5000 pytest -v tests/client-sdk/inference/test_inference.py -k "test_text_chat_completion"
pytest llama_stack/providers/tests/inference/test_prompt_adapter.py
> remove conflicting default for tool prompt format in chat completion

- llama_stack/apis/agents/client.py
- llama_stack/providers/utils/kvstore/redis/redis.py
- [Currently redis as a kvstore is bugged, as the range method uses zrangebylex method. zrangebylex method is used when it is a sorted set but we are storing the value using .set method in the redis. This causes an error. Another issue is that zrangebylex method takes 3 args but only 2 are mentioned in the range method. This causes a runtime error. That method has been replaced with the current implementation in the PR ] Addresses issue (#520 )
`python llama_stack/apis/agents/client.py localhost 8001 tools_llama_3_1 …
> Replaced zrangebylex method in the range method

- docs/source/references/llama_cli_reference/download_models.md
The documentation around model download from meta source part https://llama-stack.readthedocs.io/en/latest/references/llama_cli_reference/index.html#downloading-from-meta confused me and another colleague because we met [issue](https://github.com/meta-llama/llama-stack/issues/746) during downloading. 
After some debugging, I found that we need to quote META_URL in the command. To avoid other users have the same confusion, I updated the doc tor make it more clear
before 
after
> Improve model download doc

- llama_stack/distribution/build_container.sh
This adds support for [UBI9 (Red Hat Universal Base Image 9)](https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e). Tested `registry.access.redhat.com/ubi9/ubi-minimal:9.5`.
> Support building UBI9 base container image

- llama_stack/distribution/library_client.py
- llama_stack/providers/remote/tool_runtime/bing_search/__init__.py
- llama_stack/providers/remote/tool_runtime/bing_search/bing_search.py
- llama_stack/providers/remote/tool_runtime/brave_search/__init__.py
- llama_stack/providers/remote/tool_runtime/brave_search/brave_search.py
- llama_stack/providers/remote/tool_runtime/tavily_search/__init__.py
- llama_stack/providers/remote/tool_runtime/tavily_search/tavily_search.py
- llama_stack/providers/remote/tool_runtime/wolfram_alpha/__init__.py
- llama_stack/providers/remote/tool_runtime/wolfram_alpha/wolfram_alpha.py
- tests/client-sdk/conftest.py
This PR adds the provider data passing for the library client and changes the provider's api keys be unique
LLAMA_STACK_CONFIG="/Users/dineshyv/.llama/distributions/llamastack-fireworks/fireworks-run.yaml" pytest -v tests/client-sdk/agents/test_agents.py
run.yaml: https://gist.github.com/dineshyv/0c10b5c7d0a2fb7ba4f0ecc8dcf860d1
> Add provider data passing for library client

- docs/source/distributions/self_hosted_distro/fireworks.md
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/templates/fireworks/run.yaml
Fix https://github.com/meta-llama/llama-stack/issues/697
Run the 405b model. the full `accounts/fireworks/models/<model_id>` is the full model name for Fireworks, the 'fireworks/<model_id>' is just a short hand and sometimes have routing issues
> [Fireworks] Update model name for Fireworks

- tests/client-sdk/inference/test_inference.py
Summary:
Part of https://github.com/meta-llama/llama-stack/issues/651
We are adding more tests to the clients sdk for some basic coverage.
Those tests are inspired by the inference provider tests.
Test Plan:
Run tests via the command
```
LLAMA_STACK_CONFIG=llama_stack/templates/fireworks/run.yaml pytest tests/client-sdk/inference -v
```
Example output
```
tests/client-sdk/inference/test_inference.py::test_completion_non_streaming PASSED                                                                                                                                        [  7%]
tests/client-sdk/inference/test_inference.py::test_completion_streaming PASSED …
```
> Consolidating Inference tests under client-sdk tests

- llama_stack/providers/inline/safety/code_scanner/__init__.py
- llama_stack/templates/fireworks/fireworks.py
- llama_stack/templates/fireworks/run-with-safety.yaml
- llama_stack/templates/ollama/ollama.py
- llama_stack/templates/together/run-with-safety.yaml
- llama_stack/templates/together/together.py
- tests/client-sdk/safety/test_safety.py
Summary:
Extending tests based on the demo from Notebooks here
- https://github.com/meta-llama/llama-stack-apps/tree/main/examples/notebooks
Result coverage
Test Plan:
Ollama
```
LLAMA_STACK_CONFIG=tests/client-sdk/safety/resources/ollama.yaml pytest tests/client-sdk/safety -v
================================================================================================ test session starts =================================================================================================
platform darwin -- Python 3.11.10, pytest-8.3.3, pluggy-1.5.0 -- /opt/homebrew/Caskroom/miniconda/base/envs/llama-stack/bin/python
rootdir: /Users/vivic/Code/llama-stack
plugins: asyncio-0.24.0, anyio-4.6.2.post1
asyncio: mode=Mode.STRICT, …
```
> Consolidating Safety tests from various places under client-sdk

- .github/workflows/publish-to-test-pypi.yml
- Context: Our current `sleep 10` may not be enough time for uploaded testpypi to be able to be downloadable. 
- Solution: Add re-try logic for at most 1 minute to download testpypi package and test the downloaded package. 
- Triggered workflow: https://github.com/meta-llama/llama-stack/actions/runs/12753561894/job/35545490629?pr=749
> [CI/CD] more robust re-try for downloading testpypi package

- llama_stack/providers/remote/inference/groq/groq.py
- llama_stack/providers/remote/inference/groq/groq_utils.py
- llama_stack/providers/tests/inference/groq/test_groq_utils.py
- llama_stack/providers/tests/inference/test_text_inference.py
Contributes to issue #432
- Adds tool calls to Groq provider
- Enables tool call integration tests
- https://github.com/meta-llama/llama-stack/pull/609 
- https://github.com/meta-llama/llama-stack/pull/630 👈
Environment:
```shell
export GROQ_API_KEY=<api-key>
wget https://raw.githubusercontent.com/aidando73/llama-stack/9165502582cd7cb178bc1dcf89955b45768ab6c1/build.yaml
wget https://raw.githubusercontent.com/aidando73/llama-stack/9165502582cd7cb178bc1dcf89955b45768ab6c1/run.yaml
conda create --prefix ./envs python=3.10
conda activate ./envs
pip install -e . && llama stack build --config ./build.yaml --image-type conda
conda activate llamastack-groq
```
<details>
<summary>Unit tests</summary>
```shell
conda activate llamastack-groq
pytest …
```
> [#432] Add Groq Provider - tool calls

- llama_stack/distribution/build_container.sh
This was missed during a rebase in https://github.com/meta-llama/llama-stack/pull/676. 
Fixed the following error:
```
Error: crun: executable file `python` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
++ error_handler 88
++ echo 'Error occurred in script at line: 88'
Error occurred in script at line: 88
```
cc @hardikjshah
> Fix incorrect Python binary path for UBI9 image

- llama_stack/cli/model/prompt_format.py
- llama_stack/cli/stack/build.py
- llama_stack/cli/stack/run.py
- llama_stack/distribution/build.py
- llama_stack/distribution/stack.py
`pkg_resources` has been deprecated. This PR switches to use `importlib.resources`.
> Switch to use importlib instead of deprecated pkg_resources

- llama_stack/distribution/library_client.py
- Using Jupyter notebook with LlamaStackAsLibraryClient + streaming gives exception
```
Exception ignored in: <async_generator object HTTP11ConnectionByteStream.__aiter__ at 0x32a95a740>
File "/opt/anaconda3/envs/fresh/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 404, in _aiter_
yield part
RuntimeError: async generator ignored GeneratorExit
```
- Reproduce w/ https://github.com/meta-llama/llama-stack/blob/notebook-streaming-debug/inline.ipynb
- Issue likely comes from stream_across_asyncio_run_boundary closing connection too soon when interacting in jupyter environment
- This uses an alternative way to convert AsyncStream to SyncStream return type by sync version of LlamaStackAsLibraryClient, which calls …
> [bugfix] fix streaming GeneratorExit exception with LlamaStackAsLibraryClient

- llama_stack/cli/stack/build.py
- llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
- llama_stack/providers/utils/telemetry/tracing.py
Since we maintain global state in our telemetry pipeline, reinstantiating lib cli will cause us to add duplicate span processors causing sqlite to lock out because of constraint violations since we now have two span processor writing to sqlite. This PR changes the telemetry adapter for otel to only instantiate the provider once and add the span processsors only once.
Also fixes an issue llama stack build
tested with notebook at https://colab.research.google.com/drive/1ck7hXQxRl6UvT-ijNRZ-gMZxH1G3cN2d#scrollTo=9496f75c
> Fix telemetry to work on reinstantiating new lib cli

- llama_stack/distribution/build_conda_env.sh
- llama_stack/distribution/build_container.sh
To build a conda env for specific Llama Stack version, e.g.
`PYPI_VERSION=0.0.58 llama stack build --template together --image-type conda`
will install these in the llamastack-together env:
```
llama_models                             0.0.58
llama_stack                              0.0.58
llama_stack_client                       0.0.58
```
Without `PYPI_VERSION=`, `llama stack build --template together --image-type conda` installs the latest all.
> added support of PYPI_VERSION in stack build

- llama_stack/distribution/store/tests/test_registry.py
Summary:
Tests were broken after registry.get return type was changed from `List[RoutableObjectWithProvider]` to `Optional[RoutableObjectWithProvider]` in https://github.com/meta-llama/llama-stack/commit/efe791bab7f6dedb89707e500639c4355bc36942#diff-5de152bae521b7baef01048a4c0142484f8f1c978a04f3b55f4e4dabc52835beL29
Test Plan:
Run tests
```
pytest llama_stack/distribution/store/tests/test_registry.py -v
collected 6 items
llama_stack/distribution/store/tests/test_registry.py::test_registry_initialization PASSED                                                                  [ 16%]
llama_stack/distribution/store/tests/test_registry.py::test_basic_registration PASSED                                                                       [ 33%] …
```
> Fix broken tests in test_registry

- llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
Currently, the GPU memory will be continuously occupied after the training finishes. In this PR, we explicitly delete the reference and clean up the memory after training finishes. 
Before the change, after training a llama 3.2 3B model, >6GB GPU memory is still occupied
After the change,  after training a llama 3.2 3B model, the GPU memory drops to ~1GB
> Free up memory after post training finishes

- .github/workflows/publish-to-docker.yml
- llama_stack/cli/stack/build.py
- llama_stack/distribution/build.py
- llama_stack/distribution/build_container.sh
- llama_stack/distribution/utils/exec.py
- Add Github workflow for publishing docker images. 
- Manual Inputs
- We can use a (1) TestPyPi version / (2) build via released PyPi version
**Notes**
- Keep this workflow manually triggered as we don't want to publish nightly docker images
**Additional Changes**
- Resolve issue with running llama stack build in non-terminal device
```
File "/home/runner/.local/lib/python3.12/site-packages/llama_stack/distribution/utils/exec.py", line 25, in run_with_pty
old_settings = termios.tcgetattr(sys.stdin)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
termios.error: (25, 'Inappropriate ioctl for device')
```
- Modified build_container.sh to work in non-terminal environment
- Triggered workflow: https://github.com/meta-llama/llama-stack/actions/runs/12778759161/job/35622178782
- Tested published docker image
- …
> [CICD] Github workflow for publishing Docker images

- docs/openapi_generator/pyopenapi/operations.py
- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/agents/agents.py
- llama_stack/apis/batch_inference/batch_inference.py
- llama_stack/apis/datasetio/datasetio.py
- llama_stack/apis/datasets/datasets.py
- llama_stack/apis/eval/eval.py
- llama_stack/apis/eval_tasks/eval_tasks.py
- llama_stack/apis/inference/inference.py
- llama_stack/apis/inspect/inspect.py
- llama_stack/apis/memory/memory.py
- llama_stack/apis/memory_banks/memory_banks.py
- llama_stack/apis/models/models.py
- llama_stack/apis/post_training/post_training.py
- llama_stack/apis/safety/safety.py
- llama_stack/apis/scoring/scoring.py
- llama_stack/apis/scoring_functions/scoring_functions.py
- llama_stack/apis/shields/shields.py
- llama_stack/apis/telemetry/telemetry.py
- llama_stack/apis/tools/tools.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/distribution/server/server.py
- llama_stack/distribution/stack.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/agents/meta_reference/agents.py
- llama_stack/providers/inline/post_training/torchtune/post_training.py
- llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
- tests/client-sdk/agents/test_agents.py
This PR changes our API to follow more idiomatic REST API approaches of having paths being resources and methods indicating the action being performed.
Changes made to generator:
1) removed the prefix check of "get" as its not required and is actually needed for other method types too
2) removed _ check on path since variables can have "_"
LLAMA_STACK_BASE_URL=http://localhost:5000 pytest -v tests/client-sdk/agents/test_agents.py
> More idiomatic REST API

- llama_stack/providers/tests/inference/test_embeddings.py
- llama_stack/providers/tests/inference/test_vision_inference.py
Fixes two issues on providers/test/inference
```
===================================================================================== FAILURES =====================================================================================
__________________________________ TestVisionModelInference.test_vision_chat_completion_streaming[llama_vision-fireworks][llama_vision] ___________________________________
providers/tests/inference/test_vision_inference.py:145: in test_vision_chat_completion_streaming
content = "".join(
E   TypeError: sequence item 0: expected str instance, TextDelta found
------------------------------------------------------------------------------ Captured log teardown -------------------------------------------------------------------------------
ERROR …
```
> bug fixes on inference tests

- tests/client-sdk/inference/test_inference.py
- fixes client sdk tests
```
LLAMA_STACK_BASE_URL="http://localhost:5000" pytest -v tests/client-sdk/inference/test_inference.py
```
> [bugfix] fix inference sdk test for v1

- llama_stack/distribution/library_client.py
- llama_stack/providers/utils/telemetry/dataset_mixin.py
PR fixes couple of issues with telemetry:
1) The REST refactor changed the method from get_span_tree to query_span_tree, which is causing the server side to return empty spans
2) Library client has introduced a new event loop, which required changing the location of where start and end trace are called
LLAMA_STACK_CONFIG="/Users/dineshyv/.llama/distributions/llamastack-fireworks/fireworks-run.yaml" pytest -v tests/client-sdk/agents/test_agents.py -k "test_builtin_tool_web_search"
And querying for spans from the agent run using the library client.
> Fix telemetry

- llama_stack/apis/inspect/inspect.py
- llama_stack/distribution/inspect.py
Since provider list returns a map grouping providers by API, we should not be using data. This PR fixes the types to just be the plain dict, basically reverting back to previous behavior
llama-stack on  fix-provider-list [$] 🅒 stack❯ LLAMA_STACK_CONFIG="/Users/dineshyv/.llama/distributions/llamastack-together/together-run.yaml" pytest -v tests/client-sdk/safety/test_safety.py
> Idiomatic REST API: Inspect

- .github/workflows/publish-to-test-pypi.yml
Adds testing of the notebook to the nightly build job 
Here is a sample run -- 
https://github.com/meta-llama/llama-stack/actions/runs/12815889197?pr=785
> Add notebook testing to nightly build job

- llama_stack/providers/registry/post_training.py
This is the follow up of https://github.com/meta-llama/llama-stack/pull/674. Since torchtune is still in alpha stage and the apis are not guarantee backward compatible. Pin the torchtune and torchao pkg version to avoid the latest torchtune release breaks llama stack post training. 
We will bump the version number manually after with the new pkg release some testing 
ping an old torchtune pkg version (0.4.0) and the 0.4.0 was installed
> Pin torchtune pkg version

- tests/client-sdk/agents/test_agents.py
remove hardcoded model id for the code execution tests
Tests:
LLAMA_STACK_CONFIG="/Users/dineshyv/.llama/distributions/llamastack-fireworks/fireworks-run.yaml" pytest -v tests/client-sdk/agents/test_agents.py -k "test_code_execution"
> fix the code execution test in sdk tests

- llama_stack/providers/tests/inference/test_text_inference.py
Fixes provider tests
```
pytest -v -s -k "together or fireworks or ollama" --inference-model="meta-llama/Llama-3.1-8B-Instruct" ./llama_stack/providers/tests/inference/test_text_inference.py 
```
```
...
.... 
llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_chat_completion_streaming[-together] PASSED
llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_chat_completion_with_tool_calling[-together] PASSED
llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_chat_completion_with_tool_calling_streaming[-together] PASSED
================ 21 passed, 6 skipped, 81 deselected, 5 warnings in 32.11s =================
```
> fix provider model list test

- llama_stack/providers/utils/inference/openai_compat.py
Fixes error when running an provider using openai_compat.py
```python
File "/home/ubuntu/miniconda3/envs/llamastack-vllm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/ubuntu/miniconda3/envs/llamastack-vllm/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/ubuntu/us-south-2/llama-stack/llama_stack/distribution/server/server.py", line 426, in <module>
main()
File "/home/ubuntu/us-south-2/llama-stack/llama_stack/distribution/server/server.py", line 349, in main
impls = asyncio.run(construct_stack(config))
File "/home/ubuntu/miniconda3/envs/llamastack-vllm/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File …
```
> cannot import name 'GreedySamplingStrategy'

- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/utils/inference/prompt_adapter.py
- previous fix introduced regression for non base64 image
- add back download, and base64 check
> fix again vllm for non base64

- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/tests/inference/test_text_inference.py
- tests/client-sdk/inference/test_inference.py
1) enabled structured output for ollama /completion API. It seems we missed this one. 
2) fixed ollama structured output test in client sdk - ollama does not support list format for structured output
3) enable structured output unit test as the result was stable on Llama-3.1-8B-Instruct and ollama, fireworks, together. 
1) Run `test_completion_structured_output` on /completion API with 3 providers: ollama, fireworks, together.
pytest -v -s -k "together" --inference-model="meta-llama/Llama-3.1-8B-Instruct" llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_completion_structured_output
```
(base) sxyi@sxyi-mbp llama-stack % pytest -s -v llama_stack/providers/tests/inference --config=ci_test_config.yaml …
```
> [ez] structured output for /completion ollama & enable tests

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/tools/rag_tool.py
- llama_stack/apis/vector_io/vector_io.py
- llama_stack/distribution/routers/routers.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/tool_runtime/memory/memory.py
- llama_stack/providers/tests/tools/test_tools.py
- llama_stack/providers/tests/vector_io/test_vector_store.py
- tests/client-sdk/agents/test_agents.py
- tests/client-sdk/tool_runtime/test_rag_tool.py
Making a few small naming changes as per feedback:
- RAGToolRuntime methods are called `insert` and `query` to keep them more general
- The tool names are changed to non-namespaced forms `insert_into_memory` and `query_from_memory`
- The REST endpoints are more REST-ful
> [memory refactor][6/n] Update naming and routes

- llama_stack/providers/remote/inference/fireworks/fireworks.py
Enable downloads before sending request to fireworks. 
Test using -- 
`LLAMA_STACK_CONFIG=./llama_stack/templates/fireworks/run.yaml pytest -s -v -k 'test_image_chat_completion_streaming' tests/client-sdk`
> Fix fireworks client sdk chat completion with images

- llama_stack/templates/fireworks/remote-hosted-report.md
- llama_stack/templates/fireworks/report.md
- tests/client-sdk/report.py
Automates the model list check by querying the distro. 
Added support for both remote hosted and templates. 
Run on a remote hosted distro via 
`LLAMA_STACK_BASE_URL="https://llamastack-preview.fireworks.ai"  pytest -s -v  tests/client-sdk --report`
Run on a template via 
`LLAMA_STACK_CONFIG=fireworks pytest -s -v  tests/client-sdk --report`
> Improved report generation for providers

- tests/client-sdk/agents/test_agents.py
- tests/client-sdk/conftest.py
- tests/client-sdk/inference/test_inference.py
- tests/client-sdk/safety/conftest.py
- tests/client-sdk/safety/test_safety.py
- tests/client-sdk/vector_io/conftest.py
- tests/client-sdk/vector_io/test_vector_io.py
Default inference_model for testing: "meta-llama/Llama-3.1-8B-Instruct"
Default vision inference_model for testing: "meta-llama/Llama-3.2-11B-Vision-Instruct"
`/opt/miniconda3/envs/stack/bin/pytest -s -v --inference-model=meta-llama/Llama-3.2-3B-Instruct tests/client-sdk/agents`
`/opt/miniconda3/envs/stack/bin/pytest -s -v --embedding-model=all-MiniLM-L6-v2  tests/client-sdk/vector_io`
`/opt/miniconda3/envs/stack/bin/pytest -s -v --safety-shield=meta-llama/Llama-Guard-3-1B  tests/client-sdk/safety`
> [client sdk test] add options for inference_model, safety_shield, embedding_model

- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/tests/inference/test_text_inference.py
Adds raw completions API to vLLM
<details>
<summary>Setup</summary>
```bash
conda create -n vllm python=3.12 -y
conda activate vllm
pip install vllm
conda create --name llamastack-vllm python=3.10
conda activate llamastack-vllm
export INFERENCE_MODEL=meta-llama/Llama-3.2-3B-Instruct && \
pip install -e . && \
pip install --no-cache --index-url https://pypi.org/simple/ --extra-index-url https://test.pypi.org/simple/ llama-stack==0.1.0rc7 && \
llama stack build --template remote-vllm --image-type conda && \
llama stack run ./distributions/remote-vllm/run.yaml \
--port 5000 \
--env INFERENCE_MODEL=$INFERENCE_MODEL \
--env VLLM_URL=http://localhost:8000/v1 | tee -a llama-stack.log
```
</details>
<details>
<summary>Integration</summary>
```bash
conda activate llamastack-vllm
export …
```
> Add vLLM raw completions API

- distributions/runpod/build.yaml
- llama_stack/providers/adapters/inference/runpod/__init__.py
- llama_stack/providers/adapters/inference/runpod/config.py
- llama_stack/providers/adapters/inference/runpod/runpod.py
- llama_stack/providers/registry/inference.py
Add Runpod as a inference provider for openAI compatible managed endpoints. 
Testing 
- Configured llama stack from scratch, set `remote::runpod` as a inference provider. 
- Added Runpod Endpoint URL and API key. 
- Started llama-stack server - llama stack run my-local-stack --port 3000
```
curl http://localhost:5000/inference/chat_completion \
-H "Content-Type: application/json" \
-d '{
"model": "Llama3.1-8B-Instruct",
"messages": [
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": "Write me a 2 sentence poem about the moon"}
],
"sampling_params": {"temperature": 0.7, "seed": 42, "max_tokens": 512}
}' ```
> Add Runpod Provider + Distribution

- llama_stack/apis/agents/agents.py
- tests/client-sdk/agents/test_agents.py
Previously the tests hard coded the tool prompt format to be json which will cause it to fail when using 3.2/3.3 family of models. This change make the default to be none for the agent config and just remove the specification in the tests.
LLAMA_STACK_BASE_URL=http://localhost:8321 pytest -v tests/client-sdk/agents/test_agents.py
> make default tool prompt format none in agent config

- docs/openapi_generator/strong_typing/classdef.py
- docs/openapi_generator/strong_typing/schema.py
- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/agents/agents.py
- llama_stack/apis/eval/eval.py
- llama_stack/apis/inference/inference.py
- llama_stack/apis/post_training/post_training.py
- llama_stack/apis/scoring_functions/scoring_functions.py
- llama_stack/apis/telemetry/telemetry.py
See https://swagger.io/docs/specification/v3_0/data-models/inheritance-and-polymorphism/#discriminator
When specifying discriminators, mapping must be specified unless the value of the discriminator is the subtype itself (which in our case is not.)
The changes in the YAML are self-explanatory.
> Update discriminator to have the correct `mapping`

- llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
When you re-initialize the library client in a notebook, we were seeing this error:
```
Getting traces for session_id=5c8d1969-0957-49d2-b852-32cbb8ef8caf
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-11-d74bb6cdd3ab>](https://localhost:8080/#) in <cell line: 0>()
7 agent_logs = []
8 
----> 9 for span in client.telemetry.query_spans(
10     attribute_filters=[
11         {"key": "session_id", "op": "eq", "value": session_id},
10 frames
[/usr/local/lib/python3.11/dist-packages/llama_stack/providers/inline/telemetry/meta_reference/telemetry.py](https://localhost:8080/#) in query_traces(self, attribute_filters, limit, offset, order_by)
246     ) -> QueryTracesResponse: …
```
> Fix telemetry init

- llama_stack/apis/agents/agents.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Add response format for agents structured output.
E2E test plan with llama-stack-apps interior_design
Test ran: 
Start your distro:
llama stack run  llama_stack/templates/fireworks/run.yaml --env FIREWORKS_API_KEY=<API_KEY>
Run api test:
```PYTHONPATH=. python examples/interior_design_assistant/api.py localhost 5000 examples/interior_design_assistant/resources/documents/ examples/interior_design_assistant/resources/images/fireplaces```
Results: 
https://github.com/meta-llama/llama-stack-client-python/pull/72
> Agent response format

- docs/openapi_generator/generate.py
- docs/openapi_generator/pyopenapi/generator.py
- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
Stainless ends up reformatting the YAML when we paste it in the Studio. We cannot have that happen if we are going to ever partially automate stainless config updates. 
Try ruamel.yaml, specifically `block_seq_indent` to avoid that.
> Use ruamel.yaml to format the OpenAPI spec

- llama_stack/providers/remote/inference/nvidia/openai_utils.py
fix type mismatch in /v1/inference/completion
`llama stack run ./llama_stack/templates/nvidia/run.yaml`
`LLAMA_STACK_BASE_URL="http://localhost:8321" pytest -v tests/client-sdk/inference/test_inference.py`
> align with CompletionResponseStreamChunk.delta as str (instead of TextDelta)

- llama_stack/templates/nvidia/run.yaml
allows template distribution connect to hosted or local NIM:
use --env NVIDIA_BASE_URL=http://localhost:8000 to connect to a local NIM running at localhost:8000
use --env NVIDIA_API_KEY=blah when connecting to hosted NIM, e.g. NVIDIA_BASE_URL=https://integrate.api.nvidia.com
- `llama stack run ./llama_stack/templates/nvidia/run.yaml` -> error, e.g. API key is required for hosted NVIDIA NIM
- `llama stack run ./llama_stack/templates/nvidia/run.yaml --env NVIDIA_BASE_URL=https://integrate.api.nvidia.com` ->  error, e.g. API key is required for hosted NVIDIA NIM
- `llama stack run ./llama_stack/templates/nvidia/run.yaml --env NVIDIA_API_KEY=REDACTED` -> successful connection to NIM on https://integrate.api.nvidia.com
- `llama stack run ./llama_stack/templates/nvidia/run.yaml --env …
> add NVIDIA_BASE_URL and NVIDIA_API_KEY to control hosted vs local endpoints

- llama_stack/cli/stack/_build.py
This was missed in https://github.com/meta-llama/llama-stack/pull/802 somehow.
> Fix validator of "container" image type

- llama_stack/cli/stack/run.py
Fixes: #902
For the test verified that llama stack can run if built:
* With default "base" conda environment
* With new custom conda environment using `--image-name XXX` option
In both cases llama stack starts fine (was failing with "base") before this patch.
CC: @ashwinb
> Fix running stack built with base conda environment

- .github/workflows/tests.yml
Create a new github action that runs integration tests on fireworks and together distro upon new PR 
**Key features:**
1) Run inference client-sdk tests on fireworks and together distro. Load distro as a library
2) Pull changes from latest github repo (llama-models) and (llama-stack-client-python) 
3) output a test summary 
**Next steps:**
- Expand the ci test action to (llama-models) and (llama-stack-client-python) repo to make sure the changes there does not break the imports in llama-stack
See [the job run triggered by this PR](https://github.com/meta-llama/llama-stack/actions/runs/12926663190?pr=850)
> create a github action for triggering client-sdk tests on new pull-request

- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/utils/inference/openai_compat.py
- tests/client-sdk/inference/test_inference.py
1) As per @mattf's suggestion, we want to mark the pytest as xfail for providers that do not support the functionality. In this diff, we xfail the logProbs inference tests for providers who does not support log probs.
( log probs is only supported by together, fireworks and vllm)
2) Added logProbs support for together according to their developer [doc](https://docs.together.ai/docs/logprobs).
1) Together & Fireworks
```
export LLAMA_STACK_CONFIG=/Users/sxyi/llama-stack/llama_stack/templates/together/run.yaml  
/opt/miniconda3/envs/stack/bin/pytest -s -v /Users/sxyi/llama-stack/tests/client-sdk/inference/test_inference.py
```
```
tests/client-sdk/inference/test_inference.py::test_text_completion_streaming[meta-llama/Llama-3.1-8B-Instruct] PASSED …
```
> log probs - mark pytests as xfail for unsupported providers + add support for together

- docs/openapi_generator/strong_typing/schema.py
- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/common/content_types.py
- llama_stack/providers/utils/inference/prompt_adapter.py
- tests/client-sdk/inference/test_inference.py
- Discussion in https://github.com/meta-llama/llama-stack/pull/906#discussion_r1936260819
- image.data should accept base64 string as input instead of binary bytes, change prompt_adapter to account for that. 
```
pytest -v tests/client-sdk/inference/test_inference.py
```
with test in https://github.com/meta-llama/llama-stack/pull/906
> fix ImageContentItem to take base64 string as image.data

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- tests/client-sdk/agents/test_agents.py
Fixes a bug where agents were not working when both rag and code-interpreter were added as tools. 
Added a new client_sdk test which tests for this scenario 
```
LLAMA_STACK_CONFIG=together pytest -s -v  tests/client-sdk -k 'test_rag_and_code_agent'
```
> Fix Agents to support code and rag simultaneously

- tests/client-sdk/inference/test_inference.py
a test exists for image.url content, but not image.data content. this adds the former.
`LLAMA_STACK_BASE_URL=http://localhost:8321 pytest -v tests/client-sdk/inference/test_inference.py`
> add test for user message w/ image.data content

- docs/openapi_generator/pyopenapi/generator.py
- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
We need to change
```yaml
/v1/inference/chat-completion:
post:
responses:
'200':
description: >-
If stream=False, returns a ChatCompletionResponse with the full completion.
If stream=True, returns an SSE event stream of ChatCompletionResponseStreamChunk
content:
text/event-stream:
schema:
oneOf:
- $ref: '#/components/schemas/ChatCompletionResponse'
- $ref: '#/components/schemas/ChatCompletionResponseStreamChunk'
```
into
```yaml
/v1/inference/chat-completion:
post:
responses:
'200':
description: >-
If stream=False, returns a ChatCompletionResponse with the full completion.
If stream=True, returns an SSE event stream of ChatCompletionResponseStreamChunk
content:
text/event-stream:
schema:
$ref: '#/components/schemas/ChatCompletionResponseStreamChunk'
application/json:
schema:
$ref: …
```
> openapi gen return type fix for streaming/non-streaming

- llama_stack/providers/inline/inference/meta_reference/generation.py
This commit adds support for XPU and CPU devices into meta-reference stack for text models. On creation stack automatically identifies which device to use checking available accelerate capabilities in the following order: CUDA, then XPU, finally CPU. This behaviour can be overwritten with the `DEVICE` environment variable. In this case explicitly specified device will be used.
Tested with:
```
torchrun pytest llama_stack/providers/tests/inference/test_text_inference.py -k meta_reference
```
Results:
* Tested on: system with single CUDA device, system with single XPU device and on pure CPU system
* Results: all test pass except `test_completion_logprobs`
* `test_completion_logprobs` fails in the same way as on a baseline, i.e. unrelated with this change: `AssertionError: Unexpected …
> feat: enable xpu support for meta-reference stack

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- llama_stack/cli/stack/_build.py
- llama_stack/distribution/build.py
- llama_stack/distribution/build_conda_env.sh
- llama_stack/distribution/build_container.sh
- llama_stack/distribution/build_venv.sh
- llama_stack/distribution/client.py
- llama_stack/scripts/install_packages.sh
- llama_stack/templates/meta-reference-gpu/doc_template.md
- llama_stack/templates/meta-reference-quantized-gpu/doc_template.md
- llama_stack/templates/ollama/doc_template.md
- llama_stack/templates/remote-vllm/doc_template.md
- llama_stack/templates/template.py
- llama_stack/templates/tgi/doc_template.md
- pyproject.toml
See issue: #747  -- `uv` is just plain better. This PR does the bare minimum of replacing `pip install` by `uv pip install` and ensuring `uv` exists in the environment. 
First: create new conda, `uv pip install -e .` on `llama-stack` -- all is good. 
Next: run `llama stack build --template together` followed by `llama stack run together` -- all good
Next: run `llama stack build --template together --image-name yoyo` followed by `llama stack run together --image-name yoyo` -- all good
Next: fresh conda and `uv pip install -e .` and `llama stack build --template together --image-type venv` -- all good.
Docker: `llama stack build --template together --image-type container` works!
> Use `uv pip install` instead of `pip install`

- llama_stack/providers/remote/inference/nvidia/nvidia.py
- llama_stack/providers/remote/inference/nvidia/openai_utils.py
- llama_stack/providers/utils/inference/prompt_adapter.py
add support to the NVIDIA Inference provider for image inputs
1. Run local [Llama 3.2 11b vision instruct](https://build.nvidia.com/meta/llama-3.2-11b-vision-instruct?snippet_tab=Docker) NIM
2. Start a stack, e.g. `llama stack run llama_stack/templates/nvidia/run.yaml --env NVIDIA_BASE_URL=http://localhost:8000`
3. Run image tests, e.g. `LLAMA_STACK_BASE_URL=http://localhost:8321 pytest -v tests/client-sdk/inference/test_inference.py --vision-inference-model meta-llama/Llama-3.2-11B-Vision-Instruct -k image`
> add image support to NVIDIA inference provider

- llama_stack/distribution/build_container.sh
This was missed in https://github.com/meta-llama/llama-stack/pull/921. 
cc @ashwinb @hardikjshah
> Fix UBI9 image build when installing Python packages via uv

- llama_stack/providers/inline/ios/inference/LocalInferenceImpl/LocalInference.swift
- llama_stack/providers/inline/ios/inference/LocalInferenceImpl/Parsing.swift
To work with the updated iOSCalendarAssistantWithLocalInf [here](https://github.com/meta-llama/llama-stack-apps/compare/ios_local).
> LocalInferenceImpl update for LS 0.1

- llama_stack/providers/remote/vector_io/pgvector/pgvector.py
The connection to the DB was not closed during shutdown.
> Properly close PGVector DB connection during shutdown()

- .github/ISSUE_TEMPLATE/config.yml
This is similar to what we are doing for other projects, e.g. https://github.com/argoproj/argo-workflows/tree/main/.github/ISSUE_TEMPLATE
The benefits is to give people more options before submitting a bug report or feature request on GitHub.
> Add issue template config with docs and Discord links

- llama_stack/distribution/build_conda_env.sh
- llama_stack/distribution/build_container.sh
- llama_stack/distribution/build_venv.sh
This fixes the following timeout issue when installing PyTorch via uv. Also see reference: https://github.com/astral-sh/uv/pull/1694, https://github.com/astral-sh/uv/issues/1549
```
Installing pip dependencies
Using Python 3.10.16 environment at: /home/yutang/.conda/envs/distribution-myenv
× Failed to download and build `antlr4-python3-runtime==4.9.3`
├─▶ Failed to extract archive
├─▶ failed to unpack
│   `/home/yutang/.cache/uv/sdists-v7/.tmpDWX4iK/antlr4-python3-runtime-4.9.3/src/antlr4/ListTokenSource.py`
├─▶ failed to unpack
│   `antlr4-python3-runtime-4.9.3/src/antlr4/ListTokenSource.py` into
│   `/home/yutang/.cache/uv/sdists-v7/.tmpDWX4iK/antlr4-python3-runtime-4.9.3/src/antlr4/ListTokenSource.py`
├─▶ error decoding response body
├─▶ request or response body error
╰─▶ operation …
```
> Fix uv pip install timeout issue for PyTorch

- .gitignore
the llama-stack repo is already ignoring hidden python `.venv/` directories but not `venv/`
N/A
N/A
> github: ignore non-hidden python virtual environments

- docs/source/getting_started/index.md
Ollama download link is broken on this page: https://llama-stack.readthedocs.io/en/latest/getting_started/index.html
N/A
https://ollama.com/docs/installation ==> 404
https://ollama.com/download
> fix: broken link in Quick Start doc

- docs/source/contributing/new_api_provider.md
The `core concepts` link on [this page](https://llama-stack.readthedocs.io/en/latest/contributing/new_api_provider.html) is currently broken - this PR fixes that link
Ran local docs build as described [here](https://github.com/meta-llama/llama-stack/blob/main/CONTRIBUTING.md#building-the-documentation)
N/A
> fix: broken "core concepts" link in docs website

- docs/source/getting_started/index.md
Fixes formatting for Ollama note found here: https://llama-stack.readthedocs.io/en/latest/getting_started/index.html#start-ollama
Ran local docs build as described [here](https://github.com/meta-llama/llama-stack/blob/main/CONTRIBUTING.md#building-the-documentation)
N/A
> fix: formatting for ollama note in Quick Start doc

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/inference/inference.py
- llama_stack/distribution/routers/routers.py
- llama_stack/providers/inline/inference/meta_reference/generation.py
- llama_stack/providers/inline/inference/meta_reference/inference.py
- llama_stack/providers/inline/inference/sentence_transformers/sentence_transformers.py
- llama_stack/providers/inline/inference/vllm/vllm.py
- llama_stack/providers/remote/inference/bedrock/bedrock.py
- llama_stack/providers/remote/inference/cerebras/cerebras.py
- llama_stack/providers/remote/inference/databricks/databricks.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/groq/groq.py
- llama_stack/providers/remote/inference/groq/groq_utils.py
- llama_stack/providers/remote/inference/nvidia/nvidia.py
- llama_stack/providers/remote/inference/nvidia/openai_utils.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/runpod/runpod.py
- llama_stack/providers/remote/inference/sambanova/sambanova.py
- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/tests/inference/groq/test_groq_utils.py
- llama_stack/providers/tests/inference/test_prompt_adapter.py
- llama_stack/providers/utils/inference/prompt_adapter.py
The current default system prompt for llama3.2 tends to overindex on tool calling and doesn't work well when the prompt does not require tool calling.
This PR adds an option to override the default system prompt, and organizes tool-related configs into a new config object.
python -m unittest llama_stack.providers.tests.inference.test_prompt_adapter
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack/pull/937).
* #938
* __->__ #937
> Support sys_prompt behavior in inference

- docs/source/getting_started/index.md
- llama_stack/distribution/library_client.py
the example script can gracefully exit if the boolean returned from initialize is used properly
> if client.initialize fails, the example should exit

- docs/source/getting_started/index.md
Podman is a popular alternative to Docker, so it would be nice to make it clear that it can also be used to deploy the container for the server.  The instructions are a little different because you have to create the directory (unlike with Docker which makes the directory for you).
Documentation only.
I tried it out and it worked.
> Add Podman instructions to Quick Start

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
the `bug` and `enhancement` labels will be automatically applied to bugs and feature requests that are opened
N/A
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
> github: issue templates automatically apply relevant label

- docs/source/getting_started/index.md
Before the patch, the example could not be executed verbatim without
copy-pasting client function from the inference example. I think it's
better to have examples self-contained, especially in a getting started
guide.
See above.
Confirmed example can now be executed verbatim.
> [docs] Make RAG example self-contained

- llama_stack/providers/remote/vector_io/pgvector/__init__.py
- llama_stack/providers/remote/vector_io/pgvector/pgvector.py
- llama_stack/providers/tests/vector_io/conftest.py
- llama_stack/providers/tests/vector_io/test_vector_io.py
This PR fixes the broken pgvector provider as well as wraps all cursor object creations with context manager to ensure that they get properly closed to avoid potential memory leaks.
```
> pytest llama_stack/providers/tests/vector_io/test_vector_io.py   -m "pgvector" --env EMBEDDING_DIMENSION=384 --env PGVECTOR_PORT=7432 --env PGVECTOR_DB=db --env PGVECTOR_USER=user --env PGVECTOR_PASSWORD=pass   -v -s --tb=short --disable-warnings
llama_stack/providers/tests/vector_io/test_vector_io.py::TestVectorIO::test_banks_list[-pgvector] PASSED
llama_stack/providers/tests/vector_io/test_vector_io.py::TestVectorIO::test_banks_register[-pgvector] PASSED
llama_stack/providers/tests/vector_io/test_vector_io.py::TestVectorIO::test_query_documents[-pgvector] The scores are: [0.8168284974053789, …
```
> Fix broken pgvector provider and memory leaks

- docs/zero_to_hero_guide/README.md
The Zero to Hero guide currently references an older 0.0.61 llama-stack version. Using the most recent stable release of the product in the documentation, would help the users not to go through any issues from the older llama-stack versions.
I have ran the workflow locally using the proposed version change and I am able to proceed further ahead without any issue.
> [docs] update the zero_to_hero_guide llama stack version to 0.1.0

- docs/source/getting_started/index.md
The host.docker.internal alias was implemented in podman 4.7.0:
https://github.com/containers/podman/commit/b672ddc7929aae0c58768da38dca2adc983910e5
Follow-up to previous podman specific doc update.
> docs: clarify host.docker.internal works for recent podman

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/agents/agents.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/agents/meta_reference/agents.py
- tests/client-sdk/agents/test_agents.py
The current default system prompt for llama3.2 tends to overindex on tool calling and doesn't work well when the prompt does not require tool calling.
This PR adds an option to override the default system prompt, and organizes tool-related configs into a new config object.
LLAMA_STACK_CONFIG=together pytest \-\-inference\-model=meta\-llama/Llama\-3\.3\-70B\-Instruct -s -v tests/client-sdk/agents/test_agents.py::test_override_system_message_behavior
> sys_prompt support in Agent

- .github/PULL_REQUEST_TEMPLATE.md
Also, hiding guidance to the author under comments to avoid polluting
the description with ti.
Using `Closes #` syntax in PR template, as per:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
```
```
Hides this ^.
```
```
And this ^.
```
```
And this ^.
> github: update PR template to use correct syntax to auto-close issues

- llama_stack/providers/tests/eval/conftest.py
Replaced references to `memory` with `vector_io` in `DEFAULT_PROVIDER_COMBINATIONS` and adjusted corresponding fixture imports to ensure proper configuration for vector I/O during tests. This change aligns with the new testing structure.
Followup of https://github.com/meta-llama/llama-stack/pull/830 when the memory fixture was removed.
> test: replace memory with vector_io fixture

- docs/source/distributions/index.md
- docs/source/distributions/kubernetes_deployment.md
This PR moves some content from [the recent blog post](https://blog.vllm.ai/2025/01/27/intro-to-llama-stack-with-vllm.html) to here as a more official guide for users who'd like to deploy Llama Stack on Kubernetes.
> Add Kubernetes deployment guide

- .github/workflows/semantic-pr.yml
This adds a new workflow to check semantic PR titles to match the [Conventional Commits spec](https://www.conventionalcommits.org/). This will make it easier to browse commit history and enable automation in the future.
> ci: Add semantic PR title check

- docs/getting_started.ipynb
- docs/source/getting_started/index.md
- tests/client-sdk/agents/test_agents.py
In several examples we use the same faiss index , which means running it multiple times fills up the index with duplicates which eventually degrades the model performance on RAG as multiple copies of the same irrelevant chunks might be picked up several times. 
Fix is to ensure we create a new index each time. 
Resolves issue in this discussion - https://github.com/meta-llama/llama-stack/discussions/995 
Re-ran the getting started guide multiple times to see the same output
> fix: Update rag examples to use fresh faiss index every time

- llama_stack/providers/tests/datasetio/test_datasetio.py
- llama_stack/providers/tests/inference/test_model_registration.py
Refactored tests by removing unused exception alias (as exc_info) in pytest.raises, improving code clarity and reducing lint warnings. exc_info was never used.
> test: rm unused exception alias in pytest.raises

- llama_stack/providers/remote/inference/groq/groq.py
Imported `ToolConfig` from the `llama_stack.apis.inference` module to resolve missing reference and ensure proper functionality within the `groq.py` file.
Without the change, pytest will run with the following error:
```
uv run pytest -v -s -k "ollama" llama_stack/providers/tests/
/Users/leseb/Documents/AI/llama-stack/.venv/lib/python3.13/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid …
```
> chore: add missing ToolConfig import in groq.py

- .github/workflows/tests.yml
- tests/client-sdk/README.md
- tests/client-sdk/inference/test_text_inference.py
- tests/client-sdk/inference/test_vision_inference.py
This PR splits the inference tests into text and vision to make testing on vLLM provider easier as mentioned in https://github.com/meta-llama/llama-stack/pull/951 since serving multiple models (e.g. Llama-3.2-11B-Vision-Instruct and Llama-3.1-8B-Instruct) on a single port using the OpenAI API is [not supported yet](https://docs.vllm.ai/en/v0.5.5/serving/faq.html) so it's a bit tricky to test both at the same time.
All previously passing tests related to text still pass: `LLAMA_STACK_BASE_URL=http://localhost:5002 pytest -v tests/client-sdk/inference/test_text_inference.py` 
All vision tests passed via `LLAMA_STACK_BASE_URL=http://localhost:5002 pytest -v tests/client-sdk/inference/test_vision_inference.py`.
> test: Split inference tests to text and vision

- llama_stack/cli/stack/run.py
- llama_stack/distribution/datatypes.py
- llama_stack/distribution/server/server.py
- llama_stack/distribution/start_conda_env.sh
- llama_stack/distribution/start_container.sh
Enables HTTPS option for Llama Stack. 
While doing so, introduces a `ServerConfig` sub-structure to house all server related configuration (port, ssl, etc.)
Also simplified the `start_container.sh` entrypoint to simply be `python` instead of a complex bash command line.
Conda: 
Run:
```bash
$ llama stack build --template together
$ llama stack run --port 8322        # ensure server starts 
$ llama-stack-client configure --endpoint http://localhost:8322
$ llama-stack-client models list
```
Create a self-signed SSL key / cert pair. Then, using a local checkout of `llama-stack-client-python`, change https://github.com/meta-llama/llama-stack-client-python/blob/main/src/llama_stack_client/_base_client.py#L759 to add `kwargs.setdefault("verify", False)` so SSL verification is disabled. Then: …
> feat: Add HTTPS serving option

- llama_stack/providers/tests/inference/test_vision_inference.py
Previously, the test was failing due to a pydantic validation error caused by passing raw binary image data instead of a valid Unicode string. This fix encodes the image data as base64, ensuring it is a valid string format compatible with `ImageContentItem`.
Error:
```
______________ ERROR collecting llama_stack/providers/tests/inference/test_vision_inference.py _______________
llama_stack/providers/tests/inference/test_vision_inference.py:31: in <module>
class TestVisionModelInference:
llama_stack/providers/tests/inference/test_vision_inference.py:37: in TestVisionModelInference
ImageContentItem(image=dict(data=PASTA_IMAGE)),
E   pydantic_core._pydantic_core.ValidationError: 1 validation error for ImageContentItem
E   image.data
E     Input should be a valid string, unable to parse raw …
```
> test: encode image data as base64

- docs/source/getting_started/index.md
- llama_stack/distribution/library_client.py
currently this is the output when you run a distribution locally without running `llama stack build`:
```
File "/Users/charliedoern/Documents/llama-sdk.py", line 25, in <module>
models = client.models.list()
^^^^^^^^^^^^^^^^^^^^
File "/Users/charliedoern/Documents/llama-stack-client-python/src/llama_stack_client/resources/models.py", line 107, in list
raise exc
File "/Users/charliedoern/Documents/llama-stack-client-python/src/llama_stack_client/resources/models.py", line 95, in list
return self._get(
^^^^^^^^^^
File "/Users/charliedoern/Documents/llama-stack-client-python/src/llama_stack_client/_base_client.py", line 1212, in get
return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)) …
```
> fix: Ensure a better error stack trace when llama-stack is not built

- llama_stack/providers/remote/inference/ollama/ollama.py
Moved model availability check logic into a dedicated check_model_availability function. Eliminated redundant code by reusing the helper function in both embedding and non-embedding model registration.
Run Ollama and serve 2 models to get most the unit test pass:
```
ollama run llama3.2:3b-instruct-fp16 --keepalive 2m &
ollama run llama3.1:8b  --keepalive 2m &
```
Run the unit test:
```
uv run pytest -v -k "ollama" --inference-model=llama3.2:3b-instruct-fp16 llama_stack/providers/tests/inference/test_model_registration.py
/Users/leseb/Documents/AI/llama-stack/.venv/lib/python3.13/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for …
```
> refactor(ollama): model availability check

- docs/getting_started.ipynb
Added examples (Section 4) of using Llama Stack 0.1 distro on together and Llama 3.2 to answer questions about an image with LS Chat and Agent APIs. 
> Getting started notebook update

- tests/client-sdk/inference/test_text_inference.py
This significantly shortens the test time (about 10x faster) since most of the time is spent on outputing the tokens "there are several planets in our solar system that have...". We want to have an answer quicker, especially when testing even larger models.
```
LLAMA_STACK_BASE_URL=http://localhost:5002 pytest -v tests/client-sdk/inference/test_text_inference.py -k "test_text_chat_completion_non_streaming or test_text_chat_completion_streaming"
================================================================== test session starts ===================================================================
platform linux -- Python 3.10.16, pytest-8.3.4, pluggy-1.5.0 -- /home/yutang/.conda/envs/myenv/bin/python3.10
configfile: …
```
> test: Make text-based chat completion tests run 10x faster

- tests/client-sdk/inference/test_text_inference.py
This PR removes the warnings when running tests for `remote::vllm` provider:
```
Detected the chat template content format to be 'openai'. You can set `--chat-template-content-format` to override this.
```
All tests passed without the warning messages shown above.
> test: Use JSON tool prompt format for remote::vllm provider

- README.md
The table on the project's PyPI page does not render check marks. This PR switches to use the unicode symbol directly that can be rendered correctly on PyPI.
Before:
After:
> docs: Render check marks correctly on PyPI

- docs/source/building_applications/rag.md
This PR updates the example code in `docs/source/building_applications/rag.md` to reflect some changes in the SDK that were causing errors. It also adds a couple import statements to make things slightly easier for users.
I've run each code segment using both `llamastack/distribution-ollama:latest` and `llama stack run ollama` as my local llamastack servers with `meta-llama/Llama-3.2-3B-Instruct` as the inference model.  All code segments ran without errors in both cases.
> docs: update rag.md example code to prevent errors

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- uv.lock
Updated `uv.lock` to reflect the latest versions of `llama-models`, `llama-stack`, and `llama-stack-client` (bumped to 0.1.2). This ensures dependency consistency and avoids potential issues with outdated package references.
Added `uv-sync` hook from `uv-pre-commit` repository to ensure synchronization of dependencies.  
[//]: # (- [ ] Added a Changelog entry if the change is …
> build: update uv lock to sync package versions

- llama_stack/providers/remote/vector_io/qdrant/__init__.py
- llama_stack/providers/remote/vector_io/qdrant/qdrant.py
I tried running the Qdrant provider and found some bugs.  See #1021 for details.   @terrytangyuan wrote there:
> Please feel free to submit your changes in a PR. I fixed similar issues for pgvector provider. This might be an issue introduced from a refactoring.
So I am submitting this PR.
Closes #1021
Here are the highlights for what I did to test this:
References:
- https://llama-stack.readthedocs.io/en/latest/getting_started/index.html
- https://github.com/meta-llama/llama-stack-apps/blob/main/examples/agents/rag_with_vector_db.py
- https://github.com/meta-llama/llama-stack/blob/main/docs/zero_to_hero_guide/README.md#build-configure-and-run-llama-stack
Install and run Qdrant server:
```
podman pull qdrant/qdrant
mkdir qdrant-data
podman run -p 6333:6333 -v …
```
> fix: Update Qdrant support post-refactor

- llama_stack/providers/tests/inference/test_vision_inference.py
- tests/client-sdk/inference/test_vision_inference.py
The previous image URLs were sometimes blocked by Cloudflare, causing test failures for some users. This update replaces them with a GitHub-hosted image (`dog.png`) from the `llama-stack` repository, ensuring more reliable access during testing.
```
$ ollama run llama3.2-vision:latest --keep-alive 2m &
$ uv run pytest -v -s -k "ollama" --inference-model=llama3.2-vision:latest llama_stack/providers/tests/inference/test_vision_inference.py
/Users/leseb/Documents/AI/llama-stack/.venv/lib/python3.13/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The …
```
> test: replace blocked image URLs with GitHub-hosted

- .github/PULL_REQUEST_TEMPLATE.md
The CHANGELOG.md was removed in
https://github.com/meta-llama/llama-stack/commit/e6c9f2a4856192d6cb57a038d98d21a253c4319a so this mention is not relevant anymore.
> docs: remove changelog mention from PR template

- CONTRIBUTING.md
For what I see, it's all 4 spaces (as it should be for pep8[1]).
[1] https://peps.python.org/pep-0008/#indentation
Reflect indent reality.
> docs: reflect actual number of spaces for indent

- llama_stack/apis/agents/agents.py
- llama_stack/providers/inline/agents/meta_reference/agents.py
- tests/client-sdk/agents/test_agents.py
Summary:
Fixes AgentConfig init bug introduced with ToolConfig.
Namely, the below doesn't work
```
agent_config = AgentConfig(
**common_params,
tool_config=ToolConfig(
tool_choice="required",
),
)
```
bvecause tool_choice was defaulted to 'auto' leading to validation check failing.
Test Plan:
added unittests
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/ --safety-shield meta-llama/Llama-Guard-3-8B
> fix: agent config validation

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/inference/inference.py
- llama_stack/apis/telemetry/telemetry.py
Defines a MetricResponseMixin which can be inherited by any response class. Adds it to chat completion response types.
This is a short term solution to allow inference API to return metrics
The ideal way to do this is to have a way for all response types to include metrics
and all metric events logged to the telemetry API to be included with the response
To do this, we will need to augment all response types with a metrics field.
We have hit a blocker from stainless SDK that prevents us from doing this.
The blocker is that if we were to augment the response types that have a data field 
in them like so
class ListModelsResponse(BaseModel):
metrics: Optional[List[MetricEvent]] = None
data: List[Models]
...
The client SDK will need to access the data by using a .data field, which is not …
> feat: add MetricResponseMixin to chat completion response types

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/telemetry/telemetry.py
- llama_stack/providers/utils/telemetry/trace_protocol.py
Make attributes in telemetry be only primitive types and avoid arbitrary nesting.
```
LLAMA_STACK_DISABLE_VERSION_CHECK=true llama stack run ~/.llama/distributions/fireworks/fireworks-run.yaml
LLAMA_STACK_BASE_URL=http://localhost:8321 pytest -v tests/client-sdk/agents/test_agents.py  -k "test_builtin_tool_web_search"
```
> feat: make telemetry attributes be dict[str,PrimitiveType]

- llama_stack/cli/stack/list_providers.py
- llama_stack/providers/datatypes.py
Before:
```
 llama stack list-providers agents
+------------------------+-----------------------------------------------------------------------+
| Provider Type          | PIP Package Dependencies                                              |
+------------------------+-----------------------------------------------------------------------+
| inline::meta-reference | matplotlib,pillow,pandas,scikit-learn,aiosqlite,psycopg2-binary,redis |
+------------------------+-----------------------------------------------------------------------+
| remote::sample         |                                                                       |
+------------------------+-----------------------------------------------------------------------+
```
After:
```
 llama stack list-providers agents …
```
> fix: filter out remote::sample providers when listing

- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/utils/inference/openai_compat.py
This PR adds support for tool calling for non-streaming chat completion. Prior to this, tool calls were not passed to chat completion requests and the tools object needs to be restructured properly to be compatible with vLLM provider. 
```
LLAMA_STACK_BASE_URL=http://localhost:5002 pytest -v tests/client-sdk/inference/test_text_inference.py
================================================================= test session starts =================================================================
platform linux -- Python 3.10.16, pytest-8.3.4, pluggy-1.5.0 -- /home/yutang/.conda/envs/distribution-myenv/bin/python3.10
plugins: anyio-4.8.0
collected 12 items …
```
> feat: Support tool calling for non-streaming chat completion in remote vLLM provider

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/inference/vllm/vllm.py
- llama_stack/providers/remote/inference/bedrock/bedrock.py
- llama_stack/providers/remote/inference/cerebras/cerebras.py
- llama_stack/providers/remote/inference/databricks/databricks.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/runpod/runpod.py
- llama_stack/providers/remote/inference/sambanova/sambanova.py
- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/utils/inference/openai_compat.py
- tests/client-sdk/inference/test_text_inference.py
**Problem**
- Using script: https://gist.github.com/thoraxe/6163b2145ce7b1c24c6026b64cf90085
- This hits an issue on server with `code_interpreter` not found, as we do not pass "builtin::code_interpreter" in AgentConfig's `toolgroups`. 
This is a general issue where model always tries to output `code_interpreter` in `ToolCall` even when we do not have `code_interpreter` available for execution. 
**Reproduce Deeper Problem in chat-completion**
- Use script: https://gist.github.com/yanxi0830/163a9ad7b5db10556043fbfc7ecd7603
1. We currently always populate `code_interpreter` in `ToolCall` in ChatCompletionResponse if the model's response begins with `<|python_tag|>`. See https://github.com/meta-llama/llama-models/blob/c5f59584982e6f1c5ce2dd5a9d2a5763891ec276/models/llama3/api/chat_format.py#L …
> perf: ensure ToolCall in ChatCompletionResponse is subset of ChatCompletionRequest.tools

- llama_stack/providers/utils/inference/model_registry.py
Updated the return type of the methods `get_provider_model_id` and `get_llama_model` in the `ModelRegistryHelper` class to `Optional[str]` to indicate that they may return a string or None when no match is found. This change improves the clarity of the methods' behavior and supports better type safety.
> chore: update return type to Optional[str]

- llama_stack/providers/remote/inference/groq/groq_utils.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/utils/inference/openai_compat.py
Closes https://github.com/meta-llama/llama-stack/issues/1046. 
```
LLAMA_STACK_BASE_URL=http://localhost:5002 pytest -v tests/client-sdk/inference/test_text_inference.py
================================================================= test session starts =================================================================
platform linux -- Python 3.10.16, pytest-8.3.4, pluggy-1.5.0 -- /home/yutang/.conda/envs/distribution-myenv/bin/python3.10
plugins: anyio-4.8.0 …
```
> feat: Support tool calling for streaming chat completion in remote vLLM provider

- llama_stack/cli/model/model.py
- llama_stack/cli/stack/stack.py
when executing a sub-command like `llama model` the improper help text, sub-commands, and flags are displayed. each command group needs to have `.set_defaults` to display this info properly
before: 
```
llama model
usage: llama [-h] {model,stack,download,verify-download} ...
Welcome to the Llama CLI
options:
subcommands:
{model,stack,download,verify-download}
```
after:
```
llama model
usage: llama model [-h] {download,list,prompt-format,describe,verify-download} ...
Work with llama models
options:
model_subcommands:
{download,list,prompt-format,describe,verify-download}
```
> fix: show proper help text

- docs/source/distributions/building_distro.md
- llama_stack/cli/stack/run.py
- llama_stack/distribution/start_venv.sh
add --image-type to `llama stack run`. Which takes conda, container or venv also add start_venv.sh which start the stack using a venv
resolves #1007
running locally:
`llama stack build --template ollama --image-type venv`
`llama stack run --image-type venv ~/.llama/distributions/ollama/ollama-run.yaml`
...
```
llama stack run --image-type venv ~/.llama/distributions/ollama/ollama-run.yaml
Using run configuration: /Users/charliedoern/.llama/distributions/ollama/ollama-run.yaml
+ python -m llama_stack.distribution.server.server --yaml-config /Users/charliedoern/.llama/distributions/ollama/ollama-run.yaml --port 8321
Using config file: /Users/charliedoern/.llama/distributions/ollama/ollama-run.yaml
Run configuration:
apis:
- agents
- datasetio
...
```
> feat: add support for running in a venv

- llama_stack/cli/stack/list_providers.py
- llama_stack/cli/table.py
Support listing all for `llama stack list-providers`.
For ease of reading, sort the output rows by type.
Before the change.
```
 llama stack list-providers
usage: llama stack list-providers [-h] {inference,safety,agents,vector_io,datasetio,scoring,eval,post_training,tool_runtime,telemetry}
llama stack list-providers: error: the following arguments are required: api
```
After the change.
```
+---------------+----------------------------------+----------------------------------------------------------------------------------+
| API Type      | Provider Type                    | PIP Package Dependencies                                                         |
+---------------+----------------------------------+--------------------------------------------------------------------------------- …
```
> feat: support listing all for `llama stack list-providers`

- CONTRIBUTING.md
This adds a note to ensure pull requests follow the conventional commits format, along with a link to that format, in CONTRIBUTING.md. One of the pull-request checks enforces PR titles that match this format, so it's good to be upfront about this expectation before a new developer opens a PR.
> docs: Mention convential commits format in CONTRIBUTING.md

- llama_stack/distribution/inspect.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/distribution/server/server.py
- llama_stack/providers/inline/agents/meta_reference/agents.py
- pyproject.toml
- uv.lock
This commit enhances the signal handling mechanism in the server by
improving the `handle_signal` (previously handle_sigint) function. It
now properly retrieves the signal name, ensuring clearer logging when a
termination signal is received. Additionally, it cancels all running
tasks and waits for their completion before stopping the event loop,
allowing for a more graceful shutdown. Support for handling
SIGTERM has also been added alongside SIGINT.
Before the changes, handle_sigint used asyncio.run(run_shutdown()). However, asyncio.run() is meant to start a new event loop, and calling it inside an existing one (like when running Uvicorn) raises an error. The fix replaces asyncio.run(run_shutdown()) with an async function scheduled on the existing loop using loop.create_task(shutdown()). …
> fix: improve signal handling and update dependencies

- llama_stack/providers/remote/inference/groq/groq.py
This should be `llama-3.2-3b` instead of `llama-3.2-3b-instruct`.
> chore: Link to Groq docs in the warning message for preview model

- tests/client-sdk/inference/test_text_inference.py
top_k supported was added in https://github.com/meta-llama/llama-stack/pull/1074. The tests should be enabled as well. 
Verified that tests pass for remote::vllm:
```
LLAMA_STACK_BASE_URL=http://localhost:5003 pytest -v tests/client-sdk/inference/test_text_inference.py -k " test_completion_log_probs_non_streaming or test_completion_log_probs_streaming"
================================================================ test session starts ================================================================
platform linux -- Python 3.10.16, pytest-8.3.4, pluggy-1.5.0 -- /home/yutang/.conda/envs/distribution-myenv/bin/python3.10
plugins: anyio-4.8.0
collected 14 items / 12 deselected / 2 selected …
```
> test: Enable logprobs top_k tests for remote::vllm

- tests/client-sdk/agents/test_agents.py
Summary:
This tests the fix to the SDK in https://github.com/meta-llama/llama-stack-client-python/pull/141
Test Plan:
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/ --safety-shield meta-llama/Llama-Guard-3-8B
> test: add test for Agent.create_turn non-streaming response

- llama_stack/distribution/library_client.py
This PR fixes client sdk test failure -- https://github.com/meta-llama/llama-stack-ops/actions/runs/13320153693/job/37203122048
by updating the regex matching pattern to also consider `:path` in the routes
> fix: regex pattern matching to support :path suffix in the routes

- tests/client-sdk/vector_io/test_vector_io.py
- sqlite_vec not added to all template yet, disable test for now to unblock release cut
> fix: disable sqlite-vec test

- llama_stack/cli/model/describe.py
Missing the help info, so add it.
```
before:
$ llama model describe --help
usage: llama model describe [-h] -m MODEL_ID
Show details about a llama model
options:
-m MODEL_ID, --model-id MODEL_ID
after:
$ llama model describe --help
usage: llama model describe [-h] -m MODEL_ID
Show details about a llama model
options:
-m MODEL_ID, --model-id MODEL_ID
See `llama model list` or `llama model list --show-all` for the list of available models <<<
```
[Describe the tests you ran to verify your …
> fix: add the missed help description info

- llama_stack/providers/tests/vector_io/fixtures.py
This fixes an import introduced due to merging #1079 before #1039, and thus the changes from #1039 needing to update `QdrantConfig` to `QdrantVectorIOConfig`.
I ran the remote vllm provider inference tests against the latest main:
```
VLLM_URL="http://localhost:8001/v1" python -m pytest -s -v llama_stack/providers/tests/inference/test_text_inference.py --providers "inference=vllm_remote"
```
That failed with:
```
File "/home/bbrownin/src/llama-stack/llama_stack/providers/tests/vector_io/fixtures.py", line 20, in <module>
from llama_stack.providers.remote.vector_io.qdrant import QdrantConfig
ImportError: Error importing plugin "llama_stack.providers.tests.vector_io.fixtures": cannot import name 'QdrantConfig' from 'llama_stack.providers.remote.vector_io.qdrant' …
```
> fix: Update QdrantConfig to QdrantVectorIOConfig

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/agents/agents.py
This issue was discovered in https://github.com/meta-llama/llama-stack/pull/1009#discussion_r1947036518.
This field is no longer required after the change.
[//]: # (- [ ] Added a Changelog entry if the change is significant)
> fix: enable_session_persistence in AgentConfig should be optional

- llama_stack/cli/stack/build.py
- llama_stack/distribution/build.py
- llama_stack/distribution/build_venv.sh
- llama_stack/distribution/common.sh
Added a pre_run_checks function to ensure a smooth environment setup by verifying prerequisites. It checks for an existing virtual environment, ensures uv is installed, and deactivates any active environment if necessary.
Run the full build inside a venv created by 'uv'.
Improved string handling in printf statements and added shellcheck suppressions for expected word splitting in pip commands.
These enhancements improve robustness, prevent
conflicts, and ensure a seamless setup process.
Run the following command on either Linux or MacOS:
```
llama stack build --template ollama --image-type venv --image-name foo
+ build_name=foo
+ env_name=llamastack-foo
+ pip_dependencies='datasets matplotlib autoevals transformers blobfile opentelemetry-sdk …
```
> fix: improve stack build on venv

- llama_stack/cli/download.py
Remove the empty line from help
```
before:
$ llama model download --help
--max-parallel MAX_PARALLEL
Maximum number of concurrent downloads
--ignore-patterns IGNORE_PATTERNS
<<<<<<<<<empty line>>>>>>>>>>
For source=huggingface, files matching any of the patterns are not downloaded. Defaults to ignoring
safetensors files to avoid downloading duplicate weights.
after:
$ llama model download --help
--max-parallel MAX_PARALLEL
Maximum number of concurrent downloads
--ignore-patterns IGNORE_PATTERNS
For source=huggingface, files matching any of the patterns are not downloaded. Defaults to ignoring
safetensors files to avoid downloading duplicate weights.
```
[//]: # (If resolving an issue, uncomment …
> fix: remove the empty line

- llama_stack/providers/utils/inference/openai_compat.py
This fixes an issue when running the e2e agent example: https://github.com/meta-llama/llama-stack-apps/blob/main/examples/agents/e2e_loop_with_client_tools.py
```
|   File "/home/yutang/repos/llama-stack/llama_stack/providers/remote/inference/vllm/vllm.py", line 175, in _process_vllm_chat_completion_stream_response
|     tool_call = convert_tool_call(choice.delta.tool_calls[0])
|   File "/home/yutang/repos/llama-stack/llama_stack/providers/utils/inference/openai_compat.py", line 441, in convert_tool_call
|     return ToolCall(
|   File "/home/yutang/.conda/envs/distribution-myenv/lib/python3.10/site-packages/pydantic/main.py", line 214, in __init__
|     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
| pydantic_core._pydantic_core.ValidationError: 4 …
```
> fix: Ensure a tool call can be converted before adding to buffer

- docs/openapi_generator/README.md
These are currently incorrect.
Re-ran the command and made sure it worked.
> docs: Fix incorrect link and command for generating API reference

- docs/source/distributions/building_distro.md
- llama_stack/cli/stack/build.py
From the code and the usage, seems cannot see that need to use `--no-list-templates` to handle, and also make the user confused from the help text, so try to remove it.
```
$ llama stack build --no-list-templates
> Enter a name for your Llama Stack (e.g. my-local-stack):
$ llama stack build
> Enter a name for your Llama Stack (e.g. my-local-stack):
before:
$ llama stack build --help
--list-templates, --no-list-templates
Show the available templates for building a Llama Stack distribution (default: False)
after:
--list-templates      Show the available templates for building a Llama Stack distribution
```
[//]: # (Closes …
> chore: remove --no-list-templates option

- tests/client-sdk/inference/test_text_inference.py
This verifies that https://github.com/meta-llama/llama-stack/pull/1059's test passed for remote::vllm so I am removing the xfail here. 
Test passed:
```
LLAMA_STACK_BASE_URL=http://localhost:5002 pytest -v tests/client-sdk/inference/test_text_inference.py::test_text_chat_completion_with_tool_choice_required 
=============================================================== test session starts ===============================================================
platform linux -- Python 3.10.16, pytest-8.3.4, pluggy-1.5.0 -- /home/yutang/.conda/envs/distribution-myenv/bin/python3.10
plugins: anyio-4.8.0
collected 1 item …
```
> test: Enable test_text_chat_completion_with_tool_choice_required for remote::vllm

- docs/source/getting_started/index.md
Add provider_id  to avoid errors using the rag example with llama_stack_client
`llama_stack_client.BadRequestError: Error code: 400 - {'detail': 'Invalid value: No provider specified and multiple providers available. Please specify a provider_id.'}`
> fix(rag-example): add provider_id to avoid llama_stack_client 400 error

- llama_stack/providers/inline/inference/vllm/vllm.py
- llama_stack/providers/remote/inference/bedrock/bedrock.py
- llama_stack/providers/remote/inference/cerebras/cerebras.py
- llama_stack/providers/remote/inference/databricks/databricks.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/runpod/runpod.py
- llama_stack/providers/remote/inference/sambanova/sambanova.py
- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/utils/inference/openai_compat.py
- llama_stack/providers/utils/inference/prompt_adapter.py
There should be a choke-point for llama3.api imports -- this is the prompt adapter. Creating a ChatFormat() object on demand is inexpensive. The underlying Tokenizer is a singleton anyway.
> chore: remove llama_models.llama3.api imports from providers

- docs/source/references/python_sdk_reference/index.md
It seems that the llama_stack_client repo and the main repo were originally the same, causing links to point to local references. We’ve now updated them to use the correct llama_stack_client repo links.
> docs: fix Python llama_stack_client SDK links

- llama_stack/providers/inline/vector_io/sqlite_vec/config.py
- llama_stack/providers/inline/vector_io/sqlite_vec/sqlite_vec.py
- llama_stack/providers/tests/vector_io/test_sqlite_vec.py
1. This PR adds batch inserts into sqlite-vec as requested in https://github.com/meta-llama/llama-stack/pull/1040
- Note: the inserts uses a uuid generated from the hash of the document id and chunk content.
2. This PR also adds unit tests for sqlite-vec. In a follow up PR, I can add similar tests to Faiss.
1. Integration tests:
```python
INFERENCE_MODEL=llama3.2:3b-instruct-fp16 LLAMA_STACK_CONFIG=ollama pytest -s -v tests/client-sdk/vector_io/test_vector_io.py
...
PASSED
tests/client-sdk/vector_io/test_vector_io.py::test_vector_db_retrieve[all-MiniLM-L6-v2-sqlite_vec] PASSED
tests/client-sdk/vector_io/test_vector_io.py::test_vector_db_list PASSED
tests/client-sdk/vector_io/test_vector_io.py::test_vector_db_register[all-MiniLM-L6-v2-faiss] PASSED …
```
> feat: Chunk sqlite-vec writes

- llama_stack/providers/inline/post_training/torchtune/post_training.py
- **refactor: simplify job status extraction a bit**
- **torchtune: save job status on schedule**
- **refactor: get rid of job_list in torchtune job management code**
A failed job is now registered in API, and one can consult its status.
```
$ llama-stack-client post_training status --job-uuid test-jobe244b5b0-5053-4892-a4d9-d8fc8b116e73                                                      
JobStatusResponse(checkpoints=[], job_uuid='test-jobe244b5b0-5053-4892-a4d9-d8fc8b116e73', status='failed', completed_at=None, resources_allocated=None, scheduled_at=datetime.datetime(2025, 2, 18, 9, 4, 34, 3252), started_at=datetime.datetime(2025, 2, 18, 9, 4, 34, 10688))
```
[//]: # (## …
> fix: miscellaneous job management improvements in torchtune

- llama_stack/providers/inline/scoring/llm_as_judge/scoring_fn/fn_defs/llm_as_judge_405b_simpleqa.py
as title, to let scoring function llm_as_judge_405b_simpleqa output aggregated_results. 
We can leverage categorical_count to calculate the % of correctness as eval benchmark metrics
> feat: add aggregation_functions to llm_as_judge_405b_simpleqa

- docs/openapi_generator/README.md
This is no longer required to generated API reference after https://github.com/meta-llama/llama-stack/commit/5e7904ef6c5483bb3aaf82ec0d687ced4867ef86
> docs: Remove unused python-openapi and json-strong-typing in openapi_generator

- llama_stack/distribution/build_venv.sh
- llama_stack/distribution/common.sh
- llama_stack/distribution/utils/exec.py
I was encountering build issues when building my `ollama` environment  using `llama stack build`
```bash
llama stack build --template ollama --image-type venv
File "/Users/farceo/dev/llama-stack/.venv/bin/llama", line 10, in <module>
sys.exit(main())
^^^^^^
File "/Users/farceo/dev/llama-stack/llama_stack/cli/llama.py", line 46, in main
parser.run(args)
File "/Users/farceo/dev/llama-stack/llama_stack/cli/llama.py", line 40, in run
args.func(args)
File "/Users/farceo/dev/llama-stack/llama_stack/cli/stack/build.py", line 77, in _run_stack_build_command
return run_stack_build_command(args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/farceo/dev/llama-stack/llama_stack/cli/stack/_build.py", line 180, in run_stack_build_command …
```
> fix: Fixing some small issues with the build scripts

- llama_stack/providers/remote/inference/vllm/vllm.py
This fixes the following issue on the server side when the tool call response contains empty args. This happens when running `examples.agents.e2e_loop_with_client_tools` but `get_ticker_data` returns `[]`:
```
File "/home/yutang/repos/llama-stack/llama_stack/distribution/server/server.py", line 208, in sse_generator
async for item in event_gen:
File "/home/yutang/repos/llama-stack/llama_stack/providers/inline/agents/meta_reference/agents.py", line 169, in _create_agent_turn_streaming
async for event in agent.create_and_execute_turn(request):
File "/home/yutang/repos/llama-stack/llama_stack/providers/inline/agents/meta_reference/agent_instance.py", line 189, in create_and_execute_turn
async for chunk in self.run(
File …
```
> fix: More robust handling of the arguments in tool call response in remote::vllm

- llama_stack/providers/tests/inference/test_model_registration.py
- Updated `test_register_with_llama_model` to skip tests when using the Ollama provider, as it does not support custom model names.
- Delete `test_initialize_model_during_registering` since there is no
"load_model" semantic that is exposed publicly on a provider.
These changes ensure that tests do not fail for providers with incompatible behaviors.
Run Ollama:
```
uv run pytest -v -s -k "ollama" llama_stack/providers/tests/inference/test_model_registration.py
/Users/leseb/Documents/AI/llama-stack/.venv/lib/python3.13/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option …
```
> test: skip model registration for unsupported providers

- docs/source/contributing/new_api_provider.md
This expands upon the existing distro_codegen.py text in the new API provider documentation to include a note about not including provider-specific dependencies in the code path that builds the distribution's template.
Our distro_codegen pre-commit hook will catch this case anyway, but this attempts to inform provider authors ahead of time about that.
I built the docs website locally via the following:
```
pip install docs/requirements.txt
sphinx-build -M html docs/source docs_output
```
Then, I opened that newly generated `docs_output/html/contributing/new_api_provider.html` in my browser and confirmed everything rendered correctly.
> docs: Add note about distro_codegen.py and provider dependencies

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- docs/openapi_generator/pyopenapi/generator.py
- docs/openapi_generator/pyopenapi/specification.py
- llama_stack/apis/files/__init__.py
- llama_stack/apis/files/files.py
- llama_stack/distribution/stack.py
- llama_stack/schema_utils.py
Summary:
Adds spec definitions for file uploads operations.
This API focuses around two high level operations:
* Initiating and managing upload session
* Accessing uploaded file information
Usage examples:
To start a file upload session:
```
curl -X POST https://localhost:8321/v1/files \
-d '{
"key": "image123.jpg',
"bucket": "images",
"mime_type": "image/jpg",
"size": 12345
}'
{
“id”: <session_id>
“url”: “https://localhost:8321/v1/files/session:<session_id>”,
"offset": 0,
"size": 12345
}
```
To upload file content to an existing session
```
curl -i -X POST "https://localhost:8321/v1/files/session:<session_id> \
--data-binary @<path_to_local_file>
{
"key": "image123.jpg",
"bucket": "images",
"mime_type": "image/jpg",
"bytes": 12345,
"created_at": 1737492240
} …
```
> feat: adding endpoints for files and uploads

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- docs/openapi_generator/pyopenapi/operations.py
- llama_stack/apis/telemetry/telemetry.py
- llama_stack/distribution/server/server.py
Summary:
This bug is surfaced by using the http LS client. The issue is that non-scalar values in 'GET' method are `body` params in fastAPI, but our spec generation script doesn't respect that. We fix by just making them POST method instead.
Test Plan:
Test API call with newly sync'd client (https://github.com/meta-llama/llama-stack-client-python/pull/149)
> fix: some telemetry APIs don't currently work

- .pre-commit-config.yaml
- docs/source/distributions/self_hosted_distro/fireworks.md
- docs/source/distributions/self_hosted_distro/together.md
- llama_stack/providers/remote/inference/fireworks/models.py
- llama_stack/providers/remote/inference/ollama/models.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/together/models.py
- llama_stack/providers/tests/inference/fixtures.py
- llama_stack/providers/utils/inference/model_registry.py
- llama_stack/templates/fireworks/fireworks.py
- llama_stack/templates/fireworks/run-with-safety.yaml
- llama_stack/templates/fireworks/run.yaml
- llama_stack/templates/ollama/ollama.py
- llama_stack/templates/ollama/run-with-safety.yaml
- llama_stack/templates/ollama/run.yaml
- llama_stack/templates/together/run-with-safety.yaml
- llama_stack/templates/together/run.yaml
- llama_stack/templates/together/together.py
We have support for embeddings in our Inference providers, but so far we haven't done the final step of actually registering the known embedding models and making sure they are extremely easy to use. This is one step towards that.
Run existing inference tests.
```bash
$ cd llama_stack/providers/tests/inference
$ pytest -s -v -k fireworks test_embeddings.py \
--inference-model nomic-ai/nomic-embed-text-v1.5 --env EMBEDDING_DIMENSION=784
$  pytest -s -v -k together test_embeddings.py \
--inference-model togethercomputer/m2-bert-80M-8k-retrieval --env EMBEDDING_DIMENSION=784
$ pytest -s -v -k ollama test_embeddings.py \
--inference-model all-minilm:latest --env EMBEDDING_DIMENSION=784
```
The value of the EMBEDDING_DIMENSION isn't actually used in these tests, it is merely used by the test …
> feat: register embedding models for ollama, together, fireworks

- CONTRIBUTING.md
```
make html
/bin/sh: line 1: sphinx-build: command not found
make: *** [Makefile:20: html] Error 127
```
Tested the command `uv run ./docs/openapi_generator/run_openapi_generator.sh` successfully.
> docs: Add missing uv command for docs generation in contributing guide

- README.md
Given that we already switched to uv in other places. We should recommend uv in README's installation guide as well. It's a lot simpler.
> docs: Simplify installation guide with `uv`

- llama_stack/providers/remote/inference/vllm/vllm.py
The `tool_name` attribute of `ToolDefinition` instances can either be a str or a BuiltinTool enum type. This fixes the remote vLLM provider to use the value of those BuiltinTool enums when serializing to JSON instead of attempting to serialize the actual enum to JSON.
Reference of how this is handled in some other areas, since I followed that same pattern for the remote vLLM provider here:
- [remote nvidia provider](https://github.com/meta-llama/llama-stack/blob/v0.1.3/llama_stack/providers/remote/inference/nvidia/openai_utils.py#L137-L140)
- [meta reference provider](https://github.com/meta-llama/llama-stack/blob/v0.1.3/llama_stack/providers/inline/agents/meta_reference/agent_instance.py#L635-L636)
There is opportunity to potentially reconcile the remove nvidia and remote vllm bits where …
> fix: BuiltinTool JSON serialization in remote vLLM provider

- .github/workflows/update-readthedocs.yml
Refine the existing update-readthedocs.yml workflow to enhance
automation and reliability. Updates include:
- Expanding path triggers to cover all documentation files (docs/**) and
build artifacts.
- Adding steps to set up Python (3.11), install uv, sync dependencies,
and build HTML using make html.
- Ensuring the ReadTheDocs build trigger only runs on
workflow_dispatch events.
These improvements help validate website builds in PRs, preventing
issues before merging.
> ci: improve GitHub Actions workflow for website builds

- llama_stack/providers/tests/inference/test_prompt_adapter.py
- llama_stack/providers/utils/inference/prompt_adapter.py
Summary:
Need this to format the completion message with tool_calls correctly. See added unittest.
Test Plan:
python -m unittest llama_stack.providers.tests.inference.test_prompt_adapter
> fix: pass tool_prompt_format to chat_formatter

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/inference/inference.py
- llama_stack/distribution/routers/routers.py
- llama_stack/providers/inline/inference/vllm/vllm.py
- llama_stack/providers/remote/inference/bedrock/bedrock.py
- llama_stack/providers/remote/inference/cerebras/cerebras.py
- llama_stack/providers/remote/inference/databricks/databricks.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/groq/groq.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/runpod/runpod.py
- llama_stack/providers/remote/inference/sambanova/sambanova.py
- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/utils/inference/embedding_mixin.py
See Issue #922 
The change is slightly backwards incompatible but no callsite (in our client codebases or stack-apps) every passes a depth-2 `List[List[InterleavedContentItem]]` (which is now disallowed.)
```bash
$ cd llama_stack/providers/tests/inference
$ pytest -s -v -k fireworks test_embeddings.py \
--inference-model nomic-ai/nomic-embed-text-v1.5 --env EMBEDDING_DIMENSION=784
$  pytest -s -v -k together test_embeddings.py \
--inference-model togethercomputer/m2-bert-80M-8k-retrieval --env EMBEDDING_DIMENSION=784
$ pytest -s -v -k ollama test_embeddings.py \
--inference-model all-minilm:latest --env EMBEDDING_DIMENSION=784
```
Also ran `tests/client-sdk/inference/test_embeddings.py`
> fix(api): update embeddings signature so inputs and outputs list align

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/inference/inference.py
- llama_stack/distribution/routers/routers.py
- llama_stack/providers/inline/inference/vllm/vllm.py
- llama_stack/providers/remote/inference/bedrock/bedrock.py
- llama_stack/providers/remote/inference/cerebras/cerebras.py
- llama_stack/providers/remote/inference/databricks/databricks.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/groq/groq.py
- llama_stack/providers/remote/inference/nvidia/nvidia.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/passthrough/passthrough.py
- llama_stack/providers/remote/inference/runpod/runpod.py
- llama_stack/providers/remote/inference/sambanova/sambanova.py
- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/utils/inference/embedding_mixin.py
We need to support:
- asymmetric embedding models (#934)
- truncation policies (#933)
- varying dimensional output (#932) 
```bash
$ cd llama_stack/providers/tests/inference
$ pytest -s -v -k fireworks test_embeddings.py \
--inference-model nomic-ai/nomic-embed-text-v1.5 --env EMBEDDING_DIMENSION=784
$  pytest -s -v -k together test_embeddings.py \
--inference-model togethercomputer/m2-bert-80M-8k-retrieval --env EMBEDDING_DIMENSION=784
$ pytest -s -v -k ollama test_embeddings.py \
--inference-model all-minilm:latest --env EMBEDDING_DIMENSION=784
```
> feat(api): Add options for supporting various embedding models

- tests/client-sdk/inference/test_embedding.py
fixes test to use new name for URL import
`LLAMA_STACK_BASE_URL=http://localhost:8321 pytest -v tests/client-sdk/inference/test_embedding.py --embedding-model baai/bge-m3`
> fix: update URL import, URL -> ImageContentItemImageURL

- docs/source/references/llama_cli_reference/index.md
- llama_stack/cli/model/model.py
- llama_stack/cli/model/remove.py
add a subcommand, help to clean the unneeded model:
```
$ llama model --help
usage: llama model [-h] {download,list,prompt-format,describe,verify-download,remove} ...
Work with llama models
options:
$ llama model remove --help
usage: llama model remove [-h] -m MODEL [-f]
Remove the downloaded llama model
options:
-m MODEL, --model MODEL
Specify the llama downloaded model name
-f, --force           Used to forcefully remove the llama model from the storage without further confirmation
$ llama model remove -m Llama3.2-1B-Instruct:int4-qlora-eo8
Are you sure you want to remove …
```
> feat: model remove cmd

- tests/client-sdk/inference/test_embedding.py
#1161 updated the embedding signature making the nested list tests irrelevant
> fix: remove list of list tests, no longer relevant after #1161

- llama_stack/providers/remote/inference/nvidia/models.py
- llama_stack/templates/nvidia/run.yaml
- tests/client-sdk/inference/test_embedding.py
- Updates ImageContentItemImageURL import
- fixes `embedding_dimensions` metadata param
- Ran pytest locally, verified embedding tests pass with new types
cc: @dglogo @sumitb
> test(client-sdk): Update embedding test types to use latest imports

- llama_stack/cli/model/list.py
Currently , `model` in `--downloaded` just use the directory(already replace `:`),  so covert back to descriptor keep the same with ` llama model list`, and remove command also use `descriptor`.
```
before:
$ llama model list --downloaded
+-------------------------------------+----------+---------------------+
| Model                               | Size     | Modified Time       |
+-------------------------------------+----------+---------------------+
| Llama3.2-1B-Instruct-int4-qlora-eo8 | 1.53 GB  | 2025-02-20 16:32:49 |
+-------------------------------------+----------+---------------------+
after:
$ llama model list --downloaded
+-------------------------------------+----------+------------ …
```
> fix: convert back to model descriptor for model in list --downloaded

- CONTRIBUTING.md
This fixes the following error:
```
$ make html
/bin/sh: line 1: sphinx-build: command not found
make: *** [Makefile:20: html] Error 127
```
Also clarifies that this command only rebuilds the website without watching/refreshes.
New command works.
> docs: Add missing uv command and clarify website rebuild

- llama_stack/distribution/build_container.sh
Addresses issues where the container is unable to run as root. Gives write access to required folders.
(Closes #[1207])
I built locally and ran `llama stack build --template remote-vllm --image-type container` and validated I could see my changes in the output:
```
#11 1.186 Installed 11 packages in 61ms
#11 1.186  + llama-models==0.1.3
#11 1.186  + llama-stack==0.1.3
#11 1.186  + llama-stack-client==0.1.3
#11 1.186  + markdown-it-py==3.0.0
#11 1.186  + mdurl==0.1.2
#11 1.186  + prompt-toolkit==3.0.50
#11 1.186  + pyaml==25.1.0
#11 1.186  + pygments==2.19.1
#11 1.186  + rich==13.9.4
#11 1.186  + tiktoken==0.9.0
#11 1.186  + wcwidth==0.2.13
#11 DONE 1.6s
#12 [ 9/10] RUN mkdir -p /.llama /.cache
#12 DONE 0.3s
#13 [10/10] …
```
> fix: Updating images so that they are able to run without root access

- distributions/dependencies.json
- docs/source/distributions/self_hosted_distro/ollama.md
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/templates/ollama/build.yaml
- llama_stack/templates/ollama/ollama.py
Embedding models are tiny and can be pulled on-demand. Let's do that so the user doesn't have to do "yet another thing" to get themselves set up.
Thanks @hardikjshah for the suggestion.
Also fixed a build dependency miss (TODO: distro_codegen needs to actually check that the build template contains all providers mentioned for the run.yaml file)
First run `ollama rm all-minilm:latest`. 
Run `llama stack build --template ollama && llama stack run ollama --env INFERENCE_MODEL=llama3.2:3b-instruct-fp16`. See that it outputs a "Pulling embedding model `all-minilm:latest`" output and the stack starts up correctly. Verify that `ollama list` shows the model is correctly downloaded.
> fix: pull ollama embedding model if necessary

- llama_stack/apis/agents/agents.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/agents/meta_reference/agents.py
- llama_stack/providers/inline/agents/meta_reference/persistence.py
- https://github.com/meta-llama/llama-stack/pull/1178
- https://github.com/meta-llama/llama-stack/pull/1187
- https://github.com/meta-llama/llama-stack/pull/1194
**client changes**
- https://github.com/meta-llama/llama-stack-client-python/pull/157
- https://github.com/meta-llama/llama-stack-client-python/pull/158
```
LLAMA_STACK_BASE_URL=http://localhost:8321 pytest -v tests/client-sdk/agents/test_agents.py --inference-model meta-llama/Llama-3.1-8B-Instruct
```
```
LLAMA_STACK_CONFIG=fireworks pytest -v tests/client-sdk/agents/test_agents.py --inference-model meta-llama/Llama-3.1-8B-Instruct
```
**llama-stack-apps**
```
python -m examples.agents.react_agent localhost 8321
```
- Test with script: https://gist.github.com/yanxi0830/f2e407527f468998a700cd29fd271b15
**Output Before**: we have …
> feat(3/n): agent resume_turn

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/inference/inference.py
- llama_stack/apis/tools/rag_tool.py
- llama_stack/apis/tools/tools.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/tool_runtime/rag/memory.py
- tests/client-sdk/agents/test_agents.py
Summary:
Allows tools to output metadata. This is useful for evaluating tool outputs, e.g. RAG tool will output document IDs, which can be used to score recall.
Will need to make a similar change on the client side to support ClientTool outputting metadata.
Test Plan:
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/agents/test_agents.py
> feat: tool outputs metadata

- .pre-commit-config.yaml
- llama_stack/apis/common/type_system.py
- llama_stack/schema_utils.py
- llama_stack/scripts/distro_codegen.py
- llama_stack/scripts/run_client_sdk_tests.py
- pyproject.toml
- requirements.txt
- uv.lock
- Enable mypy to run in the CI on a subset of the repository
- Fix a few mypy errors
- Run mypy from pre-commit
> ci: add mypy for static type checking

- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/utils/inference/model_registry.py
- tests/client-sdk/conftest.py
- tests/client-sdk/inference/test_text_inference.py
- tests/client-sdk/inference/test_vision_inference.py
This PR begins the process of supporting non-llama models within Llama Stack. We start simple by adding support for this functionality within a few existing providers: fireworks, together and ollama. 
```bash
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/inference/test_text_inference.py \
--inference-model accounts/fireworks/models/phi-3-vision-128k-instruct
```
^ this passes most of the tests but as expected fails the tool calling related tests since they are very specific to Llama models
```
inference/test_text_inference.py::test_text_completion_streaming[accounts/fireworks/models/phi-3-vision-128k-instruct] PASSED
inference/test_text_inference.py::test_completion_log_probs_non_streaming[accounts/fireworks/models/phi-3-vision-128k-instruct] PASSED …
```
> feat(providers): support non-llama models for inference providers

- llama_stack/cli/model/list.py
`llama model list` or `llama model list --show-all` will list more or all for the models, so add the `search` option to simplify the output.
```
$ llama model list --help
usage: llama model list [-h] [--show-all] [-s SEARCH]
Show available llama models
options:
--show-all            Show all models (not just defaults)
-s SEARCH, --search SEARCH
Search for the input string as a substring in the model descriptor(ID)
$ llama model list -s 70b
+-----------------------+-----------------------------------+----------------+
| Model Descriptor(ID)  | Hugging Face Repo                 | Context Length | …
```
> feat: add substring search for model list

- .pre-commit-config.yaml
- llama_stack/cli/stack/_build.py
- llama_stack/distribution/build_venv.sh
- llama_stack/distribution/library_client.py
- llama_stack/distribution/start_venv.sh
- llama_stack/distribution/utils/exec.py
Make sure venv behaves like conda (no prefix is added to image_name) and `--image-type venv` inside a notebook "just works" without any fiddling
> fix: update virtualenv building so llamastack- prefix is not added, make notebook experience easier

- llama_stack/cli/stack/_build.py
- llama_stack/cli/stack/build.py
- llama_stack/cli/stack/run.py
- llama_stack/distribution/build.py
- llama_stack/distribution/utils/exec.py
- llama_stack/distribution/utils/image_types.py
--run runs the stack that was just build using the same arguments during the build process (image-name, type, etc)
This simplifies the workflow a lot and makes the UX better for most local users trying to get started rather than having to match the flags of the two commands (build and then run)
Also, moved `ImageType` to distribution.utils since there were circular import errors with its old location
tested locally using the following command: 
`llama stack build --run --template ollama --image-type venv`
> feat: add --run to llama stack build

- docs/source/concepts/index.md
- docs/source/providers/index.md
This increases visibility of the vLLM provider.
> docs: Add vLLM to the list of inference providers in concepts and providers pages

- llama_stack/cli/stack/_build.py
- llama_stack/distribution/build_container.sh
- llama_stack/distribution/build_venv.sh
When building providers in a virtual environment or containers, special
pip dependencies may not always be provided (e.g., for Ollama). The
check should only fail if the required number of arguments is missing.
Currently, two arguments are mandatory:
1. Environment name
2. Pip dependencies
Additionally, return statements were replaced with sys.exit(1) in error
conditions to ensure immediate termination on critical failures. Error
handling in the stack build process was also improved to guarantee the
program exits with status 1 when facing configuration issues or build
failures.
This command shouldn't fail:
```
llama stack build --template …
```
> fix: avoid failure when no special pip deps and better exit

- llama_stack/distribution/routers/routers.py
- llama_stack/providers/utils/inference/prompt_adapter.py
Summary:
Currently we don't set the best tool_prompt_format according to model as promisd.
Test Plan:
Added print around raw model input and inspected manually
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack/pull/1214).
* #1234
* __->__ #1214
> fix: set default tool_prompt_format in inference api

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Summary:
kotlin SDK expects this format
Test Plan:
python prints the expected format
>>> str(datetime.now().astimezone())
'2025-02-24 22:02:58.729763-08:00'
> fix: include timezone in Agent steps' timestamps

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
When there are issues with the tool call function, an exception is raised but the error message is not informative. This adds a clearer message to tell users to check their functions.
```
File "/Users/phayes/projects/llama-stack/llama-stack/llama_stack/distribution/server/server.py", line 208, in sse_generator
async for item in event_gen:
File "/Users/phayes/projects/llama-stack/llama-stack/llama_stack/providers/inline/agents/meta_reference/agents.py", line 165, in _create_agent_turn_streaming
async for event in agent.create_and_execute_turn(request):
File "/Users/phayes/projects/llama-stack/llama-stack/llama_stack/providers/inline/agents/meta_reference/agent_instance.py", line 197, in create_and_execute_turn
async for chunk in self.run(
File …
```
> fix: Raise exception when tool call result is None

- llama_stack/providers/inline/inference/meta_reference/parallel_utils.py
- llama_stack/providers/inline/inference/meta_reference/quantization/loader.py
- llama_stack/providers/inline/tool_runtime/code_interpreter/matplotlib_custom_backend.py
- llama_stack/providers/remote/inference/databricks/databricks.py
- llama_stack/providers/tests/post_training/test_post_training.py
- llama_stack/providers/utils/inference/embedding_mixin.py
- pyproject.toml
- Fixed type hinting and missing imports across multiple modules.
- Improved compatibility by using `TYPE_CHECKING` for conditional imports.
- Updated `pyproject.toml` to enforce stricter linting.
> fix: resolve type hint issues and import dependencies

- llama_stack/distribution/build_venv.sh
currently, build_venv.sh expects a `distribution_type` as the first argument but the only things ever passed are:
1. image name
2. pip dependencies
so distribution_type is never passed in meaning the script errors when calling something like:
`llama stack build --image-type venv --template ollama --image-name test`
before output:
```
llama stack build --image-type venv --template ollama --image-name venv-test
Usage: /Users/charliedoern/projects/Documents/llama-stack/llama_stack/distribution/build_venv.sh <distribution_type> <env_name> <pip_dependencies> [<special_pip_deps>]
Example: /Users/charliedoern/projects/Documents/llama-stack/llama_stack/distribution/build_venv.sh <distribution_type> mybuild ./my-stack-build.yaml 'numpy pandas scipy'
Failed to build target venv-test with return …
```
> fix: build_venv expects an extra argument

- docs/source/references/llama_stack_client_cli_reference.md
**Description:**  This PR removes the "$" symbol from the client CLI reference so that users have the ability to use the copy and paste code function without copying over the "$" symbol. Ik the "$" are good for showing user permissions, but I noticed they're not really used in other parts of the docs, and it makes the the copy and paste code blocks user flow easier.
Very small nit PR, this is not a huge deal if PR is not needed.
> docs: Remove $ from client CLI ref  to add valid copy and paste ability

- .pre-commit-config.yaml
- distributions/dependencies.json
Merges the two "files" field for codegen check. This also fixes the broken main branch CI build.
```
Distribution Template Codegen............................................Passed
- hook id: distro-codegen
- duration: 367.44s
```
> build: Merge redundant "files" field for codegen check in .pre-commit-config.yaml

- llama_stack/cli/stack/run.py
- llama_stack/distribution/server/server.py
- Introduced logging in `StackRun` to replace print-based messages
- Improved error handling for config file loading and parsing
- Replaced `cprint` with `logger.error` for consistent error messaging
- Ensured logging is used in `server.py` for startup, shutdown, and runtime messages
- Added missing exception handling for invalid providers
> refactor(server): replace print statements with logger

- llama_stack/cli/model/describe.py
If not passed the `headers`, it will display empty for the first row, also might break the second row, make the `Model` row as `headers`.
```
Before:
$ llama model describe -m Llama3.1-70B
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                             ┃                                ┃ <<<---------
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Model             │ Llama3.1-70B         │   <<<---------
├─────────────────────────────┼────────────────────────────────┤
│ Hugging Face ID             │ meta-llama/Llama-3.1-70B       │
├─────────────────────────────┼────────────────────────────────┤
│ Description                 │ Llama 3.1 70b model …
```
> fix: fix the describe table display issue

- llama_stack/cli/download.py
Actually, the incorrect token also will hit `RepositoryNotFoundError`, e.g.
```
$ llama model download --source huggingface --model-id Llama3.2-1B-Instruct:int4-qlora-eo8 --hf-token xx  ### xx is incorrect token
----RepositoryNotFoundError--->
usage: llama model download [-h] [--source {meta,huggingface}] [--model-id MODEL_ID]
[--hf-token HF_TOKEN] [--meta-url META_URL]
[--max-parallel MAX_PARALLEL] [--ignore-patterns IGNORE_PATTERNS]
[--manifest-file MANIFEST_FILE]
llama model download: error: Repository 'meta-llama/Llama-3.2-1B-Instruct-QLORA_INT4_EO8' not found on the Hugging Face Hub.
so update to:
llama model download --source huggingface --model-id Llama3.2-1B-Instruct:int4-qlora-eo8 …
```
> chore: update download error message

- llama_stack/providers/remote/inference/nvidia/nvidia.py
- llama_stack/providers/remote/inference/nvidia/openai_utils.py
- llama_stack/providers/tests/inference/conftest.py
- llama_stack/providers/tests/inference/fixtures.py
- llama_stack/providers/utils/inference/openai_compat.py
This PR:
- refactors code which converts between Llama Stack <> OpenAI compat servers which was used by the nvidia implementation to be used more broadly. Next PRs in the stack will show usage.
- adds incremental tool call parsing (when tool calls are streamed incrementally, not just whole-sale)
Run 
```bash
pytest -s -v -k nvidia llama_stack/providers/tests/inference/ --env NVIDIA_API_KEY=....
```
Text model tests pass (albeit without completions tests)
```
test_text_inference.py::TestInference::test_model_list[-nvidia] PASSED
test_text_inference.py::TestInference::test_text_completion_non_streaming[-nvidia-inference:completion:non_streaming] FAILED
test_text_inference.py::TestInference::test_text_completion_streaming[-nvidia-inference:completion:streaming] FAILED …
```
> refactor: move OpenAI compat utilities from nvidia to openai_compat

- llama_stack/cli/stack/run.py
I think this got accidentally removed as part of https://github.com/meta-llama/llama-stack/pull/1250. cc @leseb 
After the change, this arg is no longer required.
> fix(cli): Missing default for --image-type in stack run command

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/remote/inference/vllm/vllm.py
This PR makes a couple of changes required to get the test `tests/client-sdk/agents/test_agents.py::test_builtin_tool_web_search` passing on the remote-vllm provider.
First, we adjust agent_instance to also pass in the description and parameters of builtin tools. We need these parameters so we can pass the tool's expected parameters into vLLM. The meta-reference implementations may not have needed these for builtin tools, as they are able to take advantage of the Llama-model specific support for certain builtin tools. However, with vLLM, our server-side chat templates for tool calling treat all tools the same and don't separate out Llama builtin vs custom tools. So, we need to pass the full set of parameter definitions and list of required parameters for builtin tools as well.
Next, we …
> fix: Get builtin tool calling working in remote-vllm

- llama_stack/distribution/routers/routers.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/tool_runtime/rag/memory.py
- tests/client-sdk/agents/test_agents.py
Summary:
Lets the model decide which tool it needs to call to respond to a query.
Test Plan:
```
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/ --safety-shield meta-llama/Llama-Guard-3-8B
```
Also evaluated on a small benchmark with 20 questions from HotpotQA. With this PR and some prompting, the performance is 77% recall compared to 50% currently.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack/pull/1015).
* #1268
* #1239
* __->__ #1015
> feat: remove special handling of builtin::rag tool

- docs/notebooks/Alpha_Llama_Stack_Post_Training.ipynb
- add 'open in colab' icon that links to the notebook
- update the pip install llama-stack pkg part
preview
> feat: update the post training notebook

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Summary:
missed in last PR
Test Plan:
```
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/agents/test_agents.py::test_create_turn_response --safety-shield meta-llama/Llama-Guard-3-8B
```
> fix: time logging format

- docs/getting_started.ipynb
- docs/source/building_applications/agent_execution_loop.md
- docs/source/building_applications/rag.md
- docs/source/getting_started/index.md
- llama_stack/distribution/ui/page/playground/rag.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- tests/client-sdk/agents/test_agents.py
Summary:
E.g. `builtin::rag::knowledge_search`
Test Plan:
```
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/agents/ --safety-shield meta-llama/Llama-Guard-3-8B
```
> feat: allow specifying specific tool within toolgroup

- .pre-commit-config.yaml
See https://github.com/astral-sh/uv-pre-commit/blob/main/.pre-commit-hooks.yaml#L31-L40
`uv-sync` is supposed to be used on "post-checkout, post-rebase" etc. The intention here is decidedly not that. The desire is if you changed pyproject.toml, you should update `uv.lock` (and then also export it to requirements.txt via uv-export).
> chore: upgrade uv pre-commit version, uv-sync -> uv-lock

- llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
This is a follow up to:
https://github.com/meta-llama/llama-stack/pull/1140
Avoid unnecessary GPU memory clean attempt when the GPU is not used for training.
With CPU:
```
INFO 2025-02-26 16:43:56,267 torchtune.utils._logging:121: Model checkpoint of size 6.43 GB saved to /Users/ihrachys/.llama/checkpoints/meta-llama/Llama-3.2-3B-Instruct-sft-0/consolidated.00.pth
INFO 2025-02-26 16:43:56,274 torchtune.utils._logging:132: Adapter checkpoint of size 0.00 GB saved to /Users/ihrachys/.llama/checkpoints/meta-llama/Llama-3.2-3B-Instruct-sft-0/ …
```
> fix: don't attempt to clean gpu memory up when device is cpu

- distributions/dependencies.json
- docs/source/distributions/self_hosted_distro/ollama.md
- llama_stack/templates/ollama/build.yaml
- llama_stack/templates/ollama/ollama.py
- llama_stack/templates/ollama/run-with-safety.yaml
- llama_stack/templates/ollama/run.yaml
Model context protocol (MCP) allows for remote tools to be connected with Agents. The current Ollama provider does not support it. This PR adds necessary code changes to ensure that the integration between Ollama backend and MCP works.
This PR is an extension of #816 for Ollama. 
1. Run llama-stack server with the command:
```
llama stack build --template ollama --image-type conda
llama stack run ./templates/ollama/run.yaml \
--port $LLAMA_STACK_PORT \
--env INFERENCE_MODEL=$INFERENCE_MODEL \
--env OLLAMA_URL=http://localhost:11434
```
2. Run the sample client agent with MCP tool:
```
from llama_stack_client.lib.agents.agent import Agent
from …
```
> feat: Add model context protocol tools with ollama provider

- llama_stack/distribution/library_client.py
- llama_stack/providers/utils/inference/openai_compat.py
- tests/client-sdk/inference/test_text_inference.py
Tool format depends on the model. @ehhuang introduced a `get_default_tool_prompt_format` function for this purpose. We should use that instead of hacky model ID matching we had before.
Secondly, non llama models don't have this concept so testing with those models should work as is.
```bash
for distro in fireworks ollama; do
LLAMA_STACK_CONFIG=$distro \
pytest -s -v tests/client-sdk/inference/test_text_inference.py \
--inference-model=meta-llama/Llama-3.2-3B-Instruct \
--vision-inference-model=""
done
LLAMA_STACK_CONFIG=dev \
pytest -s -v tests/client-sdk/inference/test_text_inference.py \
--inference-model=openai/gpt-4o \
--vision-inference-model=""
```
> fix(test): update client-sdk tests to handle tool format parametrization better

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Summary:
Test Plan:
run with a non-existing tool group
> feat: don't silently ignore incorrect toolgroup

- llama_stack/providers/inline/agents/meta_reference/persistence.py
Reverts meta-llama/llama-stack#1296
This change breaks test: `session_info.vector_db_id` is actually used
```
pytest -v tests/client-sdk/agents/test_agents.py::test_rag_and_code_agent --inference-model meta-llama/Llama-3.1-8B-Instruct
```
> fix: Revert "chore: remove vector_db_id from AgentSessionInfo"

- llama_stack/providers/inline/inference/sentence_transformers/config.py
Now that remote-vllm include inline::sentence_transformers there is an issue building the image:
Error building stack: SentenceTransformersInferenceConfig.sample_run_config() got an unexpected keyword argument '__distro_dir__'     
To avoid that issue this fix extends the sample_run_config to accept extra kwargs
> fix: Avoid unexpected keyword argument for sentence_transformers

- llama_stack/cli/llama.py
- llama_stack/cli/model/model.py
- llama_stack/cli/stack/stack.py
- llama_stack/cli/stack/utils.py
```
before:
$ llama
usage: llama [-h] {model,stack,download,verify-download} ...
Welcome to the Llama CLI
options:
subcommands:
{model,stack,download,verify-download}
$ llama model --help
usage: llama model [-h] {download,list,prompt-format,describe,verify-download,remove} ...
Work with llama models
options:
model_subcommands:
{download,list,prompt-format,describe,verify-download,remove}
$ llama stack --help
usage: llama stack [-h] [--version] {build,list-apis,list-providers,run} ...
Operations for the Llama Stack / Distributions
options:
-h, --help            show this help message and …
```
> chore: add subcommands description in help

- llama_stack/providers/tests/test_cases/inference/chat_completion.json
- llama_stack/providers/utils/inference/litellm_openai_mixin.py
- tests/client-sdk/inference/test_text_inference.py
Handle recursive nature in the structured response_formats. 
Update test to include 1 nested model.
```
LLAMA_STACK_CONFIG=dev pytest -s -v tests/client-sdk/inference/test_text_inference.py --inference-model "openai/gpt-4o-mini" -k test_text_chat_completion_structured_output
```
> fix: Structured outputs for recursive models

- llama_stack/providers/utils/inference/openai_compat.py
- Test with script: https://gist.github.com/yanxi0830/64699f3604766ac2319421b750c5bf9c
- Agent with tool calls does not get correctly parsed with LiteLLM provider b/c we skip processing `ChatCompletionResponseEventType.complete`. 
- However, LiteLLM spits out event_type="complete" with ToolCallDelta
https://github.com/meta-llama/llama-stack/blob/2f7683bc5fc33192fe34533d47d47328ff522fee/llama_stack/providers/inline/agents/meta_reference/agent_instance.py#L570-L577
- Llama Model
```
ChatCompletionResponseStreamChunk(
│   event=Event(
│   │   delta=ToolCallDelta(
│   │   │   parse_status='succeeded',
│   │   │   tool_call=ToolCall(
│   │   │   │   arguments={'kind': 'pod', 'namespace': 'openshift-lightspeed'},
│   │   │   │   call_id='call_tIjWTUdsQXhQ2XHC5ke4EQY5',
│   │   │   │ …
```
> fix: litellm tool call parsing event type to in_progress

- llama_stack/cli/model/model.py
This fixes release build failure: https://github.com/meta-llama/llama-stack-ops/actions/runs/13579787331/job/37963565001
```
+ llama model prompt-format -m Llama3.2-11B-Vision-Instruct
File "/tmp/tmp.PXMDlmD0x5/.venv/bin/llama", line 4, in <module>
from llama_stack.cli.llama import main
File "/tmp/tmp.PXMDlmD0x5/.venv/lib/python3.10/site-packages/llama_stack/cli/llama.py", line 10, in <module>
from .model import ModelParser
File "/tmp/tmp.PXMDlmD0x5/.venv/lib/python3.10/site-packages/llama_stack/cli/model/__init__.py", line 7, in <module>
from .model import ModelParser  # noqa
File "/tmp/tmp.PXMDlmD0x5/.venv/lib/python3.10/site-packages/llama_stack/cli/model/model.py", line 16, in <module>
from llama_stack.cli.utils import print_subcommand_description …
```
> fix: Incorrect import path for print_subcommand_description()

- tests/client-sdk/inference/test_embedding.py
This fixes release build failure https://github.com/meta-llama/llama-stack-ops/actions/runs/13580302250/job/37964972403:
```
=================================== FAILURES ===================================
______ test_embedding_truncation_error[txt=8B:emb=MiniLM-long-text-None] _______
llama-stack/tests/client-sdk/inference/test_embedding.py:166: in test_embedding_truncation_error
with pytest.raises(BadRequestError) as excinfo:
E   Failed: DID NOT RAISE <class 'llama_stack_client.BadRequestError'>
______ test_embedding_truncation_error[txt=8B:emb=MiniLM-long-text-none] _______
llama-stack/tests/client-sdk/inference/test_embedding.py:166: in test_embedding_truncation_error
with pytest.raises(BadRequestError) as excinfo:
E   Failed: DID NOT RAISE <class 'llama_stack_client.BadRequestError'> …
```
> test: Only run embedding tests for remote::nvidia

- docs/getting_started.ipynb
- See https://github.com/meta-llama/llama-stack-ops/actions/runs/13580825399/job/37966677766
- Together's structured decoding API is flaky, add skip to cell
- Enable cell 21 to pass cell 21-23
> fix: update getting_started notebook to pass nbeval

- llama_stack/providers/utils/inference/openai_compat.py
`ChatCompletionResponseEventType: start` is ignored and not yielded in the agent_instance as we expect that to not have any content. 
However, litellm sends first event as `ChatCompletionResponseEventType: start` with content ( which was the first token that we were skipping ) 
```
LLAMA_STACK_CONFIG=dev pytest -s -v tests/client-sdk/agents/test_agents.py --inference-model "openai/gpt-4o-mini" -k test_agent_simple
``` 
This was failing before ( since the word hello was not in the final response )
> fix: [Litellm]Do not swallow first token

- llama_stack/models/llama/llama3/prompt_templates/system_prompts.py
The current prompt doesn't work well and tend to overindex on tool calling. This PR is not perfect, but should be an improvement over the current prompt. We can keep iterating.
Ran on a (small) eval with 20 HotpotQA examples.
With current prompt: https://gist.github.com/ehhuang/9f967e62751907165eb13781ea968f5c
{
│   'basic::equality': {'accuracy': {'accuracy': 0.2, 'num_correct': 4.0, 'num_total': 20}},
│   'F1ScoringFn': {
│   │   'f1_average': 0.25333333333333335,
│   │   'precision_average': 0.23301767676767676,
│   │   'recall_average': 0.375
│   }
}
num_tool_calls=[5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 2, 2, 1, 1, 2, 1, 2, 2]
num_examples_with_tool_call=20
num_examples_with_pythontag=0
#########################################################
With new prompt: …
> feat: update the default system prompt for 3.2/3.3 models

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/utils/telemetry/trace_protocol.py
Original telemetry outputs for agent turns look like this. 
Note: how output was a `str(message)` making it difficult to read them back for downstream tasks ( eg. building eval datasets )
```
{
│   │   'input': [
│   │   │   '{"role":"system","content":"You are a helpful assistant. Use search tool to answer the questions. "}',
│   │   │   '{"role":"user","content":"Which teams played in the NBA western conference finals of 2024","context":null}'
│   │   ],
│   │   'output': "content:  tool_calls: [ToolCall(call_id='8b7294ec-a83f-4798-ad8f-6bed662f08b6', tool_name=<BuiltinTool.brave_search: 'brave_search'>, arguments={'query': 'NBA Western Conference Finals 2024 teams'})]"
│   },
``` 
Updated the outputs to be structured .
```python
import uuid
from llama_stack_client.lib.agents.agent …
```
> fix: Agent telemetry inputs/outputs should be structured

- llama_stack/distribution/utils/exec.py
check conda env name using basepath in exec.py
The current logic for finding conda prefix does a `endswith` check with just the conda env name, but this will cause us to match incorrect if there is a different conda env which ends with same suffix. In my case, i had stack and llama-stack as the two conda envs.
llama stack run ~/.llama/distributions/fireworks/fireworks-run.yaml
> fix: check conda env name using basepath in exec.py

- llama_stack/cli/model/prompt_format.py
https://github.com/meta-llama/llama-stack/blob/19ae4b35d9d22841ca14f30166d4b317554bd28d/llama_stack/cli/model/prompt_format.py#L47
Based on the comment: `Only Llama 3.1 and 3.2 are supported`, even 3.1, 3.2 are not all models can show it with `prompt-format`, so cannot refer to `llama model list`, 
only refer to list when enter a invalid model,  so it would be nice to help to check the valid models:
```
llama model prompt-format -m Llama3.1-405B-Instruct:bf16-mp8
usage: llama model prompt-format [-h] [-m MODEL_NAME] [-l]
llama model prompt-format: error: Llama3.1-405B-Instruct:bf16-mp8 is not a valid Model <<<<---. Choose one from --
Llama3.1-8B
Llama3.1-70B
Llama3.1-405B
Llama3.1-8B-Instruct …
```
> feat: add prompt-format list

- llama_stack/providers/remote/inference/vllm/vllm.py
This is to be consistent with OpenAI API and support vLLM <= v0.6.3
References:
* https://platform.openai.com/docs/api-reference/chat/create#chat-create-tool_choice
* https://github.com/vllm-project/vllm/pull/10000
This fixes the error when running older versions of vLLM:
```
00:50:19.834 [START] /v1/inference/chat-completion
INFO 2025-02-28 00:50:20,203 httpx:1025: HTTP Request: POST https://api-xeai-granite-3-1-8b-instruct.apps.int.stc.ai.preprod.us-east-1.aws.paas.redhat.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 235, in endpoint
return await maybe_await(value)
File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", …
```
> fix: Make remote::vllm compatible with vLLM <= v0.6.3

- llama_stack/distribution/build.py
- llama_stack/distribution/build_container.sh
See individual commit messages.
Apply this diff:
```
diff --git a/llama_stack/templates/ollama/build.yaml b/llama_stack/templates/ollama/build.yaml
index da33b8d5..4a702f6f 100644
--- a/llama_stack/templates/ollama/build.yaml
+++ b/llama_stack/templates/ollama/build.yaml
@@ -28,5 +28,5 @@ distribution_spec:
- remote::tavily-search
- inline::code-interpreter
- inline::rag-runtime
-    - remote::model-context-protocol
+  container_image: "registry.access.redhat.com/ubi9"
image_type: conda
```
Then run:
```
CONTAINER_BINARY=podman llama stack build --template ollama --image-type container --image-name registry.access.redhat.com/ubi9
Containerfile created successfully in …
```
> build(container): misc improvements

- tests/client-sdk/inference/test_embedding.py
- skip media tests for models that do not support media
- skip output_dimension tests for models that do not support it
- skip task_type tests for models that do not support it
- provide task_type for models that require it
`LLAMA_STACK_BASE_URL=http://localhost:8321 pytest -v tests/client-sdk/inference/test_embedding.py --embedding-model ...`
> test: cleanup embedding model test suite

- llama_stack/providers/inline/eval/meta_reference/eval.py
- Using `eval` on server is a security risk
- Replace `eval` with `json.loads`
```
pytest -v -s --nbval-lax ./llama-stack/docs/notebooks/Llama_Stack_Benchmark_Evals.ipynb 
```
> fix: replace eval with json decoding

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- docs/openapi_generator/generate.py
- docs/openapi_generator/pyopenapi/generator.py
- docs/openapi_generator/pyopenapi/options.py
- llama_stack/apis/datatypes.py
An API spec must talk about Error handling. This was a pretty glaring omission so far. This PR begins to address it by adding a set of standard error responses we can attach to all our API calls. 
At a future point, we can add specific error types where necessary (although we should not hurry to do that; it is best done very late.)
Checked that Stainless SDK generation succeeds.
> feat: enhance OpenAPI spec to include Error types

- llama_stack/providers/inline/post_training/torchtune/datasets/format_adapter.py
- using `eval` is a security risk
- see https://github.com/meta-llama/llama-stack/pull/1327
cc @SLR722 we will need to update the corresponding dataset via
```python
def update_to_json_str():
dataset = datasets.load_dataset(...)
processed_dataset = dataset[split].map(
lambda x: {
"column": json.dumps(eval(x["column"]))
}
)
processed_dataset.push_to_hub(...)
```
> fix: replace eval with json decoding for format_adapter

- tests/client-sdk/agents/test_agents.py
Use @client_tool decorator instead of ClientTool
```
LLAMA_STACK_CONFIG=fireworks pytest -v tests/client-sdk/agents/test_agents.py --inference-model "meta-llama/Llama-3.3-70B-Instruct"
```
> chore: refactor client tool in test

- docs/zero_to_hero_guide/README.md
This PR updates the version in the [README.md](https://github.com/meta-llama/llama-stack/blob/main/docs/zero_to_hero_guide/README.md) to reflect the latest changes in Llama Stack setup.
Previously, using **llama-stack==0.1.0** caused an error when running:
```bash
llama stack build --template ollama --image-type conda
```
Upgrading to llama-stack==0.1.3 resolves this issue.
- Verified that `llama stack build --template ollama --image-type conda` works correctly.
> docs: Update llama-stack version in README.md

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- tests/client-sdk/agents/test_agents.py
Summary:
This was broken by https://github.com/meta-llama/llama-stack/pull/1015/files#r1975394190
Test Plan:
added e2e test
> fix: RAG with documents

- docs/source/distributions/building_distro.md
- llama_stack/cli/stack/build.py
https://github.com/meta-llama/llama-stack/tree/21ec67356c48ee878922d83154ba57433467b342/distributions
It should missed the `s`.
> chore: fix typo

- llama_stack/distribution/library_client.py
This led to extremely hard to debug messages.
Before:
llama_stack/distribution/library_client.py:275: in request
response = await self._call_non_streaming(
llama_stack/distribution/library_client.py:322: in _call_non_streaming
result = await matched_func(**body)
llama_stack/providers/utils/telemetry/trace_protocol.py:102: in async_wrapper
result = await method(self, *args, **kwargs)
llama_stack/providers/inline/agents/meta_reference/agents.py:80: in create_agent
value=agent_config.model_dump_json(),
E   AttributeError: 'dict' object has no attribute 'model_dump_json'
After:
E   ValueError: Failed to convert parameter {'model': 'meta-llama/Llama-3.1-8B-Instruct', 'instructions': 'You are a helpful assistant', 'sampling_params': {'strategy': {'type': 'top_p', 'temperature': 0.0001, 'top_p': …
> fix: raise error when request param failed to convert

- llama_stack/distribution/start_stack.sh
> chore: add container cmd check in start_stack.sh

- llama_stack/distribution/resolver.py
- llama_stack/distribution/stack.py
- llama_stack/providers/inline/vector_io/faiss/config.py
- llama_stack/providers/remote/vector_io/chroma/config.py
- llama_stack/providers/remote/vector_io/pgvector/config.py
- llama_stack/templates/dev/dev.py
- llama_stack/templates/dev/run.yaml
- llama_stack/templates/sambanova/run.yaml
- llama_stack/templates/sambanova/sambanova.py
- tests/client-sdk/vector_io/test_vector_io.py
- tests/test_replace_env_vars.py
We want to bundle a bunch of (typically remote) providers in a distro template and be able to configure them "on the fly" via environment variables. So far, we have been able to do this with simple env var replacements. However, sometimes you want to only conditionally enable providers (because the relevant remote services may not be alive, or relevant.) This was not possible until now. 
To aid this, we add a simple (bash-like) env var replacement enhancement: `${env.FOO+bar}` evaluates to `bar` if the variable is SET and evaluates to empty string if it is not. On top of that, we update our main resolver to ignore any provider whose ID is null. 
This allows using the distro like this:
```bash
llama stack run dev --env CHROMADB_URL=http://localhost:6001 --env ENABLE_CHROMADB=1
```
when …
> feat: allow conditionally enabling providers in run.yaml

- llama_stack/distribution/start_stack.sh
Sorry for the https://github.com/meta-llama/llama-stack/pull/1340 logic, it will cause issue if in `non-container` env.
```
Using conda <<<<<<<------ environment: stack
+ is_command_available docker
+ command -v docker
+ printf '\033[0;31mError: docker command not found. Is docker installed and in your PATH?\033[0m'
Error: docker command not found. Is docker installed and in your PATH?+ exit 1
```
> fix: update cmd check logic

- llama_stack/distribution/resolver.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/server/server.py
- llama_stack/distribution/stack.py
- llama_stack/distribution/start_stack.sh
- llama_stack/logcat.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/utils/inference/litellm_openai_mixin.py
- pyproject.toml
- tests/test_logcat.py
A self-respecting server needs good observability which starts with configurable logging. Llama Stack had little until now. This PR adds a `logcat` facility towards that. Callsites look like:
```python
logcat.debug("inference", f"params to ollama: {params}")
```
- the first parameter is a category. there is a static list of categories in `llama_stack/logcat.py`
- each category can be associated with a log-level which can be configured via the `LLAMA_STACK_LOGGING` env var.
- a value `LLAMA_STACK_LOGGING=inference=debug;server=info"` does the obvious thing. there is a special key called `all` which is an alias for all categories
Ran with `LLAMA_STACK_LOGGING="all=debug" llama stack run fireworks` and saw the following:
Hit it with a client-sdk test case and saw this:
> feat: add a configurable category-based logger

- llama_stack/distribution/routers/routers.py
Closes #1355 
Start server and execute e`xamples/agents/rag_with_vector_db.py` from `llama-stack-apps`.
> fix: Fixed use of chunk.id

- llama_stack/distribution/resolver.py
- pyproject.toml
- Modularized `resolve_impls` by extracting helper functions for validation, sorting, and instantiation.
- Improved readability by introducing `validate_and_prepare_providers`, `sort_providers_by_dependency`, and `instantiate_providers`.
- Enhanced type safety with explicit type hints (`Tuple`, `Dict`, `Set`, etc.).
- Fixed potential issues with provider module imports and added error handling.
- Updated `pyproject.toml` to enforce type checking on `resolver.py` using `mypy`.
- [//]: # (If resolving an issue, uncomment and update the line below)
Run the server.
> refactor: restructure resolver logic and improve type safety

- llama_stack/distribution/routers/routers.py
- llama_stack/providers/utils/inference/prompt_adapter.py
Summary:
https://github.com/meta-llama/llama-stack/pull/1214 introduced `get_default_tool_prompt_format` but tried to use it on the raw identifier.
Here we move calling this func later in the stack and rely on the inference provider to resolve the raw identifier into llama model, then call get_default_tool_prompt_format.
Test Plan:
```
LLAMA_STACK_CONFIG=ollama pytest -s -v tests/client-sdk/inference/test_text_inference.py::test_text_chat_completion_with_tool_calling_and_non_streaming --inference-model=llama3.2:3b-instruct-fp16 --vision-inference-model=""
```
Before:
After:
> feat: better using get_default_tool_prompt_format

- docs/source/distributions/building_distro.md
- llama_stack/cli/stack/run.py
It would be better to tell user env var usage in help text.
```
before:
$ llama stack run --help
--port PORT           Port to run the server on. Defaults to 8321
after
$ llama stack run --help
--port PORT           Port to run the server on. It can also be passed via the env var LLAMA_STACK_PORT. Defaults to 8321
```
> chore: improve --port help text

- llama_stack/providers/remote/vector_io/pgvector/pgvector.py
Fix SQL syntax errors caused by hyphens in Vector DB IDs by sanitizing table
Test confirms table names with hyphens are properly converted to underscores
> fix(pgvector): replace hyphens with underscores in table names

- CONTRIBUTING.md
- llama_stack/distribution/ui/README.md
- llama_stack/providers/tests/README.md
When going through READMEs, I found that I had to keep editing the code blocks since they were prefixed with `$ `. A common pattern is to triple click (highlight all) a block and then copy paste. This minor change will make this easier for folks to follow the READMEs.
N/A
> chore: Make README code blocks more easily copy pastable

- llama_stack/providers/inline/scoring/llm_as_judge/scoring.py
- add ability to register a llm-as-judge scoring function with custom judge prompts / params. 
- Closes https://github.com/meta-llama/llama-stack/issues/1395
**Via CLI**
```
llama-stack-client scoring_functions register \ 
--scoring-fn-id "llm-as-judge::my-prompt" \
--description "my custom judge" \
--return-type '{"type": "string"}' \
--provider-id "llm-as-judge" \
--provider-scoring-fn-id "my-prompt" \
--params '{"type": "llm_as_judge", "judge_model": "meta-llama/Llama-3.2-3B-Instruct", "prompt_template": "always output 1.0"}'
```
- Unit test will be addressed with https://github.com/meta-llama/llama-stack/issues/1396
> feat(1/n): scoring function registration for llm-as-judge

- tests/unit/providers/vector_io/test_sqlite_vec.py
- tests/unit/rag/test_vector_store.py
This fixes two tests that fail for me locally:
- tests/unit/providers/vector_io/test_sqlite_vec.py
- tests/unit/rag/test_vector_store.py
The error with test_sqlite_vec.py was:
```
@pytest.mark.asyncio
async def test_add_chunks(sqlite_vec_index, sample_chunks, sample_embeddings):
>       await sqlite_vec_index.add_chunks(sample_chunks, sample_embeddings, batch_size=2)
E       AttributeError: 'coroutine' object has no attribute 'add_chunks'
tests/unit/providers/vector_io/test_sqlite_vec.py:76: AttributeError
```
The reason for that error is the sqlite_vec_index fixture was not marked as `@pytest_asyncio.fixture` and instead was marked as `@pytest.fixture`. Thus, it was returning a coroutine from the fixture instead of the actual fixture.
The error with test_vector_store.py was:
```
> …
```
> chore: Get sqlite_vec and vector_store unit tests passing

- llama_stack/providers/inline/scoring/basic/scoring_fn/fn_defs/regex_parser_multiple_choice_answer.py
add better-performance prompt: existing prompts expect a generated response that ends in "Answer :". But during test, we found that for GPQA, the prompt used by meta internal genEval "The best answer is [ABCD]" achieves higher accuracy .
```
(myenv) [yyy@devgpu018.nha2 ~/internal-llama-stack (yyy)]$llama-stack-client eval run-benchmark "meta-reference-gpqa-cot"  --model-id   meta-llama/Llama-4-17B-Llama-API  --output-dir /tmp/gpqa    --num-examples   20
....
Sending HTTP Request: GET http://localhost:5001/v1/scoring-functions/basic::regex_parser_multiple_choice_answer
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20/20  [ 0:04:46 < 0:00:00 , 0 it/s ]
✓ Results saved to: /tmp/gpqa/meta-reference-gpqa-cot_results.json!
(myenv) …
```
> fix: regex parser to support more answer formats

- llama_stack/providers/remote/inference/vllm/vllm.py
- tests/unit/providers/inference/test_remote_vllm.py
This gracefully handles the case where the vLLM server responded to a completion request with no choices, which can happen in certain vLLM error situations. Previously, we'd error out with a stack trace about a list index out of range. Now, we just log a warning to the user and move past any chunks with an empty choices list.
A specific example of the type of stack trace this fixes:
```
File "/app/llama-stack-source/llama_stack/providers/remote/inference/vllm/vllm.py", line 170, in _process_vllm_chat_completion_stream_response
choice = chunk.choices[0]
~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Now, instead of erroring out with that stack trace, we log a warning that vLLM failed to generate any completions and alert the user to check the vLLM server logs for details.
This is …
> fix: Gracefully handle no choices in remote vLLM response

- tests/integration/test_cases/inference/chat_completion.json
When running `tests/integration/inference/test_text_inference.py` on smaller models, such as Llama-3.2-3B-Instruct, I sometimes get test flakes where the model passes "San Francisco" as an argument to my tool call instead of "San Francisco, CA" which is what we expect.
So, this expands upon that tool calling parameter's description to explicitly state that both city and state are required. With this change, the tool calling tests that are checking for this "San Francisco, CA" value are always passing for me instead of sometimes failing.
I test this locally via vLLM like:
```
VLLM_URL="http://localhost:8000/v1" \
INFERENCE_MODEL="meta-llama/Llama-3.2-3B-Instruct" \
LLAMA_STACK_CONFIG=remote-vllm \
python -m pytest -v \
tests/integration/inference/test_text_inference.py \
--inference-model …
```
> chore: Reduce flakes in test_text_inference on smaller models

- llama_stack/distribution/routers/routers.py
Some imports were not switched to in-tree copy of the modules.
This is a follow-up to:
https://github.com/meta-llama/llama-stack/pull/1344
Closes #1435
Manually started the server...
> fix: don't import from llama_models

- llama_stack/cli/model/describe.py
- llama_stack/distribution/configure.py
The method "dict" in class "BaseModel" is deprecated we should use model_dump instead.
> fix: resolve pydantic warning on .dict() usage

- docs/source/concepts/index.md
- add eval concept doc in Core Concept tab
cc @SLR722 
> docs: add back eval concept doc

- llama_stack/providers/utils/memory/vector_store.py
Fix import errors due to `chardet` and `pypdf` not being installed while imported from `url_utils.py`.
Closes #1432
Now able to run the server with the config.
> fix(deps): move chardet and pypdf imports inline where used

- tests/integration/agents/test_agents.py
- tests/integration/fixtures/recorded_responses/chat_completion.json
- tests/integration/fixtures/recorded_responses/invoke_tool.json
- re-gen to fix agents test
- update test_custom_tool
```
LLAMA_STACK_CONFIG=fireworks pytest -v tests/integration/agents/test_agents.py --text-model meta-llama/Llama-3.3-70B-Instruct
```
> fix: fix agent test recorded responses

- pyproject.toml
- uv.lock
This addresses the new vulnerability https://github.com/advisories/GHSA-cpwx-vrp4-4pq7.
> fix(security): Bump jinja2 to >=3.1.6

- .gitignore
Ignores `pytest-report.xml`. The file is produced by the unit tests github workflow.
Not needed.
> chore: add pytest-report.xml to gitignore

- docs/source/distributions/building_distro.md
- llama_stack/cli/stack/build.py
- llama_stack/cli/stack/run.py
using `formatter_class=argparse.ArgumentDefaultsHelpFormatter` displays (default: DEFAULT_VALUE) for each flag. add this formatter class to build and run to show users some default values like `conda`, `8321`, etc
ran locally with following output: 
before: 
```
llama stack run --help
usage: llama stack run [-h] [--port PORT] [--image-name IMAGE_NAME] [--disable-ipv6] [--env KEY=VALUE] [--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE]
[--image-type {conda,container,venv}]
config
Start the server for a Llama Stack Distribution. You should have already built (or downloaded) and configured the distribution.
positional arguments:
config                Path to config file to use for the run
options:
--port PORT           Port to run …
```
> refactor: display defaults in help text

- tests/integration/__init__.py
- tests/integration/agents/__init__.py
- tests/integration/inference/__init__.py
- tests/integration/safety/__init__.py
- tests/integration/vector_io/__init__.py
Since we moved the move tests/client-sdk to tests/api in https://github.com/meta-llama/llama-stack/pull/1376. The N999 rule is not needed anymore. And furthermore in
https://github.com/meta-llama/llama-stack/commit/abfbaf3c1baa067a7b5feb0866ac8ab565119a3c
> fix: remove ruff N999

- .github/dependabot.yml
Add a Dependabot configuration file (.github/dependabot.yml) to enable automated dependency updates for GitHub Actions. This ensures workflows stay up to date with the latest versions, improving security and reliability.
Dependabot is configured to:
- Monitor GitHub Actions dependencies.
- Check for updates in the workflow directory
- Run updates on a daily schedule.
> ci: enable Dependabot for GitHub Actions

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Summary:
error:
llama_stack/providers/inline/agents/meta_reference/agent_instance.py:1032: in execute_tool_call_maybe
logger.info(f"tool call {name} completed with result: {result}")
/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/logging/__init__.py:1841: in info
self.log(INFO, msg, *args, **kwargs)
/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/logging/__init__.py:1879: in log
self.logger.log(level, msg, *args, **kwargs)
/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/logging/__init__.py:1547: in log
self._log(level, msg, args, **kwargs)
/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/logging/__init__.py:1624: in _log
self.handle(record)
/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/logging/__init__.py:163 …
> chore: escape tool output for logging

- llama_stack/providers/inline/inference/vllm/config.py
- llama_stack/providers/inline/inference/vllm/openai_utils.py
- llama_stack/providers/inline/inference/vllm/vllm.py
- llama_stack/templates/vllm-gpu/run.yaml
This PR updates the inline vLLM inference provider in several significant ways:
* Models are now attached at run time to instances of the provider via the `.../models` API instead of hard-coding the model's full name into the provider's YAML configuration. 
* The provider supports models that are not Meta Llama models. Any model that vLLM supports can be loaded by passing Huggingface coordinates in the "provider_model_id" field. Custom fine-tuned versions of Meta Llama models can be loaded by specifying a path on local disk in the "provider_model_id".
* To implement full chat completions support, including tool calling and constrained decoding, the provider now routes the `chat_completions` API to a captive (i.e. called directly in-process, not via HTTPS) instance of vLLM's …
> feat: updated inline vllm inference provider

- tests/integration/fixtures/recordable_mock.py
Summary:
CI writes files to /tmp
[{"__module__": "llama_stack.apis.inference.inference", "__pydantic__": "SystemMessage", "data": {"content": "You are a helpful assistant", "role": "system"}}, {"__module__": "llama_stack.apis.inference.inference", "__pydantic__": "UserMessage", "data": {"content": "Here is a csv file, can you describe it?", "context": null, "role": "user"}}, {"__module__": "llama_stack.apis.inference.inference", "__pydantic__": "ToolResponseMessage", "data": {"call_id": "", "content": [{"text": "# User provided a file accessible to you at \\"/tmp/tmp7k7dg6qk/gcDtT5M8inflation.csv\\"\\nYou can use code_interpreter to load and inspect it.", "type": "text"}], "role": "tool", "tool_name": {"__enum__": "BuiltinTool", "__module__": "llama_stack.models.llama.datatypes", "value": …
> test: fix recordable mocks cache key

- docs/source/concepts/evaluation_concepts.md
- docs/source/references/evals_reference/index.md
- llama_stack/templates/open-benchmark/run.yaml
add proper links to the doc
preview the doc
> fix: update the open benchmark eval doc

- llama_stack/log.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Summary:
|   File "/Users/erichuang/projects/llama-stack/llama_stack/distribution/server/server.py", line 213, in sse_generator
|     logger.exception(f"Error in sse_generator: {e}")
|   File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/logging/__init__.py", line 1864, in exception
|     self.log(ERROR, msg, *args, exc_info=exc_info, **kwargs)
|   File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/logging/__init__.py", line 1879, in log
|     self.logger.log(level, msg, *args, **kwargs)
|   File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/logging/__init__.py", line 1547, in log
|     self._log(level, msg, args, **kwargs)
|   File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.10/logging/__init__.py", line 1624, in …
> fix: handle log errors

- docs/getting_started.ipynb
- Together's inference only supports 3.1 for structured decoding
```
pytest -v -s --nbval-lax ./docs/getting_started.ipynb
```
> fix: update getting_started structured decoding cell

- llama_stack/cli/stack/_build.py
- llama_stack/distribution/build.py
- llama_stack/distribution/utils/exec.py
- llama_stack/distribution/utils/image_types.py
This disambiguates "Image" term from "container image" alternative usage and allows for:
```python
if image_type == LlamaStackImagetype.venv:
...
```
accesses rather than `ImageType.venv.value`
Changes enum use to comply with semantic python styling and naming conventions.
Refactor was automated and small so simple run-through of creating images was done.
> refactor: `ImageType` to `LlamaStackImageType`

- pyproject.toml
- requirements.txt
- uv.lock
We removed `llama-models` as a dep which was pulling this in for us previously. This did not get caught in the release process because the distros we use for testing (fireworks / together) pull that in via sentence transformers which we don't use in all distros (notably ollama.)
See #1511 
Ran `llama-stack-ops/actions/test-and-cut/main.sh` with `ONLY_TEST_DONT_CUT=1 COMMIT_ID=origin/fix_jinja2` and by making it build the ollama docker. Ran the docker to ensure it does not error out with jinja2 dependency error. (Unfortunately there is another error with sqlite_vec there.)
> fix: include jinja2 as a core llama-stack dependency

- tests/unit/models/test_prompt_adapter.py
The test class by default enables debug mode, which produces some
unexpected warnings like:
```
tests/unit/models/test_prompt_adapter.py::PrepareMessagesTests::test_completion_message_encoding
WARNING  2025-03-10 20:41:48,577 asyncio:1904 uncategorized: Executing <Task pending name='Task-1'
coro=<IsolatedAsyncioTestCase._asyncioLoopRunner() running at
/home/ec2-user/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/unittest/async_case.py:95
> wait_for=<Future pending cb=[Task.task_wakeup()] created at
/home/ec2-user/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/base_events.py:42
9> created at
/home/ec2-user/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/unittest/async_case.py:11
7> took 0.231 seconds
PASSED
``` …
> fix: Disable async loop warning messages during test run

- llama_stack/log.py
currently the `"Environment variable LLAMA_STACK_LOGGING found"` message is printed with no color switch to cprint and highlight in yellow for visibility
> chore: add color to Env Variable message
