llamastack/llama-stack

tests/integration/inspect/__init__.py, tests/integration/inspect/test_inspect.py
Add unit tests for the inspect endpoint.
$ ollama run llama3.2:3b-instruct-fp16 --keepalive=60m &
$ LLAMA_STACK_CONFIG=./llama_stack/templates/ollama/run.yaml uv run pytest -v -s tests/integration/inspect/test_inspect.py
/Users/leseb/Documents/AI/llama-stack/.venv/lib/python3.10/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected …
=> test: add inspect unit test

.github/workflows/unit-tests.yml, pyproject.toml, uv.lock
The `test` section has been updated to include only the essential
dependencies needed for running integration tests, which are shared
across all providers. If a provider requires additional dependencies,
please add them to your environment separately. When using uv to
run your tests, you can specify extra dependencies with the
`--with` flag.
=> build: revamp "test" dependencies from pyproject

llama_stack/cli/stack/run.py, llama_stack/distribution/server/server.py
Users prefer to rely on the main CLI rather than invoking the server through a Python module. Users interact with a high-level CLI rather than needing to know internal module structures.
Now, when running llama stack run <path-to-config>, the server will attempt to use the system package or a virtual environment if one is active.
This also eliminates the current process dependency chain when running from a virtual environment:
-> llama stack run
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -> start_env.sh
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -> python -m server...
Run:
```
ollama run llama3.2:3b-instruct-fp16 …
```
=> feat(server): Use system packages for execution

distributions/dependencies.json, docs/source/distributions/self_hosted_distro/ollama.md, llama_stack/providers/registry/vector_io.py, llama_stack/templates/ollama/build.yaml, llama_stack/templates/ollama/ollama.py, llama_stack/templates/ollama/run-with-safety.yaml, llama_stack/templates/ollama/run.yaml
This is unfortunate because `sqlite-vec` seems promising. But its PIP package is not quite complete. It does not have binary for arm64 (I think, or maybe it even lacks 64 bit builds?) which results in the arm64 container resulting in 
```
File "/usr/local/lib/python3.10/site-packages/sqlite_vec/init.py", line 17, in load
conn.load_extension(loadable_path())
sqlite3.OperationalError: /usr/local/lib/python3.10/site-packages/sqlite_vec/vec0.so: wrong ELF class: ELFCLASS32
```
To get around I tried to install from source via `uv pip install sqlite-vec --no-binary=sqlite-vec` however it even lacks a source distribution which makes that impossible. 
Build the container locally using: 
```bash
LLAMA_STACK_DIR=. llama stack build --template ollama --image-type container
```
Run the container as: …
=> fix: revert to using faiss for ollama distro

.github/workflows/unit-tests.yml
I created a PR earlier today, but I realized the code coverage reporting isn't correct: #1512
Essentially, we need to use `--with-editable` to enable develop/editable mode through `uv`. Using editable mode will create a package.egg-link file, and that allows pytest to accurately capture code coverage.
Before, some files had "0%" or "100%" coverage, which isn't accurate:
More info on `--with-editable`: https://docs.astral.sh/uv/reference/cli/#uv-run--with-editable
Tested locally
Screenshot from CI:
=> fix: Use `--with-editable` to capture accurate code coverage reporting

llama_stack/providers/inline/agents/meta_reference/agent_instance.py, llama_stack/providers/inline/agents/meta_reference/safety.py, llama_stack/providers/utils/telemetry/tracing.py
This PR has two fixes needed for correct trace context propagation across asycnio boundary
Fix 1: Start using context vars to store the global trace context.
This is needed since we cannot use the same trace context across coroutines since the state is shared. each coroutine 
should have its own trace context so that each of it can start storing its state correctly.
Fix 2: Start a new span for each new coroutines started for running shields to keep the span tree clean
LLAMA_STACK_DISABLE_VERSION_CHECK=true llama stack run ~/.llama/distributions/together/together-run.yaml
LLAMA_STACK_CONFIG=http://localhost:8321 pytest -s --safety-shield meta-llama/Llama-Guard-3-8B --text-model meta-llama/Llama-3.1-8B-Instruct
server logs: https://gist.github.com/dineshyv/51ac5d9864ed031d0d89ce77352821fe …
=> fix: tracing fixes for trace context propogation across coroutines

llama_stack/cli/stack/run.py, llama_stack/distribution/server/server.py
Reverts meta-llama/llama-stack#1252
The above PR breaks the following invocation:
```bash
llama stack run ~/.llama/distributions/together/together-run.yaml
```
=> revert: feat(server): Use system packages for execution

llama_stack/providers/inline/post_training/torchtune/post_training.py
Added missing shutdown handler. (Currently empty.)
Without it, when server shuts down, it posts the following warning:
```
__main__:129 server: No shutdown method for TorchtunePostTrainingImpl
```
(The test plan assumes shutdown logic is fixed, see #1495)
Without the patch:
```
INFO:     Uvicorn running on http://['::', '0.0.0.0']:8321 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO     2025-03-10 20:56:43,961 __main__:140 server: Shutting down
INFO     2025-03-10 20:56:43,962 __main__:124 server: Shutting down DatasetsRoutingTable
INFO     2025-03-10 20:56:43,964 __main__:124 …
```
=> fix: Add missing shutdown handler for TorchtunePostTrainingImpl

CONTRIBUTING.md, docs/openapi_generator/README.md
Since #892, we also need to install ruamel. Instead of maintaining the list of script dependencies in multiple places, remove it and assume developers read CONTRIBUTING.md docs.
Just docs.
=> docs: Remove duplicate docs on api docs generator

llama_stack/providers/inline/agents/meta_reference/__init__.py, llama_stack/providers/inline/datasetio/localfs/__init__.py, llama_stack/providers/inline/eval/meta_reference/__init__.py, llama_stack/providers/inline/inference/meta_reference/__init__.py, llama_stack/providers/inline/inference/sentence_transformers/__init__.py, llama_stack/providers/inline/inference/vllm/__init__.py, llama_stack/providers/inline/post_training/torchtune/__init__.py, llama_stack/providers/inline/safety/code_scanner/__init__.py, llama_stack/providers/inline/safety/llama_guard/__init__.py, llama_stack/providers/inline/safety/prompt_guard/__init__.py, llama_stack/providers/inline/scoring/basic/__init__.py, llama_stack/providers/inline/scoring/braintrust/__init__.py, llama_stack/providers/inline/scoring/llm_as_judge/__init__.py, llama_stack/providers/inline/tool_runtime/code_interpreter/__init__.py, llama_stack/providers/inline/vector_io/chroma/__init__.py, llama_stack/providers/inline/vector_io/faiss/__init__.py, llama_stack/providers/inline/vector_io/milvus/__init__.py, llama_stack/providers/inline/vector_io/sqlite_vec/__init__.py
It's a dict that may contain different types, as per
resolver:instantiate_provider implementation. (AFAIU it also never
contains ProviderSpecs, but *instances* of provider implementations.)
mypy passing if enabled checks for these modules. (See #1543)
=> chore: fix typing hints for get_provider_impl deps arguments

llama_stack/distribution/server/server.py
If implementation raises CancelledError (e.g. when it runs its own async
loop for jobs), the main server shutdown handler gets confused and
doesn't attempt to shut down the main loop tasks.
While at it, also fixing the following failure when this happens:
```
UnboundLocalError: cannot access local variable 'loop' where it is not
associated with a value
```
Shutdown handlers were not running because lifespan logic was broken since ~Oct 2024. Fixed that too and enforcing `lifespan` now (making sure server will crash when it fails to interact with app through middleware).
Spotted while working on https://github.com/meta-llama/llama-stack/pull/1437
One way to trigger it without the PR above …
=> fix: Multiple fixes for server shutdown (fix lifespan handling; fix handling CancelledError when raised by provider; let uvicorn handle signals)

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/agents/agents.py
Add support for listing agents, describing an agent, and retrieving
session IDs for a given agent. This is only the API definition, the
implementations will come separately.
Closes: https://github.com/meta-llama/llama-stack/issues/1294
=> feat(api): list agents / sessions and get agent

docs/source/distributions/self_hosted_distro/fireworks.md, llama_stack/providers/remote/inference/fireworks/models.py, llama_stack/templates/ci-tests/run.yaml, llama_stack/templates/dev/run.yaml, llama_stack/templates/fireworks/run-with-safety.yaml, llama_stack/templates/fireworks/run.yaml
remove Llama-3.2-1B-Instruct for fireworks as its no longer appears to be hosted on website.
python distro_codegen.py
=> fix: remove Llama-3.2-1B-Instruct for fireworks

llama_stack/providers/inline/agents/meta_reference/agents.py
- recent merge https://github.com/meta-llama/llama-stack/pull/1410 introduce error
```
ValueError: Provider meta-reference (Api.agents) does not implement the following methods:
[('list_agent_sessions', 'not_actually_implemented'), ('list_agents', 'not_actually_implemented')]
```
```
llama stack run
```
```
LLAMA_STACK_CONFIG=fireworks pytest -v tests/integration/agents/test_agents.py --text-model meta-llama/Llama-3.3-70B-Instruct
```
https://github.com/meta-llama/llama-stack-ops/actions/runs/13795303869
=> fix: fix llama stack run with missing agent impl

distributions/remote-vllm/compose.yaml, llama_stack/providers/inline/datasetio/localfs/datasetio.py
Bug https://github.com/meta-llama/llama-stack/issues/1357
Fix a bug of a wrong file name in inline::localfs datasetio provider
=> fix: Fixed bad file name in inline::localfs

llama_stack/providers/utils/inference/openai_compat.py
Summary:
supports https://github.com/meta-llama/llama-stack-client-python/pull/193
Test Plan:
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/integration/agents/test_agents.py --safety-shield meta-llama/Llama-Guard-3-8B --text-model meta-llama/Llama-3.1-8B-Instruct
=> feat: convert typehints from client_tool to litellm format

.github/workflows/unit-tests.yml
python unit tests running via GitHub Actions were only running with python 3.10
the project supports all python versions greater than or equal to 3.10
this commit adds 3.11, 3.12, and 3.13 to the test matrix for better coverage and confidence for non-3.10 users
All tests pass locally with python 3.11, 3.12, and 3.13
=> ci: run unit tests on all supported python versions

llama_stack/distribution/server/server.py, llama_stack/log.py
uvicorn has a `log_level` arg in uvicorn.run, pass in the effective level set by the logger.
Additionally, third party libraries like httpx are using our logging format, but not honoring our log level.
This seems unintended, so loop through all items in the loggerDict and apply the same log level as what we have set.
before:
```
llama stack run --image-type venv ~/.llama/distributions/ollama/ollama-run.yaml
Environment variable LLAMA_STACK_LOGGING found: all=warn
Using virtual environment: /Users/charliedoern/projects/Documents/llama-stack/venv
+ python -m llama_stack.distribution.server.server --yaml-config /Users/charliedoern/.llama/distributions/ollama/ollama-run.yaml --port 8321
Environment variable LLAMA_STACK_LOGGING found: all=warn
WARNING  2025-03-10 16:05:49,706 root:71 …
```
=> fix: respect log_level in uvicorn and third party libs

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/agents/agents.py, llama_stack/providers/inline/agents/meta_reference/agent_instance.py, llama_stack/providers/inline/agents/meta_reference/agents.py
closes #1431 
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/integration/agents/test_agents.py --safety-shield meta-llama/Llama-Guard-3-8B --text-model meta-llama/Llama-3.1-8B-Instruct
=> chore: deprecate ToolResponseMessage in agent.resume API

.github/workflows/unit-tests.yml, README.md
This PR adds a simple unit test badge to the project README
It also modifies the workflow to run on merges to main, so that the status reflected in the README is that of main and not pull request branches
=> docs: add unit test badge to README 

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/telemetry/telemetry.py, llama_stack/distribution/routers/routers.py, llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
This change adds a compact type to include metrics in response as opposed to the full MetricEvent which is relevant for internal logging purposes.
```
LLAMA_STACK_CONFIG=~/.llama/distributions/fireworks/fireworks-run.yaml pytest -s -v agents/test_agents.py --safety-shield meta-llama/Llama-Guard-3-8B --text-model meta-llama/Llama-3.1-8B-Instruct
llama stack run ~/.llama/distributions/fireworks/fireworks-run.yaml
curl --request POST \
--url http://localhost:8321/v1/inference/chat-completion \
--header 'content-type: application/json' \
--data '{
"model_id": "meta-llama/Llama-3.1-70B-Instruct",
"messages": [
{
"content": {
"type": "text",
"text": "where do humans live"
}
}
],
"stream": false
}'
{
"metrics": [
{
"metric": "prompt_tokens",
"value": 10,
"unit": null
},
{ …
```
=> feat: Add new compact MetricInResponse type

.github/workflows/providers-build.yml
Introduced a new CI job that dynamically generates a build matrix based on available templates from `llama_stack/templates/*/build.yaml`.
This allows automated testing for all templates without manual intervention.
The CI currently builds for venv and containers.
~Will pass once https://github.com/meta-llama/llama-stack/pull/1228 merges.~
=> ci: add dynamic CI job to test templates

.github/workflows/stale_bot.yml
- Issues/PRs inactive for 60 days are marked as stale
- Stale items are closed after 30 additional days of inactivity
- Adds appropriate warning and closing messages
- Sets daily schedule for stale checks
=> ci: add GitHub Action to close stale issues and PRs

.pre-commit-config.yaml
Before the change, it was only doing it during the merge.
```
$ git checkout d263edbf90f958349c7b9adea8fd4e5181932a69
$ pre-commit run --all-files
check for merge conflicts................................................Failed
- hook id: check-merge-conflict
- exit code: 1
docs/_static/llama-stack-spec.yaml:3179: Merge conflict string '<<<<<<<' found
docs/_static/llama-stack-spec.yaml:3185: Merge conflict string '=======' found
docs/_static/llama-stack-spec.yaml:3190: Merge conflict string '>>>>>>>' found
[...]
```
=> chore: Always check that git merge conflict markers are not present

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/datatypes.py, llama_stack/apis/inspect/inspect.py, llama_stack/apis/providers/__init__.py, llama_stack/apis/providers/providers.py, llama_stack/distribution/configure.py, llama_stack/distribution/distribution.py, llama_stack/distribution/providers.py, llama_stack/distribution/resolver.py, llama_stack/distribution/server/server.py, llama_stack/distribution/stack.py, pyproject.toml, tests/integration/providers/__init__.py, tests/integration/providers/test_providers.py
currently the `inspect` API for providers is really a `list` API. Create a new `providers` API which has a GET `providers/{provider_id}` inspect API
which returns "user friendly" configuration to the end user. Also add a GET `/providers` endpoint which returns the list of providers as `inspect/providers` does today.
This API follows CRUD and is more intuitive/RESTful.
This work is part of the RFC at https://github.com/meta-llama/llama-stack/pull/1359
sensitive fields are redacted using `redact_sensetive_fields` on the server side before returning a response:
using https://github.com/meta-llama/llama-stack-client-python/pull/181 a user is able to to run the following:
`llama stack build --template ollama --image-type venv`
`llama stack run --image-type venv …
=> feat: add provider API for listing and inspecting provider info

docs/source/index.md
Forgot to update this page as well as part of https://github.com/meta-llama/llama-stack/pull/1617.
=> docs: Add OpenAI, Anthropic, Gemini to inference API providers table

llama_stack/cli/download.py, llama_stack/models/llama/llama3/prompt_templates/system_prompts.py, llama_stack/providers/inline/agents/meta_reference/agent_instance.py, llama_stack/providers/inline/agents/meta_reference/persistence.py, llama_stack/providers/inline/post_training/torchtune/post_training.py, llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py, llama_stack/providers/inline/telemetry/meta_reference/console_span_processor.py, llama_stack/providers/inline/telemetry/meta_reference/sqlite_span_processor.py, llama_stack/providers/inline/tool_runtime/code_interpreter/code_execution.py, llama_stack/providers/utils/telemetry/tracing.py, pyproject.toml
Updated all instances of datetime.now() to use timezone.utc for consistency in handling time across different systems. This ensures that timestamps are always in Coordinated Universal Time (UTC), avoiding issues with time zone discrepancies and promoting uniformity in time-related data.
=> refactor: move all datetime.now() calls to UTC

llama_stack/cli/model/prompt_format.py
Updates the help text for the `llama model prompt-format` command to clarify that users should provide a specific model name (e.g., Llama3.1-8B, Llama3.2-11B-Vision), not a model family. Removes the default value and field for `--model-name` to prevent users from mistakenly thinking a model family name is acceptable. Adds guidance to run `llama model list` to view valid model names.
Output of `llama model prompt-format -h` Before:
```
(venv) alina@fedora:~/dev/llama/llama-stack$ llama model prompt-format -h
usage: llama model prompt-format [-h] [-m MODEL_NAME]
Show llama model message formats
options:
-m MODEL_NAME, --model-name …
```
=> fix: Clarify `llama model prompt-format` help text

tests/integration/inference/test_vision_inference.py
quick fix as the vision_inference test dog.jpg path has been changed.
=> fix: change dog.jpg path in test_vision_inference.py

.github/workflows/unit-tests.yml, CONTRIBUTING.md, scripts/unit-tests.sh
Useful for local development. Now you can just trigger the script and
not care about specific arguments to pass to run unit tests.
```
$ . ./venv/bin/activate
$ ./scripts/run_tests.sh
$ echo $?
0
```
=> chore: Add ./scripts/unit-tests.sh

.pre-commit-config.yaml
It will fail if the newly generated spec docs are different.
```
$ pre-commit run --all-files
check for merge conflicts................................................Passed
trim trailing whitespace.................................................Passed
check for added large files..............................................Passed
fix end of files.........................................................Passed
Insert license in comments...............................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed …
```
=> chore: Add pre-commit check to sync api spec docs

llama_stack/distribution/datatypes.py, llama_stack/distribution/server/server.py, llama_stack/log.py
a user should be able to store a static logging configuration outside of their environment. This would make sense to store in the run yaml given that we store other things like server configuration in there.
The environment variable settings override the config settings if both are available.
The format in the config looks like this:
```
logging_config:
category_levels:
VALID_CATEGORY: VALID_STRING_LOG_LEVEL
```
any specified category out of the following:
`core | server | router | inference | agents | safety | eval | tools | client`
combined with any of the following log levels:
`debug | info | warning | error | critical`
can be placed in the category_levels list in order to achieve the desired log level
Test locally with a run config like the following:
```
version: '2'
image_name: …
```
=> feat: add support for logging config in the run.yaml

docs/source/getting_started/index.md
current docs are very tailored to `conda`
also adds guidance around running code examples within virtual environment for both `conda` and `virtualenv`
=> docs: add additional guidance around using `virtualenv`

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/datasetio/datasetio.py
- as title
- uses "cursor" pagination scheme for iterrows
=> feat(api): (1.2/n) datasets.iterrorws pagination api updates

llama_stack/distribution/routers/routers.py, llama_stack/distribution/routers/routing_tables.py, llama_stack/distribution/ui/page/evaluations/native_eval.py, llama_stack/providers/inline/datasetio/localfs/datasetio.py, llama_stack/providers/inline/eval/meta_reference/eval.py, llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py, llama_stack/providers/inline/scoring/basic/scoring.py, llama_stack/providers/inline/scoring/braintrust/braintrust.py, llama_stack/providers/inline/scoring/llm_as_judge/scoring.py, llama_stack/providers/remote/datasetio/huggingface/huggingface.py
- fix datasets api signature mis-match so that llama stack run can start
```
llama stack run
```
=> feat(dataset api): (1.4/n) fix resolver signature mismatch

llama_stack/distribution/build_container.sh
Update the container build script so that it is compatible with podman. The --progress=plain is now the default option and can be overriden.
N/A
=> fix: build distribution with podman

llama_stack/distribution/providers.py
Currently there is no shutdown method implemented for the `ProviderImpl` class
This leads to the following warning
```shell
INFO:     Waiting for application shutdown.
INFO     2025-03-17 17:25:13,280 __main__:145 server: Shutting down                                                     
INFO     2025-03-17 17:25:13,282 __main__:129 server: Shutting down ModelsRoutingTable                                  
INFO     2025-03-17 17:25:13,284 __main__:129 server: Shutting down DatasetsRoutingTable                                
INFO     2025-03-17 17:25:13,286 __main__:129 server: Shutting down DatasetIORouter                                     
INFO     2025-03-17 17:25:13,287 __main__:129 server: Shutting down TelemetryAdapter                                    
INFO     2025-03-17 …
```
=> fix: add shutdown method for ProviderImpl

.github/workflows/integration-tests.yml, .github/workflows/providers-build.yml, llama_stack/cli/stack/_build.py, llama_stack/cli/stack/run.py, llama_stack/distribution/build.py, llama_stack/distribution/utils/exec.py
A PTY is unnecessary for interactive mode since `subprocess.run()` already inherits the calling terminal’s stdin, stdout, and stderr, allowing natural interaction. Using a PTY can introduce unwanted side effects like buffering issues and inconsistent signal handling. Standard input/output is sufficient for most interactive programs.
This commit simplifies the command execution by:
1. Removing PTY-based execution in favor of direct subprocess handling
2. Consolidating command execution into a single run_command function
3. Improving error handling with specific subprocess error types
4. Adding proper type hints and documentation
5. Maintaining Ctrl+C handling for graceful interruption
```
llama stack run
```
=> refactor: simplify command execution and remove PTY handling

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
rather than have unit and functional tests run on all PRs, we should only have them run on PRs changing relevant files
=> ci: limit PR testing based on modified files

.github/dependabot.yml
This PR adds dependabot updates for Python dependencies. In addition:
* Consistent weekly schedule on a specific day
* Specific commit messages
* `open-pull-requests-limit` is intentional to avoid upgrading dependencies that will likely cause regressions. We want to keep the focus here on security updates only
=> ci: Add dependabot scans for Python deps

tests/unit/providers/inference/test_remote_vllm.py
This avoids flaky timeout issue observed in CI builds, e.g. https://github.com/meta-llama/llama-stack/actions/runs/13907179329/job/38912865968?pr=1273
Ran multiple times and pass consistently.
=> test: Bump slow_callback_duration to 200ms to avoid flaky remote vLLM unit tests

llama_stack/providers/inline/agents/meta_reference/agent_instance.py, llama_stack/providers/utils/inference/litellm_openai_mixin.py, llama_stack/providers/utils/inference/openai_compat.py, tests/integration/agents/test_agents.py
Includes fixes to get test_agents working with openAI model, e.g. tool parsing and message conversion
```
LLAMA_STACK_CONFIG=dev pytest -s -v tests/integration/agents/test_agents.py --safety-shield meta-llama/Llama-Guard-3-8B --text-model openai/gpt-4o-mini
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack/pull/1550).
* #1556
* __->__ #1550
=> fix: agents with non-llama model

llama_stack/providers/inline/agents/meta_reference/agent_instance.py, llama_stack/providers/inline/safety/llama_guard/llama_guard.py, llama_stack/providers/utils/inference/litellm_openai_mixin.py, llama_stack/providers/utils/inference/openai_compat.py, tests/integration/agents/test_agents.py
Summary:
closes #1488 
Test Plan:
added new integration test
```
LLAMA_STACK_CONFIG=dev pytest -s -v tests/integration/agents/test_agents.py --safety-shield meta-llama/Llama-Guard-3-8B --text-model openai/gpt-4o-mini
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack/pull/1556).
* __->__ #1556
* #1550
=> feat(agent): support multiple tool groups

README.md
The previous installation instructions were mostly duplicating information already covered in the documentation, either in the “Start a Server” or “Contributing Guide” sections. Removed these redundant details to avoid confusion and streamline the setup process.
=> docs: remove redundant installation instructions

llama_stack/providers/inline/inference/meta_reference/parallel_utils.py
we randomly get errors like the following, it's most likely due to accessing an object that is already deallocated
```
E0318 12:55:24.472000 1562188 site-packages/torch/distributed/elastic/multiprocessing/api.py:732] Traceback (most recent call last):
E0318 12:55:24.472000 1562188 site-packages/torch/distributed/elastic/multiprocessing/api.py:732]   File "/home/yyy/.conda/envs/myenv/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 90, in _wrap
E0318 12:55:24.472000 1562188 site-packages/torch/distributed/elastic/multiprocessing/api.py:732]     fn(i, *args)
E0318 12:55:24.472000 1562188 site-packages/torch/distributed/elastic/multiprocessing/api.py:732]   File "/home/yyy/.conda/envs/myenv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line …
```
=> fix: avoid tensor memory error

llama_stack/distribution/datatypes.py, llama_stack/distribution/server/auth.py, llama_stack/distribution/server/server.py, tests/unit/server/test_auth.py
This PR adds support (or is a proposal for) for supporting API KEY authentication on the Llama Stack server end. `llama-stack-client` already supports accepting an api_key parameter and passes it down through every request as an `Authentication: ` header. 
Currently, Llama Stack does not propose APIs for handling authentication or authorization for resources of any kind. Given that, and the fact that any deployment will typically have _some_ authentication system present, we simply adopt a delegation mechanism: delegate to an HTTPS endpoint performing key management / authentication.
It is configured via: 
```yaml
server: 
auth:
endpoint: <...>
```
in the run.yaml configuration.
When authentication is enabled:
1. Every API request must include an `Authorization: Bearer <token>` header
2. …
=> feat(auth, rfc): Add support for Bearer (api_key) Authentication

llama_stack/providers/inline/datasetio/localfs/datasetio.py, llama_stack/providers/utils/datasetio/url_utils.py
These block on io reads which in turn block the
server. Move them to their own thread.
Closes: #1697
To avoid blocking the main eventloop, updates datasetio/localfs to load data in a seperate thread
=> fix: Call pandas.read_* in a seperate thread

llama_stack/apis/datasets/datasets.py, llama_stack/distribution/routers/routing_tables.py, llama_stack/templates/open-benchmark/open_benchmark.py, llama_stack/templates/open-benchmark/run.yaml
open-benchmark templated is broken after the datasets api refactor due to 2 reasons
- provider_id and provider_resource_id are no longer needed 
- the type in run.yaml will be resolved as dict
this PR is to fix the above 2 issues 
spin up a llama stack server successfully with llama stack run `llama_stack/templates/open-benchmark/run.yaml`
=> fix: fix open-benchmark template

llama_stack/distribution/routers/routing_tables.py, tests/integration/tools/test_tools.py
FAILED tests/integration/tools/test_tools.py::test_toolsgroups_unregister[None] - AttributeError: 'coroutine' object has no attribute 'data'
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/integration/tools/test_tools.py
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack/pull/1704).
* #1705
* __->__ #1704
=> fix: toolgroups unregister

llama_stack/distribution/server/server.py
currently if you have a run yaml without temeletry the following error is hit:
TypeError: TelemetryAdapter.__init__() missing 1 required positional argument: 'deps'
this is because the TelemetryAdapter requires a deps arg to be passed. Pass {} to avoid errors.
=> fix: telemetry logger

llama_stack/apis/agents/agents.py, llama_stack/apis/common/content_types.py, llama_stack/apis/common/type_system.py, llama_stack/apis/datasets/datasets.py, llama_stack/apis/eval/eval.py, llama_stack/apis/inference/inference.py, llama_stack/apis/post_training/post_training.py, llama_stack/apis/scoring_functions/scoring_functions.py, llama_stack/apis/telemetry/telemetry.py, llama_stack/apis/tools/rag_tool.py, llama_stack/models/llama/datatypes.py
Don't set type variables from register_schema().
`mypy` is not happy about it since type variables are calculated at
runtime and hence the typing hints are not available during static
analysis.
Good news is there is no good reason to set the variables from the
return type.
=> chore: Don't set type variables from register_schema()

llama_stack/distribution/access_control.py, llama_stack/distribution/datatypes.py, llama_stack/distribution/request_headers.py, llama_stack/distribution/routers/routing_tables.py, llama_stack/distribution/server/auth.py, llama_stack/distribution/server/server.py, scripts/unit-tests.sh, tests/unit/registry/test_registry_acl.py, tests/unit/server/test_access_control.py, tests/unit/server/test_auth.py
This PR introduces a way to implement Attribute Based Access Control (ABAC) for the Llama Stack server.
The rough design is:
- https://github.com/meta-llama/llama-stack/pull/1626 added a way for the Llama Stack server to query an authenticator 
- We build upon that and expect "access attributes" as part of the response. These attributes indicate the scopes available for the request.
- We use these attributes to perform access control for registered resources as well as for constructing the default access control policies for newly created resources.
- By default, if you support authentication but don't return access attributes, we will add a unique namespace pointing to the API_KEY. That way, all resources by default will be scoped to API_KEYs.
An important aspect of this design is that …
=> feat(server): add attribute based access control for resources

llama_stack/models/llama/llama3/prompt_templates/system_prompts.py, tests/unit/models/test_system_prompts.py
closes #1584 
This should be a rather innocuous change. 
Verify that there's no more tool call parsing error for example in issue
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/integration/agents/test_agents.py --safety-shield meta-llama/Llama-Guard-3-8B --text-model meta-llama/Llama-3.1-8B-Instruct
=> fix: update default tool call system prompt

llama_stack/strong_typing/schema.py
Since Python 3.10, unions can be expressed as `type1 | type2`. Sadly,
while this is functionally equivalent to `Union[type1, type2]`, the type
of the expression is different (`types.UnionType`, not `typing.Union`).
We should handle both in schemas.
Switch a schema type from Union to `|` and confirm the generator doesn't crash with:
```
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/ihrachys/src/llama-stack/docs/openapi_generator/generate.py", line 91, in <module>
fire.Fire(main)
File "/Users/ihrachys/.cache/uv/archive-v0/FBgkcwcN-PaJ0NAur__7J/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
component_trace = _Fire(component, args, parsed_flag_args, context, name) …
```
=> fix: Support types.UnionType in schemas

.pre-commit-config.yaml
If the generator fails, pre-commit logs will now show how it failed.
Note: stdout is still suppressed, so that regular informational messages
do not pollute pre-commit output when all the hook does is update
generated files.
Inject a failure in the generator code and confirm it's seen in the output.
```
$ git diff
diff --git a/docs/openapi_generator/pyopenapi/utility.py b/docs/openapi_generator/pyopenapi/utility.py
index f60a33bb..482e26ef 100644
--- a/docs/openapi_generator/pyopenapi/utility.py
+++ b/docs/openapi_generator/pyopenapi/utility.py
@@ -127,6 +127,7 @@ def is_optional_type(type_: Any) -> bool:
def validate_api_method_return_types() -> List[str]:
"""Validate that all API …
```
=> chore: Don't hide stderr from api generator

docs/source/distributions/self_hosted_distro/remote-vllm.md, llama_stack/templates/remote-vllm/doc_template.md
This PR adds a link to tool calling instructions in vLLM. Users have asked about this many times, e.g. https://github.com/meta-llama/llama-stack/issues/1648#issuecomment-2740642077
=> docs: Add instruction on enabling tool calling for remote vLLM

llama_stack/providers/inline/telemetry/meta_reference/config.py, llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
Since we now start recording and exporting metrics, we no longer can use single OTEL endpoint to export both traces and metrics. This PR adds two sinks: OTEL_TRACE  and OTEL_METRIC to be able to selectively enable the exporters.
Start server with OTEL_TRACE as sink and verify traces show up in jaeger
=> feat: add different sinks for otel traces and metrics

.github/workflows/integration-tests.yml, .github/workflows/pre-commit.yml, .github/workflows/providers-build.yml, .github/workflows/semantic-pr.yml, .github/workflows/unit-tests.yml, .github/workflows/update-readthedocs.yml
When multiple commits are pushed to a PR, multiple CI builds will be triggered. This PR ensures that we only run one concurrent build for each PR to reduce CI loads.
=> ci: Enforce concurrency to reduce CI loads

llama_stack/templates/experimental-post-training/run.yaml
fix the template to make it compatible with the latest dataset and eval api change
run  `llama stack run llama_stack/templates/experimental-post-training/run.yaml` and spin up the llama stack server successfully
=> fix: fix experimental-post-training template

.pre-commit-config.yaml
=> fix: only invoke openapi generator if APIs or API generator changes

llama_stack/templates/remote-vllm/run-with-safety.yaml, llama_stack/templates/remote-vllm/run.yaml, llama_stack/templates/remote-vllm/vllm.py
This is to avoid errors like the following when running inference integration tests:
```
ERROR tests/integration/inference/test_text_inference.py::test_text_completion_stop_sequence[txt=8B-inference:completion:stop_sequence] - llama_stack.distribution.stack.EnvVarError: Environment variable 'VLLM_URL' not set or empty at providers.inference[0].config.url
```
It's also good to have a default, which is consistent with vLLM API server.
Integration tests can run without the error above.
=> test: Add default vLLM URL in remote-vllm template

llama_stack/providers/registry/safety.py
Required to startup a distribution with prompt guard
Closes: #1723
distribution starts with patch applied
=> fix: Add 'accelerate' dependency to 'prompt-guard'

docs/source/concepts/evaluation_concepts.md
Typo fix for `output_dir` flag and misspelling of aggregate 
N/A
=> docs: fix typos in evaluation concepts

llama_stack/schema_utils.py
Gets rid of errors like the below, which is on all webmethod decorated functions
llama_stack/apis/agents/agents.py:398: error: Value of type variable "T" of function cannot be "Callable[[Agents, AgentConfig], Coroutine[Any, Any, AgentCreateResponse]]"  [type-var]
Run mypy and observes mypy errors gone
=> chore: make mypy happy with webmethod

llama_stack/providers/inline/vector_io/sqlite_vec/sqlite_vec.py, tests/unit/providers/vector_io/test_sqlite_vec.py
This PR updates the sqlite-vec database calls to be non-blocking. Note that each operation creates a new connection, which incurs some performance overhead but is reasonable given [SQLite's threading and connections constraints](https://www.sqlite.org/threadsafe.html). 
Summary of changes:
- Refactored `SQLiteVecIndex` class to store database path instead of connection object
- Added `_create_sqlite_connection()` helper function to create connections on demand
- Ensured proper connection closure in all database operations
- Fixed test fixtures to use a file-based SQLite database for thread-safety
- Updated the `SQLiteVecVectorIOAdapter` class to handle per-operation connections
This PR helps chip away at https://github.com/meta-llama/llama-stack/issues/1489
sqlite-vec unit tests passed …
=> chore: Updating sqlite-vec to make non-blocking calls

pyproject.toml
Enable mypy pydantic plugin.
Since the project heavily relies on pydantic models, it's probably wise
to enable the plugin to avoid some potential spurious violation warnings
the further we expand mypy coverage for the code base.
It should be generally risk-free to enable the plugin for the repo.
Some info on what plugin brings to the table:
https://docs.pydantic.dev/latest/integrations/mypy/#mypy-plugin-capabilities
=> chore: enable mypy pydantic plugin

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, docs/openapi_generator/generate.py, docs/openapi_generator/pyopenapi/utility.py, llama_stack/apis/datatypes.py, llama_stack/apis/files/files.py, llama_stack/distribution/resolver.py, llama_stack/providers/registry/files.py, tests/unit/providers/test_configs.py
This is to stay consistent with other APIs.
This change registers files in API, even though there are still no
providers. Removing tests that require a provider existing for a merged
API to enable it in API layer.
=> feat(api): don't return a payload on file delete

CONTRIBUTING.md
Added more hint on `LLAMA_STACK_CONFIG` and API keys necessary for agent tests.
=> docs: Add more env vars in dotenv instructions

pyproject.toml, tests/unit/providers/nvidia/conftest.py, tests/unit/providers/nvidia/test_parameters.py, tests/unit/providers/nvidia/test_supervised_fine_tuning.py
Re-enable isort enforcement.
It was disabled in 1a73f8305b513b0880c7903d3458b4f89e45f3e3, probably by
mistake.
=> chore: re-enable isort enforcement

tests/integration/agents/test_agents.py
- we no longer query vector db when uploading documents as attachments
```
pytest --stack-config="http://localhost:8321" -v tests/integration/agents/test_agents.py --text-model meta-llama/Llama-3.3-70B-Instruct
```
```
pytest --stack-config=fireworks -v tests/integration/agents/test_agents.py --text-model meta-llama/Llama-3.3-70B-Instruct --record-responses
```
=> fix: update agents test

docs/openapi_generator/pyopenapi/utility.py
No violators are currently in-tree. This is just hardening the api specs
for future consistency.
=> chore: require `data` field for all List*Response models

docs/source/distributions/building_distro.md, llama_stack/cli/stack/_build.py, llama_stack/cli/stack/build.py, llama_stack/cli/stack/run.py, llama_stack/cli/stack/utils.py, llama_stack/distribution/server/server.py
This is the second attempt to switch to system packages by default. Now with a hack to detect conda environment - in which case conda image-type is used.
Note: Conda will only be used when --image-name is unset *and*
CONDA_DEFAULT_ENV is set. This means that users without conda will
correctly fall back to using system packages when no --image-* arguments
are passed at all.
Uses virtualenv:
```
$ llama stack build --template ollama --image-type venv
$ llama stack run --image-type venv ~/.llama/distributions/ollama/ollama-run.yaml
[...]
Using virtual environment: /home/ec2-user/src/llama-stack/schedule/.local
[...]
```
Uses system packages (virtualenv already initialized):
```
$ llama stack …
```
=> fix: Use CONDA_DEFAULT_ENV presence as a flag to use conda mode

llama_stack/distribution/ui/page/playground/rag.py
Adding chunk_size_in_tokens to playground rag_tool insert.
Tested locally.
=> fix: Adding chunk_size_in_tokens to playground rag_tool insert

llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
closes #1725 
In https://github.com/meta-llama/llama-stack/pull/1759's attempt to make trace_id consistent in llama stack and otel exports, it incorrectly sets the span_id in context, which causes the root span to have a parent ID, leading to the issue in #1725. 
This PR reverts #1759's change to set the parent context. We will need to follow up with a proper way to do this.
=> fix(telemetry): root span not yet received

llama_stack/providers/inline/telemetry/meta_reference/telemetry.py, tests/integration/telemetry/test_telemetry.py
https://github.com/meta-llama/llama-stack/pull/1828 removed __root_span__ attribute which is still needed
added telemetry integration test
LLAMA_STACK_CONFIG=http://localhost:5001 pytest -s -v tests/integration/telemetry --safety-shield meta-llama/Llama-Guard-3-8B --text-model accounts/fireworks/models/llama-v3p3-70b-instruct
=> fix(telemetry): query_spans

llama_stack/cli/stack/_build.py
closes #1834 
`llama stack build` successfully
=> fix: skip apis with no providers during `llama stack build`

docs/source/building_applications/telemetry.md
This PR updates the sink name configuration for traces and metrics in LlamaStack to align with the latest changes introduced in version 0.1.8. Previously, when using the `otel` sink along with other sinks (like `console` and `sqlite`), the system threw a **ValueError**, with the message:
```shell
Value error, 'otel' is not a valid TelemetrySink [type=value_error, input_value='console,otel,sqlite', input_type=str]
For further information visit https://errors.pydantic.dev/2.10/v/value_error
``` 
- **Test 1:**  
Ran the LlamaStack server with a configuration containing `console,otel,sqlite` as sinks.
- **Expected result:** No errors related to invalid sink names.
- **Result:** The system ran without throwing a `ValueError`.
- **Test 2:**  
Verified that the `otel_trace`, `otel_metric`  sink …
=> fix: update sink name for traces and metrics in LlamaStack 0.1.8

llama_stack/distribution/library_client.py, tests/integration/telemetry/test_telemetry.py
LLAMA_STACK_CONFIG=dev pytest -s -v tests/integration/telemetry --safety-shield meta-llama/Llama-Guard-3-8B --text-model accounts/fireworks/models/llama-v3p3-70b-instruct
=> fix(telemetry): library client does not log span

llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- `context` field in UserMessage is being deprecated, we append RAG context in content
1. Check message sent to remote provider: 
2. Test RAG_Lifecycle notebook with content as `str`
3. Test RAG_Lifecycle notebook with content as `list`
=> chore: change context to content for agent

CONTRIBUTING.md, tests/integration/README.md
* Added `--text-model` in example command.
* Added link to integration tests instruction and a note on specifying models.
This is to avoid confusion when all tests are skipped because no model is provided.
=> docs: Add link to integration tests instructions and minor clarification

docs/source/conf.py, pyproject.toml, requirements.txt, uv.lock
docs: Adding darkmode to documentation
Tested locally. 
Here's the look:
Related to https://github.com/meta-llama/llama-stack/issues/1815 
Closes https://github.com/meta-llama/llama-stack/issues/1844
=> docs: Adding darkmode to documentation

docs/source/building_applications/index.md, docs/source/conf.py, docs/source/distributions/configuration.md, docs/source/distributions/importing_as_library.md, docs/source/distributions/index.md, docs/source/distributions/kubernetes_deployment.md, docs/source/distributions/list_of_distributions.md, docs/source/distributions/starting_llama_stack_server.md, docs/source/getting_started/index.md, docs/source/index.md
The goal of this PR is to make the pages easier to navigate by surfacing the child pages on the navbar, updating some of the copy, moving some of the files around. 
Some changes:
1. Clarifying Titles
2. Restructuring "Distributions" more formally in its own page to be consistent with Providers and adding some clarity to the child pages to surface them and make them easier to navigate
3. Updated sphinx config to not collapse navigation by default
4. Updated copyright year to be calculated dynamically 
5. Moved `docs/source/distributions/index.md` -> `docs/source/distributions/starting_llama_stack_server.md`
Another for https://github.com/meta-llama/llama-stack/issues/1815
Tested locally and pages build (screen shots for example).
=> docs: Updated documentation and Sphinx configuration

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/common/responses.py, llama_stack/apis/datasetio/datasetio.py, llama_stack/distribution/routers/routers.py, llama_stack/providers/inline/datasetio/localfs/datasetio.py, llama_stack/providers/remote/datasetio/huggingface/huggingface.py, llama_stack/providers/utils/datasetio/pagination.py, uv.lock
Move pagination logic from LocalFS and HuggingFace implementations into a common helper function to ensure consistent pagination behavior across providers. This reduces code duplication and centralizes pagination logic in one place.
Run this script:
```
client = LlamaStackClient(base_url="http://localhost:8321")
response = client.datasets.register(
purpose="eval/messages-answer",  # or "eval/question-answer" or "post-training/messages"
source={"type": "uri", "uri": "huggingface://datasets/llamastack/simpleqa?split=train"},
dataset_id="my_dataset",  # optional, will be auto-generated if not provided
metadata={"description": "My evaluation dataset"},  # optional
)
datasets = client.datasets.list()
print(f"Registered datasets: {[d.identifier …
```
=> refactor: extract pagination logic into shared helper function

.github/workflows/integration-tests.yml, tests/integration/inference/test_text_inference.py
Previously, the integration tests started the server, but never really used it because `--stack-config=ollama` uses the ollama template and the inline "llama stack as library" client, not the HTTP client.
This PR makes sure we test it both ways.
We also add agents tests to the mix.
GitHub
=> test: make sure integration tests runs against the server

llama_stack/providers/remote/inference/nvidia/nvidia.py
Closes #1819 
```bash
pytest -v tests/integration/inference/test_embedding.py  --stack-config=http://localhost:5002 --embedding-model=nvidia/llama-3.2-nv-embedqa-1b-v2
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.10.0, pytest-8.3.5, pluggy-1.5.0 -- /home/ubuntu/miniconda/envs/nvidia-1/bin/python
rootdir: /home/ubuntu/llama-stack
plugins: anyio-4.9.0
collected 23 items …
```
=> fix: NVIDIA embedding results in InternalServerError

docs/source/building_applications/rag.md, docs/source/contributing/index.md
Another for https://github.com/meta-llama/llama-stack/issues/1815
This links the `CONTRIBUTING.md` file directly so that we don't have to maintain two different files.
Also I updated the title for RAG under Building AI Applications.
Look of what the Contributing page looks like, proof it sources directly from the markdown file.
=> docs: Updating docs to source from CONTRIBUTING.md

docs/source/building_applications/agent.md, docs/source/building_applications/agent_execution_loop.md, docs/source/building_applications/index.md, docs/source/building_applications/rag.md
This PR modifies some of the docs to help them map to (1) the mental model of software engineers building AI models starting with RAG and then moving to Agents and (2) aligning the navbar somewhat closer to the diagram on the home page. 
N/A Tested locally.
Take a look at the screen shot for below and after.
=> docs: Minor updates to docs to make them a little friendlier to new users

llama_stack/models/llama/llama3/prompt_templates/system_prompts.py, llama_stack/models/llama/llama4/chat_format.py, llama_stack/providers/inline/inference/meta_reference/inference.py, tests/integration/inference/test_text_inference.py, tests/integration/test_cases/inference/chat_completion.json
Running full Tool Calling required some updates to work e2e.
- Remove `python_start` and `python_end` tags 
- Tool Call messages and Tool Resposne messages should end with `<|eom|>`
- System prompt needed updates 
```
You are a helpful assisant who can can answer general questions or invoke tools when necessary.
In addition to tool calls, you should also augment your responses by using the tool outputs.
```
- Start server with meta-reference 
```
LLAMA_STACK_DISABLE_VERSION_CHECK=1 LLAMA_MODELS_DEBUG=1 INFERENCE_MODEL=meta-llama/$MODEL  llama stack run meta-reference-gpu 
``` 
- Added **NEW** tests with 5 test cases for multi-turn tool calls 
```
pytest -s -v --stack-config http://localhost:8321 tests/integration/inference/test_text_inference.py --text-model …
```
=> feat: make multi-turn tool call tests work with llama4

docs/source/distributions/importing_as_library.md
LlamaStackAsLibraryClient.initialize is not async, cannot be await'd
=> docs: update importing_as_library.md

README.md
Update "chat" badge on README to make it more visible for visitors; changing the look from
... to ...
=> docs: colorize Discord badge & add icon in README

llama_stack/providers/inline/agents/meta_reference/agent_instance.py, llama_stack/providers/inline/agents/meta_reference/agents.py
The usage of the tempdir was removed in
094eb6a5ae8dbac297fe59914db11c612250f92f.
=> chore: remove unused tempdir in agent

.github/workflows/test-external-providers.yml, docs/source/providers/external.md, docs/source/providers/index.md, llama_stack/distribution/datatypes.py, llama_stack/distribution/distribution.py, llama_stack/distribution/resolver.py, llama_stack/distribution/stack.py, tests/external-provider/llama-stack-provider-ollama/README.md, tests/external-provider/llama-stack-provider-ollama/custom_ollama.yaml, tests/external-provider/llama-stack-provider-ollama/pyproject.toml, tests/external-provider/llama-stack-provider-ollama/run.yaml, tests/unit/distribution/test_distribution.py
Providers that live outside of the llama-stack codebase are now
supported.
A new property `external_providers_dir` has been added to the main
config and can be configured as follow:
```
external_providers_dir: /etc/llama-stack/providers.d/
```
Where the expected structure is:
```
providers.d/
inference/
custom_ollama.yaml
vllm.yaml
vector_io/
qdrant.yaml
```
Where `custom_ollama.yaml` is:
```
adapter:
adapter_type: custom_ollama
pip_packages: ["ollama", "aiohttp"]
config_class: llama_stack_ollama_provider.config.OllamaImplConfig
module: llama_stack_ollama_provider
api_dependencies: []
optional_api_dependencies: []
```
Obviously the package must be installed on the system, here is the
`llama_stack_ollama_provider` example:
```
$ uv pip show llama-stack-ollama-provider
Using Python 3.10.16 …
```
=> feat: ability to execute external providers

llama_stack/providers/remote/inference/ollama/ollama.py
closes #1853 
```
uv run llama stack build --image-type conda --image-name ollama --config llama_stack/templates/ollama/build.yaml
ollama pull llama3.2:3b
LLAMA_STACK_CONFIG=http://localhost:8321 uv run pytest tests/integration/inference/test_text_inference.py -v --text-model=llama3.2:3b
```
=> fix: use ollama list to find models

llama_stack/distribution/ui/app.py, llama_stack/distribution/ui/page/playground/tools.py
This PR adds an additional page to the playground called "Tools". This page connects to a llama-stack server and lists all the available LLM models, builtin tools and MCP tools in the sidebar. Users can select whatever combination of model and tools they want from the sidebar for their agent. Once the selections are made, users can chat with their agent similarly to the RAG page and test out agent tool use.   
closes #1902 
Ran the following commands with a llama-stack server and the updated playground worked as expected. 
```
export LLAMA_STACK_ENDPOINT="http://localhost:8321"     
streamlit run  llama_stack/distribution/ui/app.py
```
=> feat: Add tools page to playground

llama_stack/distribution/ui/modules/api.py
This PR adds the "TAVILY_SEARCH_API_KEY" option to the playground to enable the use of the websearch tool.
```
export TAVILY_SEARCH_API_KEY=***
streamlit run  llama_stack/distribution/ui/app.py      
```
Without this change the builtin websearch tool will fail due to missing API key. 
Related to #1902
=> fix: add tavily_search option to playground api

docs/_static/js/detect_theme.js, docs/source/conf.py
1. Adding some lightweight JS to detect the default browser setting for dark/light mode
3. Setting default screen setting to light mode as to not change default behavior. 
From the docs: https://github.com/MrDogeBro/sphinx_rtd_dark_mode
>This lets you choose which theme the user sees when they load the docs for the first time ever. After the first time however, this setting has no effect as the users preference is stored in local storage within their browser. This option accepts a boolean for the value. If this option is true (the default option), users will start in dark mode when first visiting the site. If this option is false, users will start in light mode when they first visit the site.
Tested locally on my Mac on Safari and Chrome.
=> chore: Detect browser setting for dark/light mode and set default to light mode

llama_stack/models/llama/llama4/quantization/loader.py, llama_stack/models/llama/quantize_impls.py
Mirror to https://github.com/meta-llama/llama-models/pull/324 with some clean up
```
with-proxy pip install -e .
export INFERENCE_MODEL=meta-llama/Llama-4-Scout-17B-16E-Instruct
export INFERENCE_CHECKPOINT_DIR=../checkpoints/Llama-4-Scout-17B-16E-Instruct
export QUANTIZATION_TYPE=int4_mixed
with-proxy llama stack build --run --template meta-reference-gpu
```
=> fix: on-the-fly int4 quantize parameter

llama_stack/providers/registry/inference.py, llama_stack/templates/dependencies.json
While building the "experimental-post-training" distribution, we encountered a version conflict between torchao with inference requiring version 0.5.0 and training currently depending on version 0.8.0.
Resolves this error:
```
× No solution found when resolving dependencies:
╰─▶ Because you require torchao==0.5.0 and torchao==0.8.0, we can conclude that your requirements are unsatisfiable.
ERROR    2025-04-10 10:41:22,597 llama_stack.distribution.build:128 uncategorized: Failed to build target test with
return code 1
```
=> fix: use torchao 0.8.0 for inference

llama_stack/providers/remote/post_training/nvidia/post_training.py
The supervised_fine_tune method in NvidiaPostTrainingAdapter had some extra args that aren't part of the post_training protocol, and these extra args were causing FastAPI to throw an error when attempting to stand up an endpoint that used this provider.
(Closes #1938)
Before this change, bringing up a stack with the `nvidia` template failed. Afterwards, it passes. I'm testing this like:
```
INFERENCE_MODEL="meta/llama-3.1-8b-instruct" \
llama stack build --template nvidia --image-type venv --run
```
I also ensured the nvidia/test_supervised_fine_tuning.py tests still pass via:
```
python -m pytest \
tests/unit/providers/nvidia/test_supervised_fine_tuning.py
```
=> fix: remove extra sft args in NvidiaPostTrainingAdapter

llama_stack/providers/remote/safety/nvidia/nvidia.py, tests/unit/providers/nvidia/test_safety.py
This PR adds unit tests for the NVIDIA Safety provider implementation.
1. Ran `./scripts/unit-tests.sh tests/unit/providers/nvidia/test_safety.py` from the root of the project. Verified tests pass.
```
tests/unit/providers/nvidia/test_safety.py::TestNVIDIASafetyAdapter::test_init_nemo_guardrails Initializing NVIDIASafetyAdapter(http://nemo.test)...
PASSED
tests/unit/providers/nvidia/test_safety.py::TestNVIDIASafetyAdapter::test_init_nemo_guardrails_invalid_temperature Initializing NVIDIASafetyAdapter(http://nemo.test)...
PASSED …
```
=> feat: Add unit tests for NVIDIA safety

docs/_static/css/my_theme.css, docs/source/getting_started/detailed_tutorial.md, docs/source/getting_started/index.md
Incorporating some feedback into the docs.
- **`docs/source/getting_started/index.md`:**
- Demo actually does RAG now
- Simplified the installation command for dependencies.
- Updated demo script examples to align with the latest API changes.
- Replaced manual document manipulation with `RAGDocument` for clarity and maintainability.
- Introduced new logic for model and embedding selection using the Llama Stack Client SDK.
- Enhanced examples to showcase proper agent initialization and logging.
- **`docs/source/getting_started/detailed_tutorial.md`:**
- Updated the section for listing models to include proper code formatting with `bash`.
- Removed and reorganized the "Run the Demos" section for clarity.
- Adjusted tab-item structures and added new instructions for demo scripts.
- …
=> docs: Updated docs to show minimal RAG example and some other minor changes

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/inference/inference.py, llama_stack/apis/models/models.py, llama_stack/distribution/routers/routers.py, llama_stack/distribution/routers/routing_tables.py, llama_stack/providers/inline/inference/meta_reference/inference.py, llama_stack/providers/inline/inference/sentence_transformers/sentence_transformers.py, llama_stack/providers/inline/inference/vllm/vllm.py, llama_stack/providers/remote/inference/bedrock/bedrock.py, llama_stack/providers/remote/inference/cerebras/cerebras.py, llama_stack/providers/remote/inference/databricks/databricks.py, llama_stack/providers/remote/inference/fireworks/fireworks.py, llama_stack/providers/remote/inference/nvidia/nvidia.py, llama_stack/providers/remote/inference/ollama/ollama.py, llama_stack/providers/remote/inference/passthrough/passthrough.py, llama_stack/providers/remote/inference/runpod/runpod.py, llama_stack/providers/remote/inference/sambanova/sambanova.py, llama_stack/providers/remote/inference/tgi/tgi.py, llama_stack/providers/remote/inference/together/together.py, llama_stack/providers/remote/inference/vllm/vllm.py, llama_stack/providers/utils/inference/litellm_openai_mixin.py, llama_stack/providers/utils/inference/openai_compat.py, pyproject.toml, requirements.txt, tests/integration/inference/test_openai_completion.py, uv.lock
This stubs in some OpenAI server-side compatibility with three new endpoints:
/v1/openai/v1/models
/v1/openai/v1/completions
/v1/openai/v1/chat/completions
This gives common inference apps using OpenAI clients the ability to talk to Llama Stack using an endpoint like
http://localhost:8321/v1/openai/v1 .
The two "v1" instances in there isn't awesome, but the thinking is that Llama Stack's API is v1 and then our OpenAI compatibility layer is compatible with OpenAI V1. And, some OpenAI clients implicitly assume the URL ends with "v1", so this gives maximum compatibility.
The openai models endpoint is implemented in the routing layer, and just returns all the models Llama Stack knows about.
The following providers should be working with the new OpenAI completions and chat/completions API:
* …
=> feat: OpenAI-Compatible models, completions, chat/completions

docs/source/getting_started/detailed_tutorial.md, llama_stack/distribution/start_stack.sh
Small docs update and an update for `start-stack.sh` with missing color and if statment logic.
1. Makes a small change to start-stack.sh to resolve this error:
```cmd
/home/aireilly/.local/lib/python3.13/site-packages/llama_stack/distribution/start_stack.sh: line 76: [: missing ]'
```
2. Adds a missing $GREEN colour to start-stack.sh
3. Updated `docs/source/getting_started/detailed_tutorial.md` with some small changes and corrections.
Procedures described in `docs/source/getting_started/detailed_tutorial.md` were verified on Linux Fedora 41.
=> docs: Update docs and fix warning in start-stack.sh

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/post_training/post_training.py, llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
Today, supervised_fine_tune itself and the `TrainingConfig` class have a bunch of required fields that a provider implementation might not need. 
for example, if a provider wants to handle hyperparameters in its configuration as well as any type of dataset retrieval, optimizer or LoRA config, a user will still need to pass in a virtually empty `DataConfig`, `OptimizerConfig` and `AlgorithmConfig` in some cases.
Many of these fields are intended to work specifically with llama models and knobs intended for customizing inline. 
Adding remote post_training providers will require loosening these arguments, or forcing users to pass in empty objects to satisfy the pydantic models.
=> feat: make training config fields optional

docs/source/distributions/building_distro.md, llama_stack/cli/stack/build.py, llama_stack/cli/stack/run.py
current text for 'llama stack build' and 'llama stack run' says that if no argument is passed to '--image-name' that the active Conda environment will be used
in reality, the active enviroment is used whether it is from conda, virtualenv, etc.
N/A
N/A
=> fix: misleading help text for 'llama stack build' and 'llama stack run'

llama_stack/models/llama/llama3/prompt_templates/system_prompts.py
User reports in https://github.com/meta-llama/llama-stack/issues/1769#issuecomment-2755564632 that Agent uses tool even on a prompt 'Hello'.
Updated the default prompt. Also move the instruction part out of `function_description` so that user can override it if desired.
Also performance on 100 hotpotqa questions are similar to the current prompt.
=> feat: update default tool use prompt

.github/workflows/integration-tests.yml
workflow -
0. Checkout
1. Install uv
2. Install Ollama
3. Pull Ollama image
4. Start Ollama in background
5. Set Up Environment and Install Dependencies
6. Wait for Ollama to start
7. Start Llama Stack server in background
8. Wait for Llama Stack server to be ready
9. Run Integration Tests
changes -
(4) starts the loading of the ollama model, it does not start ollama. the model will be loaded when used. this step is removed.
(6) is handled in (2). this step is removed.
(2) is renamed to reflect it's dual purpose.
=> refactor: update integration test workflow

llama_stack/providers/inline/post_training/torchtune/post_training.py, llama_stack/providers/utils/scheduler.py, tests/unit/providers/utils/test_scheduler.py
Now a separate thread is started to execute training jobs. Training
requests now return job ID before the job completes. (Which fixes API
timeouts for any jobs that take longer than a minute.)
Note: the scheduler code is meant to be spun out in the future into a
common provider service that can be reused for different APIs and
providers. It is also expected to back the /jobs API proposed here:
https://github.com/meta-llama/llama-stack/discussions/1238
Hence its somewhat generalized form which is expected to simplify its
adoption elsewhere in the future.
Note: this patch doesn't attempt to implement missing APIs (e.g. cancel
or job removal). This work will belong to follow-up PRs. …
=> feat: Implement async job execution for torchtune training

llama_stack/providers/remote/inference/ollama/ollama.py
ollama's CLI supports running models via commands such as 'ollama run llama3.2' this syntax does not work with the INFERENCE_MODEL llamastack var as currently specifying a tag such as 'latest' is required
this commit will check to see if the 'latest' model is available and use that model if a user passes a model name without a tag but the 'latest' is available in ollama
Behavior pre-code change
```bash
$ INFERENCE_MODEL=llama3.2 llama stack build --template ollama --image-type venv --run
...
INFO     2025-04-08 13:42:42,842 llama_stack.providers.remote.inference.ollama.ollama:80 inference: checking            
connectivity to Ollama at `http://beanlab1.bss.redhat.com:11434`...                                            
File "<frozen runpy>", line 198, …
```
=> feat: allow ollama to use 'latest' if available but not specified

.github/workflows/providers-build.yml, llama_stack/cli/stack/_build.py, llama_stack/cli/stack/build.py
allow users to specify only the providers they want in the llama stack build command. If a user wants a non-interactive build, but doesn't want to use a template, `--providers` allows someone to specify something like `--providers inference=remote::ollama` for a distro with JUST ollama
`llama stack build --providers inference=remote::ollama --image-type venv`
`llama stack run --image-type venv /Users/charliedoern/projects/Documents/llama-stack/venv-run.yaml`
=> feat: add `--providers` to llama stack build

docs/source/distributions/self_hosted_distro/remote-vllm.md, llama_stack/templates/remote-vllm/doc_template.md
PR adds instructions to setup vLLM remote endpoint for vllm-remote llama stack distribution.
* Verified with manual tests of the configured vllm-remote against vllm endpoint running on the system with Intel GPU
* Also verified with ci pytests (see cmdline below). Test passes in the same capacity as it does on the A10 Nvidia setup (some tests do fail which seems to be known issues with vllm remote llama stack distribution)
```
pytest -s -v tests/integration/inference/test_text_inference.py \
--stack-config=http://localhost:5001 \
--text-model=meta-llama/Llama-3.2-3B-Instruct
```
CC: @ashwinb
=> docs: add example for intel gpu in vllm remote

llama_stack/providers/remote/inference/vllm/vllm.py, tests/unit/providers/inference/test_remote_vllm.py
Fixes: #1955
Since 0.2.0, the vLLM gets an empty list (vs ``None``in 0.1.9 and before) when there are no tools configured which causes the issue described in #1955 p. This patch avoids sending the 'tools' param to the vLLM altogether instead of an empty list.
It also adds a small unit test to avoid regressions.
The OpenAI [specification](https://platform.openai.com/docs/api-reference/chat/create) does not explicitly state that the list cannot be empty but I found this out through experimentation and it might depend on the actual remote vllm. In any case, as this parameter is Optional, is best to skip it altogether if there's no tools configured.
=> fix: Do not send an empty 'tools' list to remote vllm

docs/_static/js/detect_theme.js
This PR persists the theme preference across page navigation.
Currently, if the default theme is detected, it is used. 
But if a user flips **_the default theme_** and goes to a new page, the theme will switch back to the default. 
This resolves that issue.
=> chore: Fix to persist the theme preference across page navigation.

llama_stack/providers/remote/post_training/nvidia/models.py
Adds `meta/llama-3.2-1b-instruct` to list of models that NeMo Customizer can fine-tune. This is the model our example notebooks typically use for fine-tuning.
=> fix: Add llama-3.2-1b-instruct to NVIDIA fine-tuned model list

llama_stack/distribution/ui/page/playground/tools.py
This PR lets users select an existing vdb to use with their agent on the tools page of the playground. The drop down menu that lets users select a vdb only appears when the rag tool is selected. Without this change, there is no way for a user to specify which vdb they want their rag tool to use on the tools page. I have intentionally left the RAG options sparse here since the full RAG options are exposed on the RAG page.   
Without these changes the RAG tool will throw the following error: `name: knowledge_search) does not have any content ` 
With these changes the RAG tool works as expected.
=> fix: Updated tools playground to allow vdb selection

llama_stack/cli/stack/_build.py
Build failures are hard to read, sometimes we get errors like:
```
Error building stack: 'key'
```
Which are difficult to debug without a proper trace.
If `llama stack build` fails you get a traceback now.
=> fix: print traceback on build failure

llama_stack/cli/stack/_build.py, tests/unit/distribution/test_build_path.py
Fixes a crash that occurred when building a stack as a container image via the interactive wizard without supplying --template or --config.
- Root cause: template_or_config was None; only the container path relies on that parameter, which later reaches subprocess.run() and triggers
`TypeError: expected str, bytes or os.PathLike object, not NoneType.`
- Change: in `_run_stack_build_command_from_build_config` we now fall back to the freshly‑written build‑spec file whenever both optional sources are missing. Also adds a spy‑based unit test that asserts a valid string path is passed to build_image() for container builds.
- New unit test: test_build_path.py. Monkey‑patches build_image, captures the fourth argument, and verifies it is a real path
- Manual smoke test: 
```
llama stack build …
```
=> fix(build): always pass path when no template/config provided

.github/workflows/providers-build.yml
Other jobs already use hashes.
=> chore: Use hashes to pull actions for build-single-provider job

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/inference/inference.py
Some of our multi-turn verification tests were failing because I had accidentally marked content as a required field in the OpenAI chat completion request assistant messages, but it's actually optional. It is required for messages from other roles, but assistant is explicitly allowed to be optional.
Similarly, the assistant message tool_calls field should default to None instead of an empty list.
These two changes get the openai-llama-stack verification test back to 100% passing, just like it passes 100% when not behind Llama Stack. They also increase the pass rate of some of the other providers in the verification test, but don't get them to 100%.
I started a Llama Stack server setup to run all the verification tests (requires OPENAI_API_KEY env variable)
```
llama stack run --image-type …
```
=> fix: OpenAI spec cleanup for assistant requests

docs/source/building_applications/tools.md
- Adds a note about unexpected Brave Search output appearing even when Tavily Search is called. This behavior is expected for now and is a work in progress https://github.com/meta-llama/llama-stack/issues/1229. The note aims to clear any confusion for new users.
- Adds two example scripts demonstrating how to build an agent using:
1. WebSearch tool
2. WolframAlpha tool
These examples provide new users with an instant understanding of how to integrate these tools.
Tested these example scripts using following steps:
step 1. `ollama run llama3.2:3b-instruct-fp16 --keepalive 60m`
step 2. 
```
export INFERENCE_MODEL="meta-llama/Llama-3.2-3B-Instruct"
export LLAMA_STACK_PORT=8321
```
step 3: …
=> docs: add notes to websearch tool and two extra example scripts

llama_stack/distribution/server/server.py
https://github.com/meta-llama/llama-stack/commit/37da47ef8ee9234f370b3105d006ef20fb3cacab#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552 Pydantic was updated from v1 to v2 in this commit which caused this breaking change
Part of #1857 
This won't fix the Validation error with the example, but it will correctly supply user with a proper error rather than a 5xx code.
=> fix: update ref to raw_errors due to new version of pydantic

llama_stack/distribution/ui/page/playground/tools.py
This PR cleans up the sidebar on the tools page of the playground in the following ways:
* created a clearer hierarchy of configuration options and tool selections.
* Removed the `mcp::` or `builtin::` prefixes from the tool selection buttons.  
Run the playground and see the updated sidebar does not cause any new errors.
```
streamlit run llama_stack/distribution/ui/app.py  
```
=> feat: cleanup sidebar formatting on tools playground

llama_stack/providers/remote/inference/together/together.py
The together inference provider was throwing a stack trace every time it shut down, as it was trying to call a non-existent `close` method on the AsyncTogether client. While fixing that, I also adjusted its shutdown logic to close the OpenAI client if we've created one of those, as that client does have a `close` method.
In testing that, I also realized we were defaulting to treating all requests as streaming requests instead of defaulting to non-streaming. So, this flips that default to non-streaming to match how the other providers work.
I tested this by ensuring the together inference provider no longer spits out a long stack trace when shutting it down and by running the OpenAI API chat completion  verification suite to ensure the change in default streaming logic didn't mess anything …
=> fix: Together provider shutdown and default to non-streaming

docs/source/providers/external.md
The RamaLama project now has an external provider offering for Llama Stack: https://github.com/containers/llama-stack-provider-ramalama
See also: https://github.com/meta-llama/llama-stack/pull/1676
=> docs: add RamaLama to list of known external providers

llama_stack/providers/remote/inference/vllm/vllm.py
Closes #1968.
The asynchronous client in `VLLMInferenceAdapter` is now initialized directly before first use and not in `VLLMInferenceAdapter.initialize`. This prevents issues arising due to accessing an expired event loop from a completed `asyncio.run`.
Ran unit tests, including `test_remote_vllm.py`.
Ran the code snippet mentioned in #1968.
=> fix: Added lazy initialization of the remote vLLM client to avoid issues with expired asyncio event loop

llama_stack/distribution/ui/page/playground/tools.py
This PR adds the name of the tool that is used by the agent on the "tools" page of the playground. See image below for an example. 
Run the playground and navigate to the tools page. There users can see that this additional text is present when tools are invoked and absent when they are not. 
```
streamlit run llama_stack/distribution/ui/app.py
```
=> feat: add tool name to chat output in playground

llama_stack/distribution/routers/routers.py, llama_stack/distribution/server/server.py, tests/verifications/openai_api/fixtures/test_cases/chat_completion.yaml, tests/verifications/openai_api/test_chat_completion.py
When clients called the Open AI API with invalid input that wasn't caught by our own Pydantic API validation but instead only caught by the backend inference provider, that backend inference provider was returning a HTTP 400 error. However, we were wrapping that into a HTTP 500 error, obfuscating the actual issue from calling clients and triggering OpenAI client retry logic.
This change adjusts our existing `translate_exception` method in `server.py` to wrap `openai.BadRequestError` as HTTP 400 errors, passing through the string representation of the error message to the calling user so they can see the actual input validation error and correct it. I tried changing this in a few other places, but ultimately `translate_exception` was the only real place to handle this for both streaming …
=> fix: Return HTTP 400 for OpenAI API validation errors

docs/source/providers/external.md
the ramalama team has decided to rename their external provider `ramalama-stack` (more catchy!). Update docs accordingly
=> chore: rename ramalama provider

.github/workflows/providers-build.yml, llama_stack/cli/stack/_build.py, llama_stack/distribution/build.py, llama_stack/distribution/build_container.sh, tests/unit/distribution/test_build_path.py
As part of the build process, we now include the generated run.yaml (based of the provided build configuration file) into the container. We updated the entrypoint to use this run configuration as well.
Given this simple distribution configuration:
```
version: '2'
distribution_spec:
description: Use (an external) Ollama server for running LLM inference
providers:
inference:
- remote::ollama
vector_io:
- inline::faiss
safety:
- inline::llama-guard
agents:
- inline::meta-reference
telemetry:
- inline::meta-reference
eval:
- inline::meta-reference
datasetio:
- remote::huggingface
- inline::localfs
scoring:
- inline::basic
- inline::llm-as-judge
- inline::braintrust
tool_runtime:
- remote::brave-search
- remote::tavily-search
- inline::code-interpreter
- inline::rag-runtime
- …
```
=> feat: include run.yaml in the container image

llama_stack/providers/inline/tool_runtime/rag/memory.py
This PR addresses the content dominance problem that frequently arises with multiple models when executing queries with the RAG tool. When the retrieved content is too large, it disproportionately influences the generation process, causing the model to ignore the original question and to provide meaningless comments on the retrieved information instead.
This situation is especially common with agentic RAG, which is the standard way of doing RAG in Llama Stack, since directly manipulating the prompt combining the query with the retrieved content is not possible.
This PR appends a grounding message to the results returned by the knowledge search tool, reminding the model about the original query and the purpose of the inference call. This makes the problem significantly less likely to …
=> fix: prevent the knowledge search tool from confusing the model with long content

.github/workflows/integration-tests.yml, .github/workflows/test-external-providers.yml, .github/workflows/unit-tests.yml
Remove `distributions/**` from integration, external provider, and unit tests
N/A
=> chore: Remove `distributions/**` from integration, external provider, and unit tests

llama_stack/providers/inline/inference/meta_reference/inference.py, llama_stack/providers/inline/inference/meta_reference/parallel_utils.py
MAX_BATCH_SIZE=10 LLAMA_MODELS_DEBUG=1 LLAMA_STACK_PORT=5002 LLAMA_STACK_LOGGING='all=info' llama stack run meta-reference-gpu --env INFERENCE_MODEL=meta-llama/Llama-4-Scout-17B-16E-Instruct --env INFERENCE_CHECKPOINT_DIR=...
LLAMA_STACK_CONFIG=http://localhost:5002/ pytest -s -v tests/integration/inference --safety-shield meta-llama/Llama-Guard-3-8B --vision-model meta-llama/Llama-4-Scout-17B-16E-Instruct --text-model meta-llama/Llama-4-Scout-17B-16E-Instruct
=> fix: meta ref inference

llama_stack/providers/utils/inference/openai_compat.py, tests/unit/providers/inference/test_remote_vllm.py, tests/unit/providers/utils/inference/test_openai_compat.py
Include the tool call details with the chat when doing Rag with Remote vllm
Fixes: #1929
With this PR the tool call is included in the chat returned to vllm, the model (meta-llama/Llama-3.1-8B-Instruct) the returns the answer as expected.
=> fix: Including tool call in chat

llama_stack/distribution/server/server.py, tests/unit/server/test_sse.py
This expands the `test_sse` test suite and fixes some edge cases with bugs in our SSE error handling to ensure streaming clients always get a proper error response.
First, we handle the case where a client disconnects before we actually start streaming the response back. Previously we only handled the case where a client disconnected as we were streaming the response, but there was an edge case where a client disconnecting before we streamed any response back did not trigger our logic to cleanly handle that disconnect.
Second, we handle the case where an error is thrown from the server before the actual async generator gets created from the provider. This happens in scenarios like the newly merged OpenAI API input validation, where we eagerly raise validation errors before returning the …
=> fix: Additional streaming error handling

llama_stack/distribution/ui/page/playground/tools.py
This PR improves the Tools page in the LlamaStack Playground UI by enhancing the readability of the active tool list shown in the sidebar.
- Previously, active tools were displayed in a flat JSON array with verbose identifiers (e.g., builtin::code_interpreter:code_interpreter).
- This PR updates the logic to group tools by their toolgroup (e.g., builtin::websearch) and renders each tool name in a simplified, human-readable format (e.g., web_search).
- This change improves usability when working with multiple toolgroups, especially in configurations involving MCP tools or complex tool identifiers.
Before and After Comparison:
**Before**
**After**
- Followed the [LlamaStack UI Developer …
=> feat: Enhance tool display in Tools sidebar by simplifying tool identifiers

llama_stack/cli/stack/_build.py
Enhances the user experience in the `llama stack build` command by adding interactive TAB completion for image type selection. This ensures the UX consistency with other parts of the CLI that already support tab completion, such as provider selection, providing a more intuitive and discoverable interface for users.
=> feat(cli): add interactive tab completion for image type selection

.coveragerc
Introduce a `.coveragerc` file to omit:
- test files (*/tests/*)
- provider code (*/llama_stack/providers/*)
- template files (*/llama_stack/templates/*)
- virtual environment (.venv/*)
This ensures coverage reports focus on core application logic (API and CLI).
Note: I'm opening this for discussing as well - we might decide to ignore more and or re-add some directories!
=> chore: exclude test, provider, and template directories from coverage

tests/integration/inference/test_openai_completion.py
With https://github.com/meta-llama/llama-stack-client-python/pull/226, now we have llama-stack-client be able to used as a substitute for OpenAI client (duck-typed) so you don't need to change downstream library code.
=> fix: check that llama stack client plain can be used as a subst for OpenAI client

llama_stack/models/llama/llama4/chat_format.py
LLAMA_STACK_CONFIG=http://localhost:5002 pytest -s -v tests/integration/inference --safety-shield meta-llama/Llama-Guard-3-8B --vision-model meta-llama/Llama-4-Scout-17B-16E-Instruct --text-model meta-llama/Llama-4-Scout-17B-16E-Instruct
=> fix: tool call encoded twice

pyproject.toml, requirements.txt, uv.lock
This resolves a new critical severity on h11. See https://access.redhat.com/security/cve/cve-2025-43859. We should consider releasing a new patch with this fix.
This was updated via:
```
uv add "h11>=0.16.0"
uv export --frozen --no-hashes --no-emit-project --output-file=requirements.txt
```
=> fix: Bump h11 to 0.16.0 to fix cve-2025-43859

docs/source/distributions/self_hosted_distro/nvidia.md, llama_stack/distribution/routers/routing_tables.py, llama_stack/providers/registry/datasetio.py, llama_stack/providers/remote/datasetio/nvidia/README.md, llama_stack/providers/remote/datasetio/nvidia/__init__.py, llama_stack/providers/remote/datasetio/nvidia/config.py, llama_stack/providers/remote/datasetio/nvidia/datasetio.py, llama_stack/templates/dependencies.json, llama_stack/templates/nvidia/build.yaml, llama_stack/templates/nvidia/nvidia.py, llama_stack/templates/nvidia/run-with-safety.yaml, llama_stack/templates/nvidia/run.yaml, pyproject.toml, tests/integration/datasets/test_datasets.py, tests/integration/providers/nvidia/__init__.py, tests/integration/providers/nvidia/conftest.py, tests/integration/providers/nvidia/test_datastore.py, tests/unit/providers/nvidia/test_datastore.py
Implemetation of NeMO Datastore register, unregister API.
Open Issues: 
- provider_id gets set to `localfs` in client.datasets.register() as it is specified in routing_tables.py: DatasetsRoutingTable
see: #1860
Currently I have passed `"provider_id":"nvidia"` in metadata and have parsed that in `DatasetsRoutingTable`
(Not the best approach, but just a quick workaround to make it work for now.)
- Unit test cases: `pytest tests/unit/providers/nvidia/test_datastore.py`
```bash
========================================================== test session starts ===========================================================
platform linux -- Python 3.10.0, pytest-8.3.5, pluggy-1.5.0
rootdir: /home/ubuntu/llama-stack
plugins: anyio-4.9.0, asyncio-0.26.0, nbval-0.11.0, …
```
=> feat: Add NVIDIA NeMo datastore

.github/workflows/integration-auth-tests.yml, docs/source/distributions/configuration.md, llama_stack/distribution/datatypes.py, llama_stack/distribution/server/auth.py, llama_stack/distribution/server/auth_providers.py, llama_stack/distribution/server/server.py, pyproject.toml, requirements.txt, tests/unit/registry/test_registry_acl.py, tests/unit/server/test_auth.py, uv.lock
This commit adds a new authentication system to the Llama Stack server with support for Kubernetes and custom authentication providers. Key changes include:
- Implemented KubernetesAuthProvider for validating Kubernetes service account tokens
- Implemented CustomAuthProvider for validating tokens against external endpoints - this is the same code that was already present.
- Added test for Kubernetes
- Updated server configuration to support authentication settings
- Added documentation for authentication configuration and usage
The authentication system supports:
- Bearer token validation
- Kubernetes service account token validation
- Custom authentication endpoints
Setup a Kube cluster using Kind or Minikube.
Run a server with:
```
server:
port: 8321
auth:
provider_type: kubernetes …
```
=> feat: Add Kubernetes authentication

llama_stack/distribution/ui/page/playground/tools.py
This PR updates how the `AgentType` gets set using the radio button on the tools page of the playground. This change is needed due to the fact with its current implementation, the chat interface will resets after every input, preventing users from having a multi-turn conversation with the agent.
Run the Playground without these changes:
```bash
streamlit run llama_stack/distribution/ui/app.py
```
Navigate to the tools page and attempt to have a multi-turn conversation. You should see the conversation reset after asking a second question. 
Repeat the steps above with these changes and you will see that it works as expected when asking the agent multiple questions.
=> fix: tools page on playground resets agent after every interaction

llama_stack/providers/inline/post_training/common/validator.py, llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
Change validation to TODO same as was done [here](https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/inline/eval/meta_reference/eval.py#L87) until validation can be implemented
Closes #1849
=> fix: add todo for schema validation

llama_stack/providers/remote/inference/ollama/ollama.py
In our OpenAI API verification tests, ollama was still calling tools even when `tool_choice="none"` was passed in its chat completion requests. Because ollama isn't respecting `tool_choice` properly, this adjusts our provider implementation to remove the `tools` from the request if `tool_choice="none"` is passed in so that it does not attempt to call any of those tools.
I tested this with a couple of Llama models, using both our OpenAI completions integration tests and our verification test suites.
These all passed before, and still do.
```
INFERENCE_MODEL="llama3.2:3b-instruct-fp16" \
llama stack build --template ollama --image-type venv --run
```
```
LLAMA_STACK_CONFIG=http://localhost:8321 \
python -m pytest -v \
tests/integration/inference/test_openai_completion.py \
--text-model …
```
=> fix: ollama still using tools with `tool_choice="none"`

tests/unit/distribution/routers/test_routing_tables.py
Adds some unit tests for the routing logic
Overall unit test coverage goes from 
TOTAL                                                                     12434   8030    35%
to
TOTAL                                                                     12434   7871    37%
Better coverage on router.py, before:
```
llama_stack/distribution/routers/routers.py | 342 | 219 | 0 | 36%
llama_stack/distribution/routers/routing_tables.py | 346 | 236 | 0 | 32%
```
After:
```
llama_stack/distribution/routers/routers.py | 342 | 219 | 0 | 36%
llama_stack/distribution/routers/routing_tables.py | 349 | 89 | 0 | 74%
```
=> chore: Increase unit test coverage of routing_tables.py

.github/workflows/integration-tests.yml
* pull the embedding model so that it's not pulled during the distro server startup sequence
* cache the models
* collect logs at the end of the workflow
=> chore(ci): misc Ollama improvements

llama_stack/providers/remote/safety/nvidia/nvidia.py, tests/unit/providers/nvidia/test_safety.py
When running a Llama Stack server and invoking the `/v1/safety/run-shield` endpoint, the NVIDIA Guardrails endpoint in some cases errors with a `422: Unprocessable Entity` due to malformed input.
For example, given an request body like:
```
{
"model": "test",
"messages": [
{ "role": "user", "content": "You are stupid." }
]
}
```
`convert_pydantic_to_json_value` converts the message to:
```
{ "role": "user", "content": "You are stupid.", "context": null }
```
Which causes NVIDIA Guardrails to return an error `HTTPError: 422 Client Error: Unprocessable Entity for url: http://nemo.test/v1/guardrail/checks`, because `context` shouldn't be included in the body.
I ran the Llama Stack server …
=> fix: Fix messages format in NVIDIA safety check request body

llama_stack/cli/stack/run.py, llama_stack/distribution/build.py, pyproject.toml
- Added new Ruff lint rules to detect ambiguous or non-ASCII characters:
- Added per-file ignores where Unicode usage is still required.
- Fixed whatever had to be fixed
=> fix: enforce stricter ASCII rules lint rules in Ruff

.github/workflows/pre-commit.yml
All merges produced by github are pushes to main, which makes the check
fail. The check is local by design, not meant for CI.
=> ci: Disable no-commit-to-branch

llama_stack/providers/utils/inference/openai_compat.py
Nullable param type is not supported, e.g. ['string', 'null'], since it fails type validation. 
Tests:
Run inference with
messages:
- content: You are a helpful assistant that can use tools to get information.
role: system
- content: What's the temperature in San Francisco in celsius?
role: user
tools:
- function:
description: Get current temperature for a given location.
name: get_weather
parameters:
additionalProperties: false
properties:
location:
description: "City and country e.g. Bogot\xE1, Colombia"
type: string
unit:
description: "Unit of temperature, default to celsius"
type: [string, "null"]  # <= nullable type
required:
- location
type: object
type: function
=> fix: nullable param type for function call

llama_stack/providers/utils/inference/openai_compat.py, tests/unit/providers/utils/inference/test_openai_compat.py
When converting OpenAI message content for the "system" and "assistant" roles to Llama Stack inference APIs (used for some providers when dealing with Llama models via OpenAI API requests to get proper prompt / tool handling), we were not properly converting any non-string content.
I discovered this while running the new Responses AI verification suite against the Fireworks provider, but instead of fixing it as part of some ongoing work there split this out into a separate PR.
This fixes that, by using the `openai_content_to_content` helper we used elsewhere to ensure content parts were mapped properly.
I added a couple of new tests to `test_openai_compat` to reproduce this issue and validate its fix. I ran those as below:
```
python -m pytest -s -v …
```
=> fix: openai_compat messages system/assistant non-str content

docs/_static/css/my_theme.css
Closes #2078 
Previously, the Agent Execution Loop diagram was barely visible in dark mode:
I experimented with styling individual classes, but ultimately found that adding an off-white background provides the best visibility in both dark and light modes:
The documentation can be built locally by following the docs: https://llama-stack.readthedocs.io/en/latest/contributing/index.html#building-the-documentation 
=> fix: improve Mermaid diagram visibility in dark mode

docs/source/providers/external.md
Lists another external provider example (kfp).
=> docs: List external kubeflow pipelines provider prototype

CONTRIBUTING.md
- Clarified best practices for using `# noqa` and `# type: ignore`, requiring justification comments
- Improved formatting for readability
=> docs: expand contribution guidelines for linting exceptions

tests/unit/__init__.py, tests/unit/conftest.py, tests/unit/distribution/routers/test_routing_tables.py, tests/unit/fixtures.py, tests/unit/providers/agents/test_persistence_access_control.py, tests/unit/registry/test_registry.py, tests/unit/registry/test_registry_acl.py, tests/unit/server/test_access_control.py
Add fixtures for SqliteKVStore, DiskDistributionRegistry and CachedDiskDistributionRegistry. And use them in tests that had all been duplicating similar setups.
unit tests continue to run
=> chore: Add fixtures to conftest.py

pyproject.toml, tests/integration/datasets/test_datasets.py, uv.lock
**Fixes** #1959 
HuggingFace provides several loading paths that the datasets library can use. My theory on why the test would previously fail intermittently is because when calling `load_dataset(...)`, it may be trying several options such as local cache, Hugging Face Hub, or a dataset script, or other. There's one of these options that seem to work inconsistently in the CI.
The HuggingFace datasets library relies on the `transformers` package to load certain datasets such as `llamastack/simpleqa`, and by adding the package, we can see the dataset is loaded consistently via the Hugging Face Hub.
Please see PR in my fork demonstrating over 7 consecutive passes:
https://github.com/ChristianZaccaria/llama-stack/pull/1 
**Some References:**
- …
=> fix: test_datasets HF scenario in CI

docs/source/providers/external.md
Adds documentation for the remote [TrustyAI LM-Eval Eval Provider](https://github.com/trustyai-explainability/llama-stack-provider-lmeval). LM-Eval is a service for large language model evaluation based on the open source project [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness) and is integrated into the [TrustyAI Kubernetes Operator](https://trustyai-explainability.github.io/trustyai-site/main/trustyai-operator.html).
=> docs: Add TrustyAI LM-Eval to list of known external providers

.github/actions/setup-ollama/action.yml, .github/workflows/integration-tests.yml
This PR introduces a reusable GitHub Actions workflow for pulling and running an Ollama model, with caching to avoid repeated downloads.
Closes: #1949 
1. Trigger a workflow that uses the Ollama setup. Confirm that:
- The model is pulled successfully.
- It is placed in the correct directory, official at the moment (not ~ollama/.ollama/models as per comment so need to confirm this).
2. Re-run the same workflow to validate that:
- The model is restored from the cache.
- Execution succeeds with the cached model.
=> ci: add new action to install ollama, cache the model

CONTRIBUTING.md
Don't use unicode characters in the codebase. ASCII-only is preferred for compatibility or readability reasons
=> docs: contrib add a note about unicode in code

llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
Revert a change that by mistake forced efficiency_config on torchtune provider
users.
```
fix: Don't require efficiency_config for torchtune
It was enforced by mistake when
0751a960a518785a821407bee4b855fbf56e88cb merged.
Other asserts made sense in that the code was written, potentially, to
always expect a non-None value. But not efficiency_config.
```
=> fix: Don't require efficiency_config for torchtune

llama_stack/providers/utils/memory/vector_store.py, tests/unit/providers/utils/__init__.py, tests/unit/providers/utils/memory/__init__.py, tests/unit/providers/utils/memory/test_vector_store.py
Checks for RAGDocument of type InterleavedContent
I noticed when stepping through the code that the supported types for `RAGDocument` included `InterleavedContent` as a content type. This type is not checked against before putting the `doc.content` is regex matched against. This would cause a runtime error. This change adds an explicit check for type.
The only other part that I'm unclear on is how to handle the `ImageContent` type since this would always just return `<image>` which seems like an undesired behavior. Should the `InterleavedContent` type be removed from `RAGDocument` and replaced with `URI | str`?
=> fix: add check for interleavedContent

llama_stack/distribution/routers/routers.py, llama_stack/providers/remote/inference/ollama/ollama.py
In our OpenAI API verification tests, some providers were still calling tools even when `tool_choice="none"` was passed in the chat completion requests. Because they aren't all respecting `tool_choice` properly, this adjusts our routing implementation to remove the `tools` and `tool_choice` from the request if `tool_choice="none"` is passed in so that it does not attempt to call any of those tools. Adjusting this in the router fixes this across all providers.
This also cleans up the non-streaming together.ai responses for tools, ensuring it returns `None` instead of an empty list when there are no tool calls, to exactly match the OpenAI API responses in that case.
I observed existing failures in our OpenAI API verification suite - see …
=> fix: inference providers still using tools with `tool_choice="none"`

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/telemetry/telemetry.py, llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
Adds the API to query metrics from telemetry.
llama stack run ~/.llama/distributions/fireworks/fireworks-run.yaml
=> feat: add metrics query API

docs/source/distributions/self_hosted_distro/together.md, llama_stack/providers/remote/inference/together/models.py, llama_stack/templates/together/run-with-safety.yaml, llama_stack/templates/together/run.yaml, llama_stack/templates/verification/run.yaml
This reverts commit 0f878ad87af9d1064f5da57ef7ed51f2541232a3.
The llama4 models already existed for Together.
cc @yogishbaliga @bbrowning
=> fix: revert "feat(provider): adding llama4 support in together inference provider (#2123)"

README.md
This gives more visibility to the link to Discord. Even though it's available at the top of the README as a badge, more than 20 people have missed it and asked me where to find the link.
=> docs: Add link to Discord to README

llama_stack/providers/inline/tool_runtime/rag/memory.py, tests/unit/rag/test_rag_query.py
This PR fixes the behavior of the `/tool-runtime/rag-tool/query` endpoint when invoked with an empty `vector_db_ids` parameter.
As of now, it simply returns an empty result, which leads to a misleading error message from the server and makes it difficult and time-consuming to detect the problem with the input parameter. 
The proposed fix is to return an indicative error message in this case.
Running the following script:
```
agent = Agent(
client,
model=MODEL_ID,
instructions=SYSTEM_PROMPT,
tools=[
dict(
name="builtin::rag/knowledge_search",
args={
"vector_db_ids": [],
},
)
],
)
response = agent.create_turn(
messages=[
{
"content": "How to install OpenShift?",
}
],
session_id=agent.create_session(f"rag-session")
)
```
results in the following error message in the …
=> fix: raise an error when no vector DB IDs are provided to the RAG tool

llama_stack/distribution/providers.py, llama_stack/distribution/routers/routers.py, llama_stack/distribution/server/server.py
As per docs [1], since python 3.11 wait_for() raises TimeoutError. Since
we currently support python 3.10+, we have to catch both.
[1]: https://docs.python.org/3.12/library/asyncio-task.html#asyncio.wait_for
No explicit testing; just code hardening to reflect docs.
=> fix: catch TimeoutError in place of asyncio.TimeoutError

llama_stack/providers/remote/vector_io/chroma/chroma.py
```
$ INFERENCE_MODEL=meta-llama/Llama-3.2-3B-Instruct \
CHROMADB_URL=http://localhost:8000 \
llama stack build --image-type conda --image-name llama \
--providers vector_io=remote::chromadb,inference=remote::ollama \
--run
...
File ".../llama_stack/providers/remote/vector_io/chroma/chroma.py", line 31, in <module>
ChromaClientType = chromadb.AsyncHttpClient | chromadb.PersistentClient
TypeError: unsupported operand type(s) for |: 'function' and 'function'
```
issue: AsyncHttpClient and PersistentClient are functions that return AsyncClientAPI and ClientAPI types, respectively. | cannot be used to construct a type from functions.
previously the code was Union[AsyncHttpClient, PersistentClient], which did not trigger an error
Closes #2135
=> fix: chromadb type hint

llama_stack/apis/agents/agents.py, llama_stack/apis/eval/eval.py
This PR adds stubs to the end of functions create_agent_turn, create_openai_response and job_result. 
Ran provided unit tests
=> fix: Syntax error with missing stubs at the end of some function calls

llama_stack/providers/remote/inference/ollama/ollama.py
The ollama provider was using an older variant of the code to convert incoming parameters from the OpenAI API completions and chat completion endpoints into requests that get sent to the backend provider over its own OpenAI client. This updates it to use the common `prepare_openai_completion_params` method used elsewhere, which takes care of removing stray `None` values even for nested structures.
Without this, some other parameters, even if they have values of `None`, make their way to ollama and actually influence its inference output as opposed to when those parameters are not sent at all.
This passes tests/integration/inference/test_openai_completion.py and fixes the issue found in #2098, which was tested via manual curl requests crafted a particular way.
Closes #2098
=> fix: ollama openai completion and chat completion params

docs/source/distributions/remote_hosted_distro/watsonx.md, llama_stack/templates/dependencies.json, llama_stack/templates/watsonx/build.yaml, llama_stack/templates/watsonx/run.yaml, llama_stack/templates/watsonx/watsonx.py
Issue Link : https://github.com/meta-llama/llama-stack/issues/2117
Once added, User will be able to use Sentence Transformer model `all-MiniLM-L6-v2`
=> fix: Adding Embedding model to watsonx inference

llama_stack/distribution/datatypes.py, llama_stack/distribution/server/server.py
This adds a config option for a CA to be specified with which client certs are verified. If specified client certs are required. This offers a simple way of securing access to the server.
(Note: at present it is not possible to access the details of the client certificate using uvicorn (unless it was monkey patched). Though there is a defined TLS extension for ASGI, this is not implemented in uvicorn pending a review and likely change to the specification. See https://github.com/encode/uvicorn/pull/1119 and https://github.com/django/asgiref/issues/466. Without access to the DN it isn't possible to set user access attributes for a mutually authentication tls connection, so more fine grained access control is not yet possible). 
[//]: # (If resolving an issue, uncomment and update the line …
=> feat: enable mutual tls

tests/integration/report.py
While adding other tests, I came across this and wasn’t sure how useful it is. It doesn’t seem to be exercised anywhere in CI, but I figured I’d fix it anyway. Happy to remove it if preferred. :)
Run:
```
uv run pytest tests/integration/inference --stack-config=ollama --report=test_report.md -v --text-model="llama3.2:3b" --embedding-model=all-MiniLM-L6-v2
```
Look at the produced `test_report.md`.
=> fix: pytest reports

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/agents/agents.py, llama_stack/apis/agents/openai_responses.py, llama_stack/distribution/server/server.py, llama_stack/providers/inline/agents/meta_reference/agents.py, llama_stack/providers/inline/agents/meta_reference/openai_responses.py, tests/unit/providers/agents/meta_reference/fixtures/__init__.py, tests/unit/providers/agents/meta_reference/fixtures/simple_chat_completion.yaml, tests/unit/providers/agents/meta_reference/fixtures/tool_call_completion.yaml, tests/unit/providers/agents/meta_reference/test_openai_responses.py, tests/verifications/openai-api-verification-run.yaml, tests/verifications/openai_api/fixtures/test_cases/responses.yaml, tests/verifications/openai_api/test_responses.py
This is a combination of what was previously 3 separate PRs - #2069, #2075, and #2083. It turns out all 3 of those are needed to land a working function calling Responses implementation. The web search builtin tool was already working, but this wires in support for custom function calling.
I ended up combining all three into one PR because they all had lots of merge conflicts, both with each other but also with #1806 that just landed. And, because landing any of them individually would have only left a partially working implementation merged.
The new things added here are:
* Storing of input items from previous responses and restoring of those input items when adding previous responses to the conversation state
* Handling of multiple input item messages roles, not just "user" messages.
* …
=> feat: function tools in OpenAI Responses

tests/verifications/openai_api/fixtures/test_cases/responses.yaml
Prevent it from returning results about
'LT Wright Maverick Scout' knives. Ultimatly
we want the word "model" in the returned results
putting llm in the search term make this more likely.
Closes: #2150
=> fix: Make search tool talk about models

docs/source/providers/external.md
The provider selling point *is* using the same provider for both.
=> docs: Clarify kfp provider is both inline and remote

llama_stack/providers/remote/inference/vllm/vllm.py, tests/unit/providers/inference/test_remote_vllm.py
Closes #2111.
Fixes an error causing Llama Stack to just return `<tool_call>` and complete the turn without actually executing the tool. See the issue description for more detail.
1) Ran existing unit tests
2) Added a dedicated test verifying correct behavior in this edge case
3) Ran the code snapshot from #2111
=> fix: remote vLLM tool execution now works when the last chunk contains the call arguments

.github/workflows/integration-auth-tests.yml, .github/workflows/integration-tests.yml, .github/workflows/test-external-providers.yml
most third-party actions use hashes for pinning but not all
do proper hash pinning on all remaining actions using tags
=> ci(chore): use hashes for all version pinning

llama_stack/providers/remote/inference/openai/models.py, llama_stack/providers/remote/inference/openai/openai.py, llama_stack/providers/utils/inference/litellm_openai_mixin.py, llama_stack/templates/dev/run.yaml, llama_stack/templates/verification/run.yaml
note: the openai provider exposes the litellm specific model names to the user. this change is compatible with that. the litellm names should be deprecated.
=> feat: expand set of known openai models, allow using openai canonical model names

llama_stack/providers/remote/inference/vllm/vllm.py, llama_stack/providers/utils/inference/openai_compat.py, tests/integration/agents/test_agents.py, tests/unit/providers/inference/test_remote_vllm.py
This fixes an issue in how we used the tool_call_buf from streaming tool calls in the remote-vllm provider where it would end up concatenating parameters from multiple different tool call results instead of aggregating the results from each tool call separately.
It also fixes an issue found while digging into that where we were accidentally mixing the json string form of tool call parameters with the string representation of the python form, which mean we'd end up with single quotes in what should be double-quoted json strings.
Closes #1120
The following tests are now passing 100% for the remote-vllm provider, where some of the test_text_inference were failing before this change:
```
VLLM_URL="http://localhost:8000/v1" INFERENCE_MODEL="RedHatAI/Llama-4-Scout-17B-16E-Instruct-FP8-dynamic" …
```
=> fix: multiple tool calls in remote-vllm chat_completion

tests/integration/tool_runtime/test_rag_tool.py
LLAMA_STACK_CONFIG=http://localhost:8321 pytest tests/integration/tool_runtime/test_rag_tool.py --embedding-model text-embedding-3-small
=> test: catch BadRequestError for non-library client

docs/source/distributions/kubernetes_deployment.md, docs/source/distributions/remote_hosted_distro/watsonx.md, docs/source/distributions/self_hosted_distro/cerebras.md, docs/source/distributions/self_hosted_distro/dell.md, docs/source/distributions/self_hosted_distro/nvidia.md, docs/source/distributions/self_hosted_distro/ollama.md, docs/source/distributions/self_hosted_distro/remote-vllm.md, docs/source/distributions/self_hosted_distro/tgi.md, llama_stack/distribution/server/server.py, llama_stack/distribution/start_stack.sh, llama_stack/templates/cerebras/doc_template.md, llama_stack/templates/dell/doc_template.md, llama_stack/templates/nvidia/doc_template.md, llama_stack/templates/ollama/doc_template.md, llama_stack/templates/remote-vllm/doc_template.md, llama_stack/templates/tgi/doc_template.md, llama_stack/templates/watsonx/doc_template.md
start_stack.sh was using --yaml-config which is deprecated.
a bunch of distro docs also mentioned --yaml-config. Replaces all instances and logic for --yaml-config with --config
resolves #2189
=> fix: replace all instances of --yaml-config with --config

llama_stack/cli/stack/_build.py
fixes #2188
`INFERENCE_MODEL=meta-llama/Llama-3.3-70B-Instruct llama stack build --image-name ollama --image-type conda --template ollama --run` without error
=> fix: update llama stack build --run to use new start_stack.sh signature

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, docs/openapi_generator/pyopenapi/generator.py, llama_stack/apis/inference/inference.py, llama_stack/distribution/resolver.py, llama_stack/providers/inline/inference/meta_reference/inference.py, llama_stack/providers/inline/inference/sentence_transformers/sentence_transformers.py, llama_stack/providers/remote/inference/cerebras_openai_compat/__init__.py, llama_stack/providers/remote/inference/fireworks_openai_compat/__init__.py, llama_stack/providers/remote/inference/groq_openai_compat/__init__.py, llama_stack/providers/remote/inference/llama_openai_compat/__init__.py, llama_stack/providers/remote/inference/ollama/ollama.py, llama_stack/providers/remote/inference/sambanova_openai_compat/__init__.py, llama_stack/providers/remote/inference/together_openai_compat/__init__.py, llama_stack/providers/utils/inference/litellm_openai_mixin.py
This PR introduces APIs to retrieve past chat completion requests, which will be used in the LS UI.
Our current `Telemetry` is ill-suited for this purpose as it's untyped so we'd need to filter by obscure attribute names, making it brittle.
Since these APIs are 'provided by stack' and don't need to be implemented by inference providers, we introduce a new InferenceProvider class, containing the existing inference protocol, which is implemented by inference providers.
The APIs are OpenAI-compliant, with an additional `input_messages` field.
This PR just adds the API and marks them provided_by_stack. S
tart stack server -> doesn't crash
=> feat: introduce APIs for retrieving chat completion requests

llama_stack/cli/stack/_build.py, llama_stack/distribution/datatypes.py, llama_stack/distribution/library_client.py
The `external_config_dir` configuration parameter is not being passed to the `BuildConfig` for `LlamaStackAsLibraryClient`.
This prevents _plugin_ providers from being loaded when `llama-stack` is uses as a library.
I ran `LlamaStackAsLibraryClient` with a configuration file that contained `external_config_dir` and related configuration.
It does not work without this change: _external_ providers are not resolved.
It does work with this change :+1: 
=> fix: Pass external_config_dir to BuildConfig

llama_stack/distribution/server/server.py
`--yaml-config` is gone now with
https://github.com/meta-llama/llama-stack/pull/2196.
=> fix: remove wrong deprecated warning

llama_stack/distribution/server/server.py, llama_stack/providers/inline/telemetry/meta_reference/telemetry.py, llama_stack/providers/utils/telemetry/tracing.py
This extracts the W3C trace context headers (traceparent and tracestate) from incoming requests, stuffs them as attributes on the spans we create, and uses them within the tracing provider implementation to actually wrap our spans in the proper context.
What this means in practice is that when a client (such as an OpenAI client) is instrumented to create these traces, we'll continue that distributed trace within Llama Stack as opposed to creating our own root span that breaks the distributed trace between client and server.
It's slightly awkward to do this in Llama Stack because our Tracing API knows nothing about opentelemetry, W3C trace headers, etc - that's only knowledge the specific provider implementation has. So, that's why the trace headers get extracted by in the server code but …
=> feat: Propagate W3C trace context headers from clients

llama_stack/providers/remote/post_training/nvidia/post_training.py, tests/unit/providers/nvidia/test_parameters.py, tests/unit/providers/nvidia/test_supervised_fine_tuning.py
When launching a fine-tuning job, an upcoming version of NeMo Customizer will expect the `config` name to be formatted as `namespace/name@version`. Here, `config` is a reference to a model + additional metadata. There could be multiple `config`s that reference the same base model.
This PR updates NVIDIA's `supervised_fine_tune` to simply pass the `model` param as-is to NeMo Customizer. Currently, it expects a specific, allowlisted llama model (i.e. `meta/Llama3.1-8B-Instruct`) and converts it to the provider format (`meta/llama-3.1-8b-instruct`).
From a notebook, I built an image with my changes: 
```
!llama stack build --template nvidia --image-type venv
from …
```
=> fix: Pass model parameter as config name to NeMo Customizer

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/agents/agents.py, llama_stack/providers/inline/agents/meta_reference/agents.py, llama_stack/providers/inline/agents/meta_reference/openai_responses.py, tests/unit/providers/agents/meta_reference/test_openai_responses.py
Add support for "instructions" to the responses API. Instructions provide a way to swap out system (or developer) messages in new responses.
unit tests added
=> feat: Add "instructions" support to responses API

llama_stack/distribution/datatypes.py, llama_stack/distribution/server/auth_providers.py, tests/unit/server/test_auth.py
This adds an alternative option to the oauth_token auth provider that can be used with existing authorization services which support token introspection as defined in RFC 7662. This could be useful where token revocation needs to be handled or where opaque tokens (or other non jwt formatted tokens) are used 
Tested against keycloak
=> feat: add additional auth provider that uses oauth token introspection

docs/source/distributions/configuration.md, llama_stack/distribution/datatypes.py, llama_stack/distribution/server/auth.py, llama_stack/distribution/server/quota.py, llama_stack/distribution/server/server.py, tests/unit/server/test_quota.py
feat(quota): add server‑side per‑client request quotas (requires auth)
Unrestricted usage can lead to runaway costs and fragmented client-side
workarounds. This commit introduces a native quota mechanism to the
server, giving operators a unified, centrally managed throttle for
per-client requests—without needing extra proxies or custom client
logic.  This helps contain cloud-compute expenses, enables fine-grained
usage control, and simplifies deployment and monitoring of Llama Stack
services.  Quotas are fully opt-in and have no effect unless explicitly
configured.
Notice that Quotas are fully opt-in and require authentication to be
enabled. The 'sqlite' is the only supported quota `type` at this time,
any other `type` will  be rejected. And the only supported `period` is
'day'. …
=> feat(quota): add server‑side per‑client request quotas (requires auth)

.github/workflows/integration-auth-tests.yml, docs/source/distributions/configuration.md, llama_stack/distribution/datatypes.py, llama_stack/distribution/server/auth.py, llama_stack/distribution/server/auth_providers.py, pyproject.toml, requirements.txt, tests/unit/server/test_auth.py, uv.lock
Kubernetes since 1.20 exposes a JWKS endpoint that we can use with our recent oauth2 recent implementation.
The CI test has been kept intact for validation.
=> chore: remove k8s auth in favor of k8s jwks endpoint

docs/source/distributions/configuration.md, llama_stack/distribution/server/auth_providers.py, tests/unit/server/test_auth.py
The cache_ttl config value is not in fact tied to the lifetime of any of
the keys, it represents the time interval between for our key cache
refresher.
=> chore: clarify cache_ttl to be key_recheck_period

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, docs/source/providers/vector_io/sqlite-vec.md, llama_stack/apis/tools/rag_tool.py, llama_stack/providers/inline/tool_runtime/rag/memory.py, llama_stack/providers/inline/vector_io/faiss/faiss.py, llama_stack/providers/inline/vector_io/sqlite_vec/sqlite_vec.py, llama_stack/providers/remote/vector_io/chroma/chroma.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, llama_stack/providers/remote/vector_io/pgvector/pgvector.py, llama_stack/providers/remote/vector_io/qdrant/qdrant.py, llama_stack/providers/remote/vector_io/weaviate/weaviate.py, llama_stack/providers/utils/memory/vector_store.py, tests/unit/providers/vector_io/test_qdrant.py, tests/unit/providers/vector_io/test_sqlite_vec.py
This PR introduces support for keyword based FTS5 search with BM25 relevance scoring. It makes changes to the existing EmbeddingIndex base class in order to support a search_mode and query_str parameter, that can be used for keyword based search implementations.
run 
```
pytest llama_stack/providers/tests/vector_io/test_sqlite_vec.py -v -s --tb=short --disable-warnings --asyncio-mode=auto
```
Output:
```
pytest llama_stack/providers/tests/vector_io/test_sqlite_vec.py -v -s --tb=short --disable-warnings --asyncio-mode=auto
/Users/vnarsing/miniconda3/envs/stack-client/lib/python3.10/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option …
```
=> feat(sqlite-vec): enable keyword search for sqlite-vec

.github/workflows/integration-auth-tests.yml
Not sure why it passed CI earlier...
Strange only 24 workflows run here https://github.com/meta-llama/llama-stack/pull/2216 so the test never ran...
=> fix: use proper service account for kube auth

llama_stack/cli/stack/run.py, llama_stack/ui/package.json
TSIA
`--enable-ui` to enable
`llama stack run dev --image-type conda --enable-ui`
`localhost:8322` shows UI
llama stack run dev --image-type conda
`localhost:8322` does not work
=> feat: start ui server in `llama stack run`

tests/integration/post_training/test_post_training.py, tests/integration/telemetry/test_telemetry.py
as title. trying release 0.2.8
=> fix: skip failing tests

tests/integration/agents/test_openai_responses.py, tests/integration/inference/test_openai_completion.py
The test depends on llama's tool calling ability. In the CI, we run with a small ollama model. 
The fix might be to check for either message or function_call because the model is flaky and we aren't really testing that behavior?
=> fix: disable test_responses_store

llama_stack/providers/inline/telemetry/meta_reference/sqlite_span_processor.py, llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
Run 
```
SQLITE_STORE_DIR=$(mktemp -d) \
pytest -s -v integration/tool_runtime/test_mcp.py --stack-config fireworks
```
no more annoying errors
=> fix(telemetry): get rid of annoying sqlite span export error

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/tools/tools.py, llama_stack/distribution/resolver.py, llama_stack/distribution/routers/tool_runtime.py, llama_stack/distribution/routing_tables/common.py, llama_stack/distribution/routing_tables/toolgroups.py, llama_stack/distribution/store/registry.py, llama_stack/providers/datatypes.py, llama_stack/providers/inline/tool_runtime/rag/memory.py, llama_stack/providers/remote/tool_runtime/bing_search/bing_search.py, llama_stack/providers/remote/tool_runtime/brave_search/brave_search.py, llama_stack/providers/remote/tool_runtime/model_context_protocol/model_context_protocol.py, llama_stack/providers/remote/tool_runtime/tavily_search/tavily_search.py, llama_stack/providers/remote/tool_runtime/wolfram_alpha/wolfram_alpha.py, tests/integration/tool_runtime/test_builtin_tools.py, tests/integration/tool_runtime/test_mcp.py, tests/integration/tool_runtime/test_registration.py, tests/unit/distribution/routers/test_routing_tables.py
When registering a MCP endpoint, we cannot list tools (like we used to) since the MCP endpoint may be behind an auth wall. Registration can happen much sooner (via run.yaml). 
Instead, we do listing only when the _user_ actually calls listing. Furthermore, we cache the list in-memory in the server. Currently, the cache is not invalidated -- we may want to periodically re-list for MCP servers. Note that they must call `list_tools` before calling `invoke_tool` -- we use this critically.
This will enable us to list MCP servers in run.yaml
Existing tests, updated tests accordingly.
=> fix(tools): do not index tools, only index toolgroups

llama_stack/cli/stack/_build.py
Fixes an issue where running `llama stack build --template ollama --image-type venv --run` fails with a TypeError when validating external providers directory paths.
The error occurs because `os.path.exists()` is called with `Path(None)` instead of converting it to a string first. This change ensures consistent handling of `None` values for `external_providers_dir` across both build and [run](https://github.com/meta-llama/llama-stack/blob/main/llama_stack/cli/stack/run.py#L134) commands by using `str()` conversion before path validation.  
```bash
INFERENCE_MODEL=llama3.2:3b uv run --with llama-stack llama stack build --template ollama --image-type venv --run
```
Command completes …
=> fix: handle None external_providers_dir in build with run arg

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/agents/openai_responses.py, llama_stack/providers/inline/agents/meta_reference/openai_responses.py, tests/unit/providers/agents/meta_reference/test_openai_responses.py, tests/verifications/openai_api/conftest.py, tests/verifications/openai_api/fixtures/test_cases/responses.yaml, tests/verifications/openai_api/test_responses.py
This adds initial streaming support to the Responses API. 
This PR makes sure that the _first_ inference call made to chat completions streams out. 
There's more to be done:
- tool call output tokens need to stream out when possible
- we need to loop through multiple rounds of inference and they all need to stream out.
Added a test. Executed as:
```
FIREWORKS_API_KEY=... \
pytest -s -v 'tests/verifications/openai_api/test_responses.py' \
--provider=stack:fireworks --model meta-llama/Llama-4-Scout-17B-16E-Instruct
```
Then, started a llama stack fireworks distro and tested against it like this:
```
OPENAI_API_KEY=blah \
pytest -s -v 'tests/verifications/openai_api/test_responses.py' \
--base-url http://localhost:8321/v1/openai/v1 \
--model meta-llama/Llama-4-Scout-17B-16E-Instruct 
```
=> feat(responses): add output_text delta events to responses

llama_stack/providers/utils/inference/openai_compat.py, tests/integration/inference/test_openai_completion.py
Fix a bug in openai_compat where choices are not indexed correctly.
Added a new test.
Rerun the failed inference_store tests:
llama stack run fireworks --image-type conda
pytest -s -v tests/integration/ --stack-config http://localhost:8321 -k 'test_inference_store' --text-model meta-llama/Llama-3.3-70B-Instruct --count 10
=> fix: chat completion with more than one choice

llama_stack/providers/inline/safety/prompt_guard/config.py, llama_stack/providers/inline/safety/prompt_guard/prompt_guard.py
Previously prompt guard was hard coded to require cuda which prevented it from being used on an instance without a cuda support.
This PR allows prompt guard to be configured to use either cpu or cuda.
Closes [#2133](https://github.com/meta-llama/llama-stack/issues/2133)
1) started stack configured with prompt guard  as follows on a system without a GPU
and validated prompt guard could be used through the APIs
2) validated on a system with a gpu (but without llama stack) that the python selecting between cpu and cuda support returned the right value when a cuda device was available.
3) ran the unit tests as per - https://github.com/meta-llama/llama-stack/blob/main/tests/unit/README.md
=> feat: add cpu/cuda config for prompt guard

llama_stack/providers/inline/agents/meta_reference/openai_responses.py, tests/unit/providers/agents/meta_reference/test_openai_responses.py
We must store the full (re-hydrated) input not just the original input in the Response object. Of course, this is not very space efficient and we should likely find a better storage scheme so that we can only store unique entries in the database and then re-hydrate them efficiently later. But that can be done safely later.
Closes https://github.com/meta-llama/llama-stack/issues/2299
Unit test
=> fix(responses): use input, not original_input when storing the Response

llama_stack/providers/remote/inference/sambanova/sambanova.py
Updates sambanova inference to use strict as false in json_schema structured output
pytest -s -v tests/integration/inference/test_text_inference.py --stack-config=sambanova --text-model=sambanova/Meta-Llama-3.3-70B-Instruct
=> fix(providers): update sambanova json schema mode

docs/source/distributions/building_distro.md, llama_stack/cli/stack/run.py, llama_stack/distribution/start_stack.sh, llama_stack/distribution/utils/exec.py
Removes the ability to run llama stack container images through the llama stack CLI
Closes #2110
Run:
```
llama stack run /path/to/run.yaml --image-type container
```
Expected outcome:
```
llama stack run: error: argument --image-type: invalid choice: 'container' (choose from 'conda', 'venv')
```
=> refactor: remove container from list of run image types

llama_stack/models/llama/llama3/tokenizer.py, llama_stack/models/llama/llama4/tokenizer.py, llama_stack/models/llama/tokenizer_utils.py, llama_stack/providers/registry/inference.py, llama_stack/providers/registry/tool_runtime.py, tests/unit/models/llama/test_tokenizer_utils.py
The `load_tiktoken_bpe()` function depends on blobfile to load tokenizer.model files. However, blobfile brings in pycryptodomex, which is primarily used for JWT signing in GCP - functionality we don’t require, as we always load tokenizers from local files. pycryptodomex implements its own cryptographic primitives, which are known to be problematic and insecure. While blobfile could potentially switch to the more secure PyCA cryptography library, the project appears inactive, so this transition may not happen soon. Fortunately, `load_tiktoken_bpe()` is a simple function that just reads a BPE file and returns a dictionary mapping byte sequences to their mergeable ranks. It’s straightforward enough for us to implement ourselves.
Run unit tests
=> chore: remove usage of load_tiktoken_bpe

tests/unit/providers/inference/test_remote_vllm.py
The remote-vllm `test_chat_completion_doesnt_block_event_loop` unit test was often failing for me on a Mac with a `httpx.ReadError`. I traced this back to the swap to the `AsyncOpenAI` client in the remote-vllm provider as where this started, and it looks like the async client needs a bit more accurate HTTP request handling from our mock server.
So, this fixes that unit test to send proper Content-Type and Content-Length headers which makes the `AsyncOpenAI` client happier on Macs.
All the test_remote_vllm.py unit tests consistently pass for me on a Mac now, without any flaking in the event loop one.
`pytest -s -v tests/unit/providers/inference/test_remote_vllm.py`
=> fix: remote-vllm event loop blocking unit test on Mac

llama_stack/ui/lib/client.ts, llama_stack/ui/package-lock.json, llama_stack/ui/package.json
1. remove openai dep
2. temporarily update llama-stack-client to stainless sync'd branch as the responses/inputitems API wasn't included in the last push. This will automatically be updated to the next version in the release.
npm run dev
go to any responses details page
=> fix: remove openai dep

docs/source/distributions/k8s/apply.sh, docs/source/distributions/k8s/ui-k8s.yaml.template, llama_stack/distribution/server/server.py, llama_stack/ui/app/api/v1/[...path]/route.ts, llama_stack/ui/lib/client.ts
- no more CORS middleware needed
llama stack run starter --image-type conda
npm run dev
verify UI works in browser
temporarily change ui-k8s.yaml.template to load from PR commit
sh ./apply.sh
$ kubectl get services
go to external_ip:8322 and play around with UI
=> chore(ui): use proxy server for backend API calls; simplified k8s deployment

docs/source/index.md, docs/source/openai/index.md
This adds some initial content documenting our OpenAI compatible APIs
- Responses, Chat Completions, Completions, and Models - along with instructions on how to use them via OpenAI or Llama Stack clients and some simple examples for each.
It's not a lot of content, but it's a start so that users have some idea how to get going as we continue to work on these APIs.
I generated the docs site locally and verified things render properly. I also ran each code example to ensure it works as expected. And, I asked my AI code assistant to do a quick spell-check and review of the docs and it didn't flag any obvious errors.
=> docs: Add OpenAI API compatibility page

llama_stack/distribution/server/auth_providers.py
I accidentally left a debug print in a PR that was merged. This removes that.
=> fix: remove debug print accidentally merged

llama_stack/distribution/build.py
This PR fixes a runtime import error caused by missing OpenTelemetry dependencies during `llama stack run`.
Specifically, the following imports fail if `opentelemetry-sdk` and `opentelemetry-exporter-otlp-proto-http` are not present in the environment:
```python
from opentelemetry import metrics, trace
from opentelemetry.exporter.otlp.proto.http.metric_exporter import OTLPMetricExporter
```
See [llama\_stack/providers/inline/telemetry/meta\_reference/telemetry.py#L10-L19](https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/inline/telemetry/meta_reference/telemetry.py#L10-L19)
This PR resolves the issue by adding both packages to the `SERVER_DEPENDENCIES` list:
```python
"opentelemetry-sdk",
"opentelemetry-exporter-otlp-proto-http",
```
```bash
llama stack build …
```
=> fix(server): Add missing OpenTelemetry dependencies to resolve telemetry import errors

llama_stack/distribution/library_client.py, llama_stack/providers/inline/agents/meta_reference/openai_responses.py, llama_stack/providers/remote/inference/ollama/ollama.py, tests/unit/providers/agents/meta_reference/test_openai_responses.py
The non-streaming version is just a small layer on top of the streaming version - just pluck off the final `response.completed` event and return that as the response! 
This PR also includes a couple other changes which I ended up making while working on it on a flight:
- changes to `ollama` so it does not pull embedding models unconditionally
- a small fix to library client to make the stream and non-stream cases a bit more symmetric
=> refactor: unify stream and non-stream impls for responses

llama_stack/providers/remote/vector_io/chroma/chroma.py
fixes the remote::chromaDB provider for vector_io by updating the method definition appropriately. 
Fixed impl to use score_threshold properly. 
```
docker run --rm \
--name chromadb \
-p 8800:8000 \
-v ~/chroma:/chroma/chroma \
-e IS_PERSISTENT=TRUE \
-e ANONYMIZED_TELEMETRY=FALSE \
chromadb/chroma:latest
CHROMADB_URL="http://localhost:8800" pytest -sv tests/integration/vector_io/test_vector_io.py --stack-config vector_io=remote::chromadb,inference=fireworks --embedding-model nomic-ai/nomic-embed-text-v1.5
```
=> fix: ChromaDB provider

llama_stack/providers/remote/vector_io/pgvector/pgvector.py
Fixes provider pgvector `query_vector` function for when the distance between the query embedding and an embedding within the vector db is 0 (identical vectors). Catches `ZeroDivisionError` and then sets `score` to infinity, which represent maximum similarity. 
Closes [#2381]
Checkout this PR
Execute this code and there will no longer be a `ZeroDivisionError` exception
```
base_url = "http://localhost:8321"
client = LlamaStackClient(base_url=base_url)
models = client.models.list()
embedding_model = (
em := next(m for m in models if m.model_type == "embedding")
).identifier
embedding_dimension = 384
_ = client.vector_dbs.register(
vector_db_id="foo_db",
embedding_model=embedding_model,
embedding_dimension=embedding_dimension, …
```
=> fix(pgvector): handle case where distance is 0 by setting score to infinity

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/vector_io/vector_io.py, llama_stack/distribution/resolver.py, llama_stack/distribution/routers/vector_io.py, llama_stack/providers/inline/vector_io/faiss/faiss.py, llama_stack/providers/inline/vector_io/sqlite_vec/sqlite_vec.py, llama_stack/providers/remote/vector_io/chroma/chroma.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, llama_stack/providers/remote/vector_io/qdrant/qdrant.py, llama_stack/providers/utils/memory/openai_vector_store_mixin.py
Extracts common OpenAI vector-store code into its own mixin so that all providers can share the same core logic. 
This also makes it easy for Llama Stack to support both vector-stores and Llama Stack APIs in the interim so that both share the same underlying vector-dbs. 
Each provider contains storage specific logic to `create / edit / delete / list` vector dbs while the plumbing logic is standardized in the common code. 
Ensured that this works well with both faiss and sqllite-vec. 
```
llama stack run starter
pytest -sv --stack-config http://localhost:8321 tests/integration/vector_io/test_openai_vector_stores.py --embedding-model all-MiniLM-L6-v2
```
=> feat: OpenAIVectorIOMixin for vector_stores common logic

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/vector_io/vector_io.py, llama_stack/distribution/routers/vector_io.py, llama_stack/providers/remote/vector_io/chroma/chroma.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, llama_stack/providers/remote/vector_io/qdrant/qdrant.py, llama_stack/providers/utils/memory/openai_vector_store_mixin.py
Setting defaults to be `| None` else they get marked as required params in open-api spec.
=> fix: set appropriate defaults for params

llama_stack/providers/remote/vector_io/weaviate/weaviate.py, tests/integration/vector_io/test_vector_io.py
Fixes provider weaviate `query_vector` function for when the distance between the query embedding and an embedding within the vector db is 0 (identical vectors). Catches `ZeroDivisionError` and then sets `score` to infinity, which represent maximum similarity. 
Closes [#2381]
Checkout this PR
Execute this code and there will no longer be a `ZeroDivisionError` exception
```
base_url = "http://localhost:8321"
client = LlamaStackClient(base_url=base_url)
models = client.models.list()
embedding_model = (
em := next(m for m in models if m.model_type == "embedding")
).identifier
embedding_dimension = 384
_ = client.vector_dbs.register(
vector_db_id="foo_db",
embedding_model=embedding_model,
embedding_dimension=embedding_dimension, …
```
=> fix(weaviate): handle case where distance is 0 by setting score to infinity

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/vector_io/vector_io.py, llama_stack/distribution/routers/vector_io.py, llama_stack/providers/remote/vector_io/chroma/chroma.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, llama_stack/providers/remote/vector_io/qdrant/qdrant.py, llama_stack/providers/utils/memory/openai_vector_store_mixin.py, tests/integration/vector_io/test_openai_vector_stores.py
Updated the `search` functionality return response to match openai. 
```
pytest -sv --stack-config=http://localhost:8321 tests/integration/vector_io/test_openai_vector_stores.py --embedding-model all-MiniLM-L6-v2
```
=> feat: update search for vector_stores

.github/workflows/integration-auth-tests.yml, docs/source/distributions/configuration.md, llama_stack/distribution/server/auth_providers.py, tests/unit/server/test_auth.py
Though the jwks endpoint does not usually require authentication, it does in a kubernetes cluster. While the cluster can be configured to allow anonymous access to that endpoint, this avoids the need to do so.
=> feat(auth): allow token to be provided for use against jwks endpoint

llama_stack/providers/remote/inference/ollama/ollama.py, llama_stack/providers/utils/inference/litellm_openai_mixin.py, llama_stack/providers/utils/inference/openai_compat.py, tests/integration/inference/test_openai_embeddings.py
This PR adds OpenAI compatibility for Ollama embeddings. Closes https://github.com/meta-llama/llama-stack/issues/2428
Summary of changes:
- `llama_stack/providers/remote/inference/ollama/ollama.py`
- Implements the OpenAI embeddings endpoint for Ollama, replacing the NotImplementedError with a full function that validates the model, prepares parameters, calls the client, encodes embedding data (optionally in base64), and returns a correctly structured response.
- Updates import statements to include the new embedding response utilities.
- `llama_stack/providers/utils/inference/litellm_openai_mixin.py`
- Refactors the embedding data encoding logic to use a new shared utility (`b64_encode_openai_embeddings_response`) instead of inline base64 encoding and packing logic.
- Cleans up imports …
=> chore: Add OpenAI compatibility for Ollama embeddings

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, docs/source/providers/vector_io/sqlite-vec.md, llama_stack/apis/tools/rag_tool.py, llama_stack/providers/inline/tool_runtime/rag/memory.py, llama_stack/providers/inline/vector_io/faiss/faiss.py, llama_stack/providers/inline/vector_io/sqlite_vec/sqlite_vec.py, llama_stack/providers/remote/vector_io/chroma/chroma.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, llama_stack/providers/remote/vector_io/pgvector/pgvector.py, llama_stack/providers/remote/vector_io/qdrant/qdrant.py, llama_stack/providers/remote/vector_io/weaviate/weaviate.py, llama_stack/providers/utils/memory/vector_store.py, tests/unit/providers/vector_io/test_sqlite_vec.py
Add support for hybrid search mode in SQLite-vec provider, which combines 
keyword and vector search for better results. The implementation:
- Adds hybrid search mode as a new option alongside vector and keyword search
- Implements query_hybrid method in SQLiteVecIndex that:
- First performs keyword search to get candidate matches
- Then applies vector similarity search on those candidates
- Updates documentation to reflect the new search mode
This change improves search quality by leveraging both semantic similarity 
and keyword matching, while maintaining backward compatibility with existing 
vector and keyword search modes.
```
pytest tests/unit/providers/vector_io/test_sqlite_vec.py -v -s --tb=short
/Users/vnarsing/miniconda3/envs/stack-client/lib/python3.10/site-packages/pytest_asynci …
```
=> feat: Implement hybrid search in SQLite-vec

docs/source/distributions/self_hosted_distro/nvidia.md, llama_stack/templates/nvidia/doc_template.md
The Nvidia distribution docs had some broken links when viewing the rendered docs site, where the deep links they were attempting into our code on GitHub weren't actually getting users to the intended destination.
This updates those links to use the `{repopath}` helper we use elsewhere to generate valid deep links into the Llama Stack repository.
I generated the site locally after this change and ensured the links now resolve to their intended destination.
=> fix: broken links on nvidia distro docs when rendered

README.md, install.sh
Our "run this line to get started" pipes into `sh`, but the default shell on Ubuntu (a common setup) is `dash`, which doesn't support `pipefail`:
```
dalton@ollama-test:~$ ls -l /usr/bin/sh
lrwxrwxrwx 1 root root 4 Mar 31  2024 /usr/bin/sh -> dash
```
```
$ curl -LsSf https://github.com/meta-llama/llama-stack/raw/main/install.sh | sh
sh: 8: set: Illegal option -o pipefail
``` 
Let's be explicit with `bash`? It covers Linux, WSL, macOS and I doubt anyone's trying to run Llama Stack on embedded systems :)
```
dalton@ollama-test:~/llama-stack$ cat install.sh | sh
This script must be run with bash
dalton@ollama-test:~/llama-stack$ cat install.sh | bash
❌ Docker or Podman is required. Install Docker: https://docs.docker.com/get-docker/ or Podman: https://podman.io/getting-started/installation …
```
=> fix: clarify bash requirement in install flow

llama_stack/distribution/routers/vector_io.py
When trying to `list` vector_stores , if we cannot retrieve one, log an error and return all the ones that are valid. 
```
pytest -sv --stack-config=http://localhost:8321 tests/integration/vector_io/test_openai_vector_stores.py  --embedding-model all-MiniLM-L6-v2
```
Also tested for `--stack-config fireworks`
=> fix: Do not throw when listing vector stores

.gitignore, llama_stack/ui/.gitignore, llama_stack/ui/app/logs/chat-completions/page.tsx, llama_stack/ui/app/logs/responses/page.tsx, llama_stack/ui/components/chat-completions/chat-completion-table.test.tsx, llama_stack/ui/components/chat-completions/chat-completions-table.tsx, llama_stack/ui/components/layout/logs-layout.tsx, llama_stack/ui/components/logs/logs-table-scroll.test.tsx, llama_stack/ui/components/logs/logs-table.test.tsx, llama_stack/ui/components/logs/logs-table.tsx, llama_stack/ui/components/responses/responses-table.test.tsx, llama_stack/ui/components/responses/responses-table.tsx, llama_stack/ui/e2e/logs-table-scroll.spec.ts, llama_stack/ui/hooks/useInfiniteScroll.ts, llama_stack/ui/hooks/usePagination.ts, llama_stack/ui/jest.config.ts, llama_stack/ui/jest.setup.ts, llama_stack/ui/lib/types.ts, llama_stack/ui/package.json, llama_stack/ui/playwright.config.ts
This commit adds infinite scroll pagination to the chat completions and responses tables.
1. Run unit tests: npm run test
2. Manual testing: Navigate to chat
completions/responses pages
3. Verify infinite scroll triggers when approaching
bottom
4. Added playwright tests: npm run test:e2e
=> feat(ui): add infinite scroll pagination to chat completions/responses logs table

llama_stack/distribution/routers/vector_io.py
Since we now support Pythong starting from 3.11, this is not needed anymore.
=> fix: remove asyncio.TimeoutError since Python update

llama_stack/providers/utils/scheduler.py, tests/unit/providers/utils/test_scheduler.py
Scheduler: cancel tasks on shutdown.
Otherwise the currently running tasks will never exit (before they
actually complete), which means the process can't be properly shut down
(only with SIGKILL).
Ideally, we let tasks know that they are about to shutdown and give them
some time to do so; but in the lack of the mechanism, it's better to
cancel than linger forever.
Start a long running task (e.g. torchtune or external kfp-provider training).
Ctr-C the process in TTY. Confirm it exits in reasonable time.
```
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
13:32:26.187 - INFO - Shutting down
13:32:26.187 - INFO - Shutting down DatasetsRoutingTable
13:32:26.187 - INFO - …
```
=> fix: cancel scheduler tasks on shutdown

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/vector_io/vector_io.py, llama_stack/distribution/routers/vector_io.py, llama_stack/providers/inline/vector_io/faiss/faiss.py, llama_stack/providers/inline/vector_io/sqlite_vec/sqlite_vec.py, llama_stack/providers/remote/vector_io/chroma/chroma.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, llama_stack/providers/remote/vector_io/qdrant/qdrant.py, llama_stack/providers/utils/memory/openai_vector_store_mixin.py, tests/integration/vector_io/test_openai_vector_stores.py
This adds the ability to list, retrieve, update, and delete Vector Store Files. It implements these new APIs for the faiss and sqlite-vec providers, since those are the two that also have the rest of the vector store files implementation.
Closes #2445 
There are a number of new integration tests added, which I ran for each provider as outlined below.
faiss (from ollama distro):
```
INFERENCE_MODEL="meta-llama/Llama-3.2-3B-Instruct" \
llama stack run llama_stack/templates/ollama/run.yaml
LLAMA_STACK_CONFIG=http://localhost:8321 \
pytest -sv tests/integration/vector_io/test_openai_vector_stores.py \
--embedding-model=all-MiniLM-L6-v2
```
sqlite-vec (from starter distro):
```
llama stack run llama_stack/templates/starter/run.yaml
LLAMA_STACK_CONFIG=http://localhost:8321 \
pytest -sv …
```
=> feat: Add missing Vector Store Files API surface

llama_stack/apis/vector_io/vector_io.py
See inline comment.
fixes test
_ test_openai_vector_store_search_with_high_score_filter[llama_stack_client-meta-llama/Llama-3.3-70B-Instruct-meta-llama/Llama-4-Scout-17B-16E-Instruct-all-MiniLM-L6-v2-None-None] _
llama-stack/llama_stack/distribution/library_client.py:98: in convert_to_pydantic
return TypeAdapter(annotation).validate_python(value)
.venv/lib/python3.10/site-packages/pydantic/type_adapter.py:421: in validate_python
return self.validator.validate_python(
E   pydantic_core._pydantic_core.ValidationError: 1 validation error for nullable[SearchRankingOptions]
E   score_threshold
E     Input should be less than or equal to 1 [type=less_than_equal, input_value=1.3458905661753127, input_type=float]
E       For further information visit …
=> feat: remove score_threshold constraint

llama_stack/cli/stack/_build.py
probably related to 3.11 upgrade
^^^^
File "/opt/homebrew/Caskroom/miniconda/base/envs/myenv/lib/python3.11/site-packages/termcolor/termcolor.py", line 147, in colored
text = fmt_str % (COLORS[color], text)
~~~~~~^^^^^^^
KeyError: 'light_blue'
=> fix: stack build

.github/workflows/integration-auth-tests.yml
Since we are using a very minimal run.yaml, there is not need to build.
=> chore: do not build on auth ci test

llama_stack/distribution/build_conda_env.sh
Fixes
```
Installing pip dependencies
error: Failed to parse: `scikit-learn pymongo pythainlp datasets torch sentencepiece requests aiohttp psycopg2-binary trl pillow pandas chardet nltk scipy ollama faiss-cpu pypdf tree_sitter langdetect openai matplotlib asyncpg peft redis autoevals mcp opentelemetry-exporter-otlp-proto-http sqlalchemy[asyncio] tqdm opentelemetry-sdk aiosqlite numpy chromadb-client emoji transformers aiosqlite fastapi fire httpx uvicorn opentelemetry-sdk opentelemetry-exporter-otlp-proto-http`
Caused by: Expected one of `@`, `(`, `<`, `=`, `>`, `~`, `!`, `;`, found `p`
scikit-learn pymongo pythainlp datasets torch sentencepiece requests aiohttp psycopg2-binary trl pillow pandas chardet nltk scipy ollama faiss-cpu pypdf tree_sitter langdetect openai matplotlib asyncpg …
```
=> chore: fix build script bug

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/vector_io/vector_io.py, llama_stack/distribution/routers/vector_io.py, llama_stack/providers/remote/vector_io/chroma/chroma.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, llama_stack/providers/remote/vector_io/qdrant/qdrant.py, llama_stack/providers/utils/memory/openai_vector_store_mixin.py, tests/integration/vector_io/test_openai_vector_stores.py
Add search_mode parameter (vector/keyword/hybrid) to openai_search_vector_store method. Fixes OpenAPI
code generation by using str instead of Literal type.
Closes: #2459
=> feat: Add search_mode support to OpenAI vector store API

llama_stack/providers/utils/inference/openai_compat.py, tests/integration/agents/test_openai_responses.py
closes #2522 
added integration test
LLAMA_STACK_CONFIG=http://localhost:8321 pytest -v tests/integration/agents/test_openai_responses.py --text-model "accounts/fireworks/models/llama-v3p3-70b-instruct"  -vv -k 'function_call'
=> fix: resume responses with tool call output

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/agents/openai_responses.py, llama_stack/providers/inline/agents/meta_reference/openai_responses.py, tests/unit/providers/agents/meta_reference/test_openai_responses.py
These are a couple of fixes to get an example LangChain app working with our OpenAI Responses API implementation.
The Responses API spec requires an annotations array in `output[*].content[*].annotations` and we were not providing one. So, this adds that as an empty list, even though we don't do anything to populate it yet. This prevents an error from client libraries like Langchain that expect this field to always exist, even if an empty list.
The other fix is `web_search_preview` is a valid name for the web search tool in the Responses API, but we only responded to `web_search` or `web_search_preview_2025_03_11`.
The existing Responses unit tests were expanded to test these cases, via:
```
pytest -sv tests/unit/providers/agents/meta_reference/test_openai_responses.py
```
The existing …
=> fix: annotations list and web_search_preview in Responses

llama_stack/apis/datasets/datasets.py, llama_stack/apis/files/files.py, llama_stack/apis/models/models.py, llama_stack/distribution/access_control/datatypes.py, llama_stack/distribution/datatypes.py, llama_stack/models/llama/datatypes.py, llama_stack/providers/datatypes.py, llama_stack/providers/inline/telemetry/meta_reference/config.py
We still had a few enum declared to behave like string as well as enum. Let's use StrEnum for those.
=> fix: finish conversion to StrEnum

llama_stack/distribution/datatypes.py, llama_stack/distribution/providers.py, llama_stack/distribution/resolver.py, llama_stack/providers/remote/vector_io/chroma/chroma.py, llama_stack/providers/remote/vector_io/chroma/config.py, llama_stack/providers/remote/vector_io/pgvector/config.py, llama_stack/templates/experimental-post-training/run.yaml, llama_stack/templates/meta-reference-gpu/meta_reference.py, llama_stack/templates/meta-reference-gpu/run-with-safety.yaml, llama_stack/templates/meta-reference-gpu/run.yaml, llama_stack/templates/open-benchmark/open_benchmark.py, llama_stack/templates/open-benchmark/run.yaml, llama_stack/templates/postgres-demo/postgres_demo.py, llama_stack/templates/postgres-demo/run.yaml, llama_stack/templates/remote-vllm/run-with-safety.yaml, llama_stack/templates/remote-vllm/run.yaml, llama_stack/templates/remote-vllm/vllm.py, llama_stack/templates/starter/run.yaml, llama_stack/templates/starter/starter.py
Some templates were still using the old environment variable substition syntax instead of the new one and were not getting substituted properly.
Also, some places didn't handle the new None vs old empty string ("") values that come from the conditional environment variable substitution.
This gets the starter and remote-vllm distributions starting again, and I tested various permutations of the starter as chroma and pgvector needed some adjustments to their config classes to handle the new possible `None` values. And, I had to tweak our `Provider` class to also handle `None` values, for cases where we disable providers in the starter config via environment variables.
This may not have caught everything that was missed, but I did grep around quite a bit to try and find anything lingering. …
=> fix: Some missed env variable changes from PR 2490

requirements.txt, uv.lock
This fixes CVE-2025-50181 and CVE-2025-50182.
Changes via:
```
uv sync --upgrade-package urllib3
uv export --frozen --no-hashes --no-emit-project --no-default-groups --output-file=requirements.txt
```
=> fix(security): Upgrade urllib3 to v2.5.0. Fixes CVE-2025-50181 and CVE-2025-50182

llama_stack/distribution/routing_tables/datasets.py
Fixes an error when inferring dataset provider_id with metadata
Closes #[2506](https://github.com/meta-llama/llama-stack/issues/2506)
=> fix: dataset metadata without provider_id

llama_stack/providers/inline/vector_io/faiss/faiss.py, llama_stack/providers/utils/kvstore/sqlite/sqlite.py
The error message was misleading as it appeared to be an Ollama connectivity issue, but actually occurred during faiss vector database initialization.
The issue was in the faiss vector database serialization logic in `llama_stack/providers/inline/vector_io/faiss/faiss.py`:
1. **Saving**: `faiss.serialize_index()` returns binary data (uint8 numpy array)
2. **Bug**: Code incorrectly used `np.savetxt()` which converts binary to text with scientific notation (e.g., `7.300000000000000000e+01`)
3. **Loading**: `np.loadtxt(buffer, dtype=np.uint8)` failed to parse scientific notation back to uint8
4. **Result**: Server crashed during initialization before reaching Ollama connectivity check
Replaced text-based serialization with proper binary serialization:
```
**After (fixed):**
```python …
=> fix: ValueError in faiss vector database serialization (resolves #2519)

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, docs/openapi_generator/pyopenapi/utility.py, llama_stack/apis/agents/agents.py, llama_stack/apis/agents/openai_responses.py, llama_stack/providers/inline/agents/meta_reference/agents.py, llama_stack/providers/inline/agents/meta_reference/openai_responses.py, llama_stack/providers/utils/responses/responses_store.py, tests/integration/agents/test_openai_responses.py
This PR creates a webmethod for deleting open AI responses, adds and implementation for it and makes an integration test for the OpenAI delete response method.
Ran the standard tests and the pre-commit hooks and the unit tests.
For this pr I made the routes and implementation based on the current get and create methods. The unit tests were not able to handle this test due to the mock interface in use, which did not allow for effective CRUD to be tested. I instead created an integration test to match the existing ones in the test_openai_responses.
=> feat: Add webmethod for deleting openai responses

llama_stack/providers/remote/inference/ollama/ollama.py, llama_stack/providers/utils/inference/prompt_adapter.py, tests/verifications/openai_api/fixtures/test_cases/responses.yaml
Ollama does not support remote images. Only local file paths OR base64 inputs are supported. This PR ensures that the Stack downloads remote images and passes the base64 down to the inference engine.
Added a test cases for Responses and ran it for both `fireworks` and `ollama` providers.
=> fix(ollama): Download remote image URLs for Ollama

docs/source/distributions/configuration.md
Current text did not match section in example Ollama distro: https://llama-stack.readthedocs.io/en/latest/distributions/configuration.html
=> docs: fixed incorrect API list item

docs/source/providers/external.md, docs/source/providers/index.md
The external providers guide can now be accessed directly from the sidebar
Build locally to test the changes
=> docs: update external provider guide and navigation

docs/source/concepts/apis.md
Clarifies that non-Llama models can be trained via the Post Training API
Build docs locally
=> docs: specify the ability to train non-Llama models

tests/integration/README.md, tests/integration/fixtures/common.py
Add support for `server:<config>` format in `--stack-config` option to enable seamless one-step integration testing. This eliminates the need to manually start servers in separate terminals before running tests.
- **Auto-start server**: Automatically launches `llama stack run <config>` if target port is available
- **Smart reuse**: Reuses existing server if port is already occupied  
- **Health check polling**: Waits up to 2 minutes for server readiness via `/v1/health` endpoint
- **Custom port support**: Use `server:<config>:<port>` for non-default ports
- **Clean output**: Server runs quietly in background without cluttering test output
- **Backward compatibility**: All existing `--stack-config` formats continue to work
```bash
pytest tests/integration/inference/ …
```
=> test: Add one-step integration testing with server auto-start

llama_stack/providers/utils/vector_io/chunk_utils.py
Set parameter `usedforsecurity=False` when calling hashlib.md5 in order to fix rag_tool.insert on FIPS clusters
Closes #2571
=> fix: Set parameter usedforsecurity=False when calling hashlib.md5 in order to fix rag_tool.insert on FIPS clusters

docs/getting_started.ipynb, docs/getting_started_llama4.ipynb, docs/getting_started_llama_api.ipynb, docs/quick_start.ipynb, docs/source/getting_started/index.md
- Adding a notebook equivalent of the [getting_started/index.md#Quickstart guide](https://github.com/meta-llama/llama-stack/blob/main/docs/source/getting_started/index.md).
**Note:** works locally, but I am encountering issues when attempting to run through the notebook on Google Colab. Specifically, on the last step to run the demo, the `knowledge_search` tool doesn't seem to be called i.e.,:
```
rag_tool> Ingesting document: https://www.paulgraham.com/greatwork.html
prompt> How do you do great work?
inference> I don't have personal experiences or emotions, but I was trained on a large corpus of text data and use various techniques such as natural language processing (NLP) and machine learning algorithms to generate human-like responses.
```
I would expect to get something like:
``` …
```
=> docs: Add quick_start.ipynb notebook equivalent of index.md Quickstart guide

llama_stack/providers/registry/agents.py
The agent depends on utils.tools.mcp.
Closes: https://github.com/meta-llama/llama-stack/issues/2576
=> fix: add mcp dependency to agent provider

llama_stack/providers/utils/memory/vector_store.py, llama_stack/providers/utils/vector_io/chunk_utils.py, tests/unit/providers/vector_io/test_chunk_utils.py
This handles an edge case for `generate_chunk_id` if the concatenation of the `document_id` and `chunk_text` combination are not unique. Adding the window location ensures uniqueness.
Added unit test
=> chore: Updating chunk id generation to ensure uniqueness

llama_stack/cli/stack/_build.py
Rather than pointing to a dir in `llama_stack/templates` (the repo directory)
we should point to `$BUILD_DIR/IMAGE_NAME-run.yaml` (`~/.llama/distributions/IMAGE_NAME/IMAGE_NAME-run.yaml`)
currently we are printing:
```
You can find the newly-built template here: /Users/charliedoern/projects/Documents/llama-stack/llama_stack/templates/starter/run.yaml
You can run the new Llama Stack distro via: llama stack run /Users/charliedoern/projects/Documents/llama-stack/llama_stack/templates/starter/run.yaml --image-type venv
```
but should be printing things like:
```
You can find the newly-built template here: /Users/charliedoern/.llama/distributions/starter/starter-run.yaml
You can run the new Llama Stack distro via: llama stack run /Users/charliedoern/.llama/distributions/starter/starter-run.yaml …
```
=> fix: print proper template path upon build

llama_stack/cli/stack/run.py, llama_stack/distribution/server/server.py
currently when a template is used, we still use `--config`.
`server.py` has a dedicated `--template` flag and logic, use that instead
=> fix: use `--template` flag for server

docs/source/providers/vector_io/inline_milvus.md, llama_stack/providers/inline/vector_io/milvus/config.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, pyproject.toml, tests/unit/providers/vector_io/test_vector_io_openai_vector_stores.py, uv.lock
- Enabling Unit tests for Milvus to start to test OpenAI compatibility and fixing a few bugs. 
- Also fixed an inconsistency in the Milvus config between remote and inline. 
- Added pymilvus to extras for testing in CI
I'm going to refactor this later to include the other inline providers so that we can catch issues sooner. 
I have another PR where I've been testing to find other bugs in the implementation (and required changes drafted here: https://github.com/meta-llama/llama-stack/pull/2617).
=> chore: Adding unit tests for Milvus and OpenAI compatibility

.github/actions/setup-ollama/action.yml, .github/workflows/integration-tests.yml, llama_stack/distribution/stack.py, llama_stack/providers/inline/safety/llama_guard/llama_guard.py, llama_stack/providers/remote/inference/anthropic/models.py, llama_stack/providers/remote/inference/bedrock/models.py, llama_stack/providers/remote/inference/cerebras/models.py, llama_stack/providers/remote/inference/databricks/databricks.py, llama_stack/providers/remote/inference/fireworks/models.py, llama_stack/providers/remote/inference/gemini/models.py, llama_stack/providers/remote/inference/groq/models.py, llama_stack/providers/remote/inference/nvidia/models.py, llama_stack/providers/remote/inference/openai/models.py, llama_stack/providers/remote/inference/runpod/runpod.py, llama_stack/providers/remote/inference/sambanova/models.py, llama_stack/providers/remote/inference/together/models.py, llama_stack/providers/utils/inference/model_registry.py, llama_stack/templates/starter/run.yaml, llama_stack/templates/starter/starter.py, tests/Containerfile
We are now testing the safety capability with the starter image. This
includes a few changes:
* Enable the safety integration test
* Relax the shield model requirements from llama-guard to make it work
with llama-guard3:8b coming from Ollama
* Expose a shield for each inference provider in the starter distro. The
shield will only be registered if the provider is enabled.
Closes: https://github.com/meta-llama/llama-stack/issues/2528
=> ci: test safety with starter

pyproject.toml, requirements.txt, uv.lock
`python-jose` recommends using the `cryptography` backend in their installation docs: https://github.com/mpdavis/python-jose?tab=readme-ov-file#cryptographic-backends
This PR modifies the LLS dependencies to use this instead of the current `native-python`
=> build: replace "python-jose" with "python-jose[cryptography]"

llama_stack/distribution/server/server.py
currently when logging the run yaml, if there are path objects in the object they are represented as:
```
external_providers_dir: !!python/object/apply:pathlib.PosixPath
- '~'
- .llama
- providers.d
```
now, with a config.model_dump(mode="json"), it works properly
```
external_providers_dir: ~/.llama/providers.d
```
=> fix: properly represent paths in server logs

.pre-commit-config.yaml, llama_stack/distribution/utils/context.py, llama_stack/providers/utils/telemetry/trace_protocol.py
While investigating the `uv.lock` changes made in https://github.com/meta-llama/llama-stack/pull/2695 I noticed several of the pre-commit hook versions were out of date
This PR updates them and fixes some new `ruff` errors
=> chore: update pre-commit hook versions

.pre-commit-config.yaml
the project already had some config setup for https://pre-commit.ci/
this commit adds additional explicit fields
Closes #2711
**IMPORTANT:** A project maintainer must add `pre-commit.ci` to this repo for this to work - this can be done via https://pre-commit.ci/
=> ci: add config for pre-commit.ci

docs/source/providers/vector_io/inline_milvus.md, docs/source/providers/vector_io/inline_sqlite-vec.md, docs/source/providers/vector_io/inline_sqlite_vec.md, llama_stack/providers/inline/vector_io/milvus/config.py, llama_stack/providers/inline/vector_io/sqlite_vec/config.py, llama_stack/providers/inline/vector_io/sqlite_vec/sqlite_vec.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, llama_stack/templates/open-benchmark/run.yaml, llama_stack/templates/starter/run.yaml, tests/unit/providers/vector_io/conftest.py, tests/unit/providers/vector_io/test_sqlite_vec.py, tests/unit/providers/vector_io/test_vector_io_openai_vector_stores.py
This PR refactors and the VectorIO backend logic for `sqlite-vec` and adds unit tests and fixtures to make it easy to test both `sqlite-vec` and `milvus`.
Key changes:
- `sqlite-vec` migrated to `kvstore` registry
- added in-memory cache for sqlite-vec to be consistent with `milvus`
- default fixtures moved to `conftest.py` 
- removed redundant tests from sqlite`-vec`
- made `test_vector_io_openai_vector_stores.py` more easily extensible 
Unit tests added testing inline providers.
=> chore: Adding unit tests for OpenAI vector stores and migrating SQLite-vec registry to kvstore

llama_stack/providers/remote/inference/groq/groq.py, llama_stack/providers/remote/inference/openai/openai.py, llama_stack/providers/remote/inference/together/together.py, pyproject.toml, tests/unit/providers/inference/test_inference_client_caching.py, uv.lock
Some of our inference providers support passthrough authentication via `x-llamastack-provider-data` header values. This fixes the providers that support passthrough auth to not cache their clients to the backend providers (mostly OpenAI client instances) so that the client connecting to Llama Stack has to provide those auth values on each and every request.
I added some unit tests to ensure we're not caching clients across requests for all the fixed providers in this PR.
```
uv run pytest -sv tests/unit/providers/inference/test_inference_client_caching.py
```
I also ran some of our OpenAI compatible API integration tests for each of the changed providers, just to ensure they still work. Note that these providers don't actually pass all these tests (for unrelated reasons due to quirks of …
=> fix: Don't cache clients for passthrough auth providers

pyproject.toml, tests/unit/conftest.py, tests/unit/providers/inference/test_remote_vllm.py, tests/unit/rag/test_vector_store.py, uv.lock
this blocks network access for all `tests/unit/` tests. `tests/integration/` are untouched.
it also introduces an `allow_network` marker to explicitly allow network access.
`./scripts/unit-tests.sh`
=> chore: block network access from unit tests

.github/ISSUE_TEMPLATE/tech-debt.yml
Adds a template for technical debt. Currently we don't support blank issues so everything filed has to a bug or a feature.
This would allow maintainers as well as community members to track things we might want to merge to expose the functionality but should be addressed later. Such things can also be "good first issues" for new contributors.
Inelegant code solutions, tests we intend to temporarily disable but would like to restore, CI hacks around infrastructure or installation, etc.
=> chore: add issue template for technical debt

docs/source/providers/vector_io/remote_milvus.md, llama_stack/providers/remote/vector_io/milvus/config.py, llama_stack/providers/remote/vector_io/milvus/milvus.py, tests/unit/providers/vector_io/remote/test_milvus.py
This PR adds the keyword search implementation for Milvus. Along with the implementation for remote Milvus, the tests require us to start a Milvus containers locally.
In order to verify the implementation, run:
```
pytest tests/unit/providers/vector_io/remote/test_milvus.py -v -s --tb=short --disable-warnings --asyncio-mode=auto
```
You can also test the changes using the below script:
```
#!/usr/bin/env python3
import asyncio
import os
import uuid
from typing import List
from llama_stack_client import (
Agent, 
AgentEventLogger, 
LlamaStackClient, 
RAGDocument
)
class MilvusRAGDemo:
def __init__(self, base_url: str = "http://localhost:8321/"):
self.client = LlamaStackClient(base_url=base_url)
self.vector_db_id = f"milvus_rag_demo_{uuid.uuid4().hex[:8]}"
self.model_id = None …
```
=> feat: Implement keyword search in milvus

llama_stack/distribution/configure.py, llama_stack/distribution/server/server.py, llama_stack/distribution/stack.py, tests/unit/cli/test_stack_config.py
https://github.com/meta-llama/llama-stack/pull/2490 introduced a new function for type conversion of strings.
However, a side effect of this is that it will cast any string that can be cast to an integer if possible, which for something like `image_name` is not desired as we only accept strings for this field in the `StackRunConfig`
This PR introduces logic to ensure that `image_name` remains a string 
Closes #2749
You can run the original step to reproduce from the bug to verify this manually
```bash
OPENAI_API_KEY=bogus llama stack build --image-type venv --image-name 2745 --providers inference=remote::openai --run
```
I have also added an additional unit test to prevent any future regression here
=> fix: stop image_name from being cast to an integer

llama_stack/providers/remote/inference/llama_openai_compat/llama.py, llama_stack/providers/remote/inference/openai/openai.py, llama_stack/providers/utils/inference/litellm_openai_mixin.py, pyproject.toml, requirements.txt, uv.lock
The purpose of this task is to create a solution that can automatically detect when new models are added, deprecated, or removed by OpenAI and Llama API providers, and automatically update the list of supported models in LLamaStack.
This feature is vitally important in order to avoid missing new models and editing the entries manually hence I created automation allowing users to dynamically register:
- any models from OpenAI provider available at 
[https://api.openai.com/v1/models](https://api.openai.com/v1/models) that are not in [https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/remote/inference/openai/models.py](https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/remote/inference/openai/models.py)
- any models from Llama API provider …
=> feat: create dynamic model registration for OpenAI and Llama compat remote inference providers

tests/unit/models/test_prompt_adapter.py
This PR replaces unittest with pytest.
Part of https://github.com/meta-llama/llama-stack/issues/2680
cc @leseb
=> chore(test): migrate unit tests from unittest to pytest for prompt adapter

.pre-commit-config.yaml
use pre-commit to block addition of new asyncio marks, since we configure pytest with async-mode=auto, see https://github.com/meta-llama/llama-stack/pull/2730
=> chore: block asyncio marks in tests

tests/integration/post_training/test_post_training.py, tests/unit/models/test_prompt_adapter.py, tests/unit/providers/vector_io/remote/test_milvus.py, tests/unit/rag/test_rag_query.py
some async test markers are in the codebase causing pre-commit to fail due to #2744
remove these pytest fixtures
pre-commit passes
=> fix: remove async test markers (fix pre-commit)

tests/unit/providers/nvidia/test_datastore.py
This PR replaces unittest with pytest.
Part of https://github.com/meta-llama/llama-stack/issues/2680
cc @leseb
=> chore(test): migrate unit tests from unittest to pytest for nvidia datastore

tests/unit/models/test_system_prompts.py
This PR replaces unittest with pytest.
Part of https://github.com/meta-llama/llama-stack/issues/2680
cc @leseb
=> chore(test): migrate unit tests from unittest to pytest for system prompt

docs/source/getting_started/quickstart.md
'build' command didn't take into account ENABLE flags for starter distro
for some reason, I was having issues with HuggingFace access for the embedding model, so added a tip for that as well
Closes #2779
I ran the described steps manually, but it would be nice if someone else could try it and verify this still works
We might consider having some CI job ensure the QSG remains functional - it's not a great experience for new users if they try Llama Stack for the first time and it doesn't work as we describe
=> docs: fix steps in the Quick Start Guide

llama_stack/distribution/server/server.py
When we call `construct_stack()`, providers are instantiated and `initialize()` is called. This call can end up doing _anything_ at all -- specifically, providers are free to create long running background tasks as part of this. If we wrapped this within a `asyncio.run()` as in the current code, these tasks get canceled when the stack construction finishes. This is not correct. The PR addresses the issue by creating a persistent event loop which is used for both the stack as well as for running the uvicorn server. In other words, the lifetime of the providers (and downstream async code) is now the same as the lifetime of the uvicorn server.
This should not affect any current code since we don't have background tasks created right now. However, …
=> feat(server): construct the stack in a persistent event loop

docs/source/providers/inference/remote_ollama.md, llama_stack/apis/inference/inference.py, llama_stack/distribution/library_client.py, llama_stack/distribution/routing_tables/models.py, llama_stack/providers/remote/inference/ollama/config.py, llama_stack/providers/remote/inference/ollama/ollama.py
For self-hosted providers like Ollama (or vLLM), the backing server is running a set of models. That server should be treated as the source of truth and the Stack registry should just be a cache for those models. Of course, in production environments, you may not want this (because you know what model you are running statically) hence there's a config boolean to control this behavior.
_This is part of a series of PRs aimed at removing the requirement of needing to set `INFERENCE_MODEL` env variables for running Llama Stack server._
Copy and modify the starter.yaml template / config and enable `refresh_models: true, refresh_models_interval: 10` for the ollama provider. Then, run:
```
LLAMA_STACK_LOGGING=all=debug \
ENABLE_OLLAMA=ollama uv run llama stack run --image-type venv …
```
=> feat(ollama): periodically refresh models

docs/source/providers/inference/remote_vllm.md, llama_stack/apis/inference/inference.py, llama_stack/distribution/routing_tables/models.py, llama_stack/providers/remote/inference/ollama/ollama.py, llama_stack/providers/remote/inference/vllm/config.py, llama_stack/providers/remote/inference/vllm/vllm.py, llama_stack/templates/starter/run.yaml
Just like #2805 but for vLLM.
We also make VLLM_URL env variable optional (not required) -- if not specified, the provider silently sits idle and yells eventually if someone tries to call a completion on it. This is done so as to allow this provider to be present in the `starter` distribution.
Set up vLLM, copy the starter template and set `{ refresh_models: true, refresh_models_interval: 10 }` for the vllm provider and then run: 
```
ENABLE_VLLM=vllm VLLM_URL=http://localhost:8000/v1 \
uv run llama stack run --image-type venv /tmp/starter.yaml
```
Verify that `llama-stack-client models list` brings up the model correctly from vLLM.
=> feat(vllm): periodically refresh models

.github/workflows/integration-tests.yml, .github/workflows/integration-vector-io-tests.yml, .github/workflows/providers-build.yml, llama_stack/templates/ci-tests/__init__.py, llama_stack/templates/ci-tests/build.yaml, llama_stack/templates/ci-tests/ci_tests.py, llama_stack/templates/ci-tests/run.yaml
We need to fork off starter and a "distro for tests". The former is intended for the developer (or new user), whereas the latter for running CI. Specifically (right now), we would like to not have post-training in starter since it is heavy and causes a delay in server startup.
=> feat(ci): add a ci-tests distro

llama_stack/providers/inline/files/localfs/__init__.py, llama_stack/providers/inline/files/localfs/files.py, tests/integration/files/test_files.py, tests/unit/files/test_files.py
Supports authentication for LocalFS Files provider.
closes https://github.com/meta-llama/llama-stack/issues/2760
CI. added tests.
=> feat: enable auth for LocalFS Files Provider

.github/workflows/coverage-badge.yml
The workflow that automatically creates a PR to update the Coverage Badge fails as the `GITHUB_TOKEN` doesn't have write permissions.
As opposed to providing write permissions to the token, we can provide the permissions for just this workflow with this PR.
=> fix: Add permissions for pull request creation in coverage-badge workflow

llama_stack/apis/vector_dbs/vector_dbs.py
This PR add `provider_id` field to `VectorDBInput` class.
fixes https://github.com/meta-llama/llama-stack/issues/2819
=> fix(vectordb): VectorDBInput has no provider_id

tests/unit/providers/agent/test_get_raw_document_text.py
The pre-commit workflow was failing in the main branch and removing `@pytest.mark.asyncio `from `test_get_raw_document_text.py` fixed that.
=> fix: remove @pytest.mark.asyncio from test_get_raw_document_text.py

tests/integration/telemetry/test_telemetry.py
example error: https://github.com/meta-llama/llama-stack/actions/runs/16368394907/job/46250869773
=> test: skip flaky telemetry tests

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/vector_io/vector_io.py, llama_stack/providers/utils/memory/openai_vector_store_mixin.py
chore: Making name optional in openai_create_vector_store
CI and unit tests
=> chore: Making name optional in openai_create_vector_store

.github/workflows/integration-tests.yml, .github/workflows/integration-vector-io-tests.yml, llama_stack/distribution/routers/datasets.py, llama_stack/distribution/routers/eval_scoring.py, llama_stack/distribution/routers/inference.py, llama_stack/distribution/routers/safety.py, llama_stack/distribution/routers/tool_runtime.py, llama_stack/distribution/routers/vector_io.py, llama_stack/distribution/routing_tables/common.py, llama_stack/distribution/routing_tables/models.py, llama_stack/distribution/routing_tables/toolgroups.py, llama_stack/distribution/routing_tables/vector_dbs.py, llama_stack/providers/datatypes.py, llama_stack/providers/utils/inference/embedding_mixin.py, tests/unit/distribution/routers/test_routing_tables.py
This PR updates model registration and lookup behavior to be slightly more general / flexible. See https://github.com/meta-llama/llama-stack/issues/2843 for more details.
Note that this change is backwards compatible given the design of the `lookup_model()` method.
Added unit tests
=> feat(registry): more flexible model lookup

llama_stack/cli/utils.py, llama_stack/distribution/server/server.py
https://github.com/meta-llama/llama-stack/pull/2716/ broke commands like:
```
python -m llama_stack.distribution.server.server --config
llama_stack/templates/starter/run.yaml
```
And will fail with:
```
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/leseb/Documents/AI/llama-stack/llama_stack/distribution/server/server.py", line 626, in <module>
main()
File "/Users/leseb/Documents/AI/llama-stack/llama_stack/distribution/server/server.py", line 402, in main
config_file = resolve_config_or_template(args.config, Mode.RUN)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/leseb/Documents/AI/llama-stack/llama_stack/distribution/utils/config_resolution.py", line 43, in …
```
=> fix: honour deprecation of --config and --template

llama_stack/apis/tools/rag_tool.py, tests/unit/rag/test_rag_query.py
I noticed a few issues with my implementation of the search mode validation for RagQuery. 
This PR replaces the check for search mode in RagQuery with a Literal. 
There were issues before with
```
TypeError: Object of type RAGSearchMode is not JSON serializable
```
When using 
```
query_config = RAGQueryConfig(max_chunks=6, mode="vector").model_dump()
```
It also fixes the fact that despite user input "vector" was always the used search mode.
Verify that a chosen search mode works when using Rag Query or use below agent config:
```
agent = Agent(
client,
model=model_id,
instructions="You are a helpful assistant",
tools=[
{
"name": "builtin::rag/knowledge_search",
"args": {
"vector_db_ids": [vector_db_id],
"query_config": {
"mode": "keyword",
"max_chunks": 6
}
},
}
],
)
```
Running Unit …
=> fix: search mode validation for rag query

tests/unit/server/test_access_control.py
I fixed test_access_policy() function providing provider_model_id in each register model endpoint to pass assertions.
Initially I faced this issue:
```
tests/unit/server/test_quota.py::test_authenticated_quota_allows_up_to_limit
tests/unit/server/test_quota.py::test_authenticated_quota_blocks_after_limit
tests/unit/server/test_quota.py::test_anonymous_quota_allows_up_to_limit
tests/unit/server/test_quota.py::test_anonymous_quota_blocks_after_limit
/Users/iamiller/GitHub/llama-stack/.venv/lib/python3.12/site-packages/aiosqlite/core.py:105: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
result = function()
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html …
```
=> fix: fixed test_access_control.py unit test

llama_stack/distribution/build_container.sh
- Use printf to to escape special characters (e.g. < > )
- Apply escaping to pip_dependencies and special_pip_deps
Resolves shell interpretation of >= operators as redirections that were
causing build failing to respect versions and unexpected file creation
in /app directory.
Closes: #2866
Manually tested, will also be tested by existing CI
=> fix: prevent shell redirection issues with pip dependencies

docs/source/providers/vector_io/inline_chromadb.md, docs/source/providers/vector_io/remote_chromadb.md, llama_stack/providers/inline/vector_io/chroma/__init__.py, llama_stack/providers/inline/vector_io/chroma/config.py, llama_stack/providers/remote/vector_io/chroma/__init__.py, llama_stack/providers/remote/vector_io/chroma/chroma.py, llama_stack/providers/remote/vector_io/chroma/config.py, llama_stack/templates/ci-tests/run.yaml, llama_stack/templates/open-benchmark/open_benchmark.py, llama_stack/templates/open-benchmark/run.yaml, llama_stack/templates/postgres-demo/postgres_demo.py, llama_stack/templates/postgres-demo/run.yaml, llama_stack/templates/starter/run.yaml, llama_stack/templates/starter/starter.py, pyproject.toml, tests/integration/vector_io/test_openai_vector_stores.py, tests/unit/providers/vector_io/conftest.py, uv.lock
This PR implements the openai compatible endpoints for chromadb
Closes #2462 
Ran ollama llama stack server and ran the command
`pytest -sv --stack-config=http://localhost:8321 tests/integration/vector_io/test_openai_vector_stores.py  --embedding-model all-MiniLM-L6-v2`
8 failed, 27 passed, 8 skipped, 1 xfailed
The failed ones are regarding files api
=> chore: Added openai compatible vector io endpoints for chromadb

tests/unit/providers/nvidia/test_safety.py
This PR replaces unittest with pytest.
Part of https://github.com/meta-llama/llama-stack/issues/2680
cc @leseb
=> chore(test): migrate unit tests from unittest to pytest nvidia test safety

llama_stack/distribution/inspect.py, llama_stack/distribution/library_client.py, llama_stack/distribution/server/routes.py, llama_stack/distribution/server/server.py
This will be used to support API access control, i.e. Webmethod would have a `required_scope` attribute, and we need access to that in the middleware.
=> chore: return webmethod from find_matching_route

llama_stack/log.py, llama_stack/providers/inline/telemetry/meta_reference/console_span_processor.py
currently `print` is being used with custom formatting to achieve telemetry output in the console_span_processor
This causes telemetry not to show up in log files when using `LLAMA_STACK_LOG_FILE`. During testing it looks like telemetry is not being captured when it is
switch to using Rich formatting with the logger and then strip the formatting off when a log file is being used so the formatting looks normal
before:
console:
log file (no telemetry):
```
2025-07-21 16:01:32,481 llama_stack.providers.remote.inference.ollama.ollama:117 inference: checking connectivity to Ollama at `http://localhost:11434`...
2025-07-21 16:01:34,779 opentelemetry.trace:537 uncategorized: Overriding of current TracerProvider is not allowed
2025-07-21 16:01:35,083 __main__:587 server: Listening on ['::', …
```
=> fix: use logger for console telemetry

docs/source/distributions/configuration.md, llama_stack/apis/telemetry/telemetry.py, llama_stack/distribution/request_headers.py, llama_stack/distribution/server/auth.py, llama_stack/distribution/server/server.py, llama_stack/schema_utils.py, tests/unit/server/test_auth.py
- Added ability to specify `required_scope` when declaring an API. This is part of the `@webmethod` decorator.
- If auth is enabled, a user can access an API only if `user.attributes['scope']` includes the `required_scope`
- We add `required_scope='telemetry.read'` to the telemetry read APIs.
CI with added tests
1. Enable server.auth with github token
2. Observe `client.telemetry.query_traces()` returns 403
=> feat(auth): API access control

.github/workflows/test-external-provider-module.yml, .github/workflows/test-external.yml
currently the external provider tests don't upload log files as artifacts nor do they use LLAMA_STACK_LOG_FILE. align with the other integration tests
logs should be present in the two tests on this PR
=> test: upload logs for external provider tests

llama_stack/providers/remote/inference/llama_openai_compat/llama.py
litellm uses "meta_llama" for the provider name, see https://docs.litellm.ai/docs/providers/meta_llama ad https://github.com/BerriAI/litellm/blob/main/litellm/__init__.py#L833
=> fix: litellm_provider_name for llama-api

.github/workflows/unit-tests.yml, scripts/unit-tests.sh, tests/unit/distribution/test_distribution.py, tests/unit/providers/utils/test_model_registry.py, tests/unit/server/test_auth_github.py
- Added `set -e` to the beginning of the unit test script to ensure the script exits on failure and correctly fails the CI when tests do not pass.
- Fixed all unit tests that were silently failing in the CI.
- Fixed Python 3.13 unit test CI failing silently.
Closes #2877 
- **Previously:** Unit tests passing in CI eventhough it failed 11 tests -> [CI-run](https://github.com/ChristianZaccaria/llama-stack/actions/runs/16563146236/job/46836815012#step:4:2097)
- **Made the fix. Now, ensuring CI fails as expected on test failures:** Unit tests failing in CI with 1 failed test -> [CI-run](https://github.com/ChristianZaccaria/llama-stack/actions/runs/16564840859/job/46842342477#step:4:1506)
- This PR shows the CI passing and all unit tests passing.
=> fix: Fix unit tests CI and failing tests

llama_stack/providers/utils/inference/litellm_openai_mixin.py
This enhancement allows inference providers using LiteLLMOpenAIMixin to validate model availability against LiteLLM's official provider model listings, improving reliability and user experience when working with different AI service providers.
- Add litellm_provider_name parameter to LiteLLMOpenAIMixin constructor
- Add check_model_availability method to LiteLLMOpenAIMixin using litellm.models_by_provider
- Update Gemini, Groq, and SambaNova inference adapters to pass litellm_provider_name
standard CI.
=> feat: implement dynamic model detection support for inference providers using litellm

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/inference/inference.py, tests/unit/providers/utils/inference/test_openai_compat.py
**What:**
- Added OpenAIChatCompletionTextOnlyMessageContent type for text-only content validation
- Modified OpenAISystemMessageParam, OpenAIAssistantMessageParam, OpenAIDeveloperMessageParam, and OpenAIToolMessageParam to use text-only content type instead of mixed content
- OpenAIUserMessageParam unchanged - still accepts both text and images
- Updated OpenAPI spec files to reflect text-only content restrictions in schemas
closes #2894 
**Why:**
- Enforces OpenAI API compatibility by restricting image content to user messages only
- Prevents API misuse where images might be sent in message types that don't support them
- Aligns with OpenAI's actual API behavior where only user messages can contain multimodal content
- Improves type safety and validation at the API boundary
**Test …
=> fix(openai-compat): restrict developer/assistant/system/tool messages to text-only content

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/inference/inference.py, pyproject.toml, tests/integration/inference/test_openai_completion.py, uv.lock
OpenAI Chat Completions supports passing a base64 encoded PDF file to a model, but Llama Stack currently does not allow for this behavior. This PR extends our implementation of the OpenAI API spec to change that.
Closes #2129
A new functional test has been added to test the validity of such a request
=> feat: add base64 encoded PDF support for OpenAI Chat Completions

tests/integration/post_training/test_post_training.py
cause post training integration test to error when job fails.
ci
=> fix: error on failed job, do not wait for timeout

llama_stack/cli/stack/_build.py
when --image-name is not provided the build script default to the image_name in the config, this makes sure the same is done for the run script
llama stack build w/o --image-name
=> fix: use same image_name logic for build & run config

.github/actions/run-integration-tests/action.yml, .github/workflows/integration-tests.yml
A couple of important updates:
- When recording tests, we cannot be generating a matrix because all the independent recordings will conflict.
- In fact, we just don't need a matrix on test types any more because things are very fast and the overhead of `llama stack build` and setting up `uv` etc. is much more.
- Refactored the running of tests into an independent action
=> feat(ci): keep only one re-recording job because independent recordings will conflict

docs/quick_start.ipynb, docs/source/distributions/self_hosted_distro/starter.md, docs/source/getting_started/quickstart.md, llama_stack/templates/ci-tests/run.yaml, llama_stack/templates/starter/run.yaml, llama_stack/templates/starter/starter.py
We tried to always keep Ollama enabled. However doing so makes the provider implementation half-assed -- should it error when it cannot connect to Ollama or not? What happens during periodic model refresh? Etc. Instead do the same thing we do for vLLM -- use the `OLLAMA_URL` to conditionally enable the provider.
Run `uv run llama stack build --template starter --image-type venv --run` with and without `OLLAMA_URL` set. Verify using `llama-stack-client provider list` that ollama is correctly enabled.
=> fix: use OLLAMA_URL to activate Ollama provider in starter

.github/workflows/integration-tests.yml
We want to avoid re-triggering the workflow when random other labels are added (e.g., `meta-cla`, etc.) Also no point restarting the workflow when someone _unlabels_.
=> fix(ci): slightly update workflow trigger

pyproject.toml, uv.lock
This PR fixes the following error in unit test that was running on up to date main branch:
```
FAILED tests/unit/distribution/test_inference_recordings.py::TestInferenceRecording::test_recording_mode - ModuleNotFoundError: No module named 'ollama'
FAILED tests/unit/distribution/test_inference_recordings.py::TestInferenceRecording::test_replay_mode - ModuleNotFoundError: No module named 'ollama'
FAILED tests/unit/distribution/test_inference_recordings.py::TestInferenceRecording::test_replay_missing_recording - ModuleNotFoundError: No module named 'ollama'
FAILED tests/unit/distribution/test_inference_recordings.py::TestInferenceRecording::test_embeddings_recording - ModuleNotFoundError: No module named 'ollama'
=============================== 4 failed, 499 passed, 198 warnings in 34.50s …
```
=> fix: fix No module named 'ollama' in test_inference_recordings.py

llama_stack/apis/common/errors.py, llama_stack/distribution/routing_tables/datasets.py
1. Adds a broad schema for custom exception classes in the Llama Stack project
2. Creates a new `DatasetNotFoundError` class
3. Implements the new class where appropriate 
Relates to #2379
=> chore: standardize dataset not found error

llama_stack/distribution/routing_tables/datasets.py
get_dataset() will raise an exception if a dataset won't be returned
client handling is redundant
=> fix: remove redundant code from unregister_dataset

docs/source/providers/external/external-providers-guide.md, docs/source/providers/external/external-providers-list.md, docs/source/providers/external/index.md, docs/source/providers/index.md
**Description** 
This PR adjusts the external providers documentation to align with the new providers format. Splits up sections into the existing external providers and how to create them as well. 
Open to feedback and adjusting titles
=> docs: Reformat external provider documentation

.github/workflows/README.md, README.md, scripts/gen-ci-docs.py
It looks like the coverage badge is still present in the README. This PR removes it.
For more context: https://github.com/meta-llama/llama-stack/pull/2950
=> chore: Remove coverage badge from README.md

llama_stack/providers/utils/inference/litellm_openai_mixin.py, tests/unit/providers/inference/test_litellm_openai_mixin.py
Improve user experience by providing specific guidance when no API key is available, showing both provider data header and config options with the correct field name for each provider.
Also adds comprehensive test coverage for API key resolution scenarios.
addresses #2990 for providers using litellm openai mixin
`./scripts/unit-tests.sh tests/unit/providers/inference/test_litellm_openai_mixin.py`
=> feat: Add clear error message when API key is missing

.github/workflows/integration-tests.yml
We don't need to run on all python versions all the time
=> feat(ci): only run on 3.12, run on both 3.12 and 3.13 nightly

tests/integration/fixtures/common.py
This should be more robust as sometimes its run without running build first.
OLLAMA_URL=http://localhost:11434 LLAMA_STACK_TEST_INFERENCE_MODE=replay LLAMA_STACK_TEST_RECORDING_DIR=tests/integration/recordings LLAMA_STACK_CONFIG=server:starter uv run --with pytest-repeat pytest tests/integration/telemetry --text-model="ollama/llama3.2:3b-instruct-fp16" -vvs
=> test: use llama stack build when starting server

llama_stack/providers/remote/inference/sambanova/sambanova.py, llama_stack/providers/utils/inference/litellm_openai_mixin.py, llama_stack/providers/utils/inference/openai_compat.py
closes #2995 
update SambaNovaInferenceAdapter to efficiently use LiteLLMOpenAIMixin
```
$ uv run pytest -s -v tests/integration/inference --stack-config inference=sambanova --text-model sambanova/Meta-Llama-3.1-8B-Instruct
...
======================== 10 passed, 84 skipped, 3 xfailed, 51 warnings in 8.14s ========================
```
=> fix: sambanova inference provider

llama_stack/providers/utils/inference/litellm_openai_mixin.py, tests/integration/test_cases/inference/chat_completion.json
Improves async compatibility in the inference provider
- Replace synchronous litellm.completion() with async litellm.acompletion()
- Update comment to reference official LiteLLM async completion docs
https://github.com/meta-llama/llama-stack/blob/218c89fff11a5e81b38d3c10ea2ed7d0c164f2ea/llama_stack/providers/utils/inference/litellm_openai_mixin.py#L155-L157
```
uv run --group unit pytest tests/integration/inference/ --stack-config="inference=gemini" --text-model="gemini/gemini/gemini-2.0-flash" -v
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.12.9, …
```
=> feat: switch to async completion in LiteLLM OpenAI mixin

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/safety/safety.py, llama_stack/core/routers/safety.py, llama_stack/providers/inline/safety/llama_guard/llama_guard.py, tests/integration/safety/test_safety.py
This PR adds Open AI Compatible moderations api. Currently only implementing for llama guard safety provider
Image support, expand to other safety providers and Deprecation of run_shield will be next steps.
Added 2 new tests for safe/ unsafe text prompt examples for the new open ai compatible moderations api usage
`SAFETY_MODEL=llama-guard3:8b LLAMA_STACK_CONFIG=starter uv run pytest -v tests/integration/safety/test_safety.py --text-model=llama3.2:3b-instruct-fp16 --embedding-model=all-MiniLM-L6-v2 --safety-shield=ollama`
(Had some issue with previous PR https://github.com/meta-llama/llama-stack/pull/2994 while updating and accidentally close it , reopened new one )
=> feat: Add moderations create api

llama_stack/providers/remote/vector_io/milvus/milvus.py, llama_stack/providers/utils/memory/vector_store.py, tests/integration/vector_io/test_openai_vector_stores.py, tests/unit/providers/vector_io/remote/test_milvus.py
This PR implements hybrid search for Milvus DB based on the inbuilt milvus support.
To test:
```
pytest tests/unit/providers/vector_io/remote/test_milvus.py -v -s --tb=long --disable-warnings --asyncio-mode=auto
```
=> feat: Implement hybrid search in Milvus

llama_stack/providers/utils/telemetry/tracing.py
Ran a stress test on chat completion endpoint locally:
For 10 concurrent users over 3 minutes:
Before:
After:
(Will send scripts in a future PR.)
=> fix: telemetry logger spams when queue is full

llama_stack/core/routing_tables/toolgroups.py
=> chore: remove redundant code in unregister_toolgroup

llama_stack/log.py
Using commas is much more shell-friendly. A semi-colon is a statement delimiter and must be escaped.
This change is backwards incompatible but I imagine not many people are using this. I could be wrong. Looking for feedback.
=> chore(logging)!: use comma as a delimiter

llama_stack/providers/inline/safety/prompt_guard/prompt_guard.py
This PR addresses an issue where `PromptGuardSafetyImpl` was an incomplete implementation of an abstract class. The class was missing the required run_moderation method from its parent interface.
Currently, running `pre-commit` locally fails with the error below.
```
llama_stack/providers/inline/safety/prompt_guard/__init__.py:15: error: Cannot instantiate abstract class "PromptGuardSafetyImpl" with abstract attribute "run_moderation"  [abstract]
Found 1 error in 1 file (checked 410 source files)
```
This PR fixes the issue as follows
- Added the missing run_moderation method to PromptGuardSafetyImpl
- Method raises NotImplementedError with appropriate message indicating this functionality is not implemented for PromptGuard
- This allows the class to be properly instantiated while clearly …
=> fix: Implement missing `run_moderation` method in `PromptGuardSafetyImpl`

docs/source/apis/external.md, docs/source/providers/external/external-providers-guide.md, tests/external/llama-stack-api-weather/pyproject.toml, tests/external/llama-stack-provider-kaze/pyproject.toml
the minimum python version for the project was bumped to 3.12 a couple months ago, but there remains some artifacts in the repo suggesting we support >=3.10
=> chore: bump min python version in docs and tests

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/agents/agents.py, llama_stack/providers/inline/agents/meta_reference/agents.py, llama_stack/providers/inline/agents/meta_reference/openai_responses.py
Well our Responses tests use it so we better include it in the API, no?
I discovered it because I want to make sure `llama-stack-client` can be used always instead of `openai-python` as the client (we do want to be _truly_ compatible.)
=> feat(responses): add include parameter

.github/workflows/semantic-pr.yml
This PR changes the group name from github.ref to github.even.pull_request_number. The reason for this is that github.ref does not act as a unique identifier in the pull_request_target event and only is unique in pull_request. The github action was getting canceled was because the group name was not unique in the concurrency section. 
Closes #3102
To test this I have created a fake github action and ran it trough act to see what the github.ref variable produced and what alternatives can be used. This confirmed that the github.ref was not unique and that github.event.pull_request_number is unique to the PR.
=> fix: github action canceling valid tasks for checking semantic pr title

llama_stack/core/library_client.py, llama_stack/core/server/server.py
The purpose of this PR is to make the behavior DELETE API endpoints be consistent with standard RESTful conventions and eliminate confusion for API consumers.
Old Behavior
```
HTTP Status: 200 OK
Response Body: null
```
Eg. `curl -X DELETE http://localhost:8321/v1/shields/test-shield`
`null% `
`INFO     2025-08-12 16:11:57,932 console_span_processor:65 telemetry:  15:11:57.929 [INFO] ::1:59805 - "DELETE /v1/shields/test-shield HTTP/1.1" 200  `
Updated Behavior
```
HTTP Status: 204 No Content
Response Body: empty (no body)
```
Eg.  `curl -X DELETE http://localhost:8321/v1/shields/test-shield`
`INFO     2025-08-12 16:18:16,645 console_span_processor:62 telemetry:  15:18:16.637 [INFO] ::1:60283 - "DELETE /v1/shields/test-shield HTTP/1.1" 204  `
Closes #3090 
Run `./scripts/unit-tests.sh`
=> refactor: modify DELETE API endpoints by returning HTTP 204 No Content + empty body instead of 200 OK + response body with null

docs/source/building_applications/responses_vs_agents.md, docs/source/building_applications/tools.md, docs/source/providers/vector_io/inline_meta-reference.md, docs/source/providers/vector_io/inline_sqlite_vec.md, docs/source/providers/vector_io/remote_milvus.md, docs/source/references/llama_cli_reference/download_models.md, docs/source/references/llama_cli_reference/index.md, scripts/provider_codegen.py
**Description:** 
The standard markdown [!NOTE] format is not supported on Sphinx generated documentation, replacing those instances. Also updating other Notes, Tips and Warning blocks throughout the source docs
WIP: Working to update the provider code gen
=> docs: Update blocks formatting in docs/source files

llama_stack/core/server/server.py
The purpose of this PR is to eliminate hardcoded status codes in server's responses and replace it by `httpx.codes` functionality for better consistency across the whole project and improvement in code readability.
Run `./scripts/unit-tests.sh`
=> refactor: replace hardcoded status codes by httpx.codes

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/safety/safety.py, llama_stack/core/routers/safety.py, llama_stack/providers/inline/safety/llama_guard/llama_guard.py, llama_stack/providers/inline/safety/prompt_guard/prompt_guard.py, tests/integration/safety/test_safety.py
To be compliant with model policies for LLAMA, just return the categories as is from provider, we will lose the OAI compat in moderations api response.
`SAFETY_MODEL=llama-guard3:8b LLAMA_STACK_CONFIG=starter uv run pytest -v tests/integration/safety/test_safety.py --text-model=llama3.2:3b-instruct-fp16 --embedding-model=all-MiniLM-L6-v2 --safety-shield=ollama`
=> chore: Change moderations api response to Provider returned categories

llama_stack/providers/utils/inference/openai_compat.py, tests/unit/providers/utils/inference/test_openai_compat.py
The OpenAI compatibility layer was incorrectly importing ChatCompletionMessageToolCallParam instead of the
ChatCompletionMessageFunctionToolCall class. This caused "Cannot instantiate typing.Union" errors when processing agent requests with tool calls.
Closes: #3141
=> fix: use ChatCompletionMessageFunctionToolCall

llama_stack/providers/inline/agents/meta_reference/responses/openai_responses.py, llama_stack/providers/inline/agents/meta_reference/responses/utils.py, tests/unit/providers/agents/meta_reference/test_response_conversion_utils.py
Refactors the OpenAI response conversion utilities by moving helper functions from `openai_responses.py` to `utils.py`. Adds unit tests.
=> refactor(responses): move stuff into some utils and add unit tests

llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Replace chat_completion calls with openai_chat_completion to eliminate dependency on legacy inference APIs.
Closes #3067
=> refactor(agents): migrate to OpenAI chat completions API

.github/workflows/record-integration-tests.yml, scripts/github/schedule-record-workflow.sh, tests/README.md, tests/integration/README.md
See comment here: https://github.com/llamastack/llama-stack/pull/3162#issuecomment-3192859097 -- TL;DR it is quite complex to invoke the recording workflow correctly for an end developer writing tests. This script simplifies the work.
No more manual GitHub UI navigation!
- Auto-detects your current branch and associated PR
- Finds the right repository context (works from forks!)
- Runs the workflow where it can actually commit back
- Validates prerequisites and provides helpful error messages
First ensure you are on the branch which introduced a new test and want it recorded. **Make sure you have pushed this branch remotely, easiest is to create a PR.**
```
./scripts/github/schedule-record-workflow.sh
./scripts/github/schedule-record-workflow.sh --test-subdirs "agents,inference" …
```
=> test(recording): add a script to schedule recording workflow

llama_stack/providers/remote/inference/nvidia/NVIDIA.md, llama_stack/providers/remote/inference/nvidia/nvidia.py
NVIDIA asymmetric embedding models (e.g., `nvidia/llama-3.2-nv-embedqa-1b-v2`) require an `input_type` parameter not present in the standard OpenAI embeddings API. This PR adds the `input_type="query"` as default and updates the documentation to suggest using the `embedding` API for passage embeddings. 
Resolves #2892 
```
pytest -s -v tests/integration/inference/test_openai_embeddings.py   --stack-config="inference=nvidia"   --embedding-model="nvidia/llama-3.2-nv-embedqa-1b-v2"   --env NVIDIA_API_KEY={nvidia_api_key}   --env NVIDIA_BASE_URL="https://integrate.api.nvidia.com"
```
=> fix: fix ```openai_embeddings``` for asymmetric embedding NIMs

llama_stack/providers/utils/sqlstore/sqlalchemy_sqlstore.py
We noticed that when llama-stack is running for a long time,  we would run into database errors when trying to run messages through the agent (which we configured to persist against postgres), seemingly due to the database connections being stale or disconnected. This commit adds `pool_pre_ping=True` to the SQLAlchemy engine creation to help mitigate this issue by checking the connection before using it, and re-establishing it if necessary.
More information in:
https://docs.sqlalchemy.org/en/20/core/pooling.html#dealing-with-disconnects
We're also open to other suggestions on how to handle this issue, this PR is just a suggestion. 
We have not tested it yet (we're in the process of doing that) and we're hoping it's going to resolve our issue.
=> fix: Use `pool_pre_ping=True` in SQLAlchemy engine creation

.github/dependabot.yml
This should fix dependabot based on this thread: https://stackoverflow.com/questions/60201543/dependabot-only-updates-lock-file
=> chore: Update dependabot to capture package-lock.json

llama_stack/providers/remote/inference/nvidia/nvidia.py, tests/integration/inference/test_embedding.py
Currently the embedding integration test cases fail due to a misalignment in the error type. This PR fixes the embedding integration test by fixing the error type. 
```
pytest -s -v tests/integration/inference/test_embedding.py --stack-config="inference=nvidia" --embedding-model="nvidia/llama-3.2-nv-embedqa-1b-v2" --env NVIDIA_API_KEY={nvidia_api_key} --env NVIDIA_BASE_URL="https://integrate.api.nvidia.com"
```
=> fix: fix the error type in embedding test case

docs/source/providers/post_training/index.md, docs/source/providers/post_training/inline_huggingface-cpu.md, docs/source/providers/post_training/inline_huggingface-gpu.md, docs/source/providers/post_training/inline_torchtune-cpu.md, docs/source/providers/post_training/inline_torchtune-gpu.md, llama_stack/distributions/ci-tests/build.yaml, llama_stack/distributions/starter-gpu/__init__.py, llama_stack/distributions/starter-gpu/build.yaml, llama_stack/distributions/starter-gpu/run.yaml, llama_stack/distributions/starter-gpu/starter_gpu.py, llama_stack/distributions/starter/run.yaml, llama_stack/distributions/starter/starter.py, llama_stack/providers/registry/post_training.py
The starter distribution added post-training which added torch dependencies which pulls in all the nvidia CUDA libraries. This made our starter container very big. We have worked hard to keep the starter container small so it serves its purpose as a starter. This PR tries to get it back to its size by forking off duplicate "-gpu" providers for post-training. These forked providers are then used for a new `starter-gpu` distribution which can pull in all dependencies.
=> feat(distro): fork off a starter-gpu distribution

llama_stack/providers/inline/vector_io/sqlite_vec/sqlite_vec.py
The purpose of this PR is to refactor `SQLiteVecIndex` to eliminate redundant code and simplify the code using generic `WeightedInMemoryAggregator` that can be used for any vector db provider. This pattern is already implemented for `PGVectorIndex` in #3064
CC: @franciscojavierarceo 
1. `./scripts/unit-tests.sh`
2. Integration tests in CI Workflow
=> refactor: use generic WeightedInMemoryAggregator for hybrid search in SQLiteVecIndex

llama_stack/providers/registry/inference.py, llama_stack/providers/remote/inference/watsonx/watsonx.py
This PR updates the Watsonx provider dependencies from `ibm_watson_machine_learning` to `ibm_watsonx_ai`.
The old package `ibm_watson_machine_learning` is in **deprecation mode** ([[PyPI link](https://pypi.org/project/ibm-watson-machine-learning/)](https://pypi.org/project/ibm-watson-machine-learning/)) and relies on older versions of dependencies such as `pandas`. Updating to `ibm_watsonx_ai` ensures compatibility with current dependency versions and ongoing support.
I verified the update by running an inference using a model provided by Watsonx. The model ran successfully, confirming that the new dependency works as expected.
=> chore(python-deps): replace ibm_watson_machine_learning with ibm_watsonx_ai

llama_stack/core/routers/inference.py
Sometimes the stream don't have chunks with finish_reason, e.g. canceled stream, which throws a pydantic error as OpenAIChoice.finish_reason: str
observe no more such error when benchmarking
=> chore: handle missing finish_reason

llama_stack/providers/registry/inference.py
Noticed the test https://github.com/llamastack/llama-stack-ops/actions/workflows/test-maybe-cut.yaml are still failing randomly.
Earlier fixed this with 0.18.0 of fireworks here https://github.com/llamastack/llama-stack/pull/3267, the local testing may have inadvertently picked a lower version with `<=` which I assumed picks latest version.
Now tested with `==` to find the version where it broke and pinning to version(`<=`) where it was passing.
Tested locally with the following commands to start a container
Build container
`llama stack build --distro starter --image-type container`
start container `docker run -d -p 8321:8321 --name llama-stack-test distribution-starter:0.2.20`
check health `http://localhost:8321/v1/health`
Above steps fails without the fix
Tested with `==` to ensure the …
=> fix: Move to older version for docker container failure [fireworks-ai]

tests/integration/inference/test_openai_completion.py
skip the with_n test for groq, because it isn't supported by the provider's service
see https://console.groq.com/docs/openai#currently-unsupported-openai-features
=> chore(groq test): skip with_n tests for groq, it is not supported server-side

llama_stack/providers/registry/inference.py, llama_stack/providers/remote/inference/groq/groq.py, tests/unit/providers/inference/test_inference_client_caching.py
update Groq inference provider to use OpenAIMixin for openai-compat endpoints
changes on api.groq.com -
- json_schema is now supported for specific models, see https://console.groq.com/docs/structured-outputs#supported-models
- response_format with streaming is now supported for models that support response_format
- groq no longer returns a 400 error if tools are provided and tool_choice is not "required"
```
$ GROQ_API_KEY=... uv run llama stack build --image-type venv --providers inference=remote::groq --run
...
$ LLAMA_STACK_CONFIG=http://localhost:8321 uv run --group test pytest -v -ra --text-model groq/llama-3.3-70b-versatile tests/integration/inference/test_openai_completion.py -k 'not store'
...
SKIPPED [3] tests/integration/inference/test_openai_completion.py:44: Model …
```
=> chore: update the groq inference impl to use openai-python for openai-compat functions

llama_stack/providers/remote/inference/anthropic/anthropic.py, tests/integration/inference/test_openai_completion.py
update the Anthropic inference provider to use openai-python for the openai-compat endpoints
ci
=> chore: update the anthropic inference impl to use openai-python for openai-compat functions

docs/source/distributions/configuration.md, llama_stack/apis/common/errors.py, llama_stack/core/datatypes.py, llama_stack/core/server/auth_providers.py, tests/unit/server/test_auth.py
Add Kubernetes authentication provider support
- Add KubernetesAuthProvider class for token validation using Kubernetes SelfSubjectReview API
- Add KubernetesAuthProviderConfig with configurable API server URL, TLS settings, and claims mapping
- Implement authentication via POST requests to /apis/authentication.k8s.io/v1/selfsubjectreviews endpoint
- Add support for parsing Kubernetes SelfSubjectReview response format to extract user information
- Add KUBERNETES provider type to AuthProviderType enum
- Update create_auth_provider factory function to handle 'kubernetes' provider type
- Add comprehensive unit tests for KubernetesAuthProvider functionality
- Add documentation with configuration examples and usage instructions
The provider validates tokens by sending SelfSubjectReview …
=> feat: Add Kubernetes  auth provider to use SelfSubjectReview and kubernetes api server

docs/source/providers/external/external-providers-list.md
The MongoDB integration - Vector search, Full-Text search and Hybrid search have now been added as an external provider offering for Llama Stack: https://github.com/mongodb-partners/mongodb-llama-stack
=> docs: add MongoDB to external provider list

llama_stack/cli/stack/_build.py
enables completions storage when using `llama stack build --providers` -
- GET /v1/chat/completions
- GET /v1/chat/completions/{id}
todo: llama stack build and distro codegen should use the same code paths
ci
=> feat: include a default inference store during llama stack build

llama_stack/providers/registry/inference.py, llama_stack/providers/remote/inference/vertexai/vertexai.py, tests/integration/inference/test_openai_completion.py
update VertexAI inference provider to use openai-python for openai-compat functions
```
$ VERTEX_AI_PROJECT=... uv run llama stack build --image-type venv --providers inference=remote::vertexai --run
...
$ LLAMA_STACK_CONFIG=http://localhost:8321 uv run --group test pytest -v -ra --text-model vertexai/vertex_ai/gemini-2.5-flash tests/integration/inference/test_openai_completion.py
...
```
i don't have an account to test this. `get_api_key` may also need to be updated per https://cloud.google.com/vertex-ai/generative-ai/docs/start/openai
=> chore: update the vertexai inference impl to use openai-python for openai-compat functions

llama_stack/providers/utils/inference/inference_store.py, llama_stack/providers/utils/sqlstore/authorized_sqlstore.py
Duplicate chat completion IDs can be generated during tests especially if they are replaying recorded responses across different tests. No need to warn or error under those circumstances. In the wild, this is not likely to happen at all (no evidence) so we aren't really hiding any problem.
=> fix(inference_store): on duplicate chat completion IDs, replace

pyproject.toml
help developers identify slow tests by always passing --duration to pytest
n/a
=> chore(tests): always show slowest tests

llama_stack/testing/inference_recorder.py, tests/unit/distribution/test_inference_recordings.py
the recorder mocks the openai-python interface. the openai-python interface allows NOT_GIVEN as an input option. this change properly handles NOT_GIVEN.
ci (coverage for chat, completions, embeddings)
=> chore(recorder): add support for NOT_GIVEN

llama_stack/testing/inference_recorder.py, tests/unit/distribution/test_inference_recordings.py
the @required_args decorator in openai-python is masking the async nature of the {AsyncCompletions,chat.AsyncCompletions}.create method. see https://github.com/openai/openai-python/issues/996
this means two things -
0. we cannot use iscoroutine in the recorder to detect async vs non
1. our mocks are inappropriately introducing identifiable async
for (0), we update the iscoroutine check w/ detection of /v1/models, which is the only non-async function we mock & record.
for (1), we could leave everything as is and assume (0) will catch errors. to be defensive, we update the unit tests to mock below create methods, allowing the true openai-python create() methods to be tested.
=> chore(recorder): update mocks to be closer to non-mock environment

docs/source/providers/inference/remote_watsonx.md, llama_stack/distributions/watsonx/run.yaml, llama_stack/distributions/watsonx/watsonx.py, llama_stack/providers/remote/inference/watsonx/config.py, llama_stack/providers/remote/inference/watsonx/watsonx.py, tests/integration/inference/test_openai_completion.py, tests/integration/inference/test_text_inference.py
use a logger
* update the distro to add the Files API otherwise it won't start since it is a dependency of vector
* clarify project_id and api_key requirements
* disable openai compatible calls since the endpoint returns 404
* disable text_inference structured format tests
* fixed openai client initialization
Execute text_inference:
```
WATSONX_API_KEY=... WATSONX_PROJECT_ID=... python -m llama_stack.core.server.server llama_stack/distributions/watsonx/run.yaml
LLAMA_STACK_CONFIG=http://localhost:8321 uv run --group test pytest -vvvv -ra --text-model watsonx/meta-llama/llama-3-3-70b-instruct tests/integration/inference/test_text_inference.py
============================================= test session starts ==============================================
platform darwin -- Python 3.12.8, …
```
=> chore: various watsonx fixes

llama_stack/providers/remote/vector_io/qdrant/qdrant.py
Updates the qdrant provider's convert_id function to use a FIPS-validated cryptographic hashing function, so that llama-stack is considered to be `Designed for FIPS`.
The standard library `uuid.uuid5()` function uses SHA-1 under the hood, which is not FIPS-validated. This commit uses an approach similar to the one merged in #3423.
Closes #3476.
Unit tests from scripts/unit-tests.sh were ran to verify that the tests pass.
A small test script can display the data flow:
```python
import hashlib
import uuid
_id = "chunk_abc123"
print(_id)
hash_input = f"qdrant_id:{_id}".encode()
print(hash_input)
sha256_hash = hashlib.sha256(hash_input).hexdigest()
print(sha256_hash)
uuid_string = str(uuid.UUID(sha256_hash[:32]))
print(uuid_string)
```
=> feat: update qdrant hash function from SHA-1 to SHA-256

llama_stack/providers/utils/inference/openai_mixin.py, tests/unit/providers/inference/test_openai_base_url_config.py, tests/unit/providers/utils/inference/test_openai_mixin.py
this replaces the static model listing for any provider using OpenAIMixin
currently -
- anthropic
- azure openai
- gemini
- groq
- llama-api
- nvidia
- openai
- sambanova
- tgi
- vertexai
- vllm
- not changed: together has its own impl
- new unit tests
- manual for llama-api, openai, groq, gemini
```
for provider in llama-openai-compat openai groq gemini; do
uv run llama stack build --image-type venv --providers inference=remote::provider --run &
uv run --with llama-stack-client llama-stack-client models list | grep Total
```
results (17 sep 2025):
- llama-api: 4
- openai: 86
- groq: 21
- gemini: 66
closes #3467
=> feat: include all models from provider's /v1/models

docs/source/distributions/self_hosted_distro/nvidia.md, llama_stack/distributions/nvidia/build.yaml, llama_stack/distributions/nvidia/nvidia.py, llama_stack/distributions/nvidia/run-with-safety.yaml, llama_stack/distributions/nvidia/run.yaml
The rag-runtime tool requires files API as a dependency, but the NVIDIA distribution was missing the files provider configuration. Thus, when running:
```
llama stack build --distro nvidia --image-type venv
```
And then:
```
llama stack run {path_to_distribution_config} --image-type venv
```
It would raise an error:
```
RuntimeError: Failed to resolve 'tool_runtime' provider 'rag-runtime' of type 'inline::rag-runtime': required dependency 'files' is not available. Please add a 'files' provider to your configuration or check if the provider is properly configured.
```
This PR fixes the issue by adding missing files provider to NVIDIA distribution. 
N/A
=> fix: add missing files provider to NVIDIA distribution

benchmarking/k8s-benchmark/apply.sh, benchmarking/k8s-benchmark/stack-configmap.yaml, benchmarking/k8s-benchmark/stack-k8s.yaml.template, llama_stack/core/library_client.py, llama_stack/core/server/server.py, llama_stack/core/stack.py, tests/unit/distribution/test_library_client_initialization.py
As shown in #3421, we can scale stack to handle more RPS with k8s replicas. This PR enables multi process stack with uvicorn --workers so that we can achieve the same scaling without being in k8s. 
To achieve that we refactor main to split out the app construction logic. This method needs to be non-async. We created a new `Stack` class to house impls and have a `start()` method to be called in lifespan to start background tasks instead of starting them in the old `construct_stack`. This way we avoid having to manage an event loop manually.
CI
> uv run --with llama-stack python -m llama_stack.core.server.server benchmarking/k8s-benchmark/stack_run_config.yaml
works.
> LLAMA_STACK_CONFIG=benchmarking/k8s-benchmark/stack_run_config.yaml uv run uvicorn …
=> chore: refactor server.main

docs/source/providers/vector_io/remote_milvus.md, llama_stack/providers/registry/vector_io.py
pymilvus recently made `milvus-lite` an optional dependency to their package. If someone wants to use the inline provider we must include the extra dependency.
For more details see: https://github.com/milvus-io/pymilvus/pull/2976
=> fix: force milvus-lite installation for inline::milvus

llama_stack/providers/remote/inference/anthropic/__init__.py
removes the duplicate AnthropicProviderDataValidator
the active one is in config.py
ci
=> chore: remove duplicate AnthropicProviderDataValidator

llama_stack/testing/inference_recorder.py
- Handle Ollama format where models are nested under response['body']['models']
- Fall back to OpenAI format where models are directly in response['body']
Closes: #3457
=> fix: Update inference recorder to handle both Ollama and OpenAI model

llama_stack/providers/utils/inference/model_registry.py
change ModelRegistryHelper to use ProviderModelEntry instead of hardcoded ModelType.llm  which fixed issue #3330.
1. open llama-stack server 
```
uv sync --python 3.12
source .venv/bin/activate
uv run llama stack build --distro starter --image-type venv  --run
```
2.Used following script to test 
```
import os
def test_openai_embedding_type():
client = LlamaStackClient(
base_url=os.environ.get("LLAMA_STACK_ENDPOINT", "http://localhost:8321"),
provider_data={
"openai_api_key": os.environ.get("OPENAI_API_KEY", ""),
},
)
model = client.models.retrieve("openai/text-embedding-3-small")
print(model)
assert model.identifier == "openai/text-embedding-3-small"
assert model.model_type == "embedding"
test_openai_embedding_type()
```
logs:
```
python …
```
=> fix:  change ModelRegistryHelper to use ProviderModelEntry instead of hardcoded ModelType.llm 

docs/_static/llama-stack-spec.html, docs/_static/llama-stack-spec.yaml, llama_stack/apis/files/files.py
_[Stack 1/10] Docusaurus documentation migration_
Updates the file upload API documentation to use proper OpenAPI format for integer parameters. Replaces `<int>` with `{integer}` in the description of the `expires_after[seconds]` parameter across the HTML spec, YAML spec, and Python implementation.
- docs/openapi_generator/run_openapi_generator.sh
=> fix: fix API docstrings for proper MDX parsing

llama_stack/providers/utils/telemetry/tracing.py
Switches from `random.getrandbits` to `secrets.randbits` in the telemetry module.
Closes #3553 
Unit tests from scripts/unit-tests.sh were ran to verify the tests still pass.
=> feat: use FIPS validated CSPRNG for telemetry

llama_stack/core/store/registry.py, tests/unit/registry/test_registry.py
the commit to be reverted is an public api behavior change to something we should not support.
instead of allowing silent updates (the caller cannot see the log messages), we should be sending an error to the caller that they must first unregister the model before reusing the same name w/ a different backend.
=> fix: Revert "fix: Added a bug fix when registering new models"

tests/integration/providers/nvidia/test_datastore.py
the nvidia datastore tests were running when the datastore was not configured. they would always fail.
this introduces a skip when the nvidia datastore is not configured.
ci
=> chore: skip nvidia datastore tests when nvidia datastore is not enabled

llama_stack/providers/inline/agents/meta_reference/agent_instance.py, tests/unit/providers/agent/test_get_raw_document_text.py
This PR fix #3300 by adding mime type of application/json support in [agent_instance.py](https://github.com/llamastack/llama-stack/blob/4a59961a6cd764db739aefeba06601dfaee68d88/llama_stack/providers/inline/agents/meta_reference/agent_instance.py#L923) 
all related pytest passed, see log:
```
./scripts/unit-tests.sh tests/unit/providers/agent/test_get_raw_document_text.py -vvv
/Users/kaiwu/work/kaiwu/llama-stack/.venv/bin/python3
Uninstalled 22 packages in 5.65s
Installed 47 packages in 1.24s
================= test session starts =================
platform darwin -- Python 3.12.9, pytest-8.4.2, pluggy-1.6.0 -- /Users/kaiwu/work/kaiwu/llama-stack/.venv/bin/python
metadata: {'Python': '3.12.9', 'Platform': 'macOS-15.6.1-arm64-arm-64bit', 'Packages': {'pytest': …
```
=> fix: adding mime type of application/json support 

llama_stack/providers/inline/eval/meta_reference/eval.py, tests/integration/recordings/responses/8d035e153b6f.json, tests/integration/recordings/responses/92a9a916ef02.json, tests/integration/recordings/responses/c62eb5d7115e.json, tests/integration/recordings/responses/e25ab43491af.json, tests/integration/recordings/responses/f28a44c97ea7.json
move the eval=inline::meta-reference implementation to use openai_completion/openai_chat_completion
note: this breaks backward compatibility if eval setup used sampling params' repetition_penalty or strategy
ci w/ new recordings
=> feat: update eval runner to use openai endpoints

llama_stack/providers/utils/inference/litellm_openai_mixin.py
Refs: https://github.com/llamastack/llama-stack/issues/3420
When telemetry is enabled the router uncondionally expects the usage attribute to be availble and fails if it is not present.
Usage is not currently being requested by litellm_openai_mixin.py for streaming requests when using the responses API which means that providers like vertexai fail if telemetry is enabled and streaming is used.
This is part of the required fix. Other part is in liteLLM, will plan to submit PR for that soon.
I applied this change along with the change for litellm in a llama stack deployment and validated that I could make streaming requests through the responses API to a gemini model and they would succeed instead of failing due to the missing usage attribute when telemetry is enabled.
=> fix: ensure usage is requested if telemetry is enabled

docs/openapi_generator/pyopenapi/generator.py, docs/static/llama-stack-spec.html, docs/static/llama-stack-spec.yaml, llama_stack/apis/files/files.py, llama_stack/providers/inline/files/localfs/files.py, llama_stack/providers/remote/files/s3/files.py, llama_stack/strong_typing/inspection.py, llama_stack/strong_typing/schema.py, tests/unit/providers/files/test_s3_files.py
This was just quite incorrect. See source here: https://platform.openai.com/docs/api-reference/files/create
=> feat(files): fix expires_after API shape

docs/static/llama-stack-spec.html, docs/static/llama-stack-spec.yaml, llama_stack/apis/agents/agents.py
agents is likely to be deprecated in favor of responses. Lets level it as alpha to indicate the lack of longterm support
keep v1 route for backwards compat.
Closes #3611
=> feat(api): level /agents as `v1alpha`

llama_stack/providers/inline/files/localfs/files.py, llama_stack/providers/remote/files/s3/files.py, llama_stack/providers/utils/files/__init__.py, llama_stack/providers/utils/files/form_data.py, tests/unit/providers/utils/test_form_data.py
https://github.com/llamastack/llama-stack/pull/3604 broke multipart form data field parsing for the Files API since it changed its shape -- so as to match the API exactly to the OpenAI spec even in the generated client code. 
The underlying reason is that multipart/form-data cannot transport structured nested fields. Each field must be str-serialized. The client (specifically the OpenAI client whose behavior we must match), transports sub-fields as `expires_after[anchor]` and `expires_after[seconds]`, etc. We must be able to handle these fields somehow on the server without compromising the shape of the YAML spec.
This PR "fixes" this by adding a dependency to convert the data. The main trade-off here is that we must add this `Depends()` annotation on every provider implementation for …
=> fix(expires_after): make sure multipart/form-data is properly parsed

docs/docs/providers/telemetry/inline_meta-reference.mdx, llama_stack/distributions/ci-tests/run.yaml, llama_stack/distributions/dell/run-with-safety.yaml, llama_stack/distributions/dell/run.yaml, llama_stack/distributions/meta-reference-gpu/run-with-safety.yaml, llama_stack/distributions/meta-reference-gpu/run.yaml, llama_stack/distributions/nvidia/run-with-safety.yaml, llama_stack/distributions/nvidia/run.yaml, llama_stack/distributions/open-benchmark/run.yaml, llama_stack/distributions/starter-gpu/run.yaml, llama_stack/distributions/starter/run.yaml, llama_stack/providers/inline/telemetry/meta_reference/config.py
The current span processing dumps so much junk on the console that it makes actual understanding of what is going on in the server impossible. I am killing the console sink as a default. If you want, you are always free to change your run.yaml to add it.
Before: 
After:
=> fix(logging): disable console telemetry sink by default

docs/static/llama-stack-spec.html, docs/static/llama-stack-spec.yaml, llama_stack/apis/datasetio/datasetio.py, llama_stack/apis/datasets/datasets.py, llama_stack/apis/telemetry/telemetry.py
level the following APIs, keeping their old routes around as well until 0.4.0
1. datasetio to v1beta:  used primarily by eval and training. Given that training is v1alpha, and eval is v1alpha, datasetio is likely to change in structure as real usages of the API spin up. Register,unregister, and iter dataset is sparsely implemented meaning the shape of that route is likely to change.
2. telemetry to v1alpha: telemetry has been going through many changes. for example query_metrics was not even implemented until recently and had to change its shape to work. putting this in v1beta will allow us to fix functionality like OTEL, sqlite, etc. The routes themselves are set, but the structure might change a bit
=> feat(api): implement v1beta leveling, and additional alpha

llama_stack/log.py
- categories like "core::server" is not recognized so it's level is not set by 'all=debug'
- removed spammy telemetry debug logging
test server launched with LLAMA_STACK_LOGGING='all=debug'
=> fix: log level

docs/sidebars.ts
Currently, the docs page has the home book opened by default. This PR updates the .ts so that the sidebar books are collapsed when you first open the webpage
=> docs: Update docs navbar config

llama_stack/log.py, llama_stack/providers/inline/agents/meta_reference/responses/openai_responses.py, llama_stack/providers/utils/inference/inference_store.py, llama_stack/providers/utils/responses/responses_store.py
These aren't controllable by LLAMA_STACK_LOGGING
```
tests/integration/agents/test_persistence.py::test_delete_agents_and_sessions SKIPPED (This ...) [  3%]
tests/integration/agents/test_persistence.py::test_get_agent_turns_and_steps SKIPPED (This t...) [  7%]
tests/integration/agents/test_openai_responses.py::test_responses_store[openai_client-txt=openai/gpt-4o-tools0-True] 
instantiating llama_stack_client
WARNING  2025-10-02 13:14:33,472 root:258 uncategorized: Unknown logging category: testing. Falling back to default 'root' level: 20                  
WARNING  2025-10-02 13:14:33,477 root:258 uncategorized: Unknown logging category: providers::utils. Falling back to default 'root' level: 20         
WARNING  2025-10-02 13:14:33,960 root:258 uncategorized: Unknown logging category: …
```
=> chore: fix/add logging categories

llama_stack/apis/agents/openai_responses.py, llama_stack/providers/inline/agents/meta_reference/responses/openai_responses.py, llama_stack/providers/inline/agents/meta_reference/responses/streaming.py, llama_stack/providers/utils/responses/responses_store.py, tests/integration/responses/test_tool_responses.py, tests/unit/providers/agents/meta_reference/test_openai_responses.py, tests/unit/utils/responses/test_responses_store.py
closes #3268
closes #3498
When resuming from previous response ID, currently we attempt to convert from the stored responses input to chat completion messages, which is not always possible, e.g. for tool calls where some data is lost once converted from chat completion message to repsonses input format.
This PR stores the chat completion messages that correspond to the _last_ call to chat completion, which is sufficient to be resumed from in the next responses API call, where we load these saved messages and skip conversion entirely.
Separate issue to optimize storage: https://github.com/llamastack/llama-stack/issues/3646
existing CI tests
=> fix: responses <> chat completion input conversion

.github/workflows/integration-auth-tests.yml, llama_stack/log.py
Addresses Issue #3271 - "Starting LLS server locally on a terminal with 120 chars width results in an output with empty lines".
This removes the specific 150-character width limit specified for the Console, and will now auto-detect the terminal width instead. Now the formatting of Console output is consistent across different sizes of terminal windows.
Closes #3271
Launching the server with several different sizes of terminal windows results in Console output without unexpected spacing. e.g. `python -m llama_stack.core.server.server /tmp/run.yaml --port 8321`
=> feat: auto-detect Console width

docs/docs/building_applications/telemetry.mdx, scripts/telemetry/grafana-datasources.yaml, scripts/telemetry/otel-collector-config.yaml, scripts/telemetry/prometheus.yml, scripts/telemetry/setup_telemetry.sh
Added missing configuration files
run ./scripts/telemetry/setup_telemetry.sh
```
OTEL_SERVICE_NAME=llama_stack OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318 TELEMETRY_SINKS=otel_trace,otel_metric uv run --with llama-stack llama stack build --distro=starter --image-type=venv --run
```
Navigate to grafana localhost:3000, query metrics and traces
=> chore: fix setup_telemetry script

README.md
Previous quick start and documentation links linked to `Page Not Found`.
=> docs: Update links in README for quick start and documentation

llama_stack/providers/remote/inference/llama_openai_compat/llama.py, tests/integration/inference/test_openai_completion.py
skip completion tests for inference=remote::llama-openai-compat
ci
=> chore: inference=remote::llama-openai-compat does not support /v1/completion

llama_stack/core/distribution.py, tests/unit/distribution/test_distribution.py
when using the providers.d method of installation users could hand craft their AdapterSpec's to use overlapping code meaning one repo could contain an inline and remote impl. Currently installing a provider via module does not allow for that as each repo is only allowed to have one `get_provider_spec` method with one Spec returned
add an optional way for `get_provider_spec` to return a list of `ProviderSpec` where each can be either an inline or remote impl.
Note: the `adapter_type` in `get_provider_spec` MUST match the `provider_type` in the build/run yaml for this to work.
resolves #3226
once this merges we need to re-enable the external provider test and account for this functionality. Work needs to be done in the external provider repos to support this functionality.
=> feat: allow for multiple external provider specs

llama_stack/providers/inline/agents/meta_reference/__init__.py, llama_stack/providers/inline/agents/meta_reference/agent_instance.py, llama_stack/providers/inline/agents/meta_reference/agents.py, llama_stack/providers/registry/agents.py
there is a lot of code in the agents API using the telemetry API and its helpers without checking if that API is even enabled.
This is the only API besides inference actively using telemetry code, so after this telemetry can be optional for the entire stack
resolves #3665
existing agent tests.
=> fix: make telemetry optional for agents

llama_stack/providers/remote/inference/nvidia/nvidia.py
(Used claude to solve #3715, coded with claude but tested by me)
**Problem**: The `NVIDIAInferenceAdapter` class was missing the `alias_to_provider_id_map` attribute, which caused the error:
`ERROR 'NVIDIAInferenceAdapter' object has no attribute 'alias_to_provider_id_map'`
**Root Cause**: The `NVIDIAInferenceAdapter` only inherited from `OpenAIMixin`, but some parts of the system expected it to have the `alias_to_provider_id_map` attribute, which is provided by the `ModelRegistryHelper` class.
**Solution**:
1.  **Added ModelRegistryHelper import**: Imported the `ModelRegistryHelper` class from `llama_stack.providers.utils.inference.model_registry`
2.  **Updated inheritance**: Changed the class declaration to inherit from both `OpenAIMixin` and `ModelRegistryHelper`
3.  **Added proper …
=> fix: fix nvidia provider

llama_stack/providers/inline/agents/meta_reference/responses/openai_responses.py, llama_stack/providers/inline/agents/meta_reference/responses/streaming.py
It prevents a tool call message being added to the chat completions message without a corresponding tool call result, which is needed in the case that an approval is required first or if the approval request is denied. In both these cases the tool call messages is popped of the next turn messages.
Closes #3728
Ran the integration tests
Manual check of both approval and denial against gpt-4o
=> fix(responses): fix regression in support for mcp tool require_approval argument
