- llama_toolchain/cli/download.py
Hi there! Wauplin here, working at HF as maintainer of the [huggingface_hub](https://github.com/huggingface/huggingface_hub) Python library. Very glad to see you've integrated it into `llama-toolchain` to provide a nice CLI to your users! I had a quick look at the implementation and would like to suggest a few things:
- defaulting `--hf-token` to read `os.environ["HF_TOKEN"]` is not needed since it's already the default behavior in `huggingface_hub`. I think it's best to pass None by default which will use the default logic to check env variable, google Colab secret, local auth file, etc.
- `local_dir_use_symlinks="auto",` is not needed anymore. Since `huggingface_hub==0.23.0`, the logic when downloading to a local directory has been completed revamped. There are no symlinks between cache …
> Update download command

- README.md
- docs/cli_reference.md
- llama_toolchain/cli/llama.py
Add formal documentation for the `llama` CLI
> Add CLI reference docs

- llama_toolchain/inference/meta_reference/generation.py
We were loading weights to the GPU and then doing another `model = model.to("cuda")` which resulted in another copy! 
While doing this, I also reorganized the code a little bit so it is somewhat simpler to follow.
Install the `local` distribution and check memory usage via `nvtop` for the 8B model. Before this PR, it was about 34GB -- after this one it is ~18.4GB
> Avoid using nearly double the memory needed

- docs/cli_reference.md
: llama model template names related; separation of copy-and-pastable commands with their outputs
> update cli ref doc

- llama_toolchain/distribution/registry.py
- llama_toolchain/inference/fireworks/__init__.py
- llama_toolchain/inference/fireworks/config.py
- llama_toolchain/inference/fireworks/fireworks.py
- llama_toolchain/inference/providers.py
We want to setup Fireworks.ai as a remote inference provider for llama-stack
- integration with distribution
- fireworks as a client
first setup the distribution
```
llama distribution install --spec remote-fireworks --name remote_llama_8b
```
then start the distribution
```
llama distribution start --name remote_llama_8b --port 5000
```
then use curl to query the agentic RPC
```
curl -X POST http://localhost:5000/inference/chat_completion -H "Content-Type: application/json" -d '{"model":"Meta-Llama3.1-8B-Instruct","messages":[{"content":"hello world", "role": "user"}],"stream":false}'
data: {"completion_message":{"role":"assistant","content":"Hello world! It's nice to meet you! Is there something I can help you with, or would you like to …
```
> Fireworks basic integration

- llama_toolchain/distribution/registry.py
- llama_toolchain/inference/providers.py
- llama_toolchain/inference/together/__init__.py
- llama_toolchain/inference/together/config.py
- llama_toolchain/inference/together/together.py
We want to setup Together.ai as a remote inference provider for llama-stack.
- integration with the distribution
- Together AI as a client (with the python `together` SDK)
1. Setup the distribution
```
llama distribution install --spec remote-together --name remote_llama_8b_together
```
2. Start the distribution
```
llama distribution start --name remote_llama_8b_together --port 5555
```
3. Use curl to query the agentic RPC (non-streaming)
```
curl -X POST http://localhost:5555/inference/chat_completion -H "Content-Type: application/json" -d '{"model":"Meta-Llama3.1-8B-Instruct","messages":[{"content":"hello world", "role": "user"}],"stream":false}'
```
**Response:**
```
data: {"completion_message":{"role":"assistant","content":"Hello World! It's nice to meet you. Is there something I can …
```
> Together AI basic integration

- llama_toolchain/memory/adapters/chroma/__init__.py
- llama_toolchain/memory/adapters/chroma/chroma.py
- llama_toolchain/memory/adapters/pgvector/__init__.py
- llama_toolchain/memory/adapters/pgvector/config.py
- llama_toolchain/memory/adapters/pgvector/pgvector.py
- llama_toolchain/memory/common/vector_store.py
- llama_toolchain/memory/meta_reference/faiss/faiss.py
- llama_toolchain/memory/providers.py
**Why this PR?** 
We'd like memory (vector store) implementations which have persistence (d'oh!) This PR adds adapters for 
* ChromaDB: https://www.trychroma.com/
* Postgres with the `vector` extension enabled: https://www.postgresql.org/about/news/pgvector-070-released-2852/
----
**How I tested PGVector?**
First set up a postgres (with pgvector extension code) container:
```bash
podman run -it \
--name pgvector-container \
--network host \
--replace \
-e POSTGRES_DB=vectordb \
-e POSTGRES_USER=vectoruser \
-e POSTGRES_PASSWORD=vectorpass \
-v pgdata:/var/lib/postgresql/data \
docker.io/ankane/pgvector:latest
```
Then connect to it and create the vector extension if not already present. 
```bash
podman exec pgvector-container psql -U vectoruser -d vectordb -c "CREATE EXTENSION vector;" …
```
> Add Chroma and PGVector adapters

- llama_toolchain/agentic_system/api/api.py
- llama_toolchain/agentic_system/client.py
- llama_toolchain/agentic_system/meta_reference/agent_instance.py
- llama_toolchain/agentic_system/meta_reference/agentic_system.py
- llama_toolchain/agentic_system/meta_reference/config.py
- llama_toolchain/common/deployment_types.py
- llama_toolchain/inference/client.py
- llama_toolchain/tools/builtin.py
Start local stack distro 
```
llama stack run local --name tt
```
Run agentic client -- 
```
python -m llama_toolchain.agentic_system.client localhost 5000
User> Search web for who was 44th President of USA?
StepType.inference> <function=brave_search>{"query": "44th President of USA"}</function>
StepType.tool_execution> Tool:BuiltinTool.brave_search Args:{'query': '44th President of USA'}
StepType.tool_execution> Tool:BuiltinTool.brave_search Response:{"query": "44th President of USA", "top_k": [{"name": "Barack Obama | The White House", "url": "https://www.whitehouse.gov/about-the-white-house/presidents/barack-obama/", "snippet": "Barack Obama"}, {"name": "Presidency of Barack Obama - Wikipedia", "url": "https://en.wikipedia.org/wiki/Presidency_of_Barack_Obama", "snippet": "Presidency of …
```
> Enable Bing search

- llama_toolchain/stack.py
- rfcs/RFC-0001-llama-stack-assets/llama-stack-spec.html
- rfcs/RFC-0001-llama-stack-assets/llama-stack-spec.yaml
- add Safety to Llama Stack 
- regenerate OpenAPI spec 
- tested in https://github.com/meta-llama/llama-stack-apps/pull/68
> add safety to openapi spec

- llama_stack/providers/impls/meta_reference/agents/rag/context_retriever.py
- Unwrap ChatCompletionRequest for context_retriever
> Unwrap ChatCompletionRequest for context_retriever 

- llama_stack/providers/adapters/safety/bedrock/__init__.py
- llama_stack/providers/adapters/safety/bedrock/bedrock.py
- llama_stack/providers/adapters/safety/bedrock/config.py
- llama_stack/providers/registry/safety.py
re comitting after rebasing the fork
> Bedrock Guardrails comiting after rebasing the fork

- llama_stack/providers/impls/meta_reference/safety/shields/llama_guard.py
- llama_stack/providers/registry/safety.py
> fix safety using inference

- llama_stack/providers/impls/meta_reference/safety/shields/llama_guard.py
Fixing model loading to use hf model id
> LG safety fix

- llama_stack/distribution/server/server.py
- fix duplicate endpoints, no need to add duplicate Api.* to apis_to_serve.
> [bugfix] fix duplicate api endpoints

- README.md
- llama_stack/cli/stack/build.py
Fix for https://github.com/meta-llama/llama-stack/issues/146
> [bugfix] fix #146

- llama_stack/cli/stack/configure.py
- tests/examples/local-run.yaml
- fix conda path lookup 
```
lama stack build --template local-ollama --name mine
llama stack configure mine
```
> [bugfix] conda path lookup

- llama_stack/cli/stack/build.py
- llama_stack/distribution/build.py
- llama_stack/distribution/build_container.sh
context in https://github.com/meta-llama/llama-stack/issues/169
> [CLI] avoid configure twice

- llama_stack/providers/utils/kvstore/config.py
Fixes https://github.com/meta-llama/llama-stack/issues/189
> Add 'url' property to Redis KV config

- README.md
Closes #198
Signed-off-by: Russell Bryant <russell.bryant@gmail.com>
> README.md: Add vLLM to providers table

- llama_stack/providers/impls/meta_reference/inference/generation.py
- llama_stack/providers/impls/meta_reference/inference/model_parallel.py
- llama_stack/providers/impls/meta_reference/inference/parallel_utils.py
Use pydantic BaseModel serialization for the parallel processing queue instead of pyobj/pickle for better security
> JSON serialization for parallel processing queue

- .github/workflows/pre-commit.yml
Fixes the build failure on main branch.
> Switch to pre-commit/action

- llama_stack/cli/download.py
Update the parsing logic for comma-separated list and download function.
Tested locally with 
- a comma-separated list <img width="1536" alt="Screenshot 2024-10-16 at 7 02 09 PM" src="https://github.com/user-attachments/assets/4fa4f504-c3df-460e-91e2-b0690ba55d2c">
- a single model id
> Add llama download support for multiple models with comma-separated list

- distributions/README.md
- distributions/fireworks/README.md
- distributions/fireworks/build.yaml
- distributions/fireworks/compose.yaml
- distributions/fireworks/run.yaml
- distributions/meta-reference-gpu/README.md
- distributions/meta-reference-gpu/build.yaml
- distributions/ollama/README.md
- distributions/ollama/build.yaml
- distributions/ollama/gpu/compose.yaml
- distributions/tgi/build.yaml
- distributions/tgi/cpu/compose.yaml
- distributions/together/README.md
- distributions/together/build.yaml
- distributions/together/compose.yaml
- distributions/together/run.yaml
- llama_stack/distribution/build_container.sh
- llama_stack/providers/registry/inference.py
- add Together/Fireworks distro templates, update ollama/tgi templates
> add more distro templates

- docs/getting_started.md
> Add REST api example for chat_completion

- llama_stack/providers/adapters/inference/databricks/databricks.py
- llama_stack/providers/adapters/inference/fireworks/fireworks.py
- llama_stack/providers/adapters/inference/ollama/ollama.py
- llama_stack/providers/adapters/inference/tgi/tgi.py
- llama_stack/providers/adapters/inference/together/together.py
- llama_stack/providers/adapters/inference/vllm/vllm.py
- llama_stack/providers/tests/inference/test_inference.py
- llama_stack/providers/utils/inference/openai_compat.py
- llama_stack/providers/utils/inference/prompt_adapter.py
test plan: 
PROVIDER_ID=test-tgi PROVIDER_CONFIG=tests/inference/provider_config_example.yaml MODEL_IDS="Llama3.2-1B-Instruct" pytest -s tests/inference/test_inference.py --tb=short --disable-warnings -rs
> completion() for tgi

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- docs/getting_started.md
Closes #306
1. enhanced readme 
2. added templates for improved github workflow
N/A
Output:
N/A
Thanks for contributing 🎉!
> [enhancement] added templates and enhanced readme

- llama_stack/providers/impls/meta_reference/agents/agents.py
Added a fix for get_agents_session method.
> Fix for get_agents_session

- distributions/dell-tgi/README.md
- distributions/dell-tgi/compose.yaml
- distributions/dell-tgi/run.yaml
- distributions/meta-reference-quantized-gpu/compose.yaml
- distributions/ollama/README.md
- distributions/ollama/cpu/compose.yaml
- distributions/ollama/gpu/compose.yaml
- distributions/together/README.md
- distributions/together/run.yaml
- llama_stack/templates/fireworks/build.yaml
- llama_stack/templates/together/build.yaml
- update /distributions compose files & README audits
> update distributions compose/readme

- llama_stack/providers/utils/kvstore/config.py
- llama_stack/providers/utils/kvstore/kvstore.py
- llama_stack/providers/utils/kvstore/postgres/__init__.py
- llama_stack/providers/utils/kvstore/postgres/postgres.py
adds a postgres kvstore impl
set the metadata store to point to postgres:
```
metedata-store:
type: postgres
user: postgres
password: mysecretpassword
db: postgres
```
verified that postgres has the metadata_store table created with data:
```
postgres=# select * from metadata_store;
key    |                                                                                    data
-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_bank | {"type": "vector", "identifier": "test_bank", "provider_id": "pgvector", "embedding_model": "all-MiniLM-L6-v2", "chunk_size_in_tokens": 512, "overlap_size_in_tokens": 64}
(1 row)
```
> add postgres kvstoreimpl

- llama_stack/providers/impls/meta_reference/memory/config.py
- llama_stack/providers/impls/meta_reference/memory/faiss.py
- llama_stack/providers/impls/meta_reference/memory/tests/test_faiss.py
add ability to persist memory banks created for faiss
Unit tests
> add ability to persist memory banks created for faiss

- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/tests/memory/fixtures.py
Fixes memory bank look up in registry by providing correct memory bank types
> fix routing tables look up key for memory bank

- llama_stack/providers/registry/inference.py
- llama_stack/providers/remote/inference/together/__init__.py
Fix issue w/ 
```
pytest -v -s -m "together" inference/test_text_inference.py
```
> [bugfix] fix together data validator

- llama_stack/apis/inference/inference.py
- llama_stack/apis/models/client.py
- llama_stack/apis/models/models.py
- llama_stack/distribution/datatypes.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/distribution/store/tests/test_registry.py
- llama_stack/providers/datatypes.py
- llama_stack/providers/inline/inference/meta_reference/inference.py
- llama_stack/providers/inline/inference/vllm/vllm.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/sample/sample.py
- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/tests/inference/fixtures.py
- llama_stack/providers/tests/inference/test_text_inference.py
- llama_stack/providers/utils/inference/model_registry.py
Updates model to inherit Resource class and updates the registration signature.
Test plan:
pytest -v -s llama_stack/providers/tests/inference/test_text_inference.py -m "together" --env TOGETHER_API_KEY=<APIKEY>
> migrate model to Resource and new registration signature

- docs/zero_to_hero_guide/Tool_Calling101_Using_Together's_Llama_Stack_Server.ipynb
- docs/zero_to_hero_guide/quickstart.md
Overview: This PR introduces two new guides for Llama Stack:
1. Ollama Quickstart Guide: A step-by-step workflow for setting up and running Llama Stack with the Ollama model. 
2. Tool Calling with Together API Guide: A comprehensive notebook detailing how to use the Together.ai's Llama Stack Server API for tool calling, providing an alternative to running a local server.
> added quickstart w ollama and toolcalling using together

- llama_stack/providers/registry/inference.py
- llama_stack/providers/remote/inference/fireworks/__init__.py
- Fix issue: <img width="855" alt="image" src="https://github.com/user-attachments/assets/b5b541db-5d6c-4ba9-9701-fe281b9f92bc">
```
llama stack run 
```
```yaml
inference:
- provider_id: remote::fireworks-0
provider_type: remote::fireworks
config:
url: https://api.fireworks.ai/inference
api_key: null
```
Call model registration via SDK
> fix fireworks data validator

- README.md
- docs/zero_to_hero_guide/Tool_Calling101_Using_Together's_Llama_Stack_Server.ipynb
It shows a complete zero-setup Colab using the Llama Stack server implemented and powered by together.ai: using Llama Stack Client API to run inference, agent and 3.2 models. Good for a quick start guide.
> Added link to the Colab notebook of the Llama Stack lesson on the Llama 3.2 course on DLAI

- llama_stack/providers/inline/memory/faiss/faiss.py
faiss serialize index returns a np object, that we first need to save to buffer and then write to sqllite. Since we are using json, we need to base64 encode the data.
Same in the read path, we base64 decode and read into np array and then call into deserialize index.
tests:
torchrun $CONDA_PREFIX/bin/pytest -v -s -m "faiss" llama_stack/providers/tests/memory/test_memory.py
> fix faiss serialize and serialize of index

- llama_stack/cli/stack/build.py
- llama_stack/providers/remote/inference/together/config.py
- Fix issue w/ llama stack build using together template
- For builds from templates, copy over the `templates/<template-name>/run.yaml` file to the `~/.llama/distributions/<name>/<name>-run.yaml` instead of re-building run config. 
```
$ llama stack build --template together --image-type conda
..
Build spec configuration saved at /opt/anaconda3/envs/llamastack-together/together-build.yaml
Build Successful! Next steps:
1. Set the environment variables: LLAMASTACK_PORT, TOGETHER_API_KEY
2. `llama stack run /Users/xiyan/.llama/distributions/llamastack-together/together-run.yaml`
```
```
$ llama stack run /Users/xiyan/.llama/distributions/llamastack-together/together-run.yaml
```
```
$ llama-stack-client models list
$ pytest -v -s -m remote agents/test_agents.py --env …
```
> fix llama stack build for together & llama stack build from templates

- docs/zero_to_hero_guide/quickstart.md
Fix the instruction in quickstart readme so the new developers/users can run it without issues.
None
> update quick start to have the working instruction

- llama_stack/cli/download.py
Adds description at the end of successful download the optionally run the verify md5 checksums command.
> Added optional md5 validate command once download is completed

- llama_stack/providers/inline/inference/meta_reference/config.py
- llama_stack/providers/inline/inference/vllm/config.py
- llama_stack/providers/tests/inference/test_model_registration.py
- llama_stack/providers/utils/inference/__init__.py
- llama_stack/providers/utils/inference/prompt_adapter.py
As the title says. 
This needs https://github.com/meta-llama/llama-models/commit/8752149f58654c54c012209f43b57bb476146f0c to also land. So the next package (0.0.54) will make this work properly.
The test is:
```bash
pytest -v -s -m "llama_3b and meta_reference" test_model_registration.py
```
> Since we are pushing for HF repos, we should accept them in inference configs

- llama_stack/providers/inline/inference/meta_reference/quantization/scripts/quantize_checkpoint.py
- llama_stack/providers/inline/inference/meta_reference/quantization/scripts/run_quantize_checkpoint.sh
Fix fp8 quantization script.
```
sh run_quantize_checkpoint.sh localhost fp8 /home/yll/fp8_test/ /home/yll/fp8_test/quantized_2 /home/yll/fp8_test/tokenizer.model 1 1
```
> Fix fp8 quantization script.

- docs/zero_to_hero_guide/README.md
The formatting shown in the picture below in the Zero to Hero README.md was fixed with this PR (also shown in a picture below).
**Before**
**After**
> Fix Zero to Hero README.md Formatting

- docs/source/references/llama_stack_client_cli_reference.md
Test plan: 
make html
sphinx-autobuild source build/html
> update client cli docs

- docs/zero_to_hero_guide/Tool_Calling101_Using_Together's_Llama_Stack_Server.ipynb
Fix the error when using the newer (v0.0.55-57) llama stack client library with Together's stack service.
> specify the client version that works for current together server

- docs/source/distributions/ondevice_distro/android_sdk.md
- docs/source/index.md
Docs update for Kotlin SDK release
> Add kotlin docs

- llama_stack/distribution/server/server.py
fix issue
```
llama stack run
```
> fix telemetry import

- llama_stack/providers/inline/scoring/braintrust/braintrust.py
- llama_stack/providers/inline/scoring/braintrust/config.py
- llama_stack/templates/bedrock/run.yaml
- llama_stack/templates/fireworks/run.yaml
- llama_stack/templates/hf-endpoint/run-with-safety.yaml
- llama_stack/templates/hf-endpoint/run.yaml
- llama_stack/templates/hf-serverless/run-with-safety.yaml
- llama_stack/templates/hf-serverless/run.yaml
- llama_stack/templates/meta-reference-gpu/run-with-safety.yaml
- llama_stack/templates/meta-reference-gpu/run.yaml
- llama_stack/templates/meta-reference-quantized-gpu/run.yaml
- llama_stack/templates/ollama/run-with-safety.yaml
- llama_stack/templates/ollama/run.yaml
- llama_stack/templates/tgi/run-with-safety.yaml
- llama_stack/templates/tgi/run.yaml
- llama_stack/templates/together/run.yaml
- llama_stack/templates/vllm-gpu/run.yaml
**Why**
- braintrust provider needs OpenAI API Key set in config for DirectClient to work
```
python llama_stack/scripts/distro_codegen.py 
```
- set API key in client via provider_data
> update template run.yaml to include openai api key for braintrust

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/agents/agents.py
- llama_stack/apis/agents/event_logger.py
- llama_stack/distribution/library_client.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Library client used _server_ side types which was no bueno. The fix here is not the completely correct fix but it is good for enough and for the demo notebook.
> Fixes for library client

- docs/source/distributions/self_hosted_distro/meta-reference-gpu.md
- docs/source/distributions/self_hosted_distro/meta-reference-quantized-gpu.md
- llama_stack/templates/meta-reference-gpu/doc_template.md
- llama_stack/templates/meta-reference-quantized-gpu/doc_template.md
- Addresses issue (#586 )
```
python llama_stack/scripts/distro_codegen.py
```
> Fix issue 586

- llama_stack/providers/utils/inference/__init__.py
Llama-Stack does not support the 3.3 model. So added the support so llama-stack can do inferencing with 3.3 model. 
Verified the run of llama-stack and made sure the model is loaded. 
> Added support for llama 3.3 model

- llama_stack/distribution/library_client.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/providers/inline/telemetry/meta_reference/sqlite_span_processor.py
- llama_stack/providers/utils/telemetry/trace_protocol.py
- llama_stack/providers/utils/telemetry/tracing.py
Adds back all the tracing logic removed from library client. also adds back the logging to agent_instance.
> add tracing back to the lib cli

- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.md
- docs/source/playground/index.md
- docs/source/ui/index.md
- add docs for playground
https://github.com/user-attachments/assets/ddc5edce-eced-4a68-91da-8709005fa531
> [docs] add playground ui docs

- llama_stack/providers/tests/inference/test_text_inference.py
adds a test for the completion api's logprobs parameter
tbd which providers pass this test
> add test for completion logprobs

- docs/source/distributions/self_hosted_distro/ollama.md
> Doc: Ollama command references non-existent file

- llama_stack/distribution/library_client.py
Because of the way library client sets up async io boundaries, tracing was broken with streaming. This PR fixes the tracing to start at the right way to caputre the life time of async gen functions correctly.
Test plan:
Script ran: https://gist.github.com/yanxi0830/f6645129e55ab12de3cd6ec71564c69e
Before: No spans returned for a session
Now: We see spans
> fix trace starting in library client

- llama_stack/cli/stack/build.py
"venv" option is supported but not mentioned in the prompt.
> Add missing venv option in --image-type

- docs/source/references/evals_reference/index.md
> docs: update evals_reference/index.md

- docs/source/getting_started/index.md
Clarifying Python version requirement, fixing a sample command.
> Minor Quick Start documentation updates.

- llama_stack/apis/eval/eval.py
- llama_stack/providers/inline/post_training/torchtune/common/utils.py
Import BaseModel and Field from pydantic
> Import from the right path 

- .github/CODEOWNERS
Add my own github id to CODEOWNERS file
> Update CODEOWNERS - add sixianyi0721 as the owner

- docs/source/distributions/index.md
> fix links for distro

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/inspect/inspect.py
- llama_stack/cli/stack/stack.py
- llama_stack/distribution/inspect.py
- add --version to llama stack CLI 
- add /version endpoint
- run OpenAPI generator for the new endpoint
**CLI**
**endpoint**
> add --version to llama stack CLI & /version endpoint

- docs/source/distributions/self_hosted_distro/remote-vllm.md
> Fixed typo in default VLLM_URL in remote-vllm.md

- distributions/remote-vllm/compose.yaml
- docs/source/distributions/self_hosted_distro/bedrock.md
- docs/source/distributions/self_hosted_distro/cerebras.md
- docs/source/distributions/self_hosted_distro/fireworks.md
- docs/source/distributions/self_hosted_distro/meta-reference-gpu.md
- docs/source/distributions/self_hosted_distro/meta-reference-quantized-gpu.md
- docs/source/distributions/self_hosted_distro/ollama.md
- docs/source/distributions/self_hosted_distro/remote-vllm.md
- docs/source/distributions/self_hosted_distro/tgi.md
- docs/source/distributions/self_hosted_distro/together.md
- docs/zero_to_hero_guide/README.md
- llama_stack/cli/stack/run.py
- llama_stack/distribution/server/server.py
- llama_stack/distribution/start_container.sh
- llama_stack/templates/bedrock/bedrock.py
- llama_stack/templates/cerebras/cerebras.py
- llama_stack/templates/fireworks/fireworks.py
- llama_stack/templates/hf-endpoint/hf_endpoint.py
- llama_stack/templates/hf-serverless/hf_serverless.py
- llama_stack/templates/meta-reference-gpu/meta_reference.py
- llama_stack/templates/meta-reference-quantized-gpu/meta_reference.py
- llama_stack/templates/ollama/ollama.py
- llama_stack/templates/remote-vllm/vllm.py
- llama_stack/templates/tgi/tgi.py
- llama_stack/templates/together/together.py
- llama_stack/templates/vllm-gpu/vllm.py
Rename environment var for consistency
No regressions
> rename LLAMASTACK_PORT to LLAMA_STACK_PORT for consistency with other env vars

- llama_stack/apis/inference/inference.py
- llama_stack/providers/remote/inference/nvidia/openai_utils.py
- tests/client-sdk/agents/test_agents.py
See https://github.com/meta-llama/llama-models/pull/261 for the corresponding PR in llama-models. 
Once these PRs land, you need to work `main` from llama-models (vs. from pypi)
> Rename ipython to tool

- llama_stack/providers/inline/post_training/__init__.py
- llama_stack/providers/inline/post_training/torchtune/common/__init__.py
- llama_stack/providers/inline/post_training/torchtune/common/utils.py
- llama_stack/providers/inline/post_training/torchtune/datasets/__init__.py
- llama_stack/providers/inline/post_training/torchtune/recipes/__init__.py
- llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
add init files to post training folders to make pkg build pick up those files
WIP colab notebook https://colab.research.google.com/drive/1K4Q2wZq232_Bpy2ud4zL9aRxvCWAwyQs?usp=sharing to sharecase the post training APIs
> Add init files to post training folders

- llama_stack/templates/experimental-post-training/build.yaml
- llama_stack/templates/experimental-post-training/run.yaml
as title, add braintrust to experimental-post-training template to run llm as judge based eval for a finetuned model
> add braintrust to experimental-post-training template

- llama_stack/templates/fireworks/fireworks.py
- llama_stack/templates/fireworks/run-with-safety.yaml
- llama_stack/templates/fireworks/run.yaml
Summary:
Fixing issue reported in https://github.com/meta-llama/llama-stack/pull/755/files#r1915696188
Test Plan:
Re-run the config gen
```
pip install .
python3 llama_stack/scripts/distro_codegen.py
```
> Fix fireworks run-with-safety template

- llama_stack/providers/inline/safety/llama_guard/llama_guard.py
Fix this error
```
LLAMA_STACK_BASE_URL="http://localhost:5000" pytest -v tests/client-sdk/inference/test_inference.py
```
> [bugfix] fix llama guard parsing ContentDelta

- llama_stack/distribution/library_client.py
Library client needs to match the impl based on both the path and method. Since path is no longer static, this PR uses the inefficient way of using regexes computed based on the annotated route path to match against the incoming request path. The variables now also can come to the impl from both path or the body, which is also handled cleanly by finding all the regex matches.
LLAMA_STACK_CONFIG="/Users/dineshyv/.llama/distributions/llamastack-together/together-run.yaml" pytest -v tests/client-sdk/agents/test_agents.py
> fix routing in library client

- tests/client-sdk/inference/test_inference.py
- tests/client-sdk/memory/test_memory.py
- tests/client-sdk/safety/test_safety.py
- as title, as API have been updated
```
LLAMA_STACK_BASE_URL="http://localhost:5000" pytest -v tests/client-sdk/
```
> [bugfix] fix client-sdk tests for v1

- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/utils/inference/openai_compat.py
- add completion log probs for fireworks
> fireworks add completion logprobs adapter

- llama_stack/apis/eval/eval.py
Changes Evals API to follow more idiomatic REST
TBD, once i get an approval for rest endpoints
> Idiomatic REST API: Evals

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/inspect/inspect.py
- llama_stack/distribution/inspect.py
- tests/client-sdk/agents/test_agents.py
- tests/client-sdk/inference/test_inference.py
- tests/client-sdk/memory/test_memory.py
- tests/client-sdk/safety/test_safety.py
Client SDK fixes
LLAMA_STACK_CONFIG="/Users/dineshyv/.llama/distributions/llamastack-fireworks/fireworks-run.yaml" pytest -v tests/client-sdk/safety/test_safety.py
LLAMA_STACK_CONFIG="/Users/dineshyv/.llama/distributions/llamastack-fireworks/fireworks-run.yaml" pytest -v tests/client-sdk/memory/test_memory.py
> REST API fixes

- llama_stack/templates/hf-serverless/hf_serverless.py
- llama_stack/templates/hf-serverless/run.yaml
- llama_stack/templates/meta-reference-gpu/meta_reference.py
- llama_stack/templates/meta-reference-gpu/run.yaml
- llama_stack/templates/nvidia/nvidia.py
- llama_stack/templates/nvidia/run.yaml
- llama_stack/templates/ollama/ollama.py
- llama_stack/templates/ollama/run.yaml
- llama_stack/templates/remote-vllm/run.yaml
- llama_stack/templates/remote-vllm/vllm.py
- llama_stack/templates/tgi/run.yaml
- llama_stack/templates/tgi/tgi.py
Add toolgroup defs to all the distribution templates
> add default toolgroups to all providers

- llama_stack/templates/cerebras/cerebras.py
- llama_stack/templates/cerebras/run.yaml
- fix cerebras template
- fix agent test case without shields
```
llama stack run ./llama_stack/templates/cerebras/run.yaml 
LLAMA_STACK_BASE_URL="http://localhost:8321" pytest -v tests/client-sdk/ --html=report.html --self-contained-html
```
> Remove llama-guard in Cerebras template & improve agent test

- llama_stack/distribution/server/server.py
- llama_stack/providers/inline/inference/meta_reference/inference.py
- llama_stack/providers/utils/inference/prompt_adapter.py
- tests/client-sdk/agents/test_agents.py
- tests/client-sdk/inference/test_inference.py
Miscellaneous fixes for meta reference inference
Tests for log probs dont pass because meta reference does not support top_k > 1
> meta reference inference fixes

- llama_stack/distribution/ui/page/distribution/datasets.py
- llama_stack/distribution/ui/page/distribution/eval_tasks.py
- llama_stack/distribution/ui/page/distribution/providers.py
- llama_stack/distribution/ui/page/playground/chat.py
- llama_stack/distribution/ui/page/playground/rag.py
- update playground callsites for v1 api changes
```
cd llama_stack/distribution/ui
streamlit run app.py
```
https://github.com/user-attachments/assets/eace11c6-600a-42dc-b4e7-6948a706509f
> fix playground for v1

- .github/workflows/publish-to-test-pypi.yml
- docs/notebooks/Llama_Stack_Benchmark_Evals.ipynb
- Fix notebook for running benchmark evals
- Add to TestPyPi workflow to run notebook tests
```
pytest -v -s --nbval-lax ./docs/notebooks/Llama_Stack_Benchmark_Evals.ipynb
```
- https://github.com/meta-llama/llama-stack/blob/fix-eval-notebook/docs/notebooks/Llama_Stack_Benchmark_Evals.ipynb
> fix eval notebook & add test to workflow

- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/apis/common/type_system.py
Add missing json_schema_type annotation to ParamType deps
> add json_schema_type to ParamType deps

- docs/source/getting_started/index.md
Fixing small typo in the quick start guide
> Fixing small typo in quick start guide

- .github/workflows/publish-to-docker.yml
This was changed in https://github.com/meta-llama/llama-stack/pull/802
> Fix incorrect image type in publish-to-docker workflow

- llama_stack/providers/tests/test_report.md
MD file for the test results of provider <> inference tests 
1) install `pip install pytest-md-report`
2) Run inference tests with the additions to the commands
`--md-report --md-report-verbose=1 --md-report-output=tgi.md`
Test text model: meta-llama/Llama-3.1-8B-Instruct
Test vision model: meta-llama/Llama-3.2-11B-Vision-Instruct
> test report for v0.1

- llama_stack/templates/fireworks/report.md
- tests/client-sdk/conftest.py
- tests/client-sdk/report.py
Minor bug fix and simplify code
See the updated `llama_stack/templates/fireworks/report.md`
> bug fix for distro report generation

- tests/client-sdk/agents/test_agents.py
- tests/client-sdk/tool_runtime/test_rag_tool.py
- tests/client-sdk/vector_io/test_vector_io.py
See https://github.com/meta-llama/llama-stack/issues/827 for the broader design.
Update client-sdk tests
> [memory refactor][4/n] Update the client-sdk test for RAG

- llama_stack/templates/experimental-post-training/build.yaml
- llama_stack/templates/experimental-post-training/run.yaml
For the completion of https://github.com/meta-llama/llama-stack/pull/835
llama stack build --template experimental-post-training --image-type conda
llama stack run llama_stack/templates/experimental-post-training/run.yaml
> fix experimental-post-training template

- llama_stack/templates/cerebras/report.md
- llama_stack/templates/fireworks/report.md
- llama_stack/templates/ollama/report.md
- llama_stack/templates/tgi/report.md
- llama_stack/templates/together/report.md
- tests/client-sdk/metadata.py
- tests/client-sdk/report.py
- tests/client-sdk/vector_io/test_vector_io.py
Generate distro reports to cover inference, agents, and vector_io. 
Report generated through `/opt/miniconda3/envs/stack/bin/pytest -s -v tests/client-sdk/ --report`
> add distro report

- docs/notebooks/Llama_Stack_Building_AI_Applications.ipynb
- docs/openapi_generator/strong_typing/classdef.py
- docs/openapi_generator/strong_typing/schema.py
- docs/resources/llama-stack-spec.html
- docs/resources/llama-stack-spec.yaml
- llama_stack/distribution/store/registry.py
- tests/client-sdk/tool_runtime/test_rag_tool.py
oneOf should have discriminators so Stainless can generate better code
Going to generate the SDK now and check.
> Update OpenAPI generator to output discriminator

- docs/source/contributing/new_api_provider.md
- tests/client-sdk/README.md
> update doc for client-sdk testing 

- docs/source/contributing/new_api_provider.md
update docs for adding new API providers
> update docs for adding new API providers

- docs/source/index.md
- docs/source/introduction/index.md
README has some new content that is being synced to index.md
> sync readme.md to index.md

- docs/source/references/llama_stack_client_cli_reference.md
Syncs changes from https://github.com/meta-llama/llama-stack-client-python/pull/96
> update the client reference

- docs/source/references/python_sdk_reference/index.md
syncs changes from https://github.com/stainless-sdks/llama-stack-python/blob/main/api.md
> update python sdk reference

- llama_stack/distribution/library_client.py
remove logger handler only in notebook
> remove logger handler only in notebook

- docs/source/getting_started/index.md
Fix documentation to reflect new API
Before:
User> What are the top 5 topics that were explained? Only list succinct bullet points.
inference> I'm ready to help, but we haven't discussed any topics yet! This is the start of our conversation. What would you like to talk about? I can summarize our discussion at the end if you'd like.
Run with the change, observe relevant response
> Update 'first RAG agent' in gettingstarted doc

- .github/workflows/publish-to-docker.yml
The previous curl command was wrong and did not actually check for version correctly (status code was always 200 regardless of what you retrieved.)
Also added tagging latest. cc @wukaixingxp
> Update GH action so it correctly queries for test.pypi, etc.

- docs/source/distributions/index.md
> Fixed typo

- docs/source/building_applications/index.md
- docs/source/building_applications/tools.md
- docs/source/distributions/selection.md
> Fixed multiple typos

- llama_stack/cli/stack/_build.py
- llama_stack/cli/stack/run.py
- llama_stack/distribution/build.py
- llama_stack/distribution/build_container.sh
- llama_stack/distribution/start_container.sh
Fix the issues brought up in https://github.com/meta-llama/llama-stack/issues/870 
Test all combinations of (conda, container) vs. (template, config) combos.
> Ensure llama stack build --config <> --image-type <> works

- llama_stack/cli/stack/run.py
Add win platform run command for stack
https://github.com/meta-llama/llama-stack/pull/889
> Add run win command for stack

- docs/source/distributions/index.md
The current link doesn't work. Also changed docs to be consistent with https://github.com/meta-llama/llama-stack/pull/802.
> Fix link to selection guide and change "docker" to "container"

- docs/source/distributions/self_hosted_distro/sambanova.md
- llama_stack/providers/remote/inference/sambanova/sambanova.py
- llama_stack/templates/sambanova/run.yaml
- Fix typo
- Support Llama 3.3 70B
Run the following scripts and obtain the test results
Script
```
pytest -s -v --providers inference=sambanova llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_chat_completion_streaming --env SAMBANOVA_API_KEY={API_KEY}
```
Result
```
llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_chat_completion_streaming[-sambanova] PASSED
=========================================== 1 passed, 1 warning in 1.26s ============================================
```
Script
```
pytest -s -v --providers inference=sambanova llama_stack/providers/tests/inference/test_text_inference.py::TestInference::test_chat_completion_non_streaming --env SAMBANOVA_API_KEY={API_KEY}
```
Result
``` …
```
> SambaNova supports Llama 3.3

- docs/openapi_generator/pyopenapi/generator.py
- docs/source/distributions/self_hosted_distro/sambanova.md
- llama_stack/cli/verify_download.py
- llama_stack/providers/remote/inference/nvidia/config.py
- llama_stack/templates/nvidia/run.yaml
- llama_stack/templates/sambanova/build.yaml
- llama_stack/templates/sambanova/doc_template.md
- llama_stack/templates/sambanova/run.yaml
- llama_stack/templates/sambanova/sambanova.py
- llama_stack/templates/template.py
minor fixes to hashlib and jinja
> Sec fixes as raised by bandit

- docs/source/distributions/self_hosted_distro/sambanova.md
- llama_stack/providers/remote/inference/nvidia/config.py
- llama_stack/templates/nvidia/run.yaml
- llama_stack/templates/sambanova/build.yaml
- llama_stack/templates/sambanova/doc_template.md
- llama_stack/templates/sambanova/run.yaml
- llama_stack/templates/sambanova/sambanova.py
```
python llama_stack/scripts/distro_codegen.py
```
Run distro code-gen and fixed some sambanova discrepancies.
> Run code-gen

- tests/client-sdk/agents/test_agents.py
> fix rag tests

- docs/source/distributions/selection.md
- docs/source/distributions/self_hosted_distro/ollama.md
- docs/source/getting_started/index.md
- **[docs] Fix misc typos and formatting issues in intro docs**
- **[docs]: Export variables (e.g. INFERENCE_MODEL) in getting_started**
- **[docs] Show that `llama-stack-client configure` will ask for api key**
Miscellaneous fixes in the documentation; not worth reporting an issue.
No code changes. Addressed issues spotted when walking through the guide.
Confirmed locally.
> docs: miscellaneous small fixes

- docs/getting_started.ipynb
- docs/source/getting_started/index.md
- llama_stack/providers/tests/agents/test_agents.py
- llama_stack/providers/tests/tools/test_tools.py
- tests/client-sdk/agents/test_agents.py
datasets.rst was removed from torchtune repo.
Replace a missing 404 document with another one that exists. (Removed it from
the list when memory_optimizations.rst was already pulled.)
> docs, tests: replace datasets.rst with memory_optimizations.rst

- docs/zero_to_hero_guide/README.md
Missing T in import
N/A doc update
- [X ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
> missing T in import

- docs/readme.md
> Fix README.md notebook links

- docs/source/getting_started/index.md
Ran docs build locally
See discussion linked in the issue
> docs: add addn server guidance for Linux users in Quick Start

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- Added a checklist item in the PR template to ensure significant changes are documented in the changelog.
- Updated `CHANGELOG.md` with a placeholder for version `0.2.0`.
- This is an effort to resurrect the consistent usage of the changelog file.
> chore: update PR template to reinforce changelog

- llama_stack/cli/stack/_build.py
- llama_stack/cli/stack/build.py
very small fix I noticed some unused arguments, but this seems like the easiest one to remove since its passed in explicitly. 
> chore: remove unused argument

- CONTRIBUTING.md
- pyproject.toml
- uv.lock
Switch to uv for dependency management and update CONTRIBUTING.md with new setup instructions. Add missing dev dependencies to pyproject.toml and apply minor formatting fixes.
> docs: use uv in CONTRIBUTING guide

- README.md
This would be useful to know for people who arrive at the project for the first time.
> docs: Add license badge to README.md

- llama_stack/providers/remote/inference/vllm/vllm.py
Fixes https://github.com/meta-llama/llama-stack/issues/949.
Verified that the correct chat completion endpoint is called after the change.
Llama Stack server:
```
INFO:     ::1:32838 - "POST /v1/inference/chat-completion HTTP/1.1" 200 OK
18:36:28.187 [END] /v1/inference/chat-completion [StatusCode.OK] (1276.12ms)
```
vLLM server:
```
INFO:     ::1:36866 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```
```bash
LLAMA_STACK_BASE_URL=http://localhost:5002 pytest -s -v tests/client-sdk/inference/test_inference.py -k "test_image_chat_completion_base64 or test_image_chat_completion_non_streaming or test_image_chat_completion_streaming"
================================================================== test session starts =================================================================== …
```
> Fix incorrect handling of chat completion endpoint in remote::vLLM

- docs/zero_to_hero_guide/README.md
Corrects some typographical errors found in the `docs/zero_to_hero_guide/README.md` file.
N/A
> docs: Correct typos in Zero to Hero guide

- docs/source/building_applications/index.md
> doc: getting started notebook

- tests/client-sdk/agents/test_agents.py
Summary:
Test Plan:
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/ --safety-shield meta-llama/Llama-Guard-3-8
all tests passed
> test: fix flaky agent test

- tests/client-sdk/agents/test_agents.py
> test: remove flaky agent test

- docs/source/index.md
[//]: # (- [ ] Added a Changelog entry if the change is significant)
> docs: update index.md for 0.1.2

- requirements.txt
Updated requirements.txt
[//]: # (- [ ] Added a Changelog entry if the change is significant)
> chore: Updated requirements.txt

- README.md
Fixing some wording nits and added small formatting suggestions in the README.md
> docs: Updating wording and nits in the README.md

- rfcs/RFC-0001-llama-stack.md
Fixes urls in the rfc doc (RFC-0001-llama-stack.md)
Also fixes minor markdown linting issues
> docs: Fix url to the llama-stack-spec yaml/html files

- requirements.txt
- uv.lock
The bot just updated the project to 0.1.3 in
https://github.com/meta-llama/llama-stack/commits?author=github-actions%5Bbot%5D but the deps need to be synced.
> build: resync uv and deps on 0.1.3

- llama_stack/cli/stack/configure.py
- llama_stack/cli/stack/run.py
```
before:
$ llama stack run --help
usage: llama stack run [-h] [--port PORT] [--image-name IMAGE_NAME] [--disable-ipv6] [--env KEY=VALUE]
[--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE] [--image-type {conda,container,venv}]
config
start <<<<<<---- the server for a Llama Stack Distribution. You should have already built (or downloaded) and configured the distribution.
After:
$ llama stack run --help
usage: llama stack run [-h] [--port PORT] [--image-name IMAGE_NAME] [--disable-ipv6] [--env KEY=VALUE]
[--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE] [--image-type {conda,container,venv}]
config
Start <<<<<<---- the server for a Llama Stack Distribution. You should have already …
```
> style: fix the capitalization issue

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- tests/client-sdk/agents/test_agents.py
Summary:
titled
Test Plan:
added test in test_agents.py
> feat: log start, complete time to Agent steps

- llama_stack/cli/model/verify_download.py
- llama_stack/cli/verify_download.py
Based on the code https://github.com/meta-llama/llama-stack/blob/6b1773d530e9f168f86beb83a6ec6af73555efe4/llama_stack/cli/download.py#L379 
and test, `verify-download` should only use in `downloaded from Meta`.
```
test: no checklist.chk  file for hf download
$ llama model download --source meta --model-id Llama3.2-1B
Downloading checklist.chk            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━        100.0%  156/156 bytes   -  0:00:00
Downloading tokenizer.model          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━        100.0%  2.2/2.2 MB      -  0:00:00
Downloading params.json              ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━        100.0%  220/220 bytes   -  0:00:00
Downloading …
```
> style: update verify-download help text

- llama_stack/cli/download.py
Based on the cade:
https://github.com/meta-llama/llama-stack/blob/6b1773d530e9f168f86beb83a6ec6af73555efe4/llama_stack/cli/download.py#L454
and the test, it can use comma to specify multiple model ids. So update the usage.
```
$ llama model download --source meta --model-id Llama3.2-1B,Llama3.2-3B
Please provide the signed URL for model Llama3.2-1B you received via email after visiting https://www.llama.com/llama-downloads/ (e.g., https://llama3-1.llamameta.net/*?Policy...):
Downloading checklist.chk            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━        100.0%  156/156 bytes   -  0:00:00
Downloading tokenizer.model          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━        100.0%  2.2/2.2 MB …
```
> style: update download help text

- llama_stack/distribution/library_client.py
- llama_stack/strong_typing/auxiliary.py
- llama_stack/strong_typing/classdef.py
- llama_stack/strong_typing/deserializer.py
- llama_stack/strong_typing/inspection.py
- llama_stack/strong_typing/serializer.py
- Closes #1142 
- Root cause is due to having `Union[str, AgenToolGroupWithArgs]`
- Test with script described in issue. 
- Print out final converted pydantic object
> fix: direct client pydantic type casting

- llama_stack/cli/table.py
- llama_stack/distribution/library_client.py
- llama_stack/providers/remote/inference/nvidia/nvidia.py
- llama_stack/providers/remote/inference/nvidia/utils.py
- replace prints in codebase with logger
- update print_table to use rich Table
- library client script in https://github.com/meta-llama/llama-stack/pull/1145
```
llama stack list-providers
```
> style: remove prints in codebase

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/inference/inference.py
- llama_stack/distribution/routers/routers.py
- llama_stack/providers/utils/inference/prompt_adapter.py
- tests/client-sdk/agents/test_agents.py
- tests/client-sdk/inference/test_text_inference.py
Summary:
titled
Test Plan:
added tests and
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/ --safety-shield meta-llama/Llama-Guard-3-8B
> feat: support tool_choice = {required, none, <function>}

- llama_stack/providers/registry/inference.py
- llama_stack/providers/remote/inference/passthrough/__init__.py
- llama_stack/providers/remote/inference/passthrough/config.py
- llama_stack/providers/remote/inference/passthrough/passthrough.py
- llama_stack/templates/passthrough/build.yaml
- llama_stack/templates/passthrough/run.yaml
In this PR, we implement a passthrough inference provider that works for any endpoints that respect llama stack inference API definition.
config some endpoint that respect llama stack inference API definition and got the inference results successfully
> feat: inference passthrough provider 

- CONTRIBUTING.md
- pyproject.toml
- uv.lock
Clarify when to update documentation, explain `uv sync --extra dev` and OpenAPI generation, and specify where generated docs are stored.
> docs: improve API contribution guidelines

- llama_stack/cli/model/list.py
```
$ llama model list --help
usage: llama model list [-h] [--show-all] [--downloaded]
Show available llama models
options:
--show-all            Show all models (not just defaults)
--downloaded          List the downloaded models
$ llama model list --downloaded
+-------------+----------+---------------------+
| Model       | Size     | Modified Time       |
+-------------+----------+---------------------+
| Llama3.2-1B | 2.31 GB  | 2025-02-16 13:38:04 |
+-------------+----------+---------------------+
| Llama3.1-8B | 14.97 GB | 2025-02-16 10:36:37 |
+-------------+----------+---------------------+
```
[//]: # (If resolving an issue, …
> feat: add a option to list the downloaded models

- docs/source/concepts/index.md
- docs/source/distributions/configuration.md
- llama_stack/scripts/run_client_sdk_tests.py
- tests/client-sdk/report.py
Create a script for running all client-sdk tests on Async Library client, with the option to generate report
```
python llama_stack/scripts/run_client_sdk_tests.py --templates together fireworks --report
```
> script for running client sdk tests

- llama_stack/providers/inline/post_training/torchtune/recipes/lora_finetuning_single_device.py
You are now able to run a training cycle on CPU. This is useful for debugging and testing purposes.
On a Mac machine without CUDA devices:
```
17:00:24.417 [START] /v1/post-training/supervised-fine-tune
DEBUG 2025-02-18 12:00:24,419 torchtune.utils._logging:60: Setting manual seed to local seed 3268931494. Local seed is seed + rank = 3268931494 + 0
INFO 2025-02-18 12:00:24,463 torchtune.utils._logging:64: Identified model_type = Llama3_2. Ignoring output.weight in checkpoint in favor of the tok_embedding.weight tied weights.
INFO 2025-02-18 12:00:46,699 llama_stack.providers.inline.post_training.torchtune.recipes.lora_finetuning_single_device:182: Model is initialized with precision …
```
> feat: Enable CPU training for torchtune

- llama_stack/providers/remote/inference/nvidia/nvidia.py
Fixes logging import and the logger instance creation
cc: @dglogo
> fix: add logging import

- llama_stack/providers/inline/inference/meta_reference/inference.py
- llama_stack/providers/remote/inference/bedrock/models.py
- llama_stack/providers/remote/inference/cerebras/models.py
- llama_stack/providers/remote/inference/databricks/databricks.py
- llama_stack/providers/remote/inference/fireworks/models.py
- llama_stack/providers/remote/inference/groq/groq.py
- llama_stack/providers/remote/inference/nvidia/models.py
- llama_stack/providers/remote/inference/ollama/ollama.py
- llama_stack/providers/remote/inference/sambanova/models.py
- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/remote/inference/together/models.py
- llama_stack/providers/remote/inference/vllm/vllm.py
- llama_stack/providers/utils/inference/model_registry.py
Quick test by running:
```
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk
```
> chore: slight renaming of model alias stuff

- docs/source/building_applications/rag.md
- docs/source/building_applications/tools.md
This PR improves the documentation in several ways:
- **Fixed incorrect link in `tools.md`**  to ensure all references point to the correct resources.
- **Added instructions for running the `code-interpreter` agent in a Podman container**, helping users configure and execute the tool in containerized environments.
- **Introduced an unregister command for single and multiple vector databases**, making it easier to manage vector DBs.
- **Provided a simple example script for using the `code-interpreter` agent**, giving users a practical reference for implementation.
These updates enhance the clarity, usability, and completeness of the documentation.
The following steps were performed to …
> docs: Fix Links, Add Podman Instructions, Vector DB Unregister, and Example Script

- docs/source/distributions/remote_hosted_distro/nvidia.md
- llama_stack/providers/remote/inference/nvidia/models.py
- llama_stack/providers/remote/inference/nvidia/nvidia.py
- llama_stack/templates/nvidia/nvidia.py
- llama_stack/templates/nvidia/run.yaml
- tests/client-sdk/conftest.py
- tests/client-sdk/inference/test_embedding.py
add /v1/inference/embeddings implementation to NVIDIA provider
**open topics** -
- *asymmetric models*. NeMo Retriever includes asymmetric models, which are models that embed differently depending on if the input is destined for storage or lookup against storage. the /v1/inference/embeddings api does not allow the user to indicate the type of embedding to perform. see https://github.com/meta-llama/llama-stack/issues/934
- *truncation*. embedding models typically have a limited context window, e.g. 1024 tokens is common though newer models have 8k windows. when the input is larger than this window the endpoint cannot perform its designed function. two options: 0. return an error so the user can reduce the input size and retry; 1. perform truncation for the user and proceed (common …
> feat(providers): add NVIDIA Inference embedding provider and tests

- tests/client-sdk/agents/test_agents.py
Summary:
Test Plan:
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/agents/test_agents.py::test_rag_agent --safety-shield meta-llama/Llama-Guard-3-8B
> test: fix test_rag_agent test

- tests/client-sdk/agents/test_agents.py
> test: do not overwrite agent_config

- docs/source/distributions/selection.md
- Keep ollama hyperlink name  with others(`link` to `Guide`)
- Correct name `building_distro.md` , miss `.md` cause `404`
> docs: small fixes

- llama_stack/distribution/routers/routers.py
- llama_stack/providers/utils/inference/prompt_adapter.py
- tests/client-sdk/agents/test_agents.py
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack/pull/1234).
* __->__ #1234
* #1214
> test: fix test_tool_choice

- requirements.txt
- uv.lock
PR #1139 caused pre-commit failures on main likely due to improper rebase before merge. run pre-commit on main and commit the changes
see runs here: https://github.com/meta-llama/llama-stack/actions/runs/13511146480/job/37751484287
> fix: pre-commit updates

- docs/getting_started.ipynb
update to install properly in system python in colab
> fix: Update getting_started.ipynb

- docs/source/index.md
> fix: update index.md to include 0.1.4

- docs/zero_to_hero_guide/README.md
It should changed by https://github.com/meta-llama/llama-stack/commit/8585b95a28b31d8bfe43fd13bd699ad0190fd1bc, so show `404` when click it.
> chore: update the zero_to_hero_guide doc link

- .gitmodules
to the llama-stack-client-swift repo - PR: https://github.com/meta-llama/llama-stack-client-swift/pull/22
> chore: removed executorch submodule

- llama_stack/providers/inline/telemetry/meta_reference/sqlite_span_processor.py
Our tests sometimes error out with
```
========================== 11 passed, 342 warnings in 58.86s ==========================
Error exporting span to SQLite: Cannot operate on a closed database.
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x000000012af04280)
Current thread 0x00000001fa29c240 (most recent call first):
<no Python frame>
```
Usually able to repro this by running 10 times.
The proposed fix is to use threadsafe var for creating sqlite connection to ensure connection is only used by one thread. Not 100% if this is the fix, but am not able to repro with this.
Run 10 times and saw no more errors
```
for i in {1..10}; do …
```
> fix: sqlite conn

- docs/source/distributions/remote_hosted_distro/nvidia.md
- llama_stack/providers/remote/inference/nvidia/models.py
- llama_stack/templates/nvidia/run.yaml
add the NeMo Retriever Embedding models from https://docs.nvidia.com/nim/nemo-retriever/text-embedding/latest/support-matrix.html
> feat: add nemo retriever text embedding models to nvidia inference provider

- tests/client-sdk/inference/test_text_inference.py
No need to have complex tool prompt format related machinery in the tests.
```bash
LLAMA_STACK_CONFIG=ollama pytest -s -v tests/client-sdk/inference/test_text_inference.py --inference-model=meta-llama/Llama-3.2-3B-Instruct --vision-inference-model=""
```
> fix(test): no need to specify tool prompt format explicitly in tests

- llama_stack/cli/stack/stack.py
Missed this one additional import in https://github.com/meta-llama/llama-stack/pull/1313
> fix: Incorrect import path for print_subcommand_description()

- docs/source/getting_started/index.md
A couple of users have asked this question so I thought it would be a good idea to add a link.
> docs: Add link to distributions guide in quick start guide

- docs/source/distributions/building_distro.md
https://github.com/meta-llama/llama-stack/blob/55eb257459f5f891d7e570740e816eed950131b3/llama_stack/cli/stack/run.py#L22
https://github.com/meta-llama/llama-stack/blob/55eb257459f5f891d7e570740e816eed950131b3/llama_stack/cli/stack/_build.py#L103
> docs: update build doc

- llama_stack/distribution/build_container.sh
> chore: add container cmd check

- llama_stack/distribution/build_conda_env.sh
> chore: update cmd check

- docs/source/distributions/self_hosted_distro/meta-reference-gpu.md
- docs/source/distributions/self_hosted_distro/meta-reference-quantized-gpu.md
- docs/source/references/llama_cli_reference/download_models.md
- docs/source/references/llama_cli_reference/index.md
- llama_stack/templates/meta-reference-gpu/doc_template.md
- llama_stack/templates/meta-reference-quantized-gpu/doc_template.md
Since released the `--downloaded` option, so update the related documents.
> docs: update the downloaded list doc

- llama_stack/providers/inline/telemetry/meta_reference/sqlite_span_processor.py
Summary:
addresses https://github.com/meta-llama/llama-stack/pull/1282#discussion_r1972546802
Test Plan:
> chore: better raise

- docs/source/getting_started/index.md
Summary:
in case user sets it to a small model with poor tool use capability
Test Plan:
copy and paste to notebook and ran
> docs: update user prompt example

- llama_stack/distribution/routers/routers.py
Summary:
messes tests up
Test Plan:
run agent tests
> fix: don't update tool_config inplace

- docs/source/building_applications/agent.md
- docs/source/building_applications/agent_execution_loop.md
- docs/source/building_applications/evals.md
- docs/source/building_applications/index.md
- docs/source/building_applications/rag.md
- docs/source/building_applications/tools.md
Summary:
- [new] Agent concepts (session, turn)
- [new] how to write custom tools
- [new] non-streaming API and how to get outputs
- [update] remaining `memory` -> `rag` rename
- [new] note importance of `instructions`
Test Plan:
read
> docs: update Agent documentation

- docs/source/building_applications/tools.md
For https://github.com/meta-llama/llama-stack/actions/runs/13614599967/job/38056042207?pr=1348
```
Fixing docs/source/building_applications/tools.md
check for added large files..............................................Passed
fix end of files.........................................................Passed
Insert license in comments...............................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed
blacken-docs.............................................................Passed
uv-lock..................................................................Pas …
```
> fix: fix pre-commit check issue

- docs/source/building_applications/agent_execution_loop.md
- add missing `import`
- add client define
- update `attachments` to `documents`, https://github.com/meta-llama/llama-stack-client-python/commit/40da0d0e76a664aeb00333d536737f477be30299
> docs: update agent_execution_loop example code

- docs/source/distributions/self_hosted_distro/tgi.md
- llama_stack/templates/tgi/tgi.py
> docs: fix typo

- llama_stack/apis/inference/inference.py
- llama_stack/distribution/resolver.py
- llama_stack/distribution/routers/__init__.py
- llama_stack/distribution/routers/routers.py
- llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
Inference router computes the token usage related metrics for all providers and returns the metrics as part of response and also logs to telemetry.
LLAMA_STACK_DISABLE_VERSION_CHECK=true llama stack run ~/.llama/distributions/fireworks/fireworks-run.yaml
```
curl --request POST \
--url http://localhost:8321/v1/inference/chat-completion \
--header 'content-type: application/json' \
--data '{
"model_id": "meta-llama/Llama-3.1-70B-Instruct",
"messages": [
{
"content": {
"type": "text",
"text": "where do humans live"
}
}
],
"stream": false
}' | jq .
{
"metrics": [
{
"trace_id": "yjv1tf0jS1evOyPm",
"span_id": "WqYKvg0_",
"timestamp": "2025-02-27T18:55:10.770903Z",
"attributes": {
"model_id": "meta-llama/Llama-3.1-70B-Instruct",
"provider_id": "fireworks"
},
"type": "metric", …
```
> feat: record token usage for inference API

- docs/source/distributions/building_distro.md
currently logcat is not documented for build && run. Add documentation in building_distro.md
> docs: add information on how to set log level before running

- llama_stack/distribution/server/server.py
> chore: log exception

- docs/source/building_applications/rag.md
> docs: improve rag doc

- CHANGELOG.md
- scripts/gen-changelog.py
This is a follow-up on https://github.com/meta-llama/llama-stack/pull/1440#discussion_r1982666501. 
cc @yanxi0830 Would you like to help me include this as part of the release workflow?
> ci: Add script to generate changelog

- .cursor/rules/general.mdc
- tests/unit/server/test_resolver.py
Starting to create unit tests to cover critical (and mostly undocumented) provider resolution and routing logic.
Unit tests
> test: first unit test for resolver

- docs/source/distributions/remote_hosted_distro/index.md
Based on the client output changed, so the output is incorrect:
https://github.com/meta-llama/llama-stack-client-python/blob/458e20702b5aa8f435ac5ce114fee9252b751d25/src/llama_stack_client/lib/cli/models/models.py#L52
and https://github.com/meta-llama/llama-stack/pull/1348#pullrequestreview-2654971315 previous discussion that no need to maintain the output, so remove it.
> chore: remove the incorrect output

- pyproject.toml
- requirements.txt
- uv.lock
> build: bump llama-stack-client version

- MANIFEST.in
> build: include .md

- llama_stack/templates/open_benchmark/build.yaml
- llama_stack/templates/open_benchmark/run.yaml
- pyproject.toml
- requirements.txt
- uv.lock
> build: add 'tiktoken' to deps

- llama_stack/providers/remote/inference/together/together.py
- return results for together's get_params
- fix issue
- the `return params` was accidentally deleted in https://github.com/meta-llama/llama-stack/pull/1362/files#diff-d9345410ea64589cee96487b22eab0d45f7497a80c25dca295cecd254decb204
```
npm test examples
```
> fix: return result for together's get_params

- tests/integration/scoring/test_scoring.py
- fix scoring test
```
LLAMA_STACK_CONFIG=fireworks pytest -v tests/integration/scoring/test_scoring.py --text-model meta-llama/Llama-3.3-70B-Instruct --judge-model meta-llama/Llama-3.3-70B-Instruct
```
> fix: fix scoring tests

- tests/integration/inference/test_vision_inference.py
> test: image downloading is flaky

- CHANGELOG.md
Adds v0.1.6 release notes to changelog.
> docs: Add v0.1.6 release notes to changelog

- llama_stack/providers/inline/vector_io/faiss/faiss.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/remote/tool_runtime/bing_search/bing_search.py
- llama_stack/providers/remote/tool_runtime/brave_search/brave_search.py
- llama_stack/providers/remote/tool_runtime/tavily_search/tavily_search.py
- llama_stack/providers/remote/tool_runtime/wolfram_alpha/wolfram_alpha.py
- llama_stack/providers/utils/kvstore/mongodb/mongodb.py
This PR converts blocking calls for in built tools like wolfram, brave, tavily and bing into non blocking async calls
pytest -s -v tool_runtime/test_builtin_tools.py --stack-config=together --text-model=meta-llama/Llama-3.1-8B-Instruct
Used the command above to get the below results
> chore: made inbuilt tools blocking calls into async non blocking calls

- docs/getting_started.ipynb
Summary:
model is sometimes reluctant to use tools by default.
Test Plan:
run in notebook
> docs: update prompt for websearch example

- docs/source/building_applications/evals.md
> docs: improve eval doc

- docs/source/distributions/self_hosted_distro/ollama.md
- docs/zero_to_hero_guide/README.md
- llama_stack/templates/ollama/doc_template.md
It should changed in this pr https://github.com/meta-llama/llama-stack/pull/1190/files#diff-53e3f35ced54ee5e57dc8b0d3b04770ed84f2f6434c6f492f42569b3c2810ecd
> docs: update ollama doc url

- llama_stack/providers/remote/inference/together/together.py
Uses together async client instead of sync client
Command to run the test is in the image below(2 tests fail, and they were failing for the old stable version as well with the same errors.)
> chore: Together async client

- llama_stack/distribution/server/server.py
Summary:
Test Plan:
ERROR    2025-03-10 10:53:00,804 __main__:239 server: Error executing endpoint route='/v1/inference/chat-completion'
method='post'
> fix: server logging

- tests/integration/README.md
It should use `export` for env var for api key.
> docs: improve integration test doc

- docs/source/references/llama_cli_reference/index.md
**Description:** Fixes some small nits in the llama CLI reference
Note: There are a few nits in this PR, but also has some small suggestions, feel free to close if not necessary
> docs: Small nits in llama CLI reference

- llama_stack/templates/open-benchmark/open_benchmark.py
- llama_stack/templates/template.py
> fix: fix precommit

- llama_stack/apis/inference/inference.py
- llama_stack/distribution/library_client.py
- llama_stack/distribution/request_headers.py
- llama_stack/distribution/resolver.py
- llama_stack/distribution/routers/__init__.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/server/server.py
- llama_stack/distribution/utils/context.py
- llama_stack/distribution/utils/tests/test_context.py
- llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
This PR adds back the changes in #1300  which were reverted in  #1476 .
It also adds logic to preserve context variables across asyncio boundary. this is needed with the library client since the async generator logic yields control to code outside the event loop, and on resuming, does not have the same context as before and this requires preserving the context vars.
address #1477 
```
curl --request POST \
--url http://localhost:8321/v1/inference/chat-completion \
--header 'content-type: application/json' \
--data '{
"model_id": "meta-llama/Llama-3.1-70B-Instruct",
"messages": [
{
"content": {
"type": "text",
"text": "where do humans live"
}
}
],
"stream": false
}' | jq .
{
"metrics": [
{
"trace_id": "kCZwO3tyQC-FuAGb",
"span_id": "bsP_5a5O",
"timestamp": …
```
> feat: Add back inference metrics and preserve context variables across asyncio boundary

- llama_stack/distribution/utils/context.py
This fixes the build error
pre-commit run --all-files
check for merge conflicts................................................Passed
trim trailing whitespace.................................................Passed
check for added large files..............................................Passed
fix end of files.........................................................Passed
Insert license in comments...............................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed
blacken-docs.............................................................Passed
uv-lock..................................................................Passed …
> fix: fix build error in context.py

- llama_stack/distribution/routers/routers.py
> fix: logging

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Summary:
Refactoring only.
Centralize logic to preprocess toolgroup to one place. 
Test Plan:
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/api/agents/test_agents.py --safety-shield meta-llama/Llama-Guard-3-8B
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack/pull/1381).
* #1384
* __->__ #1381
> chore: refactor Agent toolgroup processing

- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
Summary:
Test Plan:
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/integration/agents/test_agents.py --safety-shield meta-llama/Llama-Guard-3-8B --text-model meta-llama/Llama-3.1-8B-Instruct
> chore: simplify _get_tool_defs

- .github/workflows/unit-tests.yml
additional artifacts make test results more human-readable
Ran locally
> ci: add html report to unit test artifacts

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
Summary:
Test Plan:
sh docs/openapi_generator/run_openapi_generator.sh
> fix: openapi spec gen

- llama_stack/cli/model/prompt_format.py
Fixes pre-commit check failure after merging https://github.com/meta-llama/llama-stack/pull/1010: https://github.com/meta-llama/llama-stack/actions/runs/13847489719/job/38748770971
> fix: Fix pre-commit check

- docs/source/distributions/ondevice_distro/android_sdk.md
Description: Fixes the trailing whitespace error thats coming up on main
> docs: Fix trailing whitespace error

- llama_stack/scripts/generate_prompt_format.py
The generate_response_prompt had an import error, fixed that error.
> fix: fixed import error

- docs/source/references/llama_stack_client_cli_reference.md
**Description:** Updates the client example output as well as add a suggested formatting for some of the required and optional cli flags. 
If the re-formatting is unnecessary, I can remove it from this PR and just have this fix the example output
> docs: Fixing outputs in client cli and formatting suggestions

- docs/source/distributions/building_distro.md
fixed broken tip in distro build docs
Local docs build
> docs: fixed broken tip in distro build docs

- .cursor/rules/general.mdc
I think this was included accidentally via https://github.com/meta-llama/llama-stack/pull/1475. 
@raghotham @ashwinb let me know if it's intentional to include this.
> chore: Remove unused cursor rules

- .github/workflows/integration-tests.yml
Run additional tests in a matrix to accelerate the process and clearly identify failing providers.
> ci(ollama): run more integration tests

- pyproject.toml
- scripts/gen-changelog.py
> chore: enable ruff for ./scripts too

- CONTRIBUTING.md
fix broken test path in CONTRIBUTING.md
> docs: fix broken test path in CONTRIBUTING.md

- llama_stack/providers/inline/tool_runtime/code_interpreter/code_interpreter.py
Made code interpreter tool call to be async such that its non blocking
pytest  -s -v tests/integration/agents/test_agents.py --stack-config=together --text-model=meta-llama/Llama-3.3-70B-Instruct
> chore: Make code interpreter async

- .github/workflows/changelog.yml
This is a follow up from https://github.com/meta-llama/llama-stack/pull/1463. cc @yanxi0830
> ci: Add scheduled workflow to update changelog

- llama_stack/distribution/ui/page/distribution/datasets.py
- llama_stack/distribution/ui/page/distribution/eval_tasks.py
- llama_stack/distribution/ui/page/distribution/models.py
- llama_stack/distribution/ui/page/distribution/providers.py
- llama_stack/distribution/ui/page/distribution/resources.py
- llama_stack/distribution/ui/page/distribution/scoring_functions.py
- llama_stack/distribution/ui/page/distribution/shields.py
- llama_stack/distribution/ui/page/distribution/vector_dbs.py
- llama_stack/distribution/ui/page/evaluations/app_eval.py
- llama_stack/distribution/ui/page/evaluations/native_eval.py
- llama_stack/distribution/ui/page/playground/chat.py
- llama_stack/distribution/ui/page/playground/rag.py
Fixed import errors for playground and ui
> fix: Fixed import errors for UI and playground

- docs/source/index.md
- docs/source/introduction/index.md
This is a follow-up of https://github.com/meta-llama/llama-stack/issues/965 to avoid mentioning exclusive support on Llama models.
> docs: Remove mentions of focus on Llama models

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/tools/rag_tool.py
> docs: add documentation for RAGDocument

- docs/source/building_applications/tools.md
> docs: update for mcp tools

- llama_stack/models/llama/llama3/tool_utils.py
> fix: better tool call parsing error message

- docs/getting_started.ipynb
- docs/notebooks/Llama_Stack_Agent_Workflows.ipynb
- docs/notebooks/Llama_Stack_RAG_Lifecycle.ipynb
- docs/source/building_applications/agent.md
- docs/source/building_applications/agent_execution_loop.md
- docs/source/building_applications/evals.md
- docs/source/building_applications/rag.md
- docs/source/building_applications/tools.md
- docs/source/getting_started/index.md
- llama_stack/distribution/ui/page/playground/rag.py
- tests/integration/agents/test_agents.py
> feat(api): simplify client imports

- llama_stack/distribution/store/registry.py
- tests/unit/registry/test_registry.py
We need to be able to handle stale registry entries gracefully. More needs to be done when we are deleting important attributes from resources which could have been persisted. But at the very least, the server cannot die.
Added unit tests
> fix: handle registry errors gracefully

- docs/getting_started.ipynb
As titled, due to the recent upgrade of colab. 
Pandas was out of sync with numpy breaking `llama stack build` in colab
> fix: install pandas and numpy beforehand to avoid version mismatch

- CONTRIBUTING.md
Propose new contribution guidance.
> docs: propose new contribution guidance

- llama_stack/distribution/server/server.py
This will prevent 'operations' from being flooded 
Before
After
> feat(telemetry): normalize path

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/common/job_types.py
- llama_stack/apis/eval/eval.py
- llama_stack/distribution/routers/routers.py
- llama_stack/providers/inline/eval/meta_reference/eval.py
- tests/integration/eval/test_eval.py
- We cannot directly return a literal type
> Note: this is not final jobs API change
> fix: fix jobs api literal return type

- llama_stack/distribution/server/server.py
- llama_stack/providers/inline/telemetry/meta_reference/sqlite_span_processor.py
- llama_stack/providers/inline/telemetry/meta_reference/telemetry.py
- llama_stack/providers/utils/telemetry/tracing.py
1) Uses otel compatible id generation for stack
2) Stack starts returning trace id info in the header of response
3) We inject the same trace id that we have into otel in order to force it to use our trace ids.
```
curl -i --request POST \
--url http://localhost:8321/v1/inference/chat-completion \
--header 'content-type: application/json' \
--data '{
"model_id": "meta-llama/Llama-3.1-70B-Instruct",
"messages": [
{
"content": {
"type": "text",
"text": "where do humans live"
}
}
],
"stream": false
}'
HTTP/1.1 200 OK
date: Fri, 21 Mar 2025 21:51:19 GMT
server: uvicorn
content-length: 1712
content-type: application/json
x-trace-id: 595101ede31ece116ebe35b26d67e8cf
{"metrics":[{"metric":"prompt_tokens","value":10,"unit":null},{"metric":"completion_tokens","value":320,"unit":null …
```
> feat: use same trace ids in stack and otel

- llama_stack/apis/agents/agents.py
- llama_stack/distribution/library_client.py
- llama_stack/distribution/server/endpoints.py
- llama_stack/distribution/server/server.py
- llama_stack/providers/inline/agents/meta_reference/agent_instance.py
- llama_stack/schema_utils.py
> feat(telemetry): clean up spans

- docs/source/distributions/kubernetes_deployment.md
* Removes the use of `huggingface-cli` 
* Simplifies HF cache mount path
* Simplifies vLLM server startup command
* Separates PVC/secret creation from deployment/service
* Fixes a typo: "pod" should be "deployment"
> docs: Simplify vLLM deployment in K8s deployment guide

- CHANGELOG.md
This updates the changelog manually for now until we fix the changelog workflow that requires change in repo settings (see [my comment in Discord](https://discordapp.com/channels/1257833999603335178/1337516002535014492/1354127000138289223)).
> docs: Add changelog for v0.1.7 and v0.1.8

- docs/getting_started.ipynb
> fix: fix imports for mcp registration in notebook

- docs/getting_started.ipynb
> fix: update mcp commands in getting_started.ipynb

- tests/integration/agents/test_agents.py
- this is a flaky test dependent on model output
> fix: skip code interp

- llama_stack/providers/remote/vector_io/milvus/milvus.py
This PR converts blocking Milvus Client calls to non-blocking.
Another one for https://github.com/meta-llama/llama-stack/issues/1489
I ran the integration tests from https://github.com/meta-llama/llama-stack/pull/1467 with:
```python
pytest -s -v tests/integration/vector_io/test_vector_io.py \
--stack-config inference=sentence-transformers,vector_io=inline::milvus \
--embedding-model all-miniLM-L6-V2  --env MILVUS_DB_PATH=/tmp/moo.db
INFO     2025-03-28 21:35:22,726 tests.integration.conftest:41 tests: Setting DISABLE_CODE_SANDBOX=1 for macOS          
/Users/farceo/dev/llama-stack/.venv/lib/python3.10/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures …
```
> chore: Updating Milvus Client calls to be non-blocking

- tests/integration/README.md
Update README for integration tests
> docs: Update readme for integration tests

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- docs/openapi_generator/pyopenapi/utility.py
- llama_stack/apis/tools/tools.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/routers/routing_tables.py
- llama_stack/providers/inline/tool_runtime/code_interpreter/code_interpreter.py
- llama_stack/providers/inline/tool_runtime/rag/memory.py
- llama_stack/providers/remote/tool_runtime/bing_search/bing_search.py
- llama_stack/providers/remote/tool_runtime/brave_search/brave_search.py
- llama_stack/providers/remote/tool_runtime/model_context_protocol/model_context_protocol.py
- llama_stack/providers/remote/tool_runtime/tavily_search/tavily_search.py
- llama_stack/providers/remote/tool_runtime/wolfram_alpha/wolfram_alpha.py
Don't return list for runtime tools. Instead return Response object for pagination and consistency with other APIs.
> fix(api): don't return list for runtime tools

- docs/readme.md
- docs/requirements.txt
- docs/source/getting_started/index.md
> docs: fixing sphinx imports

- docs/source/distributions/self_hosted_distro/remote-vllm.md
- llama_stack/templates/remote-vllm/doc_template.md
Add the content to use AMD GPU as the vLLM server.  Split the original part to two sub chapters,
1. AMD vLLM server
2. NVIDIA vLLM server (orignal)
> docs: Update remote-vllm.md with AMD GPU vLLM server supported.

- .github/workflows/gha_workflow_llama_stack_tests.yml
Fix hash for v3.0.1 tag for a github action.
> chore: fix hash for thollander/actions-comment-pull-request

- CHANGELOG.md
These are missing and changelog doc automation is not working yet due to missing permissions for GitHub Actions: https://dev.to/suzuki0430/how-to-enable-the-allow-github-actions-to-create-and-approve-pull-requests-option-when-its-grayed-out-3e1i
> docs: Add recent release notes

- docs/source/playground/index.md
- llama_stack/distribution/ui/README.md
- llama_stack/distribution/ui/requirements.txt
- pyproject.toml
- uv.lock
* Manage UI deps in pyproject
* Use a new "ui" dep group to pull the deps with "uv"
* Simplify the run command
* Bump versions in requirements.txt
> chore: simplify running the demo UI

- llama_stack/models/llama/llama4/args.py
- llama_stack/models/llama/llama4/model.py
See:
- https://github.com/meta-llama/llama-models/pull/322
- https://github.com/meta-llama/llama-models/pull/320
> fix: Mirror llama4 rope scaling fixes, small model simplify

- docs/source/distributions/kubernetes_deployment.md
See https://github.com/meta-llama/llama-stack/pull/1913#issuecomment-2790153778
> docs: Avoid bash script syntax highlighting for dark mode

- docs/source/getting_started/index.md
Use llama3.2:3b for consistency.
> docs: fix model name

- llama_stack/distribution/ui/page/playground/rag.py
This PR fixes two issues with the RAG page of the Playground UI:
1. When the user modifies a configurable setting via a widget (e.g., system prompt, temperature, etc.), the agent is not recreated. Thus, the change has no effect and the user gets no indication of that.
2. After the first issue is fixed, it becomes possible to recreate the agent mid-conversation or even mid-generation. To mitigate this, widgets related to agent configuration are now disabled when a conversation is in progress (i.e., when the chat is non-empty). They are automatically enabled again when the user resets the chat history.
- Launch the Playground and go to the RAG page;
- Select the vector DB ID;
- Send a message to the agent via the chat;
- The widgets in charge of the agent parameters will become disabled at …
> fix: Playground RAG page errors

- tests/verifications/openai_api/test_chat_completion.py
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack/pull/1933).
* #1934
* __->__ #1933
> test(verification): add streaming tool calling test

- docs/source/distributions/kubernetes_deployment.md
Fixes a couple of errors in PVC/Secret setup and adds context for expected Hugging Face token
> docs: fix errors in kubernetes deployment guide

- llama_stack/models/llama/llama3/tool_utils.py
- tests/unit/models/llama/llama3/test_tool_utils.py
titled
added new unit tests
pytest -s -v tests/unit/models/llama/llama3/test_tool_utils.py
> feat: support '-' in tool names

- .github/workflows/integration-tests.yml
- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/inspect/inspect.py
- llama_stack/apis/providers/providers.py
- llama_stack/distribution/inspect.py
- llama_stack/distribution/library_client.py
- llama_stack/distribution/providers.py
- llama_stack/distribution/resolver.py
- llama_stack/distribution/routers/routers.py
- llama_stack/distribution/server/server.py
- llama_stack/distribution/stack.py
- llama_stack/distribution/utils/config.py
- llama_stack/providers/datatypes.py
- llama_stack/providers/remote/inference/ollama/ollama.py
The `/v1/providers` now reports the health status of each
provider when implemented.
```
curl -L http://127.0.0.1:8321/v1/providers|jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  4072  100  4072    0     0   246k      0 --:--:-- --:--:-- --:--:--  248k
{
"data": [
{
"api": "inference",
"provider_id": "ollama",
"provider_type": "remote::ollama",
"config": {
"url": "http://localhost:11434"
},
"health": {
"status": "OK"
}
},
{
"api": "vector_io",
"provider_id": "faiss",
"provider_type": "inline::faiss",
"config": {
"kvstore": {
"type": "sqlite",
"namespace": null,
"db_path": "/Users/leseb/.llama/distributions/ollama/faiss_store.db"
}
},
"health": {
"status": "Not Implemented",
"message": "Provider does not …
```
> feat: add health to all providers through providers endpoint

- docs/source/distributions/ondevice_distro/android_sdk.md
Add updates to android site readme for 0.2.2
> docs: 0.2.2 doc updates

- docs/source/building_applications/tools.md
This was not caught as part of the CI build: https://github.com/meta-llama/llama-stack/commit/dd62a2388cf1a701af164ccc207a32c00e063f41. [This PR](https://github.com/meta-llama/llama-stack/pull/1354) was too old and didn't include the additional CI builds yet.
> fix: Fix docs lint issues

- llama_stack/providers/remote/inference/nvidia/nvidia.py
NVIDIA Inference provider was using the ModelRegistryHelper to map input model ids to provider model ids. this updates it to use the model_store.
`LLAMA_STACK_CONFIG=http://localhost:8321 uv run pytest -v tests/integration/inference/{test_embedding.py,test_text_inference.py,test_openai_completion.py} --embedding-model nvidia/llama-3.2-nv-embedqa-1b-v2 --text-model=meta-llama/Llama-3.1-70B-Instruct`
> feat: update nvidia inference provider to use model_store

- docs/source/distributions/self_hosted_distro/remote-vllm.md
- llama_stack/templates/remote-vllm/doc_template.md
This is helpful when debugging issues with vLLM + Llama Stack after this PR https://github.com/vllm-project/vllm/pull/15593
> docs: Add tips for debugging remote vLLM provider

- .github/workflows/test-external-providers.yml
- docs/source/distributions/building_distro.md
- llama_stack/cli/stack/_build.py
- llama_stack/distribution/build.py
- llama_stack/distribution/build_container.sh
- llama_stack/distribution/datatypes.py
- llama_stack/distribution/distribution.py
- scripts/distro_codegen.py
- tests/external-provider/llama-stack-provider-ollama/custom-distro.yaml
- tests/external-provider/llama-stack-provider-ollama/custom_ollama.yaml
- tests/external-provider/llama-stack-provider-ollama/run.yaml
We can now build a distribution that includes external providers.
Closes: https://github.com/meta-llama/llama-stack/issues/1948
Build a distro with an external provider following the doc instructions.
Added.
Rendered:
> feat: allow building distro with external providers

- docs/source/distributions/self_hosted_distro/nvidia.md
- llama_stack/templates/nvidia/doc_template.md
- Update NVIDIA documentation links to GA docs
- Remove reference to notebooks until merged
> feat: Update NVIDIA to GA docs; remove notebook reference until ready

- llama_stack/providers/remote/inference/fireworks/fireworks.py
We were passing a dict into the compat mixin for OpenAI Completions when using Llama models with Fireworks, and that was breaking some strong typing code that was added in openai_compat.py. We shouldn't have been converting these params to a dict in that case anyway, so this adjusts things to pass the params in as their actual original types when calling the OpenAIChatCompletionToLlamaStackMixin.
All of the fireworks provider verification tests were failing due to some OpenAI compatibility cleanup in #1962. The changes in that PR were good to make, and this just cleans up the fireworks provider code to stop passing in untyped dicts to some of those `openai_compat.py` methods since we have the original strongly-typed parameters we can pass in.
```
llama stack run --image-type venv …
```
> fix: OpenAI Completions API and Fireworks

- llama_stack/distribution/ui/page/playground/rag.py
Now, tool outputs and retrieved chunks from the vector DB (i.e., everything except for the actual model reply) are hidden under an expander form when presented to the user.
Navigate to the RAG page in the Playground UI.
> feat: Hide tool output under an expander in Playground UI

- docs/source/building_applications/rag.md
Add examples for how to define RAGDocuments. Not sure if this is the best place for these docs. @raghotham Please advise
None, documentation
> docs: add examples for how to define RAG docs

- docs/source/providers/external.md
Also does a minor reorg of the columns
> docs: add API to external providers table

- .github/workflows/test-external-providers.yml
Update External Providers CI to not run on changes to docs, rfcs, and scripts
> chore: Update External Providers CI to not run on changes to docs, rfcs, and scripts

- docs/zero_to_hero_guide/00_Inference101.ipynb
- docs/zero_to_hero_guide/01_Local_Cloud_Inference101.ipynb
- docs/zero_to_hero_guide/02_Prompt_Engineering101.ipynb
- docs/zero_to_hero_guide/03_Image_Chat101.ipynb
- docs/zero_to_hero_guide/04_Tool_Calling101.ipynb
- docs/zero_to_hero_guide/05_Memory101.ipynb
- docs/zero_to_hero_guide/06_Safety101.ipynb
- docs/zero_to_hero_guide/07_Agents101.ipynb
Adding nbformat version fixes this issue. Not sure exactly why this needs to be done, but this version was rewritten to the bottom of a nb file when I changed its name trying to get to the bottom of this. When I opened it on GH the issue was no longer present
Closes #1837 
N/A
> fix: specify nbformat version in nb

- llama_stack/distribution/ui/page/playground/tools.py
ReAct prompting attempts to use the Thinking, Action, Observation loop to improve the model's reasoning ability via prompt engineering.
With this PR, it now supports the various features in Streamlit's playground:
1. Adding the selection box for choosing between Agent Type: normal, ReAct.
2. Adding the Thinking, Action, Observation loop streamlit logic for ReAct agent, as seen in many LLM clients.
3. Improving tool calling accuracies via ReAct prompting, e.g. using web_search.
**Folded**
**Collapsed**
Run the playground and uses reasoning prompts …
> feat: Support ReAct Agent on Tools Playground

- llama_stack/models/llama/llama4/prompt_templates/system_prompts.py
- llama_stack/providers/utils/inference/prompt_adapter.py
Tests:
LLAMA_STACK_CONFIG=http://localhost:5002 pytest -s -v tests/integration/inference --safety-shield meta-llama/Llama-Guard-3-8B --vision-model meta-llama/Llama-4-Scout-17B-16E-Instruct --text-model meta-llama/Llama-4-Scout-17B-16E-Instruct
> feat: new system prompt for llama4

- llama_stack/models/llama/llama4/prompt_format.md
- llama_stack/models/llama/llama4/prompts.py
torchrun --nproc_per_node=8 scripts/generate_prompt_format.py meta-llama/Llama-4-Scout-17B-16E-Instruct ~/local/checkpoints/<path>/ llama_stack.models.llama.llama4.prompts llama_stack/models/llama/llama4/prompt_format.md
> docs: update prompt_format.md for llama4

- llama_stack/templates/llama_api/run.yaml
Distribution Template Codegen was broken
> fix: Fix precommit-hook

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/agents/agents.py
- llama_stack/providers/inline/agents/meta_reference/agents.py
- llama_stack/providers/inline/agents/meta_reference/openai_responses.py
- tests/unit/providers/agents/meta_reference/test_openai_responses.py
Add support for the temperature to the responses API 
Manually tested simple case
unit tests added for simple case and tool calls
> feat: Add temperature support to responses API

- .github/workflows/integration-auth-tests.yml
We just need to validate the auth so we don't need any API / Providers.
> chore: factor kube auth test distro

- CHANGELOG.md
We don't have GA workflow enabled to proceed with automation so I am doing this manually again.
> docs: Update changelog to include recent releases

- llama_stack/models/llama/llama4/prompt_format.md
- llama_stack/models/llama/llama4/prompt_templates/system_prompts.py
- tests/integration/inference/test_text_inference.py
- tests/integration/test_cases/inference/chat_completion.json
Tests:
LLAMA_STACK_CONFIG=http://localhost:5002 pytest -s -v tests/integration/inference --safety-shield meta-llama/Llama-Guard-3-8B --vision-model meta-llama/Llama-4-Scout-17B-16E-Instruct --text-model meta-llama/Llama-4-Scout-17B-16E-Instruct
LLAMA_STACK_CONFIG=http://localhost:5002 pytest -s -v tests/integration/inference --safety-shield meta-llama/Llama-Guard-3-8B --vision-model Llama-4-Maverick-17B-128E-Instruct --text-model Llama-4-Maverick-17B-128E-Instruct
> fix: llama4 tool use prompt fix

- CONTRIBUTING.md
> test: Document how users can run a subset of tests

- docs/source/distributions/self_hosted_distro/together.md
- llama_stack/providers/remote/inference/together/models.py
- llama_stack/templates/together/run-with-safety.yaml
- llama_stack/templates/together/run.yaml
- llama_stack/templates/verification/run.yaml
Adding Llama4 model support in TogetherAI provider
> feat(provider): adding llama4 support in together inference provider

- CONTRIBUTING.md
- docs/source/contributing/new_api_provider.md
- tests/README.md
- tests/integration/README.md
- tests/unit/README.md
- tests/verifications/README.md
reduces duplication and centralizes information to be easier to find for contributors
> docs: revamp testing documentation

- llama_stack/ui/README.md
- llama_stack/ui/app/layout.tsx
- llama_stack/ui/components/app-sidebar.tsx
- llama_stack/ui/package-lock.json
- llama_stack/ui/package.json
- Add pre-req to run the server (install deps)
- Fix the static build
Closes: https://github.com/meta-llama/llama-stack/issues/2174
> fix: misc UI changes

- .github/workflows/providers-build.yml
continuation of https://github.com/meta-llama/llama-stack/pull/2181
> fix: dev -> starter rename in ci

- llama_stack/providers/remote/inference/openai/openai.py
fixes #2121
this implementation splits reponsibility between litellm and openai libraries -
| Inference Method           | Implementation Source    |
|----------------------------|--------------------------|
| completion                 | LiteLLMOpenAIMixin       |
| chat_completion            | LiteLLMOpenAIMixin       |
| embedding                  | LiteLLMOpenAIMixin       |
| batch_completion           | LiteLLMOpenAIMixin       |
| batch_chat_completion      | LiteLLMOpenAIMixin       |
| openai_completion          | AsyncOpenAI              |
| openai_chat_completion     | AsyncOpenAI              |
smoke test with -
```
$ OPENAI_API_KEY=$LLAMA_API_KEY OPENAI_BASE_URL=https://api.llama.com/compat/v1 llama stack build --image-type conda --image-name openai --providers …
```
> feat: use openai-python for openai inference provider

- llama_stack/ui/README.md
> chore: Updated readme

- llama_stack/distribution/server/auth_providers.py
This PR adds a lock to coordinate concurrent coroutines passing through the jwt verification. As _refresh_jwks() was setting _jwks to an empty dict then repopulating it, having multiple coroutines doing this concurrently risks losing keys. The PR also builds the updated dict as a separate object and assigns it to _jwks once completed. This avoids impacting any coroutines using the key set as it is being updated.
> fix: synchronize concurrent coroutines checking & updating key set

- docs/source/distributions/building_distro.md
- llama_stack/cli/stack/list_stacks.py
- llama_stack/cli/stack/remove.py
- llama_stack/cli/stack/stack.py
```
llama stack rm llamastack-test
```
#225 
> feat: add llama stack rm command

- .github/actions/setup-runner/action.yml
- .github/workflows/integration-auth-tests.yml
- .github/workflows/integration-tests.yml
- .github/workflows/providers-build.yml
- .github/workflows/test-external-providers.yml
- .github/workflows/unit-tests.yml
- .github/workflows/update-readthedocs.yml
Use a composite action to avoid similar steps repetitions and centralization of the defaults.
> chore: refactor workflow writting

- llama_stack/distribution/inspect.py
We now only print the 'active' routes, not all the possible routes. This is based on the distribution server config by looking at enabled APIs and their respective providers.
> fix: only print routes that match the runtime config

- pyproject.toml
- uv.lock
> chore: add sqlalchemy to test dependencies

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/agents/agents.py
- llama_stack/apis/agents/openai_responses.py
- llama_stack/providers/inline/agents/meta_reference/agents.py
- llama_stack/providers/inline/agents/meta_reference/openai_responses.py
- llama_stack/providers/utils/responses/responses_store.py
- tests/integration/agents/test_openai_responses.py
- tests/unit/providers/agents/meta_reference/test_openai_responses.py
TSIA
added integration and unit tests
> feat: add responses input items api

- llama_stack/distribution/routing_tables/toolgroups.py
Two somewhat annoying fixes: 
- we are going to index tools for non-MCP toolgroups always (like we used to do). because there are just random assumptions in our tests, etc. and I don't want to fix them right now
- we need to handle the funny case of toolgroups like `builtin::rag/knowledge_search` where we added the tool name to use in the toolgroup itself.
> fix: index non-MCP toolgroups at registration time

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds updated comments for the PR template as comments were showing up in PRs when they were not meant to
> chore: fix visible comments in pr template

- scripts/distro_codegen.py
Adds an import for all of the template modules before the executor to prevent deadlock 
Closes #2278
```
for i in {1..10}; do pre-commit run --all-files; done
```
> chore: fix flaky distro_codegen script

- llama_stack/providers/remote/inference/ollama/ollama.py
The chat completion ids generated by Ollama are not unique enough to use with stored chat completions as they rely on only 3 numbers of randomness to give unique values - ie `chatcmpl-373`. This causes frequent collisions in id values of chat completions in Ollama, which creates issues in our SQL storage of chat completions by id where it expects ids to actually be unique.
So, this adjusts Ollama responses to use uuids as unique ids. This does mean we're replacing the ids generated natively by Ollama. If we don't wish to do this, we'll either need to relax the unique constraint on our chat completions id field in the inference storage or convince Ollama upstream to use something closer to uuid values here.
Closes #2315
I tested by running the openai completion / chat completion …
> fix: ollama chat completion needs unique ids

- docs/source/distributions/k8s/apply.sh
- docs/source/distributions/k8s/ingress-k8s.yaml.template
- docs/source/distributions/k8s/stack-k8s.yaml.template
- docs/source/distributions/k8s/ui-k8s.yaml.template
> docs(k8s): add UI template

- llama_stack/providers/utils/kvstore/config.py
- llama_stack/providers/utils/sqlstore/sqlstore.py
- llama_stack/templates/postgres-demo/postgres_demo.py
- llama_stack/templates/postgres-demo/run.yaml
- llama_stack/templates/starter/build.yaml
- llama_stack/templates/starter/run.yaml
- llama_stack/templates/starter/starter.py
- llama_stack/templates/template.py
Once we have this, we can use the starter distro for the Kubernetes cluster demos.
> feat: add postgres deps to starter distro

- tests/integration/files/test_files.py
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/integration/files/test_files.py::test_openai_client_basic_operations
> test: skip files integrations tests for library client

- .github/workflows/test-external-providers.yml
- llama_stack/distribution/distribution.py
- llama_stack/log.py
The test wasn't using the correct virtual environment. Also augment the
console width for logs.
> ci: fix external provider test

- .github/workflows/integration-tests.yml
Added `vector_io` to the CI integration tests.
> test: Update integration-tests.yml

- .github/TRIAGERS.md
Sadly, I won't have capacity to continue working for the project.
> chore: Remove @booxter from triagers

- .github/workflows/python-build-test.yml
- .pre-commit-config.yaml
- llama_stack/distribution/routers/vector_io.py
- llama_stack/distribution/ui/page/distribution/__init__.py
- llama_stack/models/llama/llama3_3/__init__.py
- llama_stack/models/llama/llama4/prompt_templates/__init__.py
- llama_stack/models/llama/llama4/vision/__init__.py
- llama_stack/providers/inline/post_training/huggingface/recipes/__init__.py
- llama_stack/providers/inline/scoring/basic/utils/__init__.py
- llama_stack/providers/utils/responses/__init__.py
- llama_stack/providers/utils/sqlstore/__init__.py
- llama_stack/providers/utils/tools/__init__.py
- scripts/check-init-py.sh
We now test a package build on every PRs.
Closes: https://github.com/meta-llama/llama-stack/issues/2406
> ci: add python package build test

- docs/source/distributions/configuration.md
Replace misaligned tab with spaces
Signed-off-by: Costa Shulyupin <costa.shul@redhat.com>
> docs: Fix spacing

- llama_stack/distribution/build_container.sh
Closes #2495 
Changes:
- Delay the `COPY run.yaml` into docker image step until after external provider handling
- Split the check for `external_providers_dir` into “non-empty” and “directory exists"
0. Create and Activate venv
1. Create a `simple_build.yaml`
```yaml
version: '2'
distribution_spec:
providers:
inference:
- remote::openai
image_type: container
image_name: openai-stack
```
2. Run llama stack build:
```bash
llama stack build --config simple_build.yaml
```
3. Run the docker container:
```bash
docker run \
-p 8321:8321 \
-e OPENAI_API_KEY=$OPENAI_API_KEY \
openai_stack:0.2.12
```
This should show server is running.
```
INFO     2025-06-23 19:07:57,832 llama_stack.distribution.distribution:151 core: Loading external providers from /.llama/providers.d
INFO     2025-06-23 …
```
> fix: #2495 FileNotFound Err in container image

- llama_stack/providers/inline/post_training/huggingface/recipes/finetune_single_device.py
currently only the last saved model is reported as a checkpoint and associated with the job UUID. since the HF trainer handles checkpoint collection during training, we need to add all of the `checkpoint-*` folders as Checkpoint objects. Adjust the save strategy to be per-epoch to make this easier and to use less storage
> fix: proper checkpointing logic for HF trainer

- docs/zero_to_hero_guide/04_Tool_Calling101.ipynb
- docs/zero_to_hero_guide/README.md
- update REAMDE.md format and python version
- update package name: CustomTool was renamed to ClientTool in https://github.com/meta-llama/llama-stack-client-python/pull/73
Closes #2556
> fix: update zero_to_hero package and README

- llama_stack/apis/telemetry/telemetry.py
Minor spelling fix in the comments
No code changes
> docs: Minor spelling fix

- .github/workflows/integration-tests.yml
- tests/integration/fixtures/common.py
* Use #2580 functionality to auto-start the server with the tests
* Reduce timeout to 30sec
* Print server logs on errors
* Pytest logs are collected to a file pytest.log
> ci: let pytest run the distro server

- docs/source/distributions/self_hosted_distro/starter.md
> docs: Update starter docs to include milvus inline

- docs/source/distributions/eks/apply.sh
- docs/source/distributions/eks/gp3-topology-aware.yaml
- docs/source/distributions/k8s/apply.sh
- docs/source/distributions/k8s/hf-token-secret.yaml.template
- docs/source/distributions/k8s/stack-configmap.yaml
- docs/source/distributions/k8s/stack_run_config.yaml
- docs/source/distributions/k8s/vllm-k8s.yaml.template
- docs/source/distributions/k8s/vllm-safety-k8s.yaml.template
- docs/source/distributions/kubernetes_deployment.md
- fix env variables
- use gpu for vllm
- add eks/apply.py for aws
- add template to set hf secret
bash apply.sh
> fix: update k8s templates

- llama_stack/models/llama/llama3_3/prompts.py
- pyproject.toml
> chore(api): add `mypy` coverage to `prompts`

- pyproject.toml
> chore: add `mypy` loader

- llama_stack/providers/remote/inference/runpod/runpod.py
I'm not sure how this was missed in the pyupgrade PR. This code seems broken...
> fix: runpod transition to python 3.12

- docs/_static/llama-stack-spec.html
- docs/_static/llama-stack-spec.yaml
- llama_stack/apis/common/training_types.py
- pyproject.toml
This PR adds static type coverage to `llama-stack/apis`
> chore(api): add `mypy` coverage to `apis`

- docs/source/distributions/ondevice_distro/android_sdk.md
Updates some broken or outdated links pointing to the Android Demo App
> docs: Update links to Android Demo App

- llama_stack/providers/inline/post_training/torchtune/post_training.py
- pyproject.toml
> chore: add `mypy` post training

- llama_stack/cli/stack/_build.py
- pyproject.toml
> chore(api): add `mypy` coverage to `cli/stack`

- docs/source/distributions/k8s/apply.sh
- docs/source/distributions/k8s/vllm-k8s.yaml.template
> chore: update vllm k8s command to support tool calling

- llama_stack/ui/app/logs/vector-stores/[id]/page.tsx
- llama_stack/ui/app/logs/vector-stores/layout.tsx
- llama_stack/ui/app/logs/vector-stores/page.tsx
- llama_stack/ui/components/layout/app-sidebar.tsx
- llama_stack/ui/components/layout/detail-layout.tsx
- llama_stack/ui/components/ui/message-components.tsx
- llama_stack/ui/components/vector-stores/vector-store-detail.tsx
- llama_stack/ui/package-lock.json
- llama_stack/ui/package.json
- Adds two pages to UI
- Vector stores
- Vector store detail view
- Fixed darkmode navbar highlighting
- Updated darkmode font color
- Updated llama-stack-client package
> feat: Add Vector stores UI

- docs/source/references/llama_stack_client_cli_reference.md
Adds new documentation that was missing for the Llama Stack Python Client as well as updates old/outdated docs
> docs: update outdated llama stack client documentation

- .github/actions/setup-runner/action.yml
- .github/workflows/integration-tests.yml
> test: add tests against published client

- CONTRIBUTING.md
This PR fixes typo "here here" and self loop link at [https://llama-stack.readthedocs.io/en/latest/contributing/index.html#tests/README.md](https://llama-stack.readthedocs.io/en/latest/contributing/index.html#tests/README.md)
Closes #2762
> docs: fix typo and link self loop for index.html#running-tests

- docs/source/deploying/kubernetes_deployment.md
- docs/source/distributions/k8s/apply.sh
- docs/source/distributions/k8s/stack-configmap.yaml
- docs/source/distributions/k8s/stack-k8s.yaml.template
- docs/source/distributions/k8s/stack_run_config.yaml
- docs/source/distributions/k8s/ui-k8s.yaml.template
- enables auth
- updates to use distribution-starter docker
bash apply.sh
> chore: update k8s template

- llama_stack/providers/inline/inference/meta_reference/parallel_utils.py
- pyproject.toml
> chore: add `mypy` inference parallel utils

- .github/workflows/integration-tests.yml
trigger integration tests on ALL changes to `tests/` to catch failures before they merge into main
> fix: amend integration test workflow

- docs/source/getting_started/demo_script.py
- docs/source/getting_started/quickstart.md
This PR adds the quickstart as a file to the docs so that it can be more easily maintained and run, as mentioned in https://github.com/meta-llama/llama-stack/pull/2800.
I could add this as a test in the CI but I wasn't sure if we wanted to add additional jobs there. 😅
> chore: Adding demo script and importing it into the docs

- scripts/check-workflows-use-hashes.sh
Updates the script `scripts/check-workflows-use-hashes.sh` to improve error reporting by adopting GitHub Actions error annotation format.
* Updated the script to use GitHub Actions error annotation format (`::error file={name},line={line},col={col}::{message}`) making error messages more actionable and easier to locate in workflows.
* Modified the script to include line numbers for `uses:` references by using `grep -n` and extracting line numbers, improving the precision of error reporting.
Closes #2778
- Violation check - Created test file with mixed SHA/non-SHA actions
```
echo 'uses: actions/checkout@v4' > test-workflow.yml
echo 'uses: actions/upload-artifact@main' >> test-workflow.yml
```
Result: Correctly detected violations with precise line numbers
``` …
```
> fix: update check-workflows-use-hashes to use github error format

- docs/source/concepts/apis.md
apis.md had a few APIs missing and incorrectly described APIs
> docs: update list of apis

- llama_stack/distribution/server/server.py
- llama_stack/distribution/stack.py
Avoid the error message:
```
INFO     2025-07-24 21:51:54,530 __main__:598 server: Received interrupt signal, shutting down gracefully...                                          
ERROR    2025-07-24 21:51:54,692 asyncio:1826 uncategorized: Task was destroyed but it is pending!                                                    
task: <Task pending name='Task-15' coro=<refresh_registry() running at                                                                       
/Users/leseb/Documents/AI/llama-stack/llama_stack/distribution/stack.py:356> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=>  
```
> fix(registry): ensure clean shutdown

- .github/workflows/pre-commit.yml
See PR screenshot below -- we need to run pre-commit on the dependabot PRs obviously
> fix(dependabot): run pre-commit on dependabot PRs

- llama_stack/distribution/build_container.sh
revert https://github.com/meta-llama/llama-stack/pull/2855 to unblock release (running out of disk space)
Error here: https://github.com/llamastack/llama-stack-ops/actions/runs/16579983004/job/46893549312
> chore: revert #2855

- docs/source/distributions/importing_as_library.md
Updates provider template from outdated `ollama` to `starter` 
Closes: #2839
> docs: update using llama stack as library docs

- docs/source/distributions/k8s/stack-configmap.yaml
- docs/source/distributions/k8s/stack_run_config.yaml
> chore: fix k8s config

- llama_stack/apis/common/errors.py
- llama_stack/distribution/routers/inference.py
- llama_stack/distribution/routing_tables/common.py
- llama_stack/distribution/routing_tables/models.py
- llama_stack/distribution/routing_tables/vector_dbs.py
- scripts/generate_prompt_format.py
1. Creates a new `ModelNotFoundError` class
2. Implements the new class where appropriate 
Relates to #2379
> chore: standardize model not found error

- README.md
Update README for supported DBs
> chore: Update README for supported DBs

- .github/actions/run-and-record-tests/action.yml
- scripts/integration-tests.sh
So we can run the integration tests locally. It also now shows in the log the exact command to repro:
check # of CI test are the same as before
> chore: create integration-tests script

- .github/workflows/integration-tests.yml
> chore: CI action names

- llama_stack/providers/inline/vector_io/faiss/faiss.py
- llama_stack/providers/remote/vector_io/pgvector/pgvector.py
- llama_stack/providers/remote/vector_io/weaviate/weaviate.py
- llama_stack/providers/utils/memory/openai_vector_store_mixin.py
Remove score_threshold based check from `OpenAIVectorStoreMixin`
Closes: https://github.com/meta-llama/llama-stack/issues/3018
> refactor: Remove double filtering based on score threshold

- tests/integration/vector_io/test_openai_vector_stores.py
Implement vector store search test
```
pytest tests/integration/vector_io/test_openai_vector_stores.py::test_openai_vector_store_search_modes --stack-config=http://localhost:8321 --embedding-model=all-MiniLM-L6-v2 -v
```
> test: Implement vector store search test

- llama_stack/distributions/postgres-demo/postgres_demo.py
- llama_stack/distributions/postgres-demo/run.yaml
closes https://github.com/meta-llama/llama-stack/issues/3044
matches starter's template
> chore: update postgres_demo with new config

- tests/integration/conftest.py
- tests/integration/fixtures/common.py
> fix(tests): move llama stack client init back to fixture

- docs/source/distributions/self_hosted_distro/nvidia.md
- llama_stack/distributions/nvidia/doc_template.md
- llama_stack/providers/remote/inference/nvidia/NVIDIA.md
Fix the NVIDIA inference docs by updating API methods, model IDs, and embedding example. 
N/A
> docs: fix the docs for NVIDIA Inference Provider

- docs/source/providers/vector_io/inline_faiss.md
- llama_stack/providers/inline/vector_io/faiss/faiss.py
- llama_stack/providers/registry/vector_io.py
Add unsupported search mode info about FAISS
Closes #https://github.com/meta-llama/llama-stack/issues/3012
> docs: Add unsupported search mode info about FAISS

- llama_stack/core/server/server.py
> fix: huge speed boost

- docs/source/distributions/k8s-benchmark/apply.sh
- docs/source/distributions/k8s-benchmark/locust-k8s.yaml
- docs/source/distributions/k8s-benchmark/locustfile.py
- docs/source/distributions/k8s-benchmark/openai-mock-deployment.yaml
- docs/source/distributions/k8s-benchmark/openai-mock-server.py
- docs/source/distributions/k8s-benchmark/stack-configmap.yaml
- docs/source/distributions/k8s-benchmark/stack-k8s.yaml.template
- docs/source/distributions/k8s-benchmark/stack_run_config.yaml
- pyproject.toml
- uv.lock
1. Added a simple mock openai-compat server that serves chat/completion
2. Add a benchmark server in EKS that includes mock inference server
3. Add locust (https://locust.io/) file for load testing
bash apply.sh
kubectl port-forward service/locust-web-ui 8089:8089
Go to localhost:8089 to start a load test
> chore: setup for performance benchmarking

- llama_stack/providers/inline/agents/meta_reference/openai_responses.py
- tests/integration/non_ci/responses/test_responses.py
Enhances tool execution streaming by adding support for real-time progress events during tool calls. This implementation adds streaming events for MCP and web search tools, including in-progress, searching, completed, and failed states. 
The refactored `_execute_tool_call` method now returns an async iterator that yields streaming events throughout the tool execution lifecycle.
Updated the integration test `test_response_streaming_multi_turn_tool_execution` to verify the presence and structure of new streaming events, including:
- Checking for MCP in-progress and completed events
- Verifying that progress events contain required fields (item_id, output_index, sequence_number)
- Ensuring completed events have the necessary sequence_number field
> feat(responses): stream progress of tool calls

- README.md
- This links to a scammy looking website with ads.
> chore: Remove Trendshift badge from README

- llama_stack/providers/remote/inference/nvidia/NVIDIA.md
- llama_stack/providers/remote/safety/nvidia/nvidia.py
- Documentation update and fix for the NVIDIA Inference provider. 
- Update the `run_moderation` for safety API with a `NotImplementedError` placeholder. Otherwise initialization NVIDIA inference client will raise an error. 
N/A
> docs: update the docs for NVIDIA Inference provider

- tests/integration/inference/test_openai_completion.py
The inference store writes were moved to asyncio.create_task and not await anymore
❯ OLLAMA_URL=http://localhost:11434  LLAMA_STACK_CONFIG=server:starter uv run --with pytest-repeat pytest tests/integration/inference --text-model="ollama/llama3.2:3b-instruct-fp16" -vvs -k "test_inference_store_tool_calls and 3b-instruct-fp16-True" --count=10
Uninstalled 2 packages in 102ms
Installed 2 packages in 138ms
INFO     2025-09-04 14:10:17,775 tests.integration.conftest:66 tests: Setting DISABLE_CODE_SANDBOX=1 for macOS
========================================================================================================== test session starts ===========================================================================================================
platform darwin -- Python 3.12.3, pytest-8.4.1, …
> chore: unbreak inference store test

- llama_stack/distributions/ci-tests/ci_tests.py
- llama_stack/distributions/ci-tests/run.yaml
- llama_stack/distributions/starter-gpu/run.yaml
- llama_stack/distributions/starter-gpu/starter_gpu.py
- llama_stack/distributions/starter/starter.py
> fix: Fix locations of distrubution runtime directories

- docs/source/getting_started/demo_script.py
- llama_stack/providers/inline/tool_runtime/rag/__init__.py
- llama_stack/providers/inline/tool_runtime/rag/memory.py
- llama_stack/providers/registry/tool_runtime.py
- tests/integration/tool_runtime/test_rag_tool.py
- tests/unit/rag/test_rag_query.py
This PR updates the Rag Tool to use Files API and Vector Stores API. 
I also updated the demo script and tests to reflect the changes.
Overall this should enable a smooth transition for users.
> feat: Updating Rag Tool to use Files API and Vector Stores API

- tests/integration/inference/test_openai_completion.py
the gemini api endpoints do not support the n param or completions
ci
> chore(gemini, tests): add skips for n and completions, gemini api does not support them

- llama_stack/core/library_client.py
> chore: remove unused variable

- llama_stack/core/routers/inference.py
Reverts llamastack/llama-stack#3392
> revert: Fireworks chat completion broken due to telemetry

- tests/integration/telemetry/test_openai_telemetry.py
- tests/integration/telemetry/test_telemetry.py
- tests/integration/telemetry/test_telemetry_metrics.py
- removed fixed-duration sleeps
> chore: telemetry test

- docs/static/llama-stack-spec.html
- docs/static/llama-stack-spec.yaml
- llama_stack/apis/vector_io/vector_io.py
- llama_stack/core/routers/vector_io.py
- llama_stack/providers/utils/memory/openai_vector_store_mixin.py
Adding api stubs for vector store file batches apis
https://github.com/llamastack/llama-stack/issues/3533
API Ref: https://platform.openai.com/docs/api-reference/vector-stores-file-batches
CI
> feat(api): Add Vector Store File batches api stub

- docs/src/pages/index.js
- docs/src/pages/index.module.css
* Adds canonical project information and links to client SDK / k8s operator / app examples repos to the front page
* Fixes some button rendering errors
Closes #3618  
Local rebuild of the documentation server
> docs: frontpage update

- docs/zero_to_hero_guide/06_Safety101.ipynb
* Updates the safety guide in Zero to Hero series to use Moderations API and the latest safety models
* Fixes an image link
Closes #2557
* Manual testing
> docs: update safety notebook

- .github/ISSUE_TEMPLATE/config.yml
- README.md
- docs/docs/building_applications/tools.mdx
- docs/docs/distributions/list_of_distributions.mdx
- docs/docs/index.mdx
- docs/docusaurus.config.ts
* Fixes numerous broken links in the new documentation 
* Server builds
> docs: fix broken links

- CONTRIBUTING.md
- README.md
- docs/docs/index.mdx
- pyproject.toml
* Fixes some more documentation links
* Manual testing
> docs: fix more broken links

- docs/docs/providers/agents/index.mdx
- docs/docs/providers/batches/index.mdx
- docs/docs/providers/inference/index.mdx
> chore: fix precommit

- docs/docs/providers/agents/index.mdx
- docs/docs/providers/batches/index.mdx
- docs/docs/providers/inference/index.mdx
- llama_stack/providers/remote/inference/cerebras/cerebras.py
- llama_stack/providers/remote/inference/fireworks/fireworks.py
- llama_stack/providers/remote/inference/tgi/tgi.py
- llama_stack/providers/remote/inference/together/together.py
- llama_stack/providers/utils/inference/openai_mixin.py
- tests/integration/recordings/responses/39576bcd7ed6.json
- tests/integration/recordings/responses/53d2488c9ea9.json
- tests/unit/providers/utils/inference/test_openai_mixin.py
add ModelsProtocolPrivate methods to OpenAIMixin
this will allow providers using OpenAIMixin to use a common interface
ci w/ new tests
> chore: OpenAIMixin implements ModelsProtocolPrivate

- pyproject.toml
- uv.lock
`uv add "weaviate-client>=4.16.4" --group unit`
> chore: Add weaviate client to unit group in pyproject.toml and uv.lock

- llama_stack/cli/stack/run.py
> chore: remove dead code

- llama_stack/providers/inline/vector_io/faiss/faiss.py
- llama_stack/providers/inline/vector_io/sqlite_vec/sqlite_vec.py
- llama_stack/providers/remote/vector_io/chroma/chroma.py
- llama_stack/providers/remote/vector_io/milvus/milvus.py
- llama_stack/providers/remote/vector_io/pgvector/pgvector.py
- llama_stack/providers/remote/vector_io/qdrant/qdrant.py
- llama_stack/providers/remote/vector_io/weaviate/weaviate.py
- llama_stack/providers/utils/memory/openai_vector_store_mixin.py
- tests/unit/providers/vector_io/conftest.py
Have been running into flaky unit test failures: https://github.com/llamastack/llama-stack/actions/runs/18319987543/job/52170354944?pr=3711
Fixing below
1. Shutting down properly by cancelling any stale file batches tasks running in background. 
2. Also, use unique_kvstore_config, so the test dont use same db path and maintain test isolation
Ran unit test locally and CI
> chore: fix flaky unit test and add proper shutdown for file batches

- scripts/telemetry/setup_telemetry.sh
script runs with either docker or podman
passes when run
> fix(scripts): select container runtime for telemetry
